import { createHash } from 'node:crypto'
import { redactTestOutput } from '../../scripts/redact-test-output.mjs'
import { chromium, expect } from '@playwright/test'
import { readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import assert from 'node:assert/strict'
export async function runStudioE2E({origin,email,password,temp,sha}) {
 const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE||'/usr/bin/chromium',headless:true,args:['--no-sandbox']})
 const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[]
 page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(20000)
 const checks=[];const checked=name=>checks.push(name)
 async function api(path,body,method=body===undefined?'GET':'POST'){const r=await context.request.fetch(origin+'/api/v1'+path,{method,headers:{Origin:origin},...(body===undefined?{}:{data:body})});const j=await r.json();assert.ok(r.ok(),JSON.stringify(j));return j.data}
 async function createTenant(id,name){await page.goto(origin+'/workspaces');await page.getByRole('button',{name:'+ Nuevo espacio'}).click();await page.getByLabel('Nombre de la organización').fill(name);await page.getByLabel('Identificador',{exact:false}).fill(id);await page.getByLabel('Territorio',{exact:true}).fill('Entorno aislado de verificación');await page.getByRole('button',{name:'Crear espacio',exact:true}).click();await expect(page).toHaveURL(new RegExp('/workspace/'+id+'/sources'))}
 async function addSource(id,purpose){await page.getByRole('button',{name:'+ Agregar fuente'}).click();await page.getByLabel('Nombre corto').fill(id);await page.locator('select[name="purpose"]').selectOption(purpose);await page.getByLabel('Enlace exacto').fill('https://example.com/'+id);await page.getByLabel('Confirmo que tengo autorización',{exact:false}).check();await page.getByRole('button',{name:'Guardar fuente',exact:true}).click();await expect(page.getByRole('heading',{name:id,exact:true})).toBeVisible()}
 try {
  const health=await (await context.request.get(origin+'/health')).json();assert.equal(health.release_sha,sha);assert.equal(health.deployment_class,'test');checked('exact health identity')
  const denied=await context.request.get(origin+'/api/v1/tenants');assert.equal(denied.status(),401);checked('anonymous API denied')
  await page.goto(origin+'/dashboard');await expect(page).toHaveURL(/\/login$/);await page.screenshot({path:join(temp,'login-desktop.png'),fullPage:true})
  await page.getByLabel('Usuario o correo').fill(email);await page.getByLabel('Contraseña',{exact:true}).fill(password);await page.getByRole('button',{name:'Entrar al estudio'}).click();await expect(page).toHaveURL(/\/dashboard$/);await expect(page.getByText('Dale un espacio a tu primera marca.')).toBeVisible();checked('login and honest empty dashboard')
  await createTenant('browser-a','Estudio de verificación A');await addSource('material-a','source');await addSource('reference-a','reference');checked('workspace onboarding and authority-separated sources')
  await page.goto(origin+'/workspace/browser-a/content-dna');await page.getByRole('button',{name:'+ Observar referencia'}).click();await page.getByLabel('Archivo de evidencia').setInputFiles({name:'reference-observation.txt',mimeType:'text/plain',buffer:Buffer.from('Isolated browser fixture observation; no customer material. Warm documentary with a recurring mascot and place detail.')});await page.getByLabel('Personaje o mascota',{exact:true}).check();await page.getByLabel('Detalles del lugar',{exact:true}).check();await page.getByRole('button',{name:'Construir Content DNA',exact:true}).click();await expect(page.getByText('Identidad disponible',{exact:true})).toBeVisible();checked('reference proof upload and Content DNA')
  await api('/tenants/browser-a/mascot',{source_id:'material-a'});checked('explicit tenant mascot source binding')
  await page.goto(origin+'/workspace/browser-a/weekly');await page.getByLabel('Historias a planificar').selectOption('1');await page.getByRole('button',{name:/Continuar/}).click();await page.getByLabel('material-a',{exact:false}).check();await page.getByRole('button',{name:/Continuar/}).click();await page.getByRole('button',{name:/Continuar/}).click();await page.getByRole('button',{name:/REAL FOOTAGE|Real Footage|Material real/i}).first().click();await page.getByRole('button',{name:/Continuar/}).click();await page.getByLabel('Título de historia 1').fill('Historia guiada verificada');await page.getByLabel('Intención',{exact:true}).fill('Documentar el material autorizado para una audiencia general.');await page.getByRole('button',{name:/Continuar/}).click();await page.getByRole('button',{name:'Guardar borrador',exact:true}).click();await expect(page.getByRole('button',{name:'Aprobar estos 1 conceptos'})).toBeVisible();checked('Guided draft through shared contracts without approval side effects')
  await page.getByRole('link',{name:'Modo libre',exact:true}).last().click();await page.getByLabel('¿Qué quieres crear?').fill('Hazme cuatro videos para esta semana. Dos con nuestro material real, uno más creativo usando IA y otro con el caballito.');await page.getByText('Elegir material disponible',{exact:true}).click();await page.getByLabel('material-a',{exact:false}).check();await page.getByRole('button',{name:'Crear borrador',exact:true}).click();await expect(page.getByRole('heading',{name:'4 historias para tu semana'})).toBeVisible();assert.equal(await page.getByLabel('Título de historia', {exact:false}).count(),4);assert.deepEqual(await page.getByLabel('Estrategia de producción',{exact:false}).evaluateAll(es=>es.map(e=>e.value)),['REAL_FOOTAGE','REAL_FOOTAGE','GENERATIVE','AUTO']);await page.screenshot({path:join(temp,'free-desktop.png'),fullPage:true});checked('exact four-video natural-language request strategies')
  await page.getByRole('button',{name:'Guardar borrador',exact:true}).click();await page.getByRole('button',{name:'Aprobar estos 4 conceptos',exact:true}).click();await page.getByRole('button',{name:'Solicitar producción',exact:true}).click();await expect(page).toHaveURL(/\/jobs\//);const jobId=new URL(page.url()).pathname.split('/')[2];await expect(page.getByRole('button',{name:'Aprobar esta versión',exact:true})).toBeVisible({timeout:60000});let job=await api('/jobs/'+jobId);assert.equal(job.stage,'CREATIVE_GATE');const creativeHash=job.candidate_sha;checked('asynchronous real pinned Graph reaches creative human gate')
  await page.getByRole('button',{name:'Aprobar esta versión',exact:true}).click();await expect(page.getByRole('button',{name:'Liberar entrega',exact:true})).toBeVisible({timeout:60000});job=await api('/jobs/'+jobId);assert.equal(job.stage,'RELEASE');assert.equal(job.test,true);assert.notEqual(job.candidate_sha,creativeHash);await page.screenshot({path:join(temp,'release-review-desktop.png'),fullPage:true});checked('SSE progression and visibly marked deterministic provider fixture')
  await page.getByRole('button',{name:'Liberar entrega',exact:true}).click();await expect(page.getByText('Entrega liberada y registrada. La publicación social se realiza por separado.')).toBeVisible({timeout:60000});job=await api('/jobs/'+jobId);assert.equal(job.status,'RELEASED');const artifact=job.artifacts[0];const download=await context.request.get(origin+artifact.download_url);assert.equal(download.status(),200);assert.ok((await download.body()).length>100);assert.equal(createHash('sha256').update(await download.body()).digest('hex'),artifact.sha256);const releases=await api('/releases?tenant_id=browser-a');assert.equal(releases.length,1);assert.equal(releases[0].candidate_sha,job.candidate_sha);assert.equal(releases[0].artifact_sha256,artifact.sha256);checked('hash-bound release and authenticated downloadable artifact')
  await page.goto(origin+'/releases');await expect(page.getByRole('link',{name:/Historia 1/})).toBeVisible();checked('release library')
  await createTenant('browser-b','Estudio de verificación B');await page.goto(origin+'/workspace/browser-b/weekly');await expect(page.getByText('Tu primera semana empieza aquí.')).toBeVisible();await page.goto(origin+'/workspace/browser-a/weekly');await expect(page.getByRole('button',{name:'Abrir plan'})).toHaveCount(2);checked('tenant switching keeps plans separate')
  await page.setViewportSize({width:390,height:844});await page.goto(origin+'/dashboard');await expect(page.getByRole('button',{name:'Abrir navegación'})).toBeVisible();await page.getByRole('button',{name:'Abrir navegación'}).click();await expect(page.getByRole('navigation',{name:'Principal',exact:true})).toBeVisible();await page.getByRole('link',{name:'Espacios de trabajo',exact:true}).click();await expect(page.getByRole('heading',{name:'Espacios de trabajo',exact:true})).toBeVisible();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);await page.screenshot({path:join(temp,'mobile-workspaces.png'),fullPage:true});checked('responsive mobile navigation and no horizontal overflow')
  assert.deepEqual(errors,[]);checked('no uncaught browser errors');await writeFile(join(temp,'browser-checks.json'),JSON.stringify({checks,job_id:jobId,candidate_sha:job.candidate_sha,artifact_sha:artifact.sha256},null,2));return {status:'PASS',checks,job_id:jobId,release_candidate_sha:job.candidate_sha}
 }catch(error){await page.screenshot({path:join(temp,'failure.png'),fullPage:true}).catch(()=>{});await writeFile(join(temp,'failure-dom.txt'),redactTestOutput(await page.locator('body').innerText().catch(()=>''),password));throw error}finally{await context.close();await browser.close()}
}
