import { verifyStudioEntry } from './studio-entry.mjs'
import { verifyCreativeNavigation, verifyQuickCreateEmpty } from './creative-navigation.mjs'
import { createHash } from 'node:crypto'
import { redactTestOutput } from '../../scripts/redact-test-output.mjs'
import { chromium, expect } from '@playwright/test'
import { readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import assert from 'node:assert/strict'
export async function runStudioE2E({origin,email,password,temp,sha}) {
 const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE||'/usr/bin/chromium',headless:true,args:['--no-sandbox']})
 const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[]
 page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(20000)
 const checks=[];const checked=name=>checks.push(name)
 const mediaResponses=[]
 page.on('response',response=>{if(response.url().includes('/artifacts/')&&response.request().resourceType()==='media')mediaResponses.push({status:response.status(),range:response.request().headers().range||null,content_range:response.headers()['content-range']||null})})
 async function api(path,body,method=body===undefined?'GET':'POST'){const r=await context.request.fetch(origin+'/api/v1'+path,{method,headers:{Origin:origin},...(body===undefined?{}:{data:body})});const j=await r.json();assert.ok(r.ok(),JSON.stringify(j));return j.data}
 async function createTenant(id,name){await page.goto(origin+'/workspaces');await page.getByRole('button',{name:'+ Nuevo espacio'}).click();await page.getByLabel('Nombre de la organización').fill(name);await page.getByLabel('Identificador',{exact:false}).fill(id);await page.getByLabel('Territorio',{exact:true}).fill('Entorno aislado de verificación');await page.getByRole('button',{name:'Crear espacio',exact:true}).click();await expect(page).toHaveURL(new RegExp('/workspace/'+id+'/sources'))}
 async function addSource(id,purpose){await page.getByRole('button',{name:'+ Agregar fuente'}).click();await page.getByLabel('Nombre corto').fill(id);await page.locator('select[name="purpose"]').selectOption(purpose);await page.getByLabel('Enlace exacto').fill('https://example.com/'+id);await page.getByLabel('Confirmo que tengo autorización',{exact:false}).check();await page.getByRole('button',{name:'Guardar fuente',exact:true}).click();await expect(page.getByRole('heading',{name:id,exact:true})).toBeVisible()}
 try {
  const health=await (await context.request.get(origin+'/health')).json();assert.equal(health.release_sha,sha);assert.equal(health.deployment_class,'test');checked('exact health identity')
  const readinessResponse=await context.request.get(origin+'/api/v1/health'),readiness=(await readinessResponse.json()).data;assert.equal(readinessResponse.status(),200);assert.equal(readiness.status,'ready');assert.equal(readiness.release_sha,sha);assert.deepEqual(readiness.checks,{storage:true,authentication:true,graph:true});checked('packaged authenticated service readiness and pinned Graph')
  const denied=await context.request.get(origin+'/api/v1/tenants');assert.equal(denied.status(),401);checked('anonymous API denied')
  assert.match(denied.headers()['x-robots-tag'],/noindex/)
  const robots=await context.request.get(origin+'/robots.txt');assert.equal(robots.status(),200);assert.match(await robots.text(),/Disallow: \/(?:\r?\n|$)/);assert.ok((await robots.text()).includes('Sitemap: '+origin+'/sitemap.xml'));const sitemap=await context.request.get(origin+'/sitemap.xml');assert.equal(sitemap.status(),200);assert.match(await sitemap.text(),/<urlset/);assert.doesNotMatch(await sitemap.text(),/<loc>|browser-a|job_/);const llms=await context.request.get(origin+'/llms.txt'),llm=await context.request.get(origin+'/llm.txt');assert.equal(llms.status(),200);assert.equal(llm.status(),200);assert.match(llms.headers()['content-type'],/text\/plain/);assert.equal(await llms.text(),await llm.text());assert.match(await llms.text(),/# Media Factory/);assert.doesNotMatch(await llms.text(),/browser-a|job_|identityFile|password/);checked('public discovery endpoints exclude private resources and preview indexing')
  const missingPage=await page.goto(origin+'/this-route-does-not-exist');assert.equal(missingPage.status(),404);await expect(page.getByRole('heading',{level:1,name:'Esta página no está en el estudio.'})).toBeVisible();await expect(page.getByRole('navigation',{name:'Recuperar navegación'})).toBeVisible();await expect(page.locator('meta[name="robots"]').first()).toHaveAttribute('content',/noindex/);assert.equal(await page.locator('main').count(),1);await page.screenshot({path:join(temp,'custom-404-desktop.png'),fullPage:true});checked('unknown route returns semantic custom 404 without authentication or reflected identifiers')
  for(const path of ['/constructor','/toString','/workspace/valid-id/constructor'])assert.equal((await context.request.get(origin+path)).status(),404)

  await page.goto(origin+'/dashboard');await expect(page).toHaveURL(/\/login$/);await page.screenshot({path:join(temp,'login-desktop.png'),fullPage:true})
  await expect(page).toHaveTitle('Entrar al estudio · Media Factory');await expect(page.locator('meta[name="description"]')).toHaveAttribute('content',/Tu material, tu identidad/);await expect(page.locator('link[rel="canonical"]')).toHaveAttribute('href',origin+'/login');await expect(page.locator('meta[name="robots"]').first()).toHaveAttribute('content',/noindex/);assert.equal(await page.locator('main').count(),1);assert.equal(await page.getByRole('heading',{level:1}).count(),1);const imageUrl=await page.locator('meta[property="og:image"]').first().getAttribute('content');assert.equal(new URL(imageUrl).origin,origin);assert.ok(new URL(imageUrl).pathname.startsWith('/_next/static/media/'));assert.ok(new URL(imageUrl).pathname.endsWith('.png'));const og=await context.request.get(imageUrl);assert.equal(og.status(),200);assert.match(og.headers()['content-type'],/image\/png/);const png=await og.body();const generatedOg=await context.request.get(origin+'/opengraph-image');assert.equal(generatedOg.status(),200);assert.deepEqual(png,await generatedOg.body());assert.deepEqual(png,await readFile('assets/media-factory-og.png'));assert.equal(png.subarray(0,8).toString('hex'),'89504e470d0a1a0a');assert.equal(png.readUInt32BE(16),1200);assert.equal(png.readUInt32BE(20),630);await writeFile(join(temp,'opengraph-image.png'),png);checked('public login metadata, trusted canonical and generated 1200x630 social image')
  checks.push(...await verifyStudioEntry({page,context,temp}))

  await page.getByLabel('Usuario o correo').fill(email);await page.getByLabel('Contraseña',{exact:true}).fill(password);await page.getByRole('button',{name:'Entrar al estudio'}).click();await expect(page).toHaveURL(/\/dashboard$/);await expect(page.getByText('Dale un espacio a tu primera marca.')).toBeVisible();checked('login and honest empty dashboard')
  await expect(page).toHaveTitle('Inicio · Media Factory');await expect(page.locator('meta[name="robots"]').first()).toHaveAttribute('content',/noindex/);assert.equal(await page.locator('link[rel="canonical"]').count(),0);checked('private dashboard has generic page title and no indexing or canonical identity')
  checked(await verifyQuickCreateEmpty(page))
  await createTenant('browser-a','Estudio de verificación A');await addSource('material-a','source');await addSource('reference-a','reference');checked('workspace onboarding and authority-separated sources')
  await page.goto(origin+'/workspace/browser-a/content-dna');await page.getByRole('button',{name:'+ Observar referencia'}).click();await page.getByLabel('Archivo de evidencia').setInputFiles({name:'reference-observation.txt',mimeType:'text/plain',buffer:Buffer.from('Isolated browser fixture observation; no customer material. Warm documentary with a recurring mascot and place detail.')});await page.getByLabel('Personaje o mascota',{exact:true}).check();await page.getByLabel('Detalles del lugar',{exact:true}).check();await page.getByRole('button',{name:'Construir Content DNA',exact:true}).click();await expect(page.getByText('Identidad disponible',{exact:true})).toBeVisible();checked('reference proof upload and Content DNA')
  await api('/tenants/browser-a/mascot',{source_id:'material-a'});checked('explicit tenant mascot source binding')
  await page.goto(origin+'/workspace/browser-a/weekly');await page.getByLabel('Historias a planificar').selectOption('1');await page.getByRole('button',{name:/Continuar/}).click();await page.getByLabel('material-a',{exact:false}).check();await page.getByRole('button',{name:/Continuar/}).click();await page.getByRole('button',{name:/Continuar/}).click();await page.getByRole('button',{name:/REAL FOOTAGE|Real Footage|Material real/i}).first().click();await page.getByRole('button',{name:/Continuar/}).click();await page.getByLabel('Título de historia 1').fill('Historia guiada verificada');await page.getByLabel('Intención',{exact:true}).fill('Documentar el material autorizado para una audiencia general.');await page.getByRole('button',{name:/Continuar/}).click();await page.getByRole('button',{name:'Guardar borrador',exact:true}).click();await expect(page.getByRole('button',{name:'Aprobar estos 1 conceptos'})).toBeVisible();checked('Guided draft through shared contracts without approval side effects')
  await page.getByRole('link',{name:'Modo libre',exact:true}).last().click();await page.getByLabel('¿Qué quieres crear?').fill('Hazme cuatro videos para esta semana. Dos con nuestro material real, uno más creativo usando IA y otro con el caballito.');await page.getByText('Elegir material disponible',{exact:true}).click();await page.getByLabel('material-a',{exact:false}).check();await page.getByRole('button',{name:'Crear borrador',exact:true}).click();await expect(page.getByRole('heading',{name:'4 historias para tu semana'})).toBeVisible();assert.equal(await page.getByLabel('Título de historia', {exact:false}).count(),4);assert.deepEqual(await page.getByLabel('Estrategia de producción',{exact:false}).evaluateAll(es=>es.map(e=>e.value)),['REAL_FOOTAGE','REAL_FOOTAGE','GENERATIVE','AUTO']);await page.screenshot({path:join(temp,'free-desktop.png'),fullPage:true});checked('exact four-video natural-language request strategies')
  await page.getByRole('button',{name:'Guardar borrador',exact:true}).click();await page.getByRole('button',{name:'Aprobar estos 4 conceptos',exact:true}).click();await page.getByRole('button',{name:'Solicitar producción',exact:true}).click();await expect(page).toHaveURL(/\/jobs\//);const jobId=new URL(page.url()).pathname.split('/')[2];await expect(page.getByRole('button',{name:'Aprobar esta versión',exact:true})).toBeVisible({timeout:60000});let job=await api('/jobs/'+jobId);assert.equal(job.stage,'CREATIVE_GATE');const creativeHash=job.candidate_sha;await page.goto(origin+'/jobs/'+jobId+'/review');await expect(page).toHaveTitle('Revisión de producción · Media Factory');await expect(page.getByRole('button',{name:'Aprobar esta versión',exact:true})).toBeVisible();checked('asynchronous real pinned Graph reaches creative human gate')
  await page.getByRole('button',{name:'Aprobar esta versión',exact:true}).click();await expect(page.getByRole('button',{name:'Liberar entrega',exact:true})).toBeVisible({timeout:60000});job=await api('/jobs/'+jobId);assert.equal(job.stage,'RELEASE');assert.equal(job.test,true);assert.notEqual(job.candidate_sha,creativeHash);await page.screenshot({path:join(temp,'release-review-desktop.png'),fullPage:true});checked('SSE progression and visibly marked deterministic provider fixture')
  await page.getByRole('button',{name:'Liberar entrega',exact:true}).click();await expect(page.getByText('Entrega liberada y registrada. La publicación social se realiza por separado.')).toBeVisible({timeout:60000});job=await api('/jobs/'+jobId);assert.equal(job.status,'RELEASED');const artifact=job.artifacts[0];const download=await context.request.get(origin+artifact.download_url);assert.equal(download.status(),200);assert.ok((await download.body()).length>100);assert.equal(createHash('sha256').update(await download.body()).digest('hex'),artifact.sha256);const releases=await api('/releases?tenant_id=browser-a');assert.equal(releases.length,1);assert.equal(releases[0].candidate_sha,job.candidate_sha);assert.equal(releases[0].artifact_sha256,artifact.sha256);checked('hash-bound release and authenticated downloadable artifact')
  assert.equal(job.provider_execution.provider,'deterministic-test');assert.equal(job.provider_execution.artifact_sha256,artifact.sha256);assert.equal(job.provider_execution.provenance.synthetic,true);assert.deepEqual(job.provider_execution.provenance.used_sources,[]);assert.deepEqual(releases[0].provider_execution,job.provider_execution);assert.equal(releases[0].approval.candidate_sha,job.candidate_sha);assert.ok(releases[0].reviews.some(r=>r.scope==='RELEASE'&&r.candidate_sha===job.candidate_sha&&r.actor_id===releases[0].approval.actor_id))
  const fullBytes=await download.body(),etag='"'+artifact.sha256+'"',prefix=await context.request.get(origin+artifact.download_url,{headers:{Range:'bytes=0-15','If-Range':etag}});assert.equal(prefix.status(),206);assert.equal(prefix.headers()['content-range'],'bytes 0-15/'+fullBytes.length);assert.equal(prefix.headers().etag,etag);assert.deepEqual(await prefix.body(),fullBytes.subarray(0,16));const suffix=await context.request.get(origin+artifact.download_url,{headers:{Range:'bytes=-32'}});assert.equal(suffix.status(),206);assert.deepEqual(await suffix.body(),fullBytes.subarray(-32))
  const video=page.locator('video').first();await expect(video).toBeVisible();await expect.poll(()=>video.evaluate(v=>v.readyState)).toBeGreaterThanOrEqual(1);const seeking=await video.evaluate(async v=>{const target=v.duration/2;await new Promise((resolve,reject)=>{const timer=setTimeout(()=>{cleanup();reject(new Error('Video did not seek'))},10000);const cleanup=()=>{clearTimeout(timer);v.removeEventListener('seeked',done);v.removeEventListener('error',fail)};const done=()=>{cleanup();resolve()};const fail=()=>{cleanup();reject(new Error('Video preview failed'))};v.addEventListener('seeked',done,{once:true});v.addEventListener('error',fail,{once:true});v.currentTime=target});return {duration:v.duration,target,current_time:v.currentTime,ready_state:v.readyState,error:v.error?.code||null}});assert.ok(seeking.duration>0);assert.ok(Math.abs(seeking.current_time-seeking.target)<0.1);assert.equal(seeking.error,null);await expect.poll(()=>mediaResponses.some(r=>r.status===206&&r.range?.startsWith('bytes=')&&r.content_range?.startsWith('bytes '))).toBe(true);checked('authenticated video byte ranges and browser preview seeking')
  const snapshot=page.locator('.release-snapshot');await expect(snapshot.getByRole('heading',{name:'Entrega · versión 1'})).toBeVisible();await snapshot.getByText('Archivo, aprobación y procedencia',{exact:true}).click();await expect(snapshot.locator('dt').filter({hasText:'Huella del archivo maestro'}).locator('xpath=following-sibling::dd[1]')).toHaveText(artifact.sha256);await expect(snapshot.locator('dt').filter({hasText:'Candidato aprobado'}).locator('xpath=following-sibling::dd[1]')).toHaveText(job.candidate_sha);await expect(snapshot.getByText('deterministic-test',{exact:true})).toBeVisible();await expect(snapshot.getByText('Esta prueba no utilizó material de producción.',{exact:true})).toBeVisible();await expect(snapshot.getByText('Lista para publicación manual',{exact:true})).toBeVisible();await expect(snapshot.locator('.review-history')).toContainText(releases[0].approval.actor_id);await expect(snapshot.locator('.review-history')).toContainText(job.candidate_sha);await page.screenshot({path:join(temp,'release-provenance-desktop.png'),fullPage:true});checked('released version visibly shows approved hashes, reviewer and actual provider provenance')

  await page.goto(origin+'/releases');await expect(page.getByRole('link',{name:/Historia 1/})).toBeVisible();checked('release library')
  const libraryEntry=page.locator('.release-entry');await libraryEntry.getByText('Archivo, aprobación y procedencia',{exact:true}).click();await expect(libraryEntry.getByText(artifact.sha256,{exact:true})).toBeVisible();await expect(libraryEntry.getByText('deterministic-test',{exact:true})).toBeVisible();const save=page.waitForEvent('download');await libraryEntry.getByRole('link',{name:'Descargar artefacto de prueba',exact:true}).click();const actualDownload=await save;assert.equal(await actualDownload.failure(),null);const downloadedPath=join(temp,'verified-release-download.mp4');await actualDownload.saveAs(downloadedPath);const downloadedSha=createHash('sha256').update(await readFile(downloadedPath)).digest('hex');assert.equal(downloadedSha,artifact.sha256);await page.screenshot({path:join(temp,'release-library-provenance-desktop.png'),fullPage:true});checked('release library details and actual browser download match approved master hash')
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{if(document.activeElement instanceof HTMLElement)document.activeElement.blur();window.scrollTo(0,0)});await expect.poll(()=>page.evaluate(()=>window.scrollY)).toBe(0);await expect(libraryEntry.getByText(artifact.sha256,{exact:true})).toBeVisible();await expect(libraryEntry.getByText('deterministic-test',{exact:true})).toBeVisible();await expect(libraryEntry.getByRole('link',{name:'Descargar artefacto de prueba',exact:true})).toBeVisible();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);await page.screenshot({path:join(temp,'release-library-provenance-mobile.png'),fullPage:true});checked('mobile release details and hash provenance fit the 390px viewport');await page.setViewportSize({width:1440,height:1000})
  await createTenant('browser-b','Estudio de verificación B');await page.goto(origin+'/workspace/browser-b/weekly');await expect(page.getByText('Tu primera semana empieza aquí.')).toBeVisible();await page.goto(origin+'/workspace/browser-a/weekly');await expect(page.getByRole('button',{name:'Abrir plan'})).toHaveCount(2);checked('tenant switching keeps plans separate')
  await page.setViewportSize({width:390,height:844});await page.goto(origin+'/dashboard');await expect(page.getByRole('button',{name:'Abrir navegación'})).toBeVisible();await page.getByRole('button',{name:'Abrir navegación'}).click();await expect(page.getByRole('navigation',{name:'Principal',exact:true})).toBeVisible();await page.getByRole('link',{name:'Espacios de trabajo',exact:true}).click();await expect(page.getByRole('heading',{name:'Espacios de trabajo',exact:true})).toBeVisible();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);await page.screenshot({path:join(temp,'mobile-workspaces.png'),fullPage:true});checked('responsive mobile navigation and no horizontal overflow')
  checks.push(...await verifyCreativeNavigation({page,context,origin,temp}))
  assert.deepEqual(errors,[]);checked('no uncaught browser errors');await writeFile(join(temp,'browser-checks.json'),JSON.stringify({checks,job_id:jobId,candidate_sha:job.candidate_sha,artifact_sha:artifact.sha256,download_sha256:downloadedSha,release_id:releases[0].id,provider_execution:releases[0].provider_execution,media_responses:mediaResponses,seeking},null,2));return {status:'PASS',checks,job_id:jobId,release_candidate_sha:job.candidate_sha,artifact_sha256:artifact.sha256,download_sha256:downloadedSha,release_id:releases[0].id,provider:releases[0].provider_execution.provider,media_responses:mediaResponses,seeking}
 }catch(error){await page.screenshot({path:join(temp,'failure.png'),fullPage:true}).catch(()=>{});await writeFile(join(temp,'failure-dom.txt'),redactTestOutput(await page.locator('body').innerText().catch(()=>''),password));throw error}finally{await context.close();await browser.close()}
}
