import test from 'node:test'
import assert from 'node:assert/strict'
import { mkdtemp,rm } from 'node:fs/promises'
import { captureProviderExecution,publicProviderExecution } from '../server/media-projection.mjs'
import { createService,publicJob } from '../server/services.mjs'
const sha='a'.repeat(64),artifactSha='b'.repeat(64)
const asset={source_id:'source-one',sha256:sha,path:'/private/source',size_bytes:1200,width:1080,height:1920,duration_seconds:8}
const provenance={adapter:'ffmpeg',paid:false,synthetic:false,used_sources:[{source_id:'source-one',sha256:sha,path:'/private/source'}],internal_path:'/private/provider',credentials:{token:'not-a-real-secret'}}
const capture=()=>captureProviderExecution({provider:'ffmpeg',provenance,estimate:{credits:0},assets:[asset],artifactSha,test:false})
test('provider provenance records consumed bytes and excludes private adapter metadata',()=>{const execution=capture();assert.deepEqual(execution.provenance.used_sources,[{source_id:'source-one',sha256:sha}]);assert.equal(execution.artifact_sha256,artifactSha);assert.equal(execution.provenance.synthetic,false);assert.equal(execution.estimate.cost,null);assert.doesNotMatch(JSON.stringify(execution),/private|credentials|token/);const projection=publicProviderExecution({...execution,token:'not-a-real-secret',provenance:{...execution.provenance,private_path:'/private/store'}});assert.deepEqual(projection,execution)})
test('provider cannot claim other sources, omit selected bytes, or relabel an adapter',()=>{for(const changed of [{...provenance,adapter:'higgsfield'},{...provenance,synthetic:undefined},{...provenance,used_sources:[]},{...provenance,used_sources:[{source_id:'source-one',sha256:'c'.repeat(64)}]},{...provenance,used_sources:[{source_id:'other-source',sha256:sha}]},{...provenance,used_sources:[{source_id:'source-one',sha256:sha},{source_id:'source-one',sha256:sha}]}])assert.throws(()=>captureProviderExecution({provider:'ffmpeg',provenance:changed,estimate:{credits:0},assets:[asset],artifactSha,test:false}),{code:'INVALID_PROVENANCE'})})

test('brand-asset provenance is one-to-one bound to the authorized runtime input',()=>{const brandSha='d'.repeat(64),authorized=[{asset_id:'firmes-caballito',sha256:brandSha,synthetic:false}],claim={...provenance,brand_assets:[{asset_id:'firmes-caballito',sha256:brandSha,synthetic:false}]};const execution=captureProviderExecution({provider:'ffmpeg',provenance:claim,estimate:{credits:0},assets:[asset],brandAssets:authorized,artifactSha,test:false});assert.deepEqual(execution.provenance.brand_assets,authorized);for(const value of [{claim:{...provenance,brand_assets:[]},authorized},{claim,authorized:[]},{claim:{...provenance,brand_assets:[{asset_id:'firmes-caballito',sha256:'e'.repeat(64),synthetic:false}]},authorized},{claim:{...provenance,brand_assets:[{asset_id:'other-brand',sha256:brandSha,synthetic:false}]},authorized},{claim:{...provenance,brand_assets:[{asset_id:'firmes-caballito',sha256:brandSha,synthetic:true}]},authorized}])assert.throws(()=>captureProviderExecution({provider:'ffmpeg',provenance:value.claim,estimate:{credits:0},assets:[asset],brandAssets:value.authorized,artifactSha,test:false}),{code:'INVALID_PROVENANCE'})})
test('test origin remains explicit and cannot be represented as consumed customer footage',()=>{const execution=captureProviderExecution({provider:'deterministic-test',provenance:{adapter:'deterministic-test',paid:false,synthetic:true,test:true,used_sources:[]},estimate:{credits:0},assets:[],artifactSha,test:true});assert.equal(execution.test,true);assert.equal(execution.provenance.test,true);assert.equal(execution.provenance.synthetic,true);assert.deepEqual(execution.provenance.used_sources,[])})
test('job and tenant-authorized release expose immutable reviewed provenance, not mutable job state',async t=>{const root=await mkdtemp('/tmp/media-projection-');t.after(()=>rm(root,{recursive:true,force:true}));const service=createService({dataRoot:root});service.auth.resolve=async token=>({id:token,memberships:[{tenant_id:token==='outside'?'other':'tenant-one',role:'owner'}]});const execution=capture();const release={id:'release-one',tenant_id:'tenant-one',job_id:'job-one',title:'Approved story',created_at:'2026-09-12T12:00:00Z',version:2,aspect_ratio:'9:16',candidate_sha:sha,artifact_sha256:artifactSha,publication_state:'READY_FOR_MANUAL_PUBLISH',approval:{actor_id:'owner',candidate_sha:sha},provider_execution:execution,source_assets:[asset],reviews:[{actor:'critic',stage:'CRITIC',candidate_sha:sha,created_at:'2026-09-12T12:00:00Z'}],artifacts:[{id:'artifact-one',sha256:artifactSha,mime_type:'video/mp4',size_bytes:3000}]};await service.repository.transact(s=>{s.releases[release.id]=structuredClone(release);s.jobs['job-one']={id:'job-one',tenant_id:'tenant-one',provider_execution:{...execution,provider:'changed-later'},source_asset_snapshot:[asset]};return null});const projected=await service.release('owner','release-one');assert.equal(projected.provider_execution.provider,'ffmpeg');assert.deepEqual(projected.provider_execution.provenance.used_sources,[{source_id:'source-one',sha256:sha}]);assert.equal(projected.reviews[0].scope,'CRITIC');assert.equal(projected.artifacts[0].download_url,'/api/v1/jobs/job-one/artifacts/artifact-one');assert.equal(projected.approval.candidate_sha,projected.candidate_sha);assert.doesNotMatch(JSON.stringify(projected),/private|credentials|token/);const job=publicJob({...release,id:'job-one',source_asset_snapshot:[asset]});assert.equal(job.source_assets[0].width,1080);assert.equal(job.source_assets[0].path,undefined);assert.deepEqual(await service.releases('outside'),[]);await assert.rejects(service.release('outside','release-one'),{code:'NOT_FOUND'});await assert.rejects(service.releases('outside','tenant-one'),{code:'FORBIDDEN'})})
