import test from 'node:test'
import assert from 'node:assert/strict'
import { mkdtemp, readFile, writeFile, rm, symlink } from 'node:fs/promises'
import { join } from 'node:path'
import { randomBytes, scryptSync } from 'node:crypto'
import { createService } from '../server/services.mjs'
import { handleApi } from '../server/http.mjs'
import { AtomicRepository } from '../server/repository.mjs'
import { validatePublicLocator } from '../server/contracts.mjs'
const fixture=async name=>JSON.parse(await readFile(new URL('../examples/'+name,import.meta.url),'utf8'))
async function setup(t){const root=await mkdtemp('/tmp/media-web-services-');t.after(()=>rm(root,{recursive:true,force:true}));const salt=randomBytes(24).toString('hex');const password='  test password kept verbatim  ';const hash=scryptSync(password,Buffer.from(salt,'hex'),64).toString('hex');const users=[{id:'operator',email:'operator@example.com',name:'Operator',password:{salt,hash},can_create_tenants:true,system_admin:true,memberships:[]},{id:'outsider',email:'outsider@example.com',name:'Outside',password:{salt,hash},memberships:[]}];const identityFile=join(root,'identities.json');await writeFile(identityFile,JSON.stringify({users}));const service=createService({dataRoot:join(root,'data'),identityFile,publicOrigin:'http://localhost:3000'});const login=await service.auth.login({email:users[0].email,password});const outside=await service.auth.login({email:users[1].email,password});return {service,token:login.token,outside:outside.token,root,identityFile,users,password}}
async function ready(f){const profile=await fixture('tenant-media-profile.example.json');await f.service.createTenant(f.token,{profile});const observation={schema_version:'reference-observation.v1',id:'ref-01',tenant_id:profile.tenant_id,authorization_id:'reference-page',locator:'https://example.com/reference/',evidence_sha256:'a'.repeat(64),format:'video',pacing:'moderate',branding:'subtle',observed_elements:['community-activity','mascot-character']};const proof=await f.service.uploadReferenceEvidence(f.token,profile.tenant_id,'reference-page',{bytes:Buffer.from('Reference observation evidence from an authorized page'),mime_type:'text/plain'});observation.evidence_sha256=proof.sha256;await f.service.analyzeDNA(f.token,profile.tenant_id,{observations:[observation]});return {id:profile.tenant_id,profile,observation}}
const story={id:'story-01',title:'Community activity',objective:'Document an authorized community activity for a general audience.',source_ids:['authorized-album'],story_devices:['activity-first-story'],strategy:'REAL_FOOTAGE',preferred_provider:'AUTO'}
function req(path,token,body,extra={}){return new Request('http://localhost:3000/api/v1/'+path,{method:body===undefined?'GET':'POST',headers:{...(token?{cookie:'media_factory_session='+token}:{}),...(body===undefined?{}:{origin:'http://localhost:3000','content-type':'application/json'}),...extra},...(body===undefined?{}:{body:JSON.stringify(body)})})}

import { IntegrationVault } from '../server/integration-vault.mjs';
import { chmod, unlink } from 'node:fs/promises';
import { publicJob } from '../server/services.mjs';
import { pageInfo } from '../server/site-metadata.mjs';
test('system API administration requires explicit live authority, not workspace owner or creator',async t=>{const f=await setup(t);await ready(f);assert.equal((await f.service.me(f.token)).manage_integrations,true);await assert.rejects(f.service.integrations(f.outside),{code:'FORBIDDEN'});f.users[0].system_admin=false;await writeFile(f.identityFile,JSON.stringify({users:f.users}));assert.equal((await f.service.me(f.token)).manage_integrations,false);await assert.rejects(f.service.updateIntegration(f.token,'gemini',{api_key:'fixture-key-private'}),{code:'FORBIDDEN'});f.users[0].id='host-operator';f.users[0].system_admin='true';await writeFile(f.identityFile,JSON.stringify({users:f.users}));const login=await f.service.auth.login({email:f.users[0].email,password:f.password});assert.equal((await f.service.me(login.token)).manage_integrations,false)});
test('host operator fallback exposes global administration without granting it to arbitrary configured identities',async t=>{const f=await setup(t);const salt=randomBytes(16),hash=scryptSync('fixture-host-password',salt,32);const service=createService({dataRoot:join(f.root,'host'),operatorUsername:'media-factory',operatorPasswordVerifier:salt.toString('hex')+':'+hash.toString('hex')});const login=await service.auth.login({username:'media-factory',password:'fixture-host-password'});assert.equal(login.user.manage_integrations,true)});
test('credentials persist encrypted, rotate/remove, and never activate adapters or enter product state',async t=>{const f=await setup(t);const secret='fixture-private-api-key-2026';await f.service.updateIntegration(f.token,'gemini',{api_key:secret,budget_reference:12.5});const summary=await f.service.integrations(f.token);assert.equal(summary.providers.find(p=>p.id==='gemini').key_configured,true);assert.equal(summary.providers.find(p=>p.id==='gemini').adapter_available,false);assert.equal(summary.providers.find(p=>p.id==='gemini').connection_status,'NOT_CHECKED');assert.equal(JSON.stringify(summary).includes(secret),false);assert.equal(JSON.stringify(await f.service.repository.read()).includes(secret),false);const vault=new IntegrationVault(f.service.repository.root);assert.equal((await readFile(vault.repository.file,'utf8')).includes(secret),false);assert.equal(await vault.credential('gemini'),secret);await f.service.updateIntegration(f.token,'gemini',{api_key:secret+'-rotated'});assert.equal(await vault.credential('gemini'),secret+'-rotated');await f.service.updateIntegration(f.token,'gemini',{remove_key:true});assert.equal(await vault.credential('gemini'),null);assert.equal((await f.service.integrations(f.token)).audit.length,3)});
test('vault corruption and missing/wrong/symlink keys fail closed without overwriting stored credentials',async t=>{const f=await setup(t);const vault=new IntegrationVault(f.service.repository.root);await f.service.updateIntegration(f.token,'gemini',{api_key:'fixture-private'});const before=await readFile(vault.repository.file,'utf8'),key=await readFile(vault.keyPath);await unlink(vault.keyPath);await assert.rejects(f.service.updateIntegration(f.token,'gemini',{api_key:'fixture-replacement'}),{code:'VAULT_UNAVAILABLE'});assert.equal(await readFile(vault.repository.file,'utf8'),before);await writeFile(vault.keyPath,randomBytes(32),{mode:0o600});await assert.rejects(vault.credential('gemini'),{code:'VAULT_UNAVAILABLE'});await assert.rejects(f.service.updateIntegration(f.token,'gemini',{api_key:'fixture-replacement'}),{code:'VAULT_UNAVAILABLE'});await writeFile(vault.keyPath,key);await chmod(vault.keyPath,0o644);await assert.rejects(vault.credential('gemini'),{code:'VAULT_UNAVAILABLE'});await unlink(vault.keyPath);await symlink(join(f.root,'other-key'),vault.keyPath);await assert.rejects(vault.credential('gemini'),{code:'VAULT_UNAVAILABLE'});assert.equal(await readFile(vault.repository.file,'utf8'),before)});
test('concurrent first vault writes preserve all providers and ciphertext is bound to its provider',async t=>{const f=await setup(t);await Promise.all([f.service.updateIntegration(f.token,'gemini',{api_key:'fixture-gemini'}),f.service.updateIntegration(f.token,'seedance',{api_key:'fixture-seedance'})]);const vault=new IntegrationVault(f.service.repository.root);assert.equal(await vault.credential('gemini'),'fixture-gemini');assert.equal(await vault.credential('seedance'),'fixture-seedance');await vault.repository.transact(s=>{s.integrations.seedance.encrypted=s.integrations.gemini.encrypted;return null});await assert.rejects(vault.credential('seedance'),{code:'VAULT_UNAVAILABLE'})});
test('admin HTTP keeps CSRF, anonymous/outsider denial and rejects unknown endpoints/oversized secret fields',async t=>{const f=await setup(t);assert.equal((await handleApi(req('admin/integrations'),f.service)).status,401);assert.equal((await handleApi(req('admin/integrations',f.outside),f.service)).status,403);assert.equal((await handleApi(req('admin/integrations/gemini',f.token,{api_key:'fixture-key'},{origin:'https://evil.example'}),f.service)).status,403);for(const input of [{api_key:'x'.repeat(4097)},{api_key:'fixture-key',endpoint:'http://localhost'},{budget_reference:-1},{api_key:'fixture-key',remove_key:true}])assert.equal((await handleApi(req('admin/integrations/gemini',f.token,input),f.service)).status,400);assert.equal((await handleApi(req('admin/integrations/unknown',f.token,{api_key:'fixture-key'}),f.service)).status,400)});
test('fictional character/place profiles enforce scope and authorization and freeze in plan/job snapshots',async t=>{const f=await setup(t);const {id}=await ready(f);const draft={kind:'character',name:'Caballito',description:'Mascota ficticia protagonista',reference_url:'https://example.com/horse',rights_confirmed:true,principal:true};await assert.rejects(f.service.saveCreativeProfile(f.outside,id,draft),{code:'FORBIDDEN'});await assert.rejects(f.service.saveCreativeProfile(f.token,id,{...draft,rights_confirmed:false}),{code:'AUTHORIZATION_REQUIRED'});await assert.rejects(f.service.saveCreativeProfile(f.token,id,{...draft,kind:'real-person'}),{code:'INVALID_INPUT'});const character=await f.service.saveCreativeProfile(f.token,id,draft);const place=await f.service.saveCreativeProfile(f.token,id,{kind:'place',name:'Antigua',description:'Un lugar por conocer',reference_url:'https://example.com/place',facts:'Información aportada con referencia.',rights_confirmed:true});const plan=await f.service.createPlan(f.token,id,{week_of:'2026-09-14',stories:[{...story,character_id:character.id,place_id:place.id,mascot:true}]});assert.equal(plan.stories[0].creative_context.character.content_sha,character.content_sha);await f.service.saveCreativeProfile(f.token,id,{...draft,id:character.id,description:'Nueva descripción'});await f.service.approvePlan(f.token,id,plan.id,{story_ids:[story.id]});const [job]=await f.service.launchPlan(f.token,id,plan.id);assert.equal(job.creative_context.character.description,'Mascota ficticia protagonista');assert.equal(job.creative_context.place.information_status,'USER_SOURCED_NOT_INDEPENDENTLY_VERIFIED');assert.equal(job.mascot,undefined);const raw=(await f.service.repository.read()).jobs[job.id];assert.equal(raw.mascot,true);assert.equal(publicJob(raw).creative_context.character.content_sha,character.content_sha);await assert.rejects(f.service.createPlan(f.token,id,{week_of:'2026-09-14',stories:[{...story,character_id:'profile-missing'}]}),{code:'PROFILE_REQUIRED'})});
test('journey distinguishes a registered link, available media, draft, queued work and review without fake progress',async t=>{const f=await setup(t);await f.service.createTenant(f.token,{organization:'Test',tenant_id:'journey-test'});let j=await f.service.journey(f.token,'journey-test');assert.equal(j.requested,0);assert.match(j.next.label,/Agregar/);await f.service.addSource(f.token,'journey-test',{source:{id:'clip',locator:'https://example.org/video',authorization:'explicit',match:'exact',purpose:'source'}});j=await f.service.journey(f.token,'journey-test');assert.equal(j.sources,1);assert.equal(j.uploaded,0);assert.match(j.next.label,/Subir/);await f.service.repository.transact(s=>{s.jobs.fake={id:'fake',tenant_id:'journey-test',title:'Test',status:'BLOCKED',stage:'SOURCE',graph:{nodes:[{status:'done'},{status:'blocked'}]}};return null});j=await f.service.journey(f.token,'journey-test');assert.equal(j.active,0);assert.equal(j.blocked,1);assert.equal(j.recent_jobs[0].completed_stages,1);assert.match(j.next.label,/Resolver/);await assert.rejects(f.service.journey(f.outside,'journey-test'),{code:'FORBIDDEN'})});
test('new admin and profile pages are private metadata routes',()=>{assert.equal(pageInfo(['admin','integrations']).public,false);assert.equal(pageInfo(['workspace','studio-one','creative-profiles']).public,false);assert.equal(pageInfo(['admin','unexpected']),null)});

test('fixer: queued admin writes recheck revoked authority before committing',async t=>{const f=await setup(t);const vault=new IntegrationVault(f.service.repository.root);await f.service.updateIntegration(f.token,'gemini',{budget_reference:5});let release,entered;const started=new Promise(r=>entered=r),hold=new Promise(r=>release=r);const blocker=vault.repository.transact(async()=>{entered();await hold;return null});await started;let observed;const authorized=new Promise(r=>observed=r),resolve=f.service.auth.resolve.bind(f.service.auth);f.service.auth.resolve=async token=>{const actor=await resolve(token);observed();return actor};const pending=f.service.updateIntegration(f.token,'gemini',{api_key:'fixture-revoked'});const denial=assert.rejects(pending,{code:'FORBIDDEN'});await authorized;await new Promise(r=>setImmediate(r));f.users[0].system_admin=false;await writeFile(f.identityFile,JSON.stringify({users:f.users}));release();await blocker;await denial;const summary=await vault.summary();assert.equal(summary.audit.length,1);assert.equal(summary.providers.gemini.key_configured,false)});
test('fixer: explicit budget clear differs from omission',async t=>{const f=await setup(t);await f.service.updateIntegration(f.token,'gemini',{budget_reference:20});await f.service.updateIntegration(f.token,'gemini',{});assert.equal((await f.service.integrations(f.token)).providers.find(p=>p.id==='gemini').budget_reference,20);await f.service.updateIntegration(f.token,'gemini',{budget_reference:null});assert.equal((await f.service.integrations(f.token)).providers.find(p=>p.id==='gemini').budget_reference,null)});
test('fixer: malformed GCM envelopes reject truncated tags IVs and noncanonical encoding',async t=>{const f=await setup(t);await f.service.updateIntegration(f.token,'gemini',{api_key:'fixture-envelope'});const vault=new IntegrationVault(f.service.repository.root),original=structuredClone((await vault.repository.read()).integrations.gemini.encrypted);for(const corrupt of [{...original,tag:Buffer.from(original.tag,'base64').subarray(0,12).toString('base64')},{...original,iv:Buffer.alloc(8).toString('base64')},{...original,value:original.value+' '},{...original,version:2}]){await vault.repository.transact(s=>{s.integrations.gemini.encrypted=corrupt;return null});await assert.rejects(vault.credential('gemini'),{code:'VAULT_UNAVAILABLE'});}await unlink(vault.keyPath);await assert.rejects(vault.key(true),{code:'VAULT_UNAVAILABLE'});await assert.rejects(readFile(vault.keyPath),{code:'ENOENT'})});
test('fixer: Free Mode resolves principal fictional profile and plan links recover exact drafts',async t=>{const f=await setup(t);const {id}=await ready(f);await f.service.repository.transact(s=>{delete s.tenants[id].brand.mascot_asset_key;s.source_assets={[id]:{'authorized-album':{sha256:'a'.repeat(64)}}};return null});const character=await f.service.saveCreativeProfile(f.token,id,{kind:'character',name:'Caballito de Firmes',description:'Mascota autorizada',reference_url:'https://example.com/horse',rights_confirmed:true,principal:true});const draft=await f.service.freeDraft(f.token,id,{text:'Hazme un video con el caballito.',week_of:'2026-09-14'});assert.deepEqual(draft.clarifications,[]);assert.equal(draft.stories[0].character_id,character.id);const plan=await f.service.createPlan(f.token,id,{week_of:'2026-09-14',stories:draft.stories});assert.equal((await f.service.journey(f.token,id)).next.href,'/workspace/'+id+'/weekly?plan='+plan.id);const cleared=await f.service.createPlan(f.token,id,{week_of:'2026-09-14',stories:[{...story,character_id:null,place_id:null,mascot:false}]});assert.equal(cleared.stories[0].creative_context.character,null)});

test('fixer: oversized UTF8 key rejected before storage and permitted maximum remains readable',async t=>{const f=await setup(t);await assert.rejects(f.service.updateIntegration(f.token,'gemini',{api_key:'é'.repeat(4096)}),{code:'INVALID_INPUT'});await f.service.updateIntegration(f.token,'gemini',{api_key:'é'.repeat(2048)});assert.equal(await new IntegrationVault(f.service.repository.root).credential('gemini'),'é'.repeat(2048))});
