import test from 'node:test'
import assert from 'node:assert/strict'
import { mkdtemp, readFile, writeFile, rm, symlink } from 'node:fs/promises'
import { join } from 'node:path'
import { randomBytes, scryptSync } from 'node:crypto'
import { createService } from '../server/services.mjs'
import { handleApi } from '../server/http.mjs'
import { AtomicRepository } from '../server/repository.mjs'
import { validatePublicLocator } from '../server/contracts.mjs'
const fixture=async name=>JSON.parse(await readFile(new URL('../examples/'+name,import.meta.url),'utf8'))
async function setup(t){const root=await mkdtemp('/tmp/media-web-services-');t.after(()=>rm(root,{recursive:true,force:true}));const salt=randomBytes(24).toString('hex');const password='  test password kept verbatim  ';const hash=scryptSync(password,Buffer.from(salt,'hex'),64).toString('hex');const users=[{id:'operator',email:'operator@example.com',name:'Operator',password:{salt,hash},can_create_tenants:true,memberships:[]},{id:'outsider',email:'outsider@example.com',name:'Outside',password:{salt,hash},memberships:[]}];const identityFile=join(root,'identities.json');await writeFile(identityFile,JSON.stringify({users}));const service=createService({dataRoot:join(root,'data'),identityFile,publicOrigin:'http://localhost:3000'});const login=await service.auth.login({email:users[0].email,password});const outside=await service.auth.login({email:users[1].email,password});return {service,token:login.token,outside:outside.token,root,identityFile,users,password}}
async function ready(f){const profile=await fixture('tenant-media-profile.example.json');await f.service.createTenant(f.token,{profile});const observation={schema_version:'reference-observation.v1',id:'ref-01',tenant_id:profile.tenant_id,authorization_id:'reference-page',locator:'https://example.com/reference/',evidence_sha256:'a'.repeat(64),format:'video',pacing:'moderate',branding:'subtle',observed_elements:['community-activity','mascot-character']};const proof=await f.service.uploadReferenceEvidence(f.token,profile.tenant_id,'reference-page',{bytes:Buffer.from('Reference observation evidence from an authorized page'),mime_type:'text/plain'});observation.evidence_sha256=proof.sha256;await f.service.analyzeDNA(f.token,profile.tenant_id,{observations:[observation]});return {id:profile.tenant_id,profile,observation}}
const story={id:'story-01',title:'Community activity',objective:'Document an authorized community activity for a general audience.',source_ids:['authorized-album'],story_devices:['activity-first-story'],strategy:'REAL_FOOTAGE',preferred_provider:'AUTO'}
function req(path,token,body,extra={}){return new Request('http://localhost:3000/api/v1/'+path,{method:body===undefined?'GET':'POST',headers:{...(token?{cookie:'media_factory_session='+token}:{}),...(body===undefined?{}:{origin:'http://localhost:3000','content-type':'application/json'}),...extra},...(body===undefined?{}:{body:JSON.stringify(body)})})}
test('authentication preserves password bytes, revokes changed identity and starts without tenants',async t=>{const f=await setup(t);assert.deepEqual(await f.service.listTenants(f.token),[]);await assert.rejects(f.service.auth.login({email:'operator@example.com',password:f.password.trim()}),{code:'INVALID_CREDENTIALS'});f.users[0].disabled=true;await writeFile(f.identityFile,JSON.stringify({users:f.users}));await assert.rejects(f.service.me(f.token),{code:'UNAUTHENTICATED'})})
test('tenant membership enforced for reads/writes and onboarding has no fake source',async t=>{const f=await setup(t);const tenant=await f.service.createTenant(f.token,{organization:'Studio',tenant_id:'studio-one'});assert.equal(tenant.setup_status,'SOURCE_REQUIRED');assert.deepEqual(tenant.sources,[]);assert.equal(tenant.browser_context_ref,undefined);await assert.rejects(f.service.getTenant(f.outside,'studio-one'),{code:'FORBIDDEN'});await assert.rejects(f.service.addSource(f.outside,'studio-one',{source:{}}),{code:'FORBIDDEN'});await f.service.addSource(f.token,'studio-one',{source:{id:'footage',locator:'https://example.org/film',authorization:'explicit',match:'exact',purpose:'source'}});assert.equal((await f.service.getTenant(f.token,'studio-one')).setup_status,'READY');assert.equal((await f.service.repository.read()).onboarding['studio-one'],undefined)})
test('strict source/reference separation, provenance and secret validation',async t=>{const f=await setup(t);const {id,observation}=await ready(f);await assert.rejects(f.service.createPlan(f.token,id,{week_of:'2026-09-14',stories:[{...story,source_ids:['reference-page']}]}),/purpose=source/);await assert.rejects(f.service.analyzeDNA(f.token,id,{observations:[{...observation,authorization_id:'authorized-album'}]}),{code:'REFERENCE_REQUIRED'});await assert.rejects(f.service.analyzeDNA(f.token,id,{observations:[{...observation,script:'copied text'}]}),{code:'INVALID_CONTRACT'});await assert.rejects(f.service.createTenant(f.token,{organization:'cookie=sessionSecret',tenant_id:'bad-one'}),{code:'SECRET_MATERIAL'})})
test('private, browser and signed source locators are rejected',()=>{for(const url of ['http://localhost:9222','http://127.0.0.1/a','http://169.254.169.254/','https://site.local/file','http://[::1]/','https://example.org/?X-Amz-Credential=secret','https://example.org/?access_token=secret','https://example.org:9222/json'])assert.throws(()=>validatePublicLocator(url),/Source|source|Private|Credential/);assert.equal(validatePublicLocator('https://example.org/public/video'),'https://example.org/public/video')})
test('plans reject injected approval and produce same id under concurrent requests',async t=>{const f=await setup(t);const {id}=await ready(f);await assert.rejects(f.service.createPlan(f.token,id,{week_of:'2026-09-14',stories:[{...story,approved:true}]}),{code:'INVALID_INPUT'});const plans=await Promise.all(Array.from({length:8},()=>f.service.createPlan(f.token,id,{week_of:'2026-09-14',stories:[story]})));assert.equal(new Set(plans.map(p=>p.id)).size,1);assert.equal(plans[0].stories[0].approved,false);await assert.rejects(f.service.launchPlan(f.token,id,plans[0].id),{code:'APPROVAL_REQUIRED'});await f.service.approvePlan(f.token,id,plans[0].id,{story_ids:['story-01']});const jobs=await Promise.all(Array.from({length:5},()=>f.service.launchPlan(f.token,id,plans[0].id)));assert.equal(new Set(jobs.map(v=>v[0].id)).size,1);assert.equal(Object.keys((await f.service.repository.read()).jobs).length,1);assert.equal((await f.service.repository.read()).jobs[jobs[0][0].id].started,true)})
test('source/DNA changes invalidate plans and idempotency includes strategy',async t=>{const f=await setup(t);const {id,observation}=await ready(f);const p=await f.service.createPlan(f.token,id,{week_of:'2026-09-14',stories:[story]});const q=await f.service.createPlan(f.token,id,{week_of:'2026-09-14',stories:[{...story,strategy:'GENERATIVE'}]});assert.notEqual(p.id,q.id);await f.service.analyzeDNA(f.token,id,{observations:[{...observation,pacing:'fast'}]});await assert.rejects(f.service.approvePlan(f.token,id,p.id,{story_ids:['story-01']}),{code:'PLAN_STALE'})})
test('Free Mode exact mixed Spanish example becomes four unapproved concepts, no-AI remains real',async t=>{const f=await setup(t);const {id}=await ready(f);const draft=await f.service.freeDraft(f.token,id,{week_of:'2026-09-14',text:'Hazme cuatro videos para esta semana. Dos con nuestro material real, uno más creativo usando IA y otro con el caballito.'});assert.equal(draft.stories.length,4);assert.deepEqual(draft.stories.map(s=>s.strategy),['REAL_FOOTAGE','REAL_FOOTAGE','GENERATIVE','AUTO']);assert.equal(draft.stories[3].mascot,true);assert.equal(draft.ready_to_save,true);assert.ok(draft.stories.every(s=>s.approved===undefined));assert.equal(Object.keys((await f.service.repository.read()).plans).length,0);for(const text of ['Hazme dos videos, no uses IA','Create two videos without AI','Haz tres videos sin IA'])assert.ok((await f.service.freeDraft(f.token,id,{week_of:'2026-09-14',text})).stories.every(s=>s.strategy==='REAL_FOOTAGE'));const unclear=await f.service.freeDraft(f.token,id,{week_of:'2026-09-14',text:'hola'});assert.equal(unclear.ready_to_save,false)})
test('targeted political or sensitive persuasion cannot enter plans/intent',async t=>{const f=await setup(t);const {id}=await ready(f);for(const text of ['Create two videos to target Catholic voters by religion','Create three videos to persuade undecided elderly women in district X','Haz dos videos para segmentar votantes por religión'])await assert.rejects(f.service.freeDraft(f.token,id,{week_of:'2026-09-14',text}),{code:'AUDIENCE_POLICY'});await assert.rejects(f.service.createPlan(f.token,id,{week_of:'2026-09-14',stories:[{...story,objective:'Target Catholic voters by religion'}]}),{code:'AUDIENCE_POLICY'})})
test('HTTP cookies, CSRF, malformed body, path traversal and safe errors',async t=>{const f=await setup(t);const login=await handleApi(req('auth/login',null,{email:'operator@example.com',password:f.password}),f.service);assert.equal(login.status,200);assert.match(login.headers.get('set-cookie'),/HttpOnly; SameSite=Strict/);assert.equal(login.headers.get('set-cookie').includes('Secure'),false);const csrf=await handleApi(req('tenants',f.token,{organization:'X',tenant_id:'xx'},{origin:'https://evil.example'}),f.service);assert.equal(csrf.status,403);const missing=await handleApi(req('tenants'),f.service);assert.equal(missing.status,401);const injected=await handleApi(req('tenants',f.token,{organization:'X',tenant_id:'xx',role:'owner'}),f.service);assert.equal(injected.status,400);await assert.rejects(f.service.getTenant(f.token,'../escape'),{code:'INVALID_ID'});const bad=new Request('http://localhost:3000/api/v1/tenants',{method:'POST',headers:{origin:'http://localhost:3000','content-type':'application/json'},body:'{'});assert.equal((await handleApi(bad,f.service)).status,400);assert.equal(JSON.stringify(await missing.json()).includes(f.root),false)})
test('repository serializes separate instances and rejects symlink state',async t=>{const root=await mkdtemp('/tmp/media-web-store-');t.after(()=>rm(root,{recursive:true,force:true}));const a=new AtomicRepository(root),b=new AtomicRepository(root);await Promise.all(Array.from({length:20},(_,i)=>(i%2?a:b).transact(s=>{s.counter=(s.counter||0)+1;return s.counter})));assert.equal((await a.read()).counter,20);await rm(join(root,'state.json'));await symlink('/tmp/escape-state.json',join(root,'state.json'));await assert.rejects(a.read(),{code:'UNSAFE_STORAGE'})})
test('SSE rejects unauthorized reads and pushes durable state updates',async t=>{const f=await setup(t);const {id}=await ready(f);const plan=await f.service.createPlan(f.token,id,{week_of:'2026-09-14',stories:[story]});await f.service.approvePlan(f.token,id,plan.id,{story_ids:['story-01']});const [job]=await f.service.launchPlan(f.token,id,plan.id);assert.equal((await handleApi(req('jobs/'+job.id+'/events'),f.service)).status,401);assert.equal((await handleApi(req('jobs/'+job.id+'/events',f.outside),f.service)).status,403);const stream=await handleApi(req('jobs/'+job.id+'/events',f.token),f.service);assert.equal(stream.headers.get('content-type'),'text/event-stream');const reader=stream.body.getReader();const first=new TextDecoder().decode((await reader.read()).value);assert.match(first,/event: product-state/);assert.match(first,/BRIEF/);await f.service.repository.transact(s=>{s.jobs[job.id].status='BLOCKED';return null});const second=new TextDecoder().decode((await reader.read()).value);assert.match(second,/BLOCKED/);await reader.cancel()})
test('HTTP rejects declared and streamed oversized JSON before parsing',async t=>{const f=await setup(t);const large=await handleApi(req('auth/login',null,{}, {'content-length':'300000'}),f.service);assert.equal(large.status,413);const streamed=new Request('http://localhost:3000/api/v1/auth/login',{method:'POST',headers:{origin:'http://localhost:3000','content-type':'application/json'},body:new ReadableStream({start(c){c.enqueue(new Uint8Array(270000));c.close()}}),duplex:'half'});assert.equal((await handleApi(streamed,f.service)).status,413)})
test('viewer cannot approve concepts and configured identity roles override persisted memberships',async t=>{const f=await setup(t);const {id}=await ready(f);const plan=await f.service.createPlan(f.token,id,{week_of:'2026-09-14',stories:[story]});f.users[0].memberships=[{tenant_id:id,role:'viewer'}];await writeFile(f.identityFile,JSON.stringify({users:f.users}));assert.equal((await f.service.getTenant(f.token,id)).role,'viewer');await assert.rejects(f.service.approvePlan(f.token,id,plan.id,{story_ids:['story-01']}),{code:'FORBIDDEN'});await assert.rejects(f.service.createPlan(f.token,id,{week_of:'2026-09-14',stories:[story]}),{code:'FORBIDDEN'})})
test('reference DNA requires evidence bytes actually stored for the selected reference',async t=>{const f=await setup(t);const {id,observation}=await ready(f);await assert.rejects(f.service.analyzeDNA(f.token,id,{observations:[{...observation,evidence_sha256:'b'.repeat(64)}]}),{code:'EVIDENCE_REQUIRED'});await assert.rejects(f.service.uploadReferenceEvidence(f.outside,id,'reference-page',{bytes:Buffer.from('proof'),mime_type:'text/plain'}),{code:'FORBIDDEN'});await assert.rejects(f.service.uploadReferenceEvidence(f.token,id,'authorized-album',{bytes:Buffer.from('proof'),mime_type:'text/plain'}),{code:'REFERENCE_REQUIRED'})})
test('malformed durable state fails closed with controlled storage error',async t=>{const root=await mkdtemp('/tmp/media-web-corrupt-');t.after(()=>rm(root,{recursive:true,force:true}));await writeFile(join(root,'state.json'),JSON.stringify({version:1,tenants:{},jobs:{}}));await assert.rejects(new AtomicRepository(root).read(),{code:'STORAGE_UNAVAILABLE'})})
test('ProductError identity remains stable across independently evaluated server bundles',async()=>{const first=await import('../server/errors.mjs');const second=await import('../server/errors.mjs?bundle=isolated-regression');assert.equal(first.ProductError,second.ProductError);assert.ok(new second.ProductError('UNAUTHENTICATED','Sign in',401) instanceof first.ProductError)})
test('stored reference evidence tampering invalidates DNA analysis',async t=>{const f=await setup(t);const {id,observation}=await ready(f);await writeFile(join(f.service.repository.root,'reference-evidence',id,observation.evidence_sha256),'changed proof');await assert.rejects(f.service.analyzeDNA(f.token,id,{observations:[observation]}),{code:'EVIDENCE_CHANGED'})})
test('mascot setup binds a selected production source and rejects a reference',async t=>{const f=await setup(t);const {id}=await ready(f);await assert.rejects(f.service.setMascot(f.token,id,{source_id:'reference-page'}),{code:'SOURCE_REQUIRED'});const tenant=await f.service.setMascot(f.token,id,{source_id:'authorized-album'});assert.equal(tenant.brand.mascot_asset_key,'source:authorized-album');await assert.rejects(f.service.setMascot(f.outside,id,{source_id:'authorized-album'}),{code:'FORBIDDEN'})})
test('Free Mode respects indirect AI negations and explicit alternative distributions',async t=>{const f=await setup(t);const {id}=await ready(f);for(const text of ['Hazme dos videos sin usar IA.','Hazme dos videos, no utilices IA.','Create two videos without using AI.']){const draft=await f.service.freeDraft(f.token,id,{week_of:'2026-09-14',text});assert.ok(draft.stories.every(s=>s.strategy==='REAL_FOOTAGE'),text)}for(const [text,expected] of [['Hazme cuatro videos: dos con IA y dos con material real.',['GENERATIVE','GENERATIVE','REAL_FOOTAGE','REAL_FOOTAGE']],['Hazme cuatro videos. Uno real y tres usando IA.',['REAL_FOOTAGE','GENERATIVE','GENERATIVE','GENERATIVE']]]){const draft=await f.service.freeDraft(f.token,id,{week_of:'2026-09-14',text});assert.equal(draft.ready_to_save,true,text);assert.deepEqual(draft.stories.map(s=>s.strategy),expected,text)}const unclear=await f.service.freeDraft(f.token,id,{week_of:'2026-09-14',text:'Hazme cuatro videos: dos con IA y uno real.'});assert.equal(unclear.ready_to_save,false)})
test('login concurrency limit reserves capacity before awaiting identity loading',async t=>{const f=await setup(t);const original=f.service.auth.identities.bind(f.service.auth);let max=0;f.service.auth.identities=async()=>{max=Math.max(max,f.service.auth.activeLogins);await new Promise(r=>setTimeout(r,15));return original()};const results=await Promise.allSettled(Array.from({length:12},(_,i)=>f.service.auth.login({email:'unknown'+i+'@example.org',password:'wrong password'})));assert.equal(max,4);assert.equal(results.filter(r=>r.status==='rejected'&&r.reason.code==='RATE_LIMITED').length,8);assert.equal(f.service.auth.activeLogins,0)})
test('legacy planner contract rejection returns a controlled HTTP 400',async t=>{const f=await setup(t);const {id}=await ready(f);const invalid={...story,story_devices:[]};const result=await handleApi(req('tenants/'+id+'/weekly-plans',f.token,{week_of:'2026-09-14',stories:[invalid]}),f.service);assert.equal(result.status,400);const body=await result.json();assert.equal(body.error.code,'INVALID_PLAN');assert.match(body.error.message,/Content DNA device/)})


test('FIRMES avatar catalog and MCP-ready tool definitions stay membership-bound over HTTP',async t=>{
 const f=await setup(t)
 const profile={schema_version:'tenant-media-profile.v1',tenant_id:'firmes-avatar-api',organization:'FIRMES Avatar API',territory:'Guatemala',runtime_namespace:'firmes-avatar-api',browser_context_ref:'firmes-avatar-api-browser',content_context:'community',audience_policy:{mode:'general-audience',sensitive_trait_targeting:false,voter_microtargeting:false},brand:{display_name:'FIRMES',identity_key:'firmes',visual_language:'FIRMES burgundy'},sources:[{id:'authorized-source',locator:'https://example.org/firmes-avatar',authorization:'explicit',match:'exact',purpose:'source'}],production_defaults:{aspect_ratio:'9:16',cadence:'weekly',duration_seconds:[5,15]}}
 await f.service.createTenant(f.token,{profile})
 const catalogResponse=await handleApi(req('tenants/firmes-avatar-api/avatar-catalog',f.token),f.service)
 assert.equal(catalogResponse.status,200)
 const catalog=(await catalogResponse.json()).data
 assert.equal(catalog.enabled,true)
 assert.equal(catalog.outfits.length,5)
 assert.equal(catalog.accessories.length,10)
 assert.equal(catalog.motion_profile.mode,'GENERATIVE_MOTION')
 const toolsResponse=await handleApi(req('tenants/firmes-avatar-api/avatar-mcp-tools',f.token),f.service)
 assert.equal(toolsResponse.status,200)
 assert.deepEqual((await toolsResponse.json()).data.tools.map(v=>v.name),['avatar.catalog','avatar.compile','avatar.critic_plan'])
 assert.equal((await handleApi(req('tenants/firmes-avatar-api/avatar-catalog',f.outside),f.service)).status,403)
})
