import test from 'node:test'
import assert from 'node:assert/strict'
import {mkdtemp,rm,writeFile,readFile} from 'node:fs/promises'
import {join} from 'node:path'
import {tmpdir} from 'node:os'
import {randomBytes,scryptSync} from 'node:crypto'
import {createService} from '../server/services.mjs'
import {handleApi} from '../server/http.mjs'

async function fixture(t){
 const root=await mkdtemp(join(tmpdir(),'media-v11-local-'));t.after(()=>rm(root,{recursive:true,force:true}))
 const salt=randomBytes(24).toString('hex'),password='owner-password-v11',hash=scryptSync(password,Buffer.from(salt,'hex'),64).toString('hex'),identityFile=join(root,'identities.json')
 await writeFile(identityFile,JSON.stringify({users:[{id:'owner',email:'owner@example.com',name:'Owner',password:{salt,hash},can_create_tenants:true,system_admin:true,memberships:[]}]}))
 const service=createService({dataRoot:join(root,'data'),identityFile,publicOrigin:'https://media.example.org'}),owner=(await service.auth.login({email:'owner@example.com',password})).token
 await service.createTenant(owner,{organization:'FIRMES Antigua',tenant_id:'firmes-antigua',territory:'Antigua Guatemala',content_context:'community',visual_language:'documental'})
 await service.createTenant(owner,{organization:'FIRMES Jocotenango',tenant_id:'firmes-jocotenango',territory:'Jocotenango',content_context:'community',visual_language:'documental'})
 return{root,service,owner,password}
}

async function localId(service,email){const state=await service.repository.read(),account=Object.values(state.local_accounts||{}).find(v=>v.email===email);assert.ok(account);return account.id}

const request=(path,body)=>new Request('https://media.example.org/api/v1/'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{origin:'https://media.example.org','content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)})

test('municipality catalog is public and exposes only the entry labels needed before authentication',async t=>{
 const f=await fixture(t),response=await handleApi(request('auth/municipalities'),f.service);assert.equal(response.status,200);const data=(await response.json()).data;assert.deepEqual(data.map(v=>v.municipality),['Antigua Guatemala','Jocotenango']);assert.deepEqual(Object.keys(data[0]).sort(),['municipality','organization','tenant_id'])
})

test('self-registration stores no plaintext DPI and remains pending without a membership',async t=>{
 const f=await fixture(t),dpi='1234 56789 0101',plain='1234567890101',response=await f.service.auth.register({name:'Ana Demo',email:'ana@example.com',dpi,password:'very-secure-password',tenant_id:'firmes-antigua'});assert.deepEqual(response,{status:'REQUEST_RECEIVED',tenant_id:'firmes-antigua'});const state=await f.service.repository.read(),stored=Object.values(state.local_accounts).find(v=>v.email==='ana@example.com');assert.ok(stored);assert.equal(stored.dpi_last4,'0101');assert.equal(stored.status,'PENDING_APPROVAL');assert.deepEqual(state.memberships[stored.id],[]);assert.match(stored.dpi_lookup,/^[a-f0-9]{64}$/);assert.equal(stored.dpi_lookup.includes(plain),false);assert.equal(JSON.stringify(state).includes(plain),false);assert.equal((await readFile(join(f.root,'data','.local-account-pepper'))).length,32);await assert.rejects(f.service.auth.login({identifier:'ana@example.com',password:'very-secure-password',tenant_id:'firmes-antigua'}),e=>e.code==='ACCOUNT_PENDING_APPROVAL');await assert.rejects(f.service.auth.login({identifier:plain,password:'very-secure-password',tenant_id:'firmes-antigua'}),e=>e.code==='ACCOUNT_PENDING_APPROVAL')
})

test('pending registration is visible only to managers of the requested municipality and approval assigns an explicit role',async t=>{
 const f=await fixture(t);await f.service.auth.register({name:'Editor Local',email:'editor.local@example.com',dpi:'1234567890102',password:'editor-password-v11',tenant_id:'firmes-antigua'});const userId=await localId(f.service,'editor.local@example.com');let antigua=await f.service.team(f.owner,'firmes-antigua'),jocotenango=await f.service.team(f.owner,'firmes-jocotenango');assert.equal(antigua.registrations.length,1);assert.equal(antigua.registrations[0].user_id,userId);assert.equal(antigua.registrations[0].dpi_last4,'0102');assert.equal(jocotenango.registrations.length,0);await f.service.approveRegistration(f.owner,'firmes-antigua',userId,{responsibility:'editor'});antigua=await f.service.team(f.owner,'firmes-antigua');assert.equal(antigua.registrations.length,0);const member=antigua.members.find(v=>v.user_id===userId);assert.equal(member.role,'editor');assert.equal(member.account_type,'self_service');const login=await f.service.auth.login({identifier:'editor.local@example.com',password:'editor-password-v11',tenant_id:'firmes-antigua'});assert.equal(login.user.current_tenant_id,'firmes-antigua');assert.equal(login.user.memberships.find(v=>v.tenant_id==='firmes-antigua').role,'editor');await assert.rejects(f.service.auth.login({identifier:'editor.local@example.com',password:'editor-password-v11',tenant_id:'firmes-jocotenango'}),e=>e.code==='ACCESS_NOT_APPROVED')
})

test('approved account can authenticate by DPI, and membership removal invalidates municipality-bound sessions',async t=>{
 const f=await fixture(t),dpi='1234567890103';await f.service.auth.register({name:'Consulta Local',email:'consulta@example.com',dpi,password:'consulta-password-v11',tenant_id:'firmes-antigua'});const userId=await localId(f.service,'consulta@example.com');await f.service.approveRegistration(f.owner,'firmes-antigua',userId,{responsibility:'viewer'});const login=await f.service.auth.login({identifier:dpi,password:'consulta-password-v11',tenant_id:'firmes-antigua'});assert.equal(login.user.email,'consulta@example.com');assert.equal(login.user.memberships[0].role,'viewer');await f.service.removeTeamMember(f.owner,'firmes-antigua',userId);await assert.rejects(f.service.auth.resolve(login.token),e=>e.code==='UNAUTHENTICATED');await assert.rejects(f.service.auth.login({identifier:dpi,password:'consulta-password-v11',tenant_id:'firmes-antigua'}),e=>e.code==='ACCESS_NOT_APPROVED')
})

test('rejected accounts stay denied and approval inputs use the same non-owner role allowlist',async t=>{
 const f=await fixture(t);await f.service.auth.register({name:'Rejected Local',email:'rejected@example.com',dpi:'1234567890104',password:'rejected-password-v11',tenant_id:'firmes-antigua'});const userId=await localId(f.service,'rejected@example.com');for(const role of ['owner','__proto__','constructor'])await assert.rejects(f.service.approveRegistration(f.owner,'firmes-antigua',userId,{responsibility:role}),e=>e.code==='INVALID_ROLE');await f.service.rejectRegistration(f.owner,'firmes-antigua',userId);await assert.rejects(f.service.auth.login({identifier:'rejected@example.com',password:'rejected-password-v11',tenant_id:'firmes-antigua'}),e=>e.code==='ACCESS_NOT_APPROVED');const state=await f.service.repository.read();assert.equal(state.local_accounts[userId].status,'REJECTED');assert.deepEqual(state.memberships[userId],[])
})

test('registration validates email, 13-digit DPI, password strength, municipality, and duplicate identity',async t=>{
 const f=await fixture(t),base={name:'Valid Person',email:'valid@example.com',dpi:'1234567890105',password:'valid-password-v11',tenant_id:'firmes-antigua'};await assert.rejects(f.service.auth.register({...base,dpi:'123'}),e=>e.code==='INVALID_DPI');await assert.rejects(f.service.auth.register({...base,password:'short'}),e=>e.code==='WEAK_PASSWORD');await assert.rejects(f.service.auth.register({...base,email:'bad-email'}),e=>e.code==='INVALID_EMAIL');await assert.rejects(f.service.auth.register({...base,tenant_id:'unknown-municipality'}),e=>e.code==='INVALID_MUNICIPALITY');const first=await f.service.auth.register(base),before=Object.keys((await f.service.repository.read()).local_accounts).length;assert.deepEqual(first,{status:'REQUEST_RECEIVED',tenant_id:'firmes-antigua'});for(const duplicate of [{...base,dpi:'1234567890106'},{...base,email:'other@example.com'},{...base,email:'owner@example.com',dpi:'1234567890107'}])assert.deepEqual(await f.service.auth.register(duplicate),{status:'REQUEST_RECEIVED',tenant_id:'firmes-antigua'});assert.equal(Object.keys((await f.service.repository.read()).local_accounts).length,before)
})

test('HTTP registration and login accept the new contract while legacy configured operator login remains compatible',async t=>{
 const f=await fixture(t);let response=await handleApi(request('auth/register',{name:'HTTP Local',email:'http@example.com',dpi:'1234567890108',password:'http-password-v11',tenant_id:'firmes-antigua'}),f.service);assert.equal(response.status,201);const created=(await response.json()).data;assert.deepEqual(created,{status:'REQUEST_RECEIVED',tenant_id:'firmes-antigua'});const userId=await localId(f.service,'http@example.com');await f.service.approveRegistration(f.owner,'firmes-antigua',userId,{responsibility:'viewer'});response=await handleApi(request('auth/login',{identifier:'1234567890108',password:'http-password-v11',tenant_id:'firmes-antigua'}),f.service);assert.equal(response.status,200);assert.match(response.headers.get('set-cookie'),/media_factory_session=/);const legacy=await f.service.auth.login({email:'owner@example.com',password:f.password});assert.equal(legacy.user.id,'owner')
})

test('V11 login and Team UI expose municipality registration, DPI privacy copy and admin approval controls',async()=>{
 const login=await readFile('components/StudioEntry.tsx','utf8'),team=await readFile('components/Team.tsx','utf8');assert.match(login,/Correo o DPI/);assert.match(login,/DPI guatemalteco/);assert.match(login,/Municipio/);assert.match(login,/Crear cuenta/);assert.match(login,/PENDING|pendiente/i);assert.match(login,/no consulta RENAP/i);assert.match(team,/Solicitudes pendientes/);assert.match(team,/Aprobar/);assert.match(team,/Rechazar/);assert.ok(team.includes('Correo/DPI + contraseña'))
})

test('approved IT account can authorize another local request while private credential material stays server-side',async t=>{
 const f=await fixture(t);await f.service.auth.register({name:'IT Local',email:'it.local@example.com',dpi:'1234567890109',password:'it-local-password-v11',tenant_id:'firmes-antigua'});const itId=await localId(f.service,'it.local@example.com');await f.service.approveRegistration(f.owner,'firmes-antigua',itId,{responsibility:'it'});const it=await f.service.auth.login({identifier:'it.local@example.com',password:'it-local-password-v11',tenant_id:'firmes-antigua'});await f.service.auth.register({name:'Second Local',email:'second.local@example.com',dpi:'1234567890110',password:'second-local-password-v11',tenant_id:'firmes-antigua'});const pendingId=await localId(f.service,'second.local@example.com'),itView=await f.service.team(it.token,'firmes-antigua');assert.equal(itView.can_manage,true);assert.ok(itView.registrations.some(v=>v.user_id===pendingId));const serialized=JSON.stringify(itView);assert.equal(serialized.includes('dpi_lookup'),false);assert.equal(serialized.includes('password'),false);assert.equal(serialized.includes('1234567890110'),false);await f.service.approveRegistration(it.token,'firmes-antigua',pendingId,{responsibility:'viewer'});const login=await f.service.auth.login({identifier:'second.local@example.com',password:'second-local-password-v11',tenant_id:'firmes-antigua'});assert.equal(login.user.memberships[0].role,'viewer')
})

test('pending registration queue is bounded per municipality without weakening duplicate privacy',async t=>{
 const f=await fixture(t);await f.service.repository.transact(state=>{for(let i=0;i<100;i++){const id='local_queue_'+String(i).padStart(3,'0');state.local_accounts[id]={id,name:'Queued '+i,email:'queued-'+i+'@example.com',dpi_lookup:String(i).padStart(64,'a').slice(-64),dpi_last4:String(i).padStart(4,'0'),password:{salt:'00'.repeat(24),hash:'00'.repeat(64)},status:'PENDING_APPROVAL',requested_tenant_id:'firmes-antigua',requested_at:new Date().toISOString(),created_at:new Date().toISOString()};state.memberships[id]=[]}return null});await assert.rejects(f.service.auth.register({name:'Queue Overflow',email:'overflow@example.com',dpi:'1234567890112',password:'overflow-password-v11',tenant_id:'firmes-antigua'}),e=>e.code==='REGISTRATION_QUEUE_FULL');const duplicate=await f.service.auth.register({name:'Existing Queue',email:'queued-1@example.com',dpi:'1234567890113',password:'duplicate-password-v11',tenant_id:'firmes-antigua'});assert.deepEqual(duplicate,{status:'REQUEST_RECEIVED',tenant_id:'firmes-antigua'})
})
