import test from 'node:test'
import assert from 'node:assert/strict'
import { pageInfo,pageMetadata,publicOrigin,robotsMetadata,sitemapMetadata,llmsText } from '../server/site-metadata.mjs'
const preview={MEDIA_FACTORY_PUBLIC_ORIGIN:'https://studio.example.org',MEDIA_FACTORY_DEPLOYMENT_CLASS:'controlled_single_operator_preview'}
const production={...preview,MEDIA_FACTORY_DEPLOYMENT_CLASS:'production',MEDIA_FACTORY_PUBLIC_INDEXING:'1'}
test('only explicitly published HTTPS production login enters the index and sitemap',()=>{for(const env of [preview,{...preview,MEDIA_FACTORY_PUBLIC_INDEXING:'1'},{...production,MEDIA_FACTORY_PUBLIC_INDEXING:'0'},{...production,MEDIA_FACTORY_PUBLIC_ORIGIN:'http://studio.example.org'}]){assert.equal(pageMetadata(['login'],env).robots.index,false);assert.deepEqual(sitemapMetadata(env),[]);assert.equal(robotsMetadata(env).rules.disallow,'/');assert.equal(robotsMetadata(env).rules.allow,undefined)}assert.equal(pageMetadata(['login'],production).robots.index,true);assert.deepEqual(sitemapMetadata(production),[{url:'https://studio.example.org/login'}]);assert.equal(robotsMetadata(production).rules.allow,'/login$')})
test('private routes never put tenant or job identities into metadata, canonicals, or sitemap',()=>{const paths=[[],['dashboard'],['workspaces'],['review'],['releases'],['jobs','private-job-name'],['workspace','private-tenant-name','sources'],['workspace','private-tenant-name','content-dna'],['workspace','private-tenant-name','weekly'],['workspace','private-tenant-name','free']];const titles=new Set();for(const path of paths){const meta=pageMetadata(path,production);assert.equal(meta.robots.index,false);assert.equal(meta.alternates,undefined);assert.equal(meta.openGraph.url,undefined);assert.doesNotMatch(JSON.stringify(meta),/private-job-name|private-tenant-name/);titles.add(meta.title)}assert.equal(titles.size,9)})
test('canonical metadata uses only validated operator origin and ignores URL injection',()=>{const meta=pageMetadata(['login'],production);assert.equal(meta.alternates.canonical,'https://studio.example.org/login');assert.equal(meta.openGraph.images[0].url,'https://studio.example.org/opengraph-image');for(const origin of ['javascript:alert(1)','https://user:secret@example.org','https://example.org/?token=secret','https://example.org/private/path','https://example.org/#secret','not-a-url']){const env={...production,MEDIA_FACTORY_PUBLIC_ORIGIN:origin};assert.equal(publicOrigin(env),null);assert.equal(pageMetadata(['login'],env).alternates,undefined);assert.deepEqual(sitemapMetadata(env),[])}})
test('catchall rejects unknown or overlong route shapes without reflecting submitted names',()=>{for(const segments of [['constructor'],['toString'],['__proto__'],['workspace','valid-id','constructor'],['workspace','valid-id','toString'],['workspace','valid-id','__proto__'],['does-not-exist'],['dashboard','extra'],['login','anything'],['workspace'],['workspace','valid-id','unknown'],['workspace','valid-id','weekly','extra'],['jobs'],['jobs','../private'],['jobs','id','extra']]){assert.equal(pageInfo(segments),null);const meta=pageMetadata(segments,production);assert.equal(meta.title,'Página no encontrada');assert.equal(meta.robots.index,false);assert.doesNotMatch(meta.description,/does-not-exist|\.\.\/private/)}})
test('llms discovery lists public product facts without private resources or invented integrations',()=>{const text=llmsText(preview);assert.match(text,/^# Media Factory/);assert.match(text,/https:\/\/studio\.example\.org\/login/);assert.match(text,/requieren autorización/);assert.doesNotMatch(text,/\/workspace\/|\/jobs\/|\/api\/|token=|Higgsfield.*disponible/);assert.match(text,/Liberar una entrega no la publica/)})

test('job review route resolves safely and production indexing rejects infrastructure origins',()=>{assert.equal(pageInfo(['jobs','private-job','review']).title,'Revisión de producción');assert.equal(pageInfo(['jobs','private-job','studio']).title,'Studio de producción');assert.equal(pageMetadata(['jobs','private-job','studio'],production).robots.index,false);assert.equal(pageMetadata(['jobs','private-job','review'],production).robots.index,false);assert.doesNotMatch(JSON.stringify(pageMetadata(['jobs','private-job','review'],production)),/private-job/);for(const origin of ['https://localhost','https://127.0.0.1','https://127.1','https://0x7f000001','https://10.1.2.3','https://172.16.1.2','https://192.168.1.1','https://169.254.169.254','https://[::1]','https://[::ffff:127.0.0.1]','https://[fe80::1]','https://service.local','https://service.internal','https://studio.example.org:9222']){const env={...production,MEDIA_FACTORY_PUBLIC_ORIGIN:origin};assert.equal(publicOrigin(env),null,origin);assert.equal(pageMetadata(['login'],env).robots.index,false,origin);assert.deepEqual(sitemapMetadata(env),[],origin)}assert.equal(publicOrigin({MEDIA_FACTORY_PUBLIC_ORIGIN:'http://127.0.0.1:4188',MEDIA_FACTORY_DEPLOYMENT_CLASS:'test'}),'http://127.0.0.1:4188')})

test('published OG and Twitter image use only the controlled imported application asset',()=>{const path='/_next/static/media/media-factory-og.abc123.png',meta=pageMetadata(['login'],production,path);assert.equal(meta.openGraph.images[0].url,'https://studio.example.org'+path);assert.deepEqual(meta.twitter.images,['https://studio.example.org'+path]);for(const input of ['https://outside.example/image.png','//outside.example/image.png','/_next/static/media/../secret.png','/_next/static/media/image.png?token=secret'])assert.throws(()=>pageMetadata(['login'],production,input),/controlled application asset/)})
