import test from 'node:test'
import assert from 'node:assert/strict'
import { mkdtemp, readFile, writeFile, mkdir } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { AtomicRepository } from '../server/repository.mjs'
import { withJobLease } from '../server/worker-lock.mjs'
import { publicJob } from '../server/services.mjs'
import { ExecutionService } from '../server/execution.mjs'
import { digest, GRAPH_REVISION } from '../server/worker-policy.mjs'
import { execFile as callback } from 'node:child_process'
import { promisify } from 'node:util'
import { inspectVideo, FFmpegAdapter } from '../server/worker-adapters.mjs'
import { normalizeAudioFinishingContract } from '../server/audio-finishing.mjs'
const execFile=promisify(callback)
const runtime=process.env.GRAPH_HARNESS_RUNTIME_ROOT||'/home/agent/.cache/media-content-harness/graph-harness-sdlc'
const actor={id:'owner',memberships:[{tenant_id:'tenant-a',role:'owner'}]}
async function fixture(options={}){const root=await mkdtemp(join(tmpdir(),'media-web-execution-'));const repository=new AtomicRepository(root);const source={id:'real-source',locator:'https://example.com/authorized',purpose:'source',authorization:'explicit',match:'exact'};await repository.transact(s=>{s.tenants['tenant-a']={tenant_id:'tenant-a',sources:[source]};s.dna['tenant-a']={revision:'dna-1'};s.jobs['job-one']={id:'job-one',tenant_id:'tenant-a',title:'A real story',objective:'Show our work',source_ids:[source.id],story_devices:['activity-first-story'],strategy:'REAL_FOOTAGE',preferred_provider:'AUTO',target:{aspect_ratio:'9:16',duration_seconds:[1,2]},source_authorization_snapshot:[source],content_dna_revision:'dna-1',status:'BRIEF',stage:'BRIEF',artifacts:[],evidence:[],approvals:[],blockers:[],created_by:'owner'};return null});const service=new ExecutionService({repository,dataRoot:root,graphRuntimeRoot:runtime,testMode:true,deploymentClass:'test',releaseSha:'a'.repeat(40),...options});assert.equal((await service.health()).graph,true,'Mandatory pinned Graph runtime must be available; this test must not skip');return {root,repository,service,source}}
async function runToReview(f){await f.service.start(actor,'job-one');await f.service.drain();return (await f.repository.read()).jobs['job-one']}
async function approve(f){const j=(await f.repository.read()).jobs['job-one'];const value=await f.service.approve(actor,j.id,{candidate_sha:j.candidate_sha,review_stage:j.stage});await f.service.drain();return (await f.repository.read()).jobs[j.id]}
test('actual pinned Graph runs to hash-bound treatment and release; fixture evidence stays test-labeled',async()=>{const f=await fixture();let j=await runToReview(f);assert.equal(j.status,'AWAITING_REVIEW',JSON.stringify(j.blockers));assert.equal(j.stage,'CREATIVE_GATE');assert.equal(publicJob(j).test,true);assert.equal(j.graph.runtime_revision,GRAPH_REVISION);await assert.rejects(f.service.approve(actor,j.id,{}),e=>e.code==='STALE_CANDIDATE');j=await approve(f);assert.equal(j.status,'AWAITING_REVIEW',JSON.stringify(j.blockers));assert.equal(j.stage,'RELEASE');assert.match(j.artifact_url,/^\/api\/v1\/jobs\//);const data=await f.service.artifact(actor,j.id,j.artifacts.at(-1).id);assert.equal(digest(data.bytes),j.artifact_sha256);j=await approve(f);assert.equal(j.status,'RELEASED');assert.equal(publicJob(j).test,true);assert.ok(j.graph.nodes.every(n=>n.status==='done'));assert.ok(j.evidence.every(e=>e.test===true));const release=Object.values((await f.repository.read()).releases)[0];assert.equal(release.test,true);assert.equal(release.artifacts.length,1);const lines=(await readFile(join(f.root,'graph/tenant-a/job-one/events.jsonl'),'utf8')).trim().split('\n').map(JSON.parse);assert.ok(lines.some(e=>e.event_type==='approval.recorded'));assert.ok(lines.some(e=>e.event_type==='gate.evaluated'));})
test('cross-tenant actions and artifacts fail before data access; viewers cannot approve',async()=>{const f=await fixture();const j=await runToReview(f);const outsider={id:'other',memberships:[{tenant_id:'tenant-b',role:'owner'}]};await assert.rejects(f.service.start(outsider,j.id),e=>e.code==='FORBIDDEN');await assert.rejects(f.service.artifact(outsider,j.id,'artifact_abc'),e=>e.code==='NOT_FOUND');await assert.rejects(f.service.approve({id:'view',memberships:[{tenant_id:'tenant-a',role:'viewer'}]},j.id,{candidate_sha:j.candidate_sha,review_stage:j.stage}),e=>e.code==='FORBIDDEN')})
test('localized repair invalidates candidate and descendants while preserving ingested upstream',async()=>{const f=await fixture();let j=await runToReview(f);const old=j.candidate_sha;await f.service.requestChanges(actor,j.id,{candidate_sha:old,review_stage:j.stage,reason:'Use a warmer opening'});await f.service.drain();j=(await f.repository.read()).jobs[j.id];assert.equal(j.stage,'CREATIVE_GATE');assert.equal(j.status,'AWAITING_REVIEW',JSON.stringify(j.blockers));assert.notEqual(j.candidate_sha,old);assert.ok(j.graph.nodes.filter(n=>['BRIEF','SOURCE','INGEST'].includes(n.id)).every(n=>n.status==='done'&&n.revision===0));assert.equal(j.graph.repair_plan_count,1);await assert.rejects(f.service.approve(actor,j.id,{candidate_sha:old,review_stage:j.stage}),e=>e.code==='STALE_CANDIDATE')})
test('source authorization and DNA changes invalidate human approval',async()=>{const f=await fixture();const j=await runToReview(f);await f.repository.transact(s=>{s.tenants['tenant-a'].sources[0].locator='https://example.com/replaced';return null});await assert.rejects(f.service.approve(actor,j.id,{candidate_sha:j.candidate_sha,review_stage:j.stage}),e=>e.code==='SOURCE_CHANGED');await f.repository.transact(s=>{s.tenants['tenant-a'].sources[0]=f.source;s.dna['tenant-a'].revision='dna-2';return null});await assert.rejects(f.service.approve(actor,j.id,{candidate_sha:j.candidate_sha,review_stage:j.stage}),e=>e.code==='DNA_CHANGED')})
test('restart recovery and double start preserve one Graph history',async()=>{const f=await fixture();await f.repository.transact(s=>{s.jobs['job-one'].started=true;s.jobs['job-one'].status='RUNNING';return null});await f.service.recover();f.service.onJobsQueued(['job-one','job-one']);await f.service.drain();const j=(await f.repository.read()).jobs['job-one'];assert.equal(j.status,'AWAITING_REVIEW',JSON.stringify(j.blockers));const before=j.graph.event_count;const next=new ExecutionService({repository:f.repository,dataRoot:f.root,graphRuntimeRoot:runtime,testMode:true,deploymentClass:'test'});assert.deepEqual(await next.recover(),{queued:0});await Promise.all([next.start(actor,j.id),next.start(actor,j.id)]);await next.drain();assert.equal((await f.repository.read()).jobs[j.id].graph.event_count,before)})
test('production missing source bytes is blocked in actual Graph, no fixture adapter exposed',async()=>{const f=await fixture({testMode:false,deploymentClass:'controlled_single_operator_preview'});assert.ok(!f.service.providers.list().some(p=>p.id==='deterministic-test'));let j=await runToReview(f);assert.equal(j.status,'BLOCKED');assert.equal(j.blockers[0].code,'SOURCE_BYTES_REQUIRED');assert.deepEqual(j.blockers[0].source_ids,['real-source']);assert.equal(publicJob(j).test,false);assert.deepEqual(publicJob(j).blockers[0].source_ids,['real-source']);const state=await f.service.service().status(f.service.paths(j));assert.equal(state.nodes.find(n=>n.id==='INGEST').status,'blocked');assert.ok(!j.evidence.some(e=>['CRITIC','INDEPENDENT_VERIFIER'].includes(e.stage)));assert.throws(()=>new ExecutionService({repository:f.repository,dataRoot:f.root,graphRuntimeRoot:runtime,testMode:true,deploymentClass:'production'}),e=>e.code==='TEST_MODE_FORBIDDEN')})

test('blocked production resumes the same Graph after its missing authorized video is uploaded',async()=>{const f=await fixture({testMode:false,deploymentClass:'controlled_single_operator_preview'});let j=await runToReview(f);assert.equal(j.status,'BLOCKED');const fixtureDir=join(f.root,'resume-fixture');await mkdir(fixtureDir);const source=join(fixtureDir,'source.mp4');await execFile('/usr/bin/ffmpeg',['-nostdin','-v','error','-y','-f','lavfi','-i','color=c=green:s=180x320:d=1','-c:v','libx264','-threads','1','-pix_fmt','yuv420p',source]);const uploaded=await f.service.uploadSource(actor,'tenant-a','real-source',{bytes:await readFile(source),mime_type:'video/mp4'});await f.service.start(actor,j.id);await f.service.drain();j=(await f.repository.read()).jobs[j.id];assert.equal(j.status,'AWAITING_REVIEW',JSON.stringify(j.blockers));assert.equal(j.stage,'CREATIVE_GATE');assert.equal(j.source_asset_snapshot[0].sha256,uploaded.sha256);const state=await f.service.service().status(f.service.paths(j));assert.equal(state.nodes.find(n=>n.id==='INGEST').status,'done')})
test('media inspection rejects playlists and local or network indirection before ffprobe',async()=>{const f=await fixture();const playlist=join(f.root,'malicious.mp4');await writeFile(playlist,'#EXTM3U\n#EXTINF:2,\nhttp://127.0.0.1:9999/private\nfile:///etc/passwd\n');await assert.rejects(inspectVideo(playlist),e=>e.code==='INVALID_MEDIA');await assert.rejects(f.service.uploadSource(actor,'tenant-a','real-source',{bytes:await readFile(playlist),mime_type:'video/mp4'}),e=>e.code==='INVALID_MEDIA')})
test('provider failure remains a blocker and cannot create release evidence',async()=>{const f=await fixture();const adapter=f.service.providers.get('deterministic-test');adapter.generate=async()=>{throw new Error('provider failed')};let j=await runToReview(f);j=await approve(f);assert.equal(j.status,'BLOCKED');assert.ok(!j.artifacts.length);assert.equal(Object.keys((await f.repository.read()).releases).length,0)})
test('real footage adapter preserves all selected sources, target dimensions, and ambient audio',async()=>{const f=await fixture();const directory=join(f.root,'render');await mkdir(directory);const first=join(directory,'a.mp4');const second=join(directory,'b.mp4');for(const [path,color,tone] of [[first,'red',440],[second,'green',660]])await execFile('/usr/bin/ffmpeg',['-nostdin','-v','error','-y','-f','lavfi','-i','color=c='+color+':s=180x320:d=1','-f','lavfi','-i','sine=frequency='+tone+':duration=1','-c:v','libx264','-threads','1','-c:a','aac','-pix_fmt','yuv420p','-shortest',path]);const assets=await Promise.all([first,second].map(async(path,i)=>({path,source_id:'source-'+i,sha256:digest(await readFile(path))})));const adapter=new FFmpegAdapter();const input={assets,directory,job:{target:{duration_seconds:[1,2],aspect_ratio:'1:1'}}};const generated=await adapter.generate(await adapter.prepare(input));const media=await inspectVideo(generated.output);assert.equal(media.width,1080);assert.equal(media.height,1080);assert.equal(media.has_audio,true);assert.ok(Math.abs(media.duration_seconds-1)<0.2);assert.equal(adapter.provenance(input).used_sources.length,2)})
test('production uploaded media binds creative candidate, separate real reviewers, and final release',async()=>{const f=await fixture({testMode:false,deploymentClass:'production'});const fixtureDir=join(f.root,'fixture');await mkdir(fixtureDir);const source=join(fixtureDir,'source.mp4');await execFile('/usr/bin/ffmpeg',['-nostdin','-v','error','-y','-f','lavfi','-i','color=c=yellow:s=180x320:d=2','-c:v','libx264','-threads','1','-pix_fmt','yuv420p',source]);const uploaded=await f.service.uploadSource(actor,'tenant-a','real-source',{bytes:await readFile(source),mime_type:'video/mp4'});let j=await runToReview(f);assert.equal(j.stage,'CREATIVE_GATE');assert.equal(j.source_asset_snapshot[0].sha256,uploaded.sha256);j=await approve(f);assert.equal(j.stage,'CRITIC',JSON.stringify(j.blockers));const verifiedCandidate=j.candidate_sha;await assert.rejects(f.service.approve(actor,j.id,{candidate_sha:j.candidate_sha,review_stage:j.stage}),e=>e.code==='INDEPENDENT_REVIEW_REQUIRED');const critic={id:'critic-human',memberships:[{tenant_id:'tenant-a',role:'reviewer'}]};await f.service.approve(critic,j.id,{candidate_sha:j.candidate_sha,review_stage:j.stage});await f.service.drain();j=(await f.repository.read()).jobs[j.id];assert.equal(j.stage,'INDEPENDENT_VERIFIER');assert.equal(j.candidate_sha,verifiedCandidate);await assert.rejects(f.service.approve(critic,j.id,{candidate_sha:j.candidate_sha,review_stage:j.stage}),e=>e.code==='INDEPENDENT_REVIEW_REQUIRED');const verifier={id:'verifier-human',memberships:[{tenant_id:'tenant-a',role:'reviewer'}]};await f.service.approve(verifier,j.id,{candidate_sha:j.candidate_sha,review_stage:j.stage});await f.service.drain();j=(await f.repository.read()).jobs[j.id];assert.equal(j.stage,'RELEASE');assert.equal(j.candidate_sha,verifiedCandidate);assert.ok(j.evidence.filter(e=>['CRITIC','INDEPENDENT_VERIFIER'].includes(e.stage)).every(e=>e.test===false));j=await approve(f);assert.equal(j.status,'RELEASED');const released=Object.values((await f.repository.read()).releases)[0];assert.equal(released.test,false);assert.equal(j.provider_execution.provider,'ffmpeg');assert.equal(j.provider_execution.artifact_sha256,j.artifact_sha256);assert.deepEqual(j.provider_execution.provenance.used_sources,[{source_id:'real-source',sha256:uploaded.sha256}]);assert.equal(j.review_candidate.provider_execution_sha,digest(j.provider_execution));assert.deepEqual(released.provider_execution,j.provider_execution);assert.equal(released.reviews.length,4);assert.equal(released.source_assets[0].sha256,uploaded.sha256);await f.repository.transact(s=>{s.jobs[j.id].provider_execution.provenance.used_sources=[];return null});assert.equal(Object.values((await f.repository.read()).releases)[0].provider_execution.provenance.used_sources.length,1)})
test('controlled single-operator preview lets the owner approve Critic and Verifier on the same hash while labeling the relaxed separation',async()=>{
 const f=await fixture({testMode:false,deploymentClass:'controlled_single_operator_preview'}),fixtureDir=join(f.root,'single-operator-preview');await mkdir(fixtureDir);const source=join(fixtureDir,'source.mp4');await execFile('/usr/bin/ffmpeg',['-nostdin','-v','error','-y','-f','lavfi','-i','color=c=0x800020:s=180x320:d=2','-c:v','libx264','-threads','1','-pix_fmt','yuv420p',source]);await f.service.uploadSource(actor,'tenant-a','real-source',{bytes:await readFile(source),mime_type:'video/mp4'});let j=await runToReview(f);assert.equal(j.stage,'CREATIVE_GATE');j=await approve(f);assert.equal(j.stage,'CRITIC',JSON.stringify(j.blockers));const candidate=j.candidate_sha;await f.service.approve(actor,j.id,{candidate_sha:candidate,review_stage:'CRITIC'});await f.service.drain();j=(await f.repository.read()).jobs[j.id];assert.equal(j.stage,'INDEPENDENT_VERIFIER',JSON.stringify(j.blockers));assert.equal(j.candidate_sha,candidate);assert.equal(j.critic_actor,actor.id);await f.service.approve(actor,j.id,{candidate_sha:candidate,review_stage:'INDEPENDENT_VERIFIER'});await f.service.drain();j=(await f.repository.read()).jobs[j.id];assert.equal(j.stage,'RELEASE',JSON.stringify(j.blockers));assert.equal(j.candidate_sha,candidate);const governed=j.approvals.filter(a=>['CRITIC','INDEPENDENT_VERIFIER'].includes(a.stage));assert.deepEqual(governed.map(a=>a.actor),['owner','owner']);assert.deepEqual(governed.map(a=>a.review_policy),['SINGLE_OPERATOR_PREVIEW','SINGLE_OPERATOR_PREVIEW']);j=await approve(f);assert.equal(j.status,'RELEASED');const released=Object.values((await f.repository.read()).releases)[0];assert.deepEqual(released.reviews.filter(a=>['CRITIC','INDEPENDENT_VERIFIER'].includes(a.stage)).map(a=>a.review_policy),['SINGLE_OPERATOR_PREVIEW','SINGLE_OPERATOR_PREVIEW']);const events=(await readFile(join(f.root,'graph/tenant-a/job-one/events.jsonl'),'utf8')).trim().split('\n').map(JSON.parse);const notes=events.filter(e=>e.event_type==='approval.recorded'&&['CRITIC','INDEPENDENT_VERIFIER'].includes(e.node_id)).map(e=>e.payload?.note);assert.ok(notes.every(note=>/single-operator preview/i.test(note)))
})

test('production still rejects producer self-review even when the producer is an owner',async()=>{
 const f=await fixture({testMode:false,deploymentClass:'production'}),fixtureDir=join(f.root,'production-independent-review');await mkdir(fixtureDir);const source=join(fixtureDir,'source.mp4');await execFile('/usr/bin/ffmpeg',['-nostdin','-v','error','-y','-f','lavfi','-i','color=c=blue:s=180x320:d=2','-c:v','libx264','-threads','1','-pix_fmt','yuv420p',source]);await f.service.uploadSource(actor,'tenant-a','real-source',{bytes:await readFile(source),mime_type:'video/mp4'});let j=await runToReview(f);j=await approve(f);assert.equal(j.stage,'CRITIC');await assert.rejects(f.service.approve(actor,j.id,{candidate_sha:j.candidate_sha,review_stage:'CRITIC'}),e=>e.code==='INDEPENDENT_REVIEW_REQUIRED')
})

test('same fixture bytes after localized media repair receive a fresh candidate scope',async()=>{const f=await fixture();await runToReview(f);let j=await approve(f);const old=j.candidate_sha;const oldArtifact=j.artifact_sha256;await f.service.requestChanges(actor,j.id,{candidate_sha:old,review_stage:j.stage,reason:'A different ending'});await f.service.drain();j=(await f.repository.read()).jobs[j.id];assert.equal(j.stage,'RELEASE');assert.equal(j.artifact_sha256,oldArtifact);assert.notEqual(j.candidate_sha,old);await assert.rejects(f.service.approve(actor,j.id,{candidate_sha:old,review_stage:j.stage}),e=>e.code==='STALE_CANDIDATE')})
test('approval intent survives a crash after Graph approval and resumes without a second decision',async()=>{const f=await fixture();const j=await runToReview(f);const complete=f.service.complete.bind(f.service);f.service.complete=async(...args)=>{await complete(...args);throw new Error('simulated process loss after durable Graph event')};await assert.rejects(f.service.approve(actor,j.id,{candidate_sha:j.candidate_sha,review_stage:j.stage}),/simulated process loss/);const interrupted=(await f.repository.read()).jobs[j.id];assert.equal(interrupted.pending_review.candidate_sha,j.candidate_sha);const restarted=new ExecutionService({repository:f.repository,dataRoot:f.root,graphRuntimeRoot:runtime,testMode:true,deploymentClass:'test'});await restarted.recover();await restarted.drain();const resumed=(await f.repository.read()).jobs[j.id];assert.equal(resumed.pending_review,null);assert.equal(resumed.stage,'RELEASE',JSON.stringify(resumed.blockers));const events=(await readFile(join(f.root,'graph/tenant-a/job-one/events.jsonl'),'utf8')).trim().split('\n').map(JSON.parse);assert.equal(events.filter(e=>e.event_type==='approval.recorded'&&e.node_id==='CREATIVE_GATE').length,1)})
test('production arbitrary creative repair remains manual and never silently rerenders',async()=>{const f=await fixture();const j=await runToReview(f);f.service.testMode=false;f.service.deploymentClass='controlled_single_operator_preview';await f.service.requestChanges(actor,j.id,{candidate_sha:j.candidate_sha,review_stage:j.stage,reason:'Change the mood and add a stronger story'});const repaired=(await f.repository.read()).jobs[j.id];assert.equal(repaired.status,'BLOCKED');assert.equal(repaired.blockers[0].code,'MANUAL_REPAIR_REQUIRED');assert.equal(repaired.repair_requires_manual,true);assert.equal(repaired.candidate_sha,null);assert.equal(Object.keys((await f.repository.read()).releases).length,0)})
test('manual creative blocker can be explicitly withdrawn on the same production without claiming the edit was applied',async()=>{const f=await fixture({testMode:false,deploymentClass:'controlled_single_operator_preview'});const dir=join(f.root,'manual-repair-withdraw');await mkdir(dir);const source=join(dir,'source.mp4');await execFile('/usr/bin/ffmpeg',['-nostdin','-v','error','-y','-f','lavfi','-i','color=c=yellow:s=180x320:d=2','-c:v','libx264','-threads','1','-pix_fmt','yuv420p',source]);await f.service.uploadSource(actor,'tenant-a','real-source',{bytes:await readFile(source),mime_type:'video/mp4'});let j=await runToReview(f);j=await approve(f);assert.equal(j.stage,'CRITIC',JSON.stringify(j.blockers));const sameId=j.id,priorTreatment=digest(j.treatment);await f.service.requestChanges(actor,j.id,{candidate_sha:j.candidate_sha,review_stage:j.stage,reason:'Make the opening warmer and more cinematic'});j=(await f.repository.read()).jobs[j.id];assert.equal(j.id,sameId);assert.equal(j.status,'BLOCKED');assert.equal(j.stage,'PROVIDER_PRODUCTION');assert.equal(j.blockers[0].code,'MANUAL_REPAIR_REQUIRED');assert.equal(j.repair_requires_manual,true);assert.equal(j.repair_instructions,'Make the opening warmer and more cinematic');assert.equal(publicJob(j).repair_requires_manual,true);assert.equal(publicJob(j).repair_instructions,'Make the opening warmer and more cinematic');assert.equal(j.artifact_sha256,null);await f.service.repairBlocked(actor,j.id,{action:'WITHDRAW_MANUAL_CHANGE'});await f.service.drain();j=(await f.repository.read()).jobs[j.id];assert.equal(j.id,sameId);assert.equal(j.status,'AWAITING_REVIEW',JSON.stringify(j.blockers));assert.equal(j.stage,'CRITIC');assert.equal(j.blockers.length,0);assert.equal(j.repair_requires_manual,false);assert.equal(j.repair_instructions,null);assert.deepEqual(j.repair_controls,{blocker_action:'WITHDRAW_MANUAL_CHANGE'});assert.equal(publicJob(j).repair_requires_manual,false);assert.deepEqual(publicJob(j).repair_controls,{blocker_action:'WITHDRAW_MANUAL_CHANGE'});assert.equal(digest(j.treatment),priorTreatment);assert.ok(j.artifact_sha256);assert.ok(j.repairs.some(r=>r.action==='WITHDRAW_MANUAL_CHANGE'));const state=await f.service.service().status(f.service.paths(j));assert.equal(state.nodes.find(n=>n.id==='PROVIDER_PRODUCTION').status,'done');assert.equal(state.nodes.find(n=>n.id==='CRITIC').status,'spec_ready')})
test('stable artifact candidate is shared by verifier and release, with stage replay rejected',async()=>{const f=await fixture();await runToReview(f);let j=await approve(f);const oldScope={candidate_sha:j.candidate_sha,review_stage:'INDEPENDENT_VERIFIER'};await assert.rejects(f.service.approve(actor,j.id,oldScope),e=>e.code==='STALE_CANDIDATE');assert.equal(j.review_candidate.stage,undefined)})
test('mascot request reaches human creative review, then fails closed before unsupported composition',async()=>{const f=await fixture();await f.repository.transact(s=>{s.jobs['job-one'].mascot=true;return null});let j=await runToReview(f);assert.equal(j.status,'AWAITING_REVIEW');assert.equal(j.stage,'CREATIVE_GATE');assert.equal(j.artifacts.length,0);j=await approve(f);assert.equal(j.status,'BLOCKED');assert.equal(j.stage,'PROVIDER_PRODUCTION');assert.equal(j.blockers[0].code,'MASCOT_RENDER_UNAVAILABLE');assert.equal(j.artifacts.length,0);assert.equal(j.provider_execution,undefined)})
test('actual adapter paid capability or nonzero estimate is blocked before generate',async()=>{const f=await fixture();let invoked=false;const adapter=f.service.providers.get('deterministic-test');adapter.estimate=()=>({credits:5});adapter.generate=async()=>{invoked=true;throw new Error('must not execute')};await runToReview(f);const j=await approve(f);assert.equal(j.status,'BLOCKED');assert.equal(j.blockers[0].code,'SPEND_APPROVAL_REQUIRED');assert.equal(invoked,false)})
test('repair intent survives a crash after Graph invalidation without duplicating repair plans',async()=>{const f=await fixture();const j=await runToReview(f);const service=f.service.service.bind(f.service);f.service.service=()=>{const graph=service();const fail=graph.failAndRepair.bind(graph);graph.failAndRepair=async(...args)=>{await fail(...args);throw new Error('simulated loss after Graph invalidation')};return graph};await assert.rejects(f.service.requestChanges(actor,j.id,{candidate_sha:j.candidate_sha,review_stage:j.stage,reason:'Different opening'}),/simulated loss/);const restarted=new ExecutionService({repository:f.repository,dataRoot:f.root,graphRuntimeRoot:runtime,testMode:true,deploymentClass:'test'});await restarted.recover();await restarted.drain();const result=(await f.repository.read()).jobs[j.id];assert.equal(result.stage,'CREATIVE_GATE',JSON.stringify(result.blockers));assert.equal(result.pending_review,null);assert.equal(result.graph.repair_plan_count,1)})
test('kernel job lease excludes concurrent workers and ignores obsolete dead reclaim files',async()=>{const root=await mkdtemp(join(tmpdir(),'media-worker-lease-'));const path=join(root,'worker.lock');await writeFile(path,JSON.stringify({pid:99999999,identity:'stale',token:'obsolete'}));await writeFile(path+'.reclaim',JSON.stringify({pid:99999999,identity:'stale',token:'obsolete'}));let unlock,entered;const ready=new Promise(resolve=>entered=resolve);const hold=new Promise(resolve=>unlock=resolve);const first=withJobLease(path,async()=>{entered();await hold;return 'first'});await ready;await assert.rejects(withJobLease(path,async()=> 'second'),e=>e.code==='JOB_BUSY');unlock();assert.equal(await first,'first');assert.equal(await withJobLease(path,async()=> 'recovered'),'recovered')})
test('rejection intent survives a crash after blocking Graph and becomes terminal on recovery',async()=>{const f=await fixture();const j=await runToReview(f);const service=f.service.service.bind(f.service);f.service.service=()=>{const graph=service();const transition=graph.transition.bind(graph);graph.transition=async(input)=>{const result=await transition(input);if(input.to==='blocked')throw new Error('simulated loss after Graph block');return result};return graph};await assert.rejects(f.service.reject(actor,j.id,{candidate_sha:j.candidate_sha,review_stage:j.stage,reason:'This concept is not appropriate'}),/simulated loss/);const restarted=new ExecutionService({repository:f.repository,dataRoot:f.root,graphRuntimeRoot:runtime,testMode:true,deploymentClass:'test'});await restarted.recover();await restarted.drain();const rejected=(await f.repository.read()).jobs[j.id];assert.equal(rejected.status,'REJECTED');assert.equal(rejected.pending_review,null);assert.equal(Object.keys((await f.repository.read()).releases).length,0)})

test('changed provider provenance invalidates review before Graph approval or release',async()=>{const f=await fixture();await runToReview(f);const j=await approve(f);assert.equal(j.stage,'RELEASE');await f.repository.transact(s=>{s.jobs[j.id].provider_execution.provenance.synthetic=false;return null});await assert.rejects(f.service.approve(actor,j.id,{candidate_sha:j.candidate_sha,review_stage:j.stage}),{code:'PROVENANCE_CHANGED'});const state=await f.repository.read();assert.equal(Object.keys(state.releases).length,0);assert.equal(state.jobs[j.id].pending_review,null);assert.equal(state.jobs[j.id].approvals.length,1)})
test('provenance drift during approval cannot enter the immutable release snapshot',async()=>{const f=await fixture();await runToReview(f);const j=await approve(f);const complete=f.service.complete.bind(f.service);f.service.complete=async(...args)=>{await complete(...args);if(args[1]==='RELEASE')await f.repository.transact(s=>{s.jobs[j.id].provider_execution.provenance.synthetic=false;return null})};await assert.rejects(f.service.approve(actor,j.id,{candidate_sha:j.candidate_sha,review_stage:j.stage}),{code:'PROVENANCE_CHANGED'});assert.equal(Object.keys((await f.repository.read()).releases).length,0)})
test('requested repair clears current output provenance and keeps historical artifact bytes',async()=>{const f=await fixture();await runToReview(f);const j=await approve(f);assert.ok(j.provider_execution);f.service.testMode=false;await f.service.requestChanges(actor,j.id,{candidate_sha:j.candidate_sha,review_stage:j.stage,reason:'A different visual treatment'});const repaired=(await f.repository.read()).jobs[j.id];assert.equal(repaired.status,'BLOCKED');assert.equal(repaired.provider_execution,null);assert.equal(repaired.production_provider,null);assert.equal(repaired.production_note,null);assert.equal(repaired.artifact_sha256,null);assert.equal(repaired.review_candidate,null);assert.equal(repaired.artifacts.length,1)})

test('blocked mascot production can be explicitly repaired to real footage on the same Graph and requires fresh review',async()=>{const f=await fixture();await f.repository.transact(s=>{s.jobs['job-one'].mascot=true;return null});let j=await runToReview(f);j=await approve(f);assert.equal(j.status,'BLOCKED');assert.equal(j.stage,'PROVIDER_PRODUCTION');assert.equal(j.blockers[0].code,'MASCOT_RENDER_UNAVAILABLE');const sameId=j.id;await f.service.repairBlocked(actor,j.id,{action:'USE_REAL_FOOTAGE'});await f.service.drain();j=(await f.repository.read()).jobs[j.id];assert.equal(j.id,sameId);assert.equal(j.mascot,false);assert.equal(j.strategy,'REAL_FOOTAGE');assert.equal(j.preferred_provider,'AUTO');assert.equal(j.repair_revision,1);assert.deepEqual(j.repair_controls,{blocker_action:'USE_REAL_FOOTAGE'});assert.equal(j.status,'AWAITING_REVIEW',JSON.stringify(j.blockers));assert.equal(j.stage,'CREATIVE_GATE');assert.equal(j.blockers.length,0);assert.equal(j.artifact_sha256,null);assert.equal(j.provider_execution,null);assert.match(j.treatment.edit_plan,/Every selected source/);const state=await f.service.service().status(f.service.paths(j));assert.equal(state.nodes.find(n=>n.id==='BRIEF').revision,0);assert.equal(state.nodes.find(n=>n.id==='SOURCE').revision,0);assert.equal(state.nodes.find(n=>n.id==='INGEST').revision,0);assert.equal(state.nodes.find(n=>n.id==='DIRECTOR_TREATMENT').revision,1);assert.equal(state.nodes.find(n=>n.id==='CREATIVE_GATE').revision,1);assert.equal(state.repair_plan_count,1)})

test('blocked production repair is role-bound and rejects unsupported mutations',async()=>{const f=await fixture();await f.repository.transact(s=>{s.jobs['job-one'].mascot=true;return null});let j=await runToReview(f);j=await approve(f);const viewer={id:'view',memberships:[{tenant_id:'tenant-a',role:'viewer'}]};await assert.rejects(f.service.repairBlocked(viewer,j.id,{action:'USE_REAL_FOOTAGE'}),e=>e.code==='FORBIDDEN');await assert.rejects(f.service.repairBlocked(actor,j.id,{action:'UNSUPPORTED'}),e=>e.code==='INVALID_REPAIR_ACTION');j=(await f.repository.read()).jobs[j.id];assert.equal(j.status,'BLOCKED');assert.equal(j.mascot,true);assert.equal(j.blockers[0].code,'MASCOT_RENDER_UNAVAILABLE')})

test('source-too-short blocker has an explicit same-job duration-fit repair and fresh creative review',async()=>{
 const f=await fixture({testMode:false,deploymentClass:'controlled_single_operator_preview'});await f.repository.transact(s=>{s.jobs['job-one'].target={aspect_ratio:'9:16',duration_seconds:[2,4]};return null});
 const dir=join(f.root,'short-source');await mkdir(dir);const source=join(dir,'short.mp4');await execFile('/usr/bin/ffmpeg',['-nostdin','-v','error','-y','-f','lavfi','-i','color=c=blue:s=180x320:d=1','-c:v','libx264','-threads','1','-pix_fmt','yuv420p',source]);
 await f.service.uploadSource(actor,'tenant-a','real-source',{bytes:await readFile(source),mime_type:'video/mp4'});let j=await runToReview(f);assert.equal(j.stage,'CREATIVE_GATE');j=await approve(f);assert.equal(j.status,'BLOCKED');assert.equal(j.blockers[0].code,'SOURCE_TOO_SHORT');const id=j.id;
 await f.service.repairBlocked(actor,id,{action:'FIT_SOURCE_DURATION'});await f.service.drain();j=(await f.repository.read()).jobs[id];assert.equal(j.id,id);assert.equal(j.status,'AWAITING_REVIEW',JSON.stringify(j.blockers));assert.equal(j.stage,'CREATIVE_GATE');assert.equal(j.repair_controls.blocker_action,'FIT_SOURCE_DURATION');assert.ok(j.repair_controls.duration_seconds>=1&&j.repair_controls.duration_seconds<2);assert.equal(j.blockers.length,0);assert.equal(j.artifact_sha256,null);assert.equal(j.treatment.repair_controls.duration_seconds,j.repair_controls.duration_seconds);const state=await f.service.service().status(f.service.paths(j));assert.equal(state.nodes.find(n=>n.id==='DIRECTOR_TREATMENT').revision,1);assert.equal(state.nodes.find(n=>n.id==='CREATIVE_GATE').revision,1);assert.equal(state.repair_plan_count,1)
})

test('authorized FIRMES caballito is composited by the local zero-credit adapter with immutable brand provenance',async()=>{
 const f=await fixture({testMode:false,deploymentClass:'controlled_single_operator_preview'});await f.repository.transact(s=>{s.tenants['tenant-a'].organization='FIRMES';s.tenants['tenant-a'].brand={display_name:'FIRMES',identity_key:'firmes'};s.jobs['job-one'].mascot=true;s.jobs['job-one'].creative_context={character:{id:'caballito-main',kind:'character',name:'Caballito de Firmes',rights_confirmed:true,principal:true,information_status:'AUTHORIZED_FICTIONAL_REFERENCE'}};return null});
 const dir=join(f.root,'firmes-caballito');await mkdir(dir);const source=join(dir,'source.mp4');await execFile('/usr/bin/ffmpeg',['-nostdin','-v','error','-y','-f','lavfi','-i','color=c=white:s=180x320:d=2','-c:v','libx264','-threads','1','-pix_fmt','yuv420p',source]);const uploaded=await f.service.uploadSource(actor,'tenant-a','real-source',{bytes:await readFile(source),mime_type:'video/mp4'});let j=await runToReview(f);assert.equal(j.stage,'CREATIVE_GATE');const expectedBrand=[{asset_id:'firmes-caballito-manual-p42',sha256:'b17c55ffb0eec46bfa719128ee68a9f18475c45afb90d6d73ce9d82567938397',synthetic:false}];assert.equal(j.treatment.character_composition_status,'AUTHORIZED_LOCAL_COMPOSITE');assert.deepEqual(j.treatment.authorized_brand_assets,expectedBrand);assert.deepEqual(j.review_candidate.treatment.authorized_brand_assets,expectedBrand);j=await approve(f);assert.equal(j.stage,'CRITIC',JSON.stringify(j.blockers));assert.ok(j.artifact_sha256);assert.equal(j.production_provider,'ffmpeg');assert.match(j.production_note,/FIRMES caballito/);assert.deepEqual(j.provider_execution.provenance.used_sources,[{source_id:'real-source',sha256:uploaded.sha256}]);assert.deepEqual(j.provider_execution.provenance.brand_assets,[{asset_id:'firmes-caballito-manual-p42',sha256:'b17c55ffb0eec46bfa719128ee68a9f18475c45afb90d6d73ce9d82567938397',synthetic:false}]);const artifact=j.artifacts.at(-1),media=await inspectVideo(join(f.root,'graph','tenant-a','job-one','artifacts',artifact.filename));assert.equal(media.width,1080);assert.equal(media.height,1920);assert.ok(media.duration_seconds>=0.9);assert.equal(j.provider_execution.estimate.credits,0)
})


test('critic request to add the FIRMES caballito is executed on the same job instead of entering the manual blocker',async()=>{
 const f=await fixture({testMode:false,deploymentClass:'controlled_single_operator_preview'});await f.repository.transact(s=>{s.tenants['tenant-a'].organization='FIRMES';s.tenants['tenant-a'].brand={display_name:'FIRMES',identity_key:'firmes'};s.jobs['job-one'].mascot=false;return null});
 const dir=join(f.root,'firmes-requested-mascot-repair');await mkdir(dir);const source=join(dir,'source.mp4');await execFile('/usr/bin/ffmpeg',['-nostdin','-v','error','-y','-f','lavfi','-i','testsrc2=size=360x640:rate=30:duration=2','-f','lavfi','-i','sine=frequency=330:duration=2','-c:v','libx264','-threads','1','-c:a','aac','-pix_fmt','yuv420p','-shortest',source]);await f.service.uploadSource(actor,'tenant-a','real-source',{bytes:await readFile(source),mime_type:'video/mp4'});
 let j=await runToReview(f);assert.equal(j.stage,'CREATIVE_GATE');j=await approve(f);assert.equal(j.stage,'CRITIC',JSON.stringify(j.blockers));assert.equal(j.mascot??false,false);const sameId=j.id,firstArtifact=j.artifact_sha256;
 const critic={id:'critic-human',memberships:[{tenant_id:'tenant-a',role:'reviewer'}]};await f.service.requestChanges(critic,j.id,{candidate_sha:j.candidate_sha,review_stage:j.stage,reason:'no, necesitamos agregar al caballito.'});await f.service.drain();j=(await f.repository.read()).jobs[j.id];
 assert.equal(j.id,sameId);assert.equal(j.status,'AWAITING_REVIEW',JSON.stringify(j.blockers));assert.equal(j.stage,'CRITIC');assert.equal(j.mascot,true);assert.equal(j.repair_requires_manual,false);assert.equal(j.blockers.length,0);assert.equal(j.repair_controls.blocker_action,'ADD_FIRMES_MASCOT');assert.equal(j.repair_controls.authorized_by,'critic-human');assert.ok(j.repair_controls.authorized_review_id);assert.notEqual(j.artifact_sha256,firstArtifact);assert.equal(j.treatment.character_composition_status,'AUTHORIZED_LOCAL_COMPOSITE');assert.deepEqual(j.provider_execution.provenance.brand_assets,[{asset_id:'brand_asset_firmes_caballito_v1',sha256:'b17c55ffb0eec46bfa719128ee68a9f18475c45afb90d6d73ce9d82567938397',synthetic:false}]);assert.ok(j.repairs.some(r=>r.action==='ADD_FIRMES_MASCOT'&&r.brand_asset_sha256==='b17c55ffb0eec46bfa719128ee68a9f18475c45afb90d6d73ce9d82567938397'));
 const state=await f.service.service().status(f.service.paths(j));assert.equal(state.nodes.find(n=>n.id==='DIRECTOR_TREATMENT').revision,1);assert.equal(state.nodes.find(n=>n.id==='CREATIVE_GATE').revision,1);assert.equal(state.nodes.find(n=>n.id==='CREATIVE_GATE').status,'done');assert.equal(state.nodes.find(n=>n.id==='PROVIDER_PRODUCTION').revision,1);assert.equal(state.nodes.find(n=>n.id==='PROVIDER_PRODUCTION').status,'done');assert.equal(state.nodes.find(n=>n.id==='CRITIC').status,'spec_ready');
 const events=(await readFile(join(f.root,'graph','tenant-a','job-one','events.jsonl'),'utf8')).trim().split('\n').map(JSON.parse);assert.ok(events.some(e=>e.event_type==='evidence.recorded'&&e.node_id==='CREATIVE_GATE'&&e.actor==='critic-human'&&e.payload?.metadata?.repair_action==='ADD_FIRMES_MASCOT'));
})

test('legacy manual blocker for the exact Caballito request can be upgraded and applied on the same job',async()=>{
 const f=await fixture({testMode:false,deploymentClass:'controlled_single_operator_preview'});await f.repository.transact(s=>{s.tenants['tenant-a'].organization='FIRMES';s.tenants['tenant-a'].brand={display_name:'FIRMES',identity_key:'firmes'};s.jobs['job-one'].mascot=false;return null});
 const dir=join(f.root,'firmes-legacy-blocker');await mkdir(dir);const source=join(dir,'source.mp4');await execFile('/usr/bin/ffmpeg',['-nostdin','-v','error','-y','-f','lavfi','-i','testsrc2=size=360x640:rate=30:duration=2','-c:v','libx264','-threads','1','-pix_fmt','yuv420p',source]);await f.service.uploadSource(actor,'tenant-a','real-source',{bytes:await readFile(source),mime_type:'video/mp4'});
 let j=await runToReview(f);j=await approve(f);assert.equal(j.stage,'CRITIC');const sameId=j.id,firstArtifact=j.artifact_sha256,critic={id:'critic-human',memberships:[{tenant_id:'tenant-a',role:'reviewer'}]};await f.service.requestChanges(critic,j.id,{candidate_sha:j.candidate_sha,review_stage:j.stage,reason:'Make the opening warmer and more cinematic'});j=(await f.repository.read()).jobs[j.id];assert.equal(j.status,'BLOCKED');assert.equal(j.blockers[0].code,'MANUAL_REPAIR_REQUIRED');await f.repository.transact(s=>{s.jobs[j.id].repair_instructions='no, necesitamos agregar al caballito.';return null});
 await f.service.repairBlocked(actor,j.id,{action:'APPLY_SUPPORTED_CHANGE'});await f.service.drain();j=(await f.repository.read()).jobs[j.id];assert.equal(j.id,sameId);assert.equal(j.status,'AWAITING_REVIEW',JSON.stringify(j.blockers));assert.equal(j.stage,'CRITIC');assert.equal(j.mascot,true);assert.equal(j.repair_requires_manual,false);assert.equal(j.repair_controls.blocker_action,'ADD_FIRMES_MASCOT');assert.equal(j.blockers.length,0);assert.notEqual(j.artifact_sha256,firstArtifact);assert.deepEqual(j.provider_execution.provenance.brand_assets,[{asset_id:'brand_asset_firmes_caballito_v1',sha256:'b17c55ffb0eec46bfa719128ee68a9f18475c45afb90d6d73ce9d82567938397',synthetic:false}]);assert.ok(j.repairs.some(r=>r.action==='ADD_FIRMES_MASCOT'&&r.brand_asset_sha256==='b17c55ffb0eec46bfa719128ee68a9f18475c45afb90d6d73ce9d82567938397'));
})

test('negated mascot add language is not silently treated as an executable add request',async()=>{
 const f=await fixture({testMode:false,deploymentClass:'controlled_single_operator_preview'});await f.repository.transact(s=>{s.tenants['tenant-a'].organization='FIRMES';s.tenants['tenant-a'].brand={display_name:'FIRMES',identity_key:'firmes'};return null});const dir=join(f.root,'firmes-negated-add');await mkdir(dir);const source=join(dir,'source.mp4');await execFile('/usr/bin/ffmpeg',['-nostdin','-v','error','-y','-f','lavfi','-i','color=c=blue:s=180x320:d=2','-c:v','libx264','-threads','1','-pix_fmt','yuv420p',source]);await f.service.uploadSource(actor,'tenant-a','real-source',{bytes:await readFile(source),mime_type:'video/mp4'});let j=await runToReview(f);j=await approve(f);const critic={id:'critic-human',memberships:[{tenant_id:'tenant-a',role:'reviewer'}]};await f.service.requestChanges(critic,j.id,{candidate_sha:j.candidate_sha,review_stage:j.stage,reason:'no necesitamos agregar al caballito'});j=(await f.repository.read()).jobs[j.id];assert.equal(j.status,'BLOCKED');assert.equal(j.blockers[0].code,'MANUAL_REPAIR_REQUIRED');assert.equal(j.mascot??false,false);assert.equal(j.repair_requires_manual,true)
})

test('creative approval rejects treatment drift after the exact caballito asset was hash-bound',async()=>{
 const f=await fixture({testMode:false,deploymentClass:'controlled_single_operator_preview'});await f.repository.transact(s=>{s.tenants['tenant-a'].organization='FIRMES';s.tenants['tenant-a'].brand={display_name:'FIRMES',identity_key:'firmes'};s.jobs['job-one'].mascot=true;s.jobs['job-one'].creative_context={character:{id:'caballito-main',kind:'character',name:'Caballito de Firmes',rights_confirmed:true,principal:true}};return null});const dir=join(f.root,'firmes-treatment-drift');await mkdir(dir);const source=join(dir,'source.mp4');await execFile('/usr/bin/ffmpeg',['-nostdin','-v','error','-y','-f','lavfi','-i','color=c=white:s=180x320:d=2','-c:v','libx264','-threads','1','-pix_fmt','yuv420p',source]);await f.service.uploadSource(actor,'tenant-a','real-source',{bytes:await readFile(source),mime_type:'video/mp4'});const j=await runToReview(f);assert.equal(j.stage,'CREATIVE_GATE');await f.repository.transact(s=>{s.jobs[j.id].treatment.authorized_brand_assets[0].sha256='f'.repeat(64);return null});await assert.rejects(f.service.approve(actor,j.id,{candidate_sha:j.candidate_sha,review_stage:j.stage}),{code:'TREATMENT_CHANGED'});const after=(await f.repository.read()).jobs[j.id];assert.equal(after.stage,'CREATIVE_GATE');assert.equal(after.artifact_sha256??null,null)
})

test('soundtrack upload accepts real MP3 WAV and M4A files while rejecting MIME-disguised bytes',async()=>{
 const f=await fixture({testMode:false,deploymentClass:'controlled_single_operator_preview'}),dir=join(f.root,'audio-input-formats');await mkdir(dir)
 const mp3=join(dir,'soundtrack.mp3'),wav=join(dir,'soundtrack.wav'),m4a=join(dir,'soundtrack.m4a')
 await execFile('/usr/bin/ffmpeg',['-nostdin','-v','error','-y','-f','lavfi','-i','sine=frequency=220:duration=1.2','-c:a','libmp3lame','-b:a','192k',mp3])
 await execFile('/usr/bin/ffmpeg',['-nostdin','-v','error','-y','-f','lavfi','-i','sine=frequency=330:duration=1.2','-c:a','pcm_s16le',wav])
 await execFile('/usr/bin/ffmpeg',['-nostdin','-v','error','-y','-f','lavfi','-i','sine=frequency=440:duration=1.2','-c:a','aac','-b:a','192k',m4a])
 const a=await f.service.uploadAudioAsset(actor,'job-one',{bytes:await readFile(mp3),mime_type:'audio/mpeg'}),b=await f.service.uploadAudioAsset(actor,'job-one',{bytes:await readFile(wav),mime_type:'audio/wav'}),c=await f.service.uploadAudioAsset(actor,'job-one',{bytes:await readFile(m4a),mime_type:'audio/mp4'})
 assert.equal(a.codec,'mp3');assert.equal(a.sample_rate,44100);assert.ok(a.duration_seconds>1)
 assert.match(b.codec,/pcm_/);assert.equal(b.sample_rate,44100);assert.ok(b.duration_seconds>1)
 assert.equal(c.codec,'aac');assert.equal(c.sample_rate,44100);assert.ok(c.duration_seconds>1)
 await assert.rejects(f.service.uploadAudioAsset(actor,'job-one',{bytes:Buffer.from('not-an-mp3'),mime_type:'audio/mpeg'}),e=>e.code==='INVALID_SOUNDTRACK')
})

test('audio finishing preserves picture lock, creates a fresh master, and returns the same job to Critic',async()=>{
 const f=await fixture({testMode:false,deploymentClass:'controlled_single_operator_preview'}),dir=join(f.root,'audio-finishing');await mkdir(dir)
 const source=join(dir,'picture.mp4'),soundtrack=join(dir,'soundtrack.mp4')
 await execFile('/usr/bin/ffmpeg',['-nostdin','-v','error','-y','-f','lavfi','-i','testsrc2=size=360x640:rate=30:duration=2','-f','lavfi','-i','sine=frequency=440:duration=2','-c:v','libx264','-threads','1','-c:a','aac','-pix_fmt','yuv420p','-shortest',source])
 await execFile('/usr/bin/ffmpeg',['-nostdin','-v','error','-y','-f','lavfi','-i','sine=frequency=220:duration=4','-c:a','aac','-vn',soundtrack])
 await f.service.uploadSource(actor,'tenant-a','real-source',{bytes:await readFile(source),mime_type:'video/mp4'});let j=await runToReview(f);j=await approve(f);assert.equal(j.stage,'CRITIC',JSON.stringify(j.blockers));const oldCandidate=j.candidate_sha,pictureLock=j.artifact_sha256,providerExecution=digest(j.provider_execution)
 const audio=await f.service.uploadAudioAsset(actor,j.id,{bytes:await readFile(soundtrack),mime_type:'video/mp4'});assert.match(audio.id,/^audio_[a-f0-9]{64}$/);assert.equal(audio.sample_rate,44100)
 await f.service.configureAudioFinishing(actor,j.id,{preserve_original_intro:{enabled:true,from_seconds:0},soundtrack:{asset_id:audio.id,start_seconds:0,gain_db:-8},voice:{preserve:true,delay_ms:0},mix:{voice_priority:true,duck_under_voice:true},outro:{enabled:true,source_in_seconds:1,source_out_seconds:2,approved_phrase:'Firmes Firmes',tail_ms:600,echo:true,reverb:true},master:{integrated_lufs:-14,true_peak_max_dbtp:-1.5,compressor:'gentle',limiter:true},sync:{lock_to_video_duration:true}})
 await f.service.drain();j=(await f.repository.read()).jobs[j.id];assert.equal(j.stage,'CRITIC',JSON.stringify(j.blockers));assert.equal(j.status,'AWAITING_REVIEW');assert.notEqual(j.artifact_sha256,pictureLock);assert.notEqual(j.candidate_sha,oldCandidate);assert.equal(digest(j.provider_execution),providerExecution);assert.equal(j.provider_execution.artifact_sha256,pictureLock);assert.equal(j.audio_finishing.status,'APPLIED');assert.equal(j.audio_finishing_execution.picture_lock_sha256,pictureLock);assert.equal(j.audio_finishing_execution.output_sha256,j.artifact_sha256);assert.equal(j.audio_finishing_execution.soundtrack_sha256,audio.sha256);assert.equal(j.audio_finishing_execution.qa.sample_rate,48000);assert.equal(j.audio_finishing_execution.qa.channels,2);assert.ok(Math.abs(j.audio_finishing_execution.qa.integrated_lufs+14)<=1);assert.ok(j.audio_finishing_execution.qa.true_peak_dbtp<=-1.25);assert.ok(Math.abs(j.audio_finishing_execution.qa.audio_duration_seconds-j.audio_finishing_execution.qa.video_duration_seconds)<=0.04);assert.match(j.production_note,/Audio master/);assert.ok(j.repairs.some(r=>r.action==='AUDIO_FINISHING'&&r.picture_lock_sha256===pictureLock));const publicValue=publicJob(j);assert.equal(publicValue.audio_assets.length,1);assert.equal(publicValue.audio_assets[0].id,audio.id);assert.equal(JSON.stringify(publicValue).includes(f.root),false)
 const state=await f.service.service().status(f.service.paths(j));assert.equal(state.nodes.find(n=>n.id==='PROVIDER_PRODUCTION').revision,0);assert.equal(state.nodes.find(n=>n.id==='PROVIDER_PRODUCTION').status,'done');assert.equal(state.nodes.find(n=>n.id==='TECHNICAL_QA').revision,1);assert.equal(state.nodes.find(n=>n.id==='TECHNICAL_QA').status,'done');assert.equal(state.nodes.find(n=>n.id==='CRITIC').revision,0);assert.equal(state.nodes.find(n=>n.id==='CRITIC').status,'spec_ready');await assert.rejects(f.service.approve({id:'critic-human',memberships:[{tenant_id:'tenant-a',role:'reviewer'}]},j.id,{candidate_sha:oldCandidate,review_stage:'CRITIC'}),e=>e.code==='STALE_CANDIDATE')
})

test('a later visual repair invalidates the prior audio master but keeps the uploaded soundtrack available',async()=>{
 const f=await fixture({testMode:false,deploymentClass:'controlled_single_operator_preview'}),dir=join(f.root,'audio-invalidated-by-picture');await mkdir(dir)
 const source=join(dir,'picture.mp4'),soundtrack=join(dir,'soundtrack.mp4')
 await execFile('/usr/bin/ffmpeg',['-nostdin','-v','error','-y','-f','lavfi','-i','testsrc2=size=360x640:rate=30:duration=2','-f','lavfi','-i','sine=frequency=440:duration=2','-c:v','libx264','-threads','1','-c:a','aac','-pix_fmt','yuv420p','-shortest',source]);await execFile('/usr/bin/ffmpeg',['-nostdin','-v','error','-y','-f','lavfi','-i','sine=frequency=220:duration=3','-c:a','aac','-vn',soundtrack])
 await f.service.uploadSource(actor,'tenant-a','real-source',{bytes:await readFile(source),mime_type:'video/mp4'});let j=await runToReview(f);j=await approve(f);const audio=await f.service.uploadAudioAsset(actor,j.id,{bytes:await readFile(soundtrack),mime_type:'video/mp4'});await f.service.configureAudioFinishing(actor,j.id,{soundtrack:{asset_id:audio.id},master:{integrated_lufs:-14,true_peak_max_dbtp:-1.5}});await f.service.drain();j=(await f.repository.read()).jobs[j.id];assert.equal(j.audio_finishing.status,'APPLIED',JSON.stringify(j.blockers));const finishedSha=j.artifact_sha256
 await f.service.requestChanges({id:'critic-human',memberships:[{tenant_id:'tenant-a',role:'reviewer'}]},j.id,{candidate_sha:j.candidate_sha,review_stage:j.stage,reason:'duration: 1.5'});await f.service.drain();j=(await f.repository.read()).jobs[j.id];assert.equal(j.audio_finishing,null);assert.equal(j.audio_finishing_execution,null);assert.equal(j.audio_assets.length,1);assert.equal(j.audio_assets[0].id,audio.id);assert.equal(j.stage,'CREATIVE_GATE');assert.equal(j.artifact_sha256,null);assert.equal(j.provider_execution,null);assert.ok(j.artifacts.some(a=>a.sha256===finishedSha))
})

test('audio finishing requires explicit outro timecodes and an uploaded soundtrack; reviewers cannot mutate the master',async()=>{
 const f=await fixture();await runToReview(f);let j=await approve(f);assert.equal(j.stage,'RELEASE');const reviewer={id:'reviewer',memberships:[{tenant_id:'tenant-a',role:'reviewer'}]}
 await assert.rejects(f.service.configureAudioFinishing(actor,j.id,{soundtrack:{asset_id:'missing'}}),e=>e.code==='SOUNDTRACK_REQUIRED')
 await assert.rejects(f.service.configureAudioFinishing(reviewer,j.id,{soundtrack:{asset_id:'missing'}}),e=>e.code==='FORBIDDEN')
 assert.throws(()=>normalizeAudioFinishingContract({soundtrack:{asset_id:'a'},outro:{enabled:true,marker:'firmes_firmes'}}),e=>e.code==='INVALID_INPUT'||e.code==='INVALID_AUDIO_FINISHING')
})
