'use client';
import {useState,type ChangeEvent} from 'react';
import {Problem,Tag,type Item,type ApiError} from './ui';

export function ExternalGenerationPanel({job,onChanged}:{job:Item;onChanged:()=>void}){
 const pkg=job.external_generation_package,[busy,setBusy]=useState(false),[error,setError]=useState<ApiError|null>(null),[copied,setCopied]=useState(false);
 if(!pkg)return null;
 async function copyPrompt(){try{await navigator.clipboard.writeText(pkg.prompt||'');setCopied(true);setTimeout(()=>setCopied(false),1800)}catch{setError({code:'CLIPBOARD',message:'No se pudo copiar automáticamente. Selecciona el prompt y cópialo manualmente.'})}}
 async function upload(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setBusy(true);setError(null);try{const response=await fetch('/api/v1/jobs/'+encodeURIComponent(job.id)+'/external-result',{method:'POST',credentials:'same-origin',headers:{'Content-Type':file.type},body:file});const payload=await response.json();if(!response.ok)throw payload.error||{code:String(response.status),message:'No pudimos incorporar el resultado.'};onChanged()}catch(err){setError(err as ApiError)}finally{setBusy(false);e.target.value=''}}
 const expected=pkg.expected_output||{};const accept=expected.medium==='video'?'video/mp4':'image/png,image/jpeg';
 return <section className="panel external-generation-panel"><div className="section-title"><div><p className="eyebrow">GENERACIÓN EXTERNA / MISMO JOB</p><h2>{pkg.generation_phase==='HERO_IMAGE'?'Primero genera la imagen hero.':pkg.generation_phase==='VIDEO_FROM_APPROVED_HERO'?'Anima la imagen hero aprobada.':'Genera el resultado y tráelo de vuelta.'}</h2></div><Tag tone="success">Disponible</Tag></div><p>Media Factory ya preparó el prompt, las referencias y sus roles. Puedes usar CapCut, Seedance, H3 u otra herramienta aprobada. Al subir el resultado, este mismo trabajo continúa directo a Critic.</p><div className="chips">{(pkg.references||[]).map((r:Item)=><Tag key={r.asset_id}>{String(r.reference_id).replaceAll('_',' ')} · {String(r.role).replaceAll('_',' ')}</Tag>)}</div><div className="external-generation-actions"><button className="primary" type="button" onClick={copyPrompt}>{copied?'Prompt copiado':'Copiar prompt'}</button>{(pkg.references||[]).map((r:Item)=><a key={r.asset_id} className="button secondary" href={r.download_url} target="_blank" rel="noopener noreferrer">Ver {r.role==='CHARACTER_IDENTITY_ONLY'?'personaje':r.role==='ENVIRONMENT_ONLY'?'entorno':'referencia'} ↗</a>)}</div><details open><summary>Prompt compilado</summary><pre className="external-prompt">{pkg.prompt}</pre></details><details><summary>Checklist del paquete</summary><ul>{(pkg.checklist||[]).map((v:string)=><li key={v}>{v}</li>)}</ul></details><div className="notice"><strong>Salida esperada:</strong> {expected.medium==='video'?'video MP4':'imagen PNG/JPEG'} · {expected.aspect_ratio}{expected.duration_seconds?' · '+expected.duration_seconds+' s':''}</div><label className="button primary external-upload">{busy?'Incorporando resultado…':'Subir resultado'}<input type="file" accept={accept} onChange={upload} disabled={busy} hidden/></label><Problem error={error}/></section>
}

export function CriticRubricPanel({rubric,onFinding}:{rubric:Item;onFinding:(value:string)=>void}){
 if(!rubric)return null;const groups=[['Identidad',rubric.identity_checks],['Vestuario',rubric.wardrobe_checks],['Entorno',rubric.environment_checks],['Exclusiones',rubric.negative_checks],['Composición',rubric.composition_checks],['Técnica',rubric.technical_checks]].filter(([,values])=>Array.isArray(values)&&values.length);
 const common=['La identidad del Caballito cambió.','Apareció vestuario o equipo industrial prohibido.','Falta un elemento requerido del entorno.','Se filtró el entorno de la referencia del personaje.'];
 return <div className="critic-rubric"><p className="eyebrow">RÚBRICA ESTRUCTURADA</p><p>Revisa contra el contrato de la escena, no con un “se ve bien”. Si falla, registra el hallazgo exacto; el mismo job vuelve a generación.</p><div className="critic-rubric-grid">{groups.map(([label,values])=><div key={String(label)}><strong>{label}</strong><ul>{(values as string[]).map(v=><li key={v}>{v}</li>)}</ul></div>)}</div><div className="chips">{common.map(v=><button type="button" className="secondary" key={v} onClick={()=>onFinding(v)}>{v}</button>)}</div></div>
}
