'use client';
import Link from 'next/link';
import { useEffect, useState, useRef } from 'react';
import { CreationGuide } from './CreationGuide';
import { api, useLoad, items, Header, Icon, Tag, Empty, Loading, Problem, Field, DateLabel, Status, strategies, type Item, type Resource, type ApiError } from './ui';
import {FirmesFrame,FirmesCaballito,isFirmesTenant} from './FirmesBrand';
import {ExternalGenerationPanel,CriticRubricPanel} from './ExternalGenerationPanel';
export function JobLibrary({ tenants, releases }: { tenants: Resource; releases: boolean }) {
 const list = items(tenants.data), [selected, setSelected] = useState('');
 useEffect(() => { if (!selected && list.length) setSelected(list[0].tenant_id); }, [selected, tenants.data]);
 const jobs = useLoad(selected ? (releases ? '/releases' : '/jobs') + '?tenant_id=' + encodeURIComponent(selected) : null);
 return <>{selected&&<CreationGuide id={selected}/>}<Header eyebrow={releases ? 'HISTORIAS QUE YA TIENEN TU VISTO BUENO' : 'LA ÚLTIMA MIRADA ES TUYA'} title={releases ? 'Entregas' : 'Revisar videos'} description={releases ? 'Tus videos aprobados, listos para descargar.' : 'Mira cada versión, apruébala o pide un cambio.'} /><div className="filter-bar"><Field label="Espacio de trabajo"><select value={selected} onChange={e => setSelected(e.target.value)}><option value="" disabled>Selecciona un espacio</option>{list.map(t => <option key={t.tenant_id} value={t.tenant_id}>{t.organization}</option>)}</select></Field><button className="secondary" onClick={jobs.reload} disabled={!selected}>Actualizar</button></div>{tenants.loading || jobs.loading ? <Loading /> : tenants.error ? <Problem error={tenants.error} retry={tenants.reload} /> : jobs.error ? <Problem error={jobs.error} retry={jobs.reload} /> : items(jobs.data).length ? <div className="list-panel">{items(jobs.data).map(j => releases ? <article className="release-entry" key={j.id}><div className="list-row job-row"><div className="job-icon"><Icon name="release" /></div><div className="grow"><h3><Link href={'/jobs/' + j.job_id}>{j.title || 'Producción ' + j.job_id}</Link></h3><p>{list.find(t => t.tenant_id === j.tenant_id)?.organization || j.tenant_id} · <DateLabel value={j.created_at} /></p></div><Tag>Versión {j.version}</Tag>{j.test && <Tag tone="warning">Prueba de integración</Tag>}</div><ReleaseDetails release={j} /></article> : <Link className="list-row job-row" key={j.id} href={'/jobs/' + (j.job_id || j.id)}><div className="job-icon"><Icon name={releases ? 'release' : 'play'} /></div><div className="grow"><h3>{j.title || 'Producción ' + (j.job_id || j.id).slice(0, 8)}</h3><p><DateLabel value={j.released_at || j.created_at} />{j.strategy && ' · ' + (strategies.find(s => s.value === j.strategy)?.title || j.strategy)}</p>{releases && <Tag>Versión {j.version || 1}</Tag>}{j.test && <Tag tone="warning">Prueba de integración</Tag>}</div><Status value={j.status || 'RELEASED'} /><span aria-hidden="true">↗</span></Link>)}</div> : <Empty icon={releases ? 'release' : 'review'} title={releases ? 'Aquí estarán tus entregas.' : 'Aquí verás tus historias en producción.'} action={!releases && <Link className="button secondary" href={selected ? '/workspace/' + selected + '/weekly' : '/workspaces'}>Crear un plan</Link>}>{releases ? 'Tus videos aparecerán aquí cuando los hayas aprobado.' : 'Guarda y aprueba un plan para solicitar tu primera producción.'}</Empty>}</>;
}
const stageNames: Record<string, string> = { BRIEF: 'Brief', SOURCE: 'Fuentes', INGEST: 'Preparación', DIRECTOR_TREATMENT: 'Tratamiento', CONCEPT_REVIEW: 'Concepto', CREATIVE_GATE: 'Revisión creativa', PROVIDER_PRODUCTION: 'Producción', TECHNICAL_QA: 'Calidad técnica', CRITIC: 'Revisión crítica', FIXER: 'Ajustes', INDEPENDENT_VERIFIER: 'Verificación', COMPLIANCE: 'Conformidad', RELEASE: 'Entrega' };
const simpleJourney=[
 {label:'Preparar',stages:['BRIEF','SOURCE','INGEST','DIRECTOR_TREATMENT','CONCEPT_REVIEW','CREATIVE_GATE']},
 {label:'Crear',stages:['PROVIDER_PRODUCTION','TECHNICAL_QA','FIXER']},
 {label:'Revisar',stages:['CRITIC','INDEPENDENT_VERIFIER','COMPLIANCE']},
 {label:'Entregar',stages:['RELEASE']},
] as const;
function simpleJourneyIndex(stage:string,status:string){if(status==='RELEASED')return 3;const index=simpleJourney.findIndex(group=>(group.stages as readonly string[]).includes(stage));return index<0?0:index}

export function JobDetail({ id, manageIntegrations=false }: { id: string; manageIntegrations?: boolean }) {
 const connected = useRef(false);
 const job = useLoad('/jobs/' + encodeURIComponent(id)), [busy, setBusy] = useState(false), [error, setError] = useState<ApiError | null>(null), [message, setMessage] = useState(''), [reason, setReason] = useState(''), [live, setLive] = useState(false);
 const release = useLoad(job.data?.release_id ? '/releases/' + encodeURIComponent(job.data.release_id) : null);
 const jobTenant=useLoad(job.data?.tenant_id?'/tenants/'+encodeURIComponent(job.data.tenant_id):null);
 useEffect(() => { const events = new EventSource('/api/v1/jobs/' + encodeURIComponent(id) + '/events'); events.onopen = () => { connected.current = true; setLive(true); }; events.onmessage = () => job.reload(); events.addEventListener('product-state', job.reload); events.onerror = () => { connected.current = false; setLive(false); }; const interval = setInterval(() => { if (!connected.current) job.reload(); }, 15000); return () => { connected.current = false; events.close(); clearInterval(interval); }; }, [id, job.reload]);
 if (job.loading && !job.data) return <Loading text="Abriendo producción…" />;
 if (job.error) return <Problem error={job.error} retry={job.reload} />;
 const j = job.data; if (!j) return null;
 const artifacts: Item[] = (j.artifacts || []).filter((a: Item) => j.artifact_sha256 && a.sha256 === j.artifact_sha256), reviewable = j.review_state === 'AWAITING_REVIEW', released = j.status === 'RELEASED', isRelease = j.stage === 'RELEASE';
 const blockerCodes=new Set((j.blockers||[]).map((b:Item)=>typeof b==='string'?b:b?.code).filter(Boolean));
 const sourceBlocker=(j.blockers||[]).find((b:Item)=>b?.code==='SOURCE_BYTES_REQUIRED'), missingSource=sourceBlocker?.source_ids?.[0]||j.source_ids?.[0];
 const sourceResolutionHref=sourceBlocker&&j.tenant_id&&missingSource?'/workspace/'+encodeURIComponent(j.tenant_id)+'/sources?focus='+encodeURIComponent(missingSource)+'&resume='+encodeURIComponent(j.id)+'&return='+encodeURIComponent('/jobs/'+j.id):null;
 const durationBlocker=blockerCodes.has('SOURCE_TOO_SHORT'), shortSource=j.source_ids?.[0], shortResolutionHref=durationBlocker&&j.tenant_id&&shortSource?'/workspace/'+encodeURIComponent(j.tenant_id)+'/sources?focus='+encodeURIComponent(shortSource)+'&resume='+encodeURIComponent(j.id)+'&return='+encodeURIComponent('/jobs/'+j.id):null;
 const sourceDurations=(j.source_assets||[]).map((a:Item)=>Number(a.duration_seconds)).filter((v:number)=>Number.isFinite(v)&&v>0), fitDuration=sourceDurations.length?Math.floor(Math.min(...sourceDurations)*sourceDurations.length*10)/10:null;
 const decisionBlocker=[...blockerCodes].some(code=>['MASCOT_RENDER_UNAVAILABLE','ADAPTER_REQUIRED','PROVIDER_UNAVAILABLE','PROVIDER_CREDENTIAL_MISSING'].includes(String(code)));
 const manualBlocker=blockerCodes.has('MANUAL_REPAIR_REQUIRED');
 const compatibleBlockedMascotChange=manualBlocker&&/(caballito|caballo|mascota|horse|mascot)/i.test(j.repair_instructions||'')&&/(agregar|añadir|anadir|poner|incluir|add|include|quitar|eliminar|retirar|remove|without)/i.test(j.repair_instructions||'');
 const humanBlocker=blockerCodes.has('HUMAN_APPROVAL_REQUIRED');
 const editHref=j.tenant_id?(j.creation_mode==='GUIDED_SCENE'?'/workspace/'+encodeURIComponent(j.tenant_id)+'/scene':'/workspace/'+encodeURIComponent(j.tenant_id)+'/weekly?plan='+encodeURIComponent(j.plan_id||'')+'&story='+encodeURIComponent(j.story_id||'')+'&return='+encodeURIComponent('/jobs/'+j.id)):null;
 const integrationHref='/admin/integrations?focus=video-generation&return='+encodeURIComponent('/jobs/'+j.id);
 const simpleStep=simpleJourneyIndex(j.stage,j.status), completedStages=j.graph?.nodes?.filter((n:Item)=>n.status==='done').length||0, totalStages=j.graph?.nodes?.length||13;
 const statusTitle=released?'Tu video está listo':reviewable?'Tu video está listo para revisar':j.status==='BLOCKED'?'Necesitamos una decisión tuya':j.status==='WAITING_EXTERNAL_GENERATION'?'Falta recibir el resultado de creación':j.status==='RUNNING'||j.status==='QUEUED'?'Estamos preparando tu video':'Tu producción está en proceso';
 const statusCopy=released?'Puedes descargar la entrega o consultar sus detalles cuando quieras.':reviewable?'Mira la versión y decide si la aprobamos o si quieres un cambio.':j.status==='BLOCKED'?'Elige una de las opciones de arriba. No perderás el trabajo ya realizado.':j.status==='WAITING_EXTERNAL_GENERATION'?'En cuanto llegue el resultado, esta misma producción continuará automáticamente.':'Se actualiza automáticamente. Puedes salir de esta pantalla y volver después.';
 async function action(name: string) { setBusy(true); setError(null); try { const updated=await api('/jobs/' + id + '/' + name, name === 'start' ? {} : { candidate_sha: j.candidate_sha, review_stage: j.stage, ...(name !== 'approve' ? { reason: reason.trim() } : {}) }); const repairAction=updated?.repair_controls?.blocker_action; setMessage(name === 'approve' ? isRelease ? 'Entrega lista. No se ha publicado en redes sociales.' : 'Tu aprobación quedó registrada sobre esta versión.' : name === 'request-changes' && repairAction==='ADD_FIRMES_MASCOT' ? 'Listo: agregaremos el Caballito FIRMES autorizado y te mostraremos la nueva versión aquí mismo.' : name === 'request-changes' && repairAction==='REMOVE_MASCOT' ? 'Listo. Quitaremos la mascota y te mostraremos la nueva versión aquí mismo.' : name === 'request-changes' ? 'Listo. Prepararemos una nueva versión con tu comentario.' : 'Acción registrada.'); setReason(''); job.reload(); } catch (err) { setError(err as ApiError); } finally { setBusy(false); } }
 async function repair(actionName: 'USE_REAL_FOOTAGE'|'REMOVE_MASCOT'|'FIT_SOURCE_DURATION'|'WITHDRAW_MANUAL_CHANGE'|'APPLY_SUPPORTED_CHANGE') { setBusy(true); setError(null); try { const updated=await api('/jobs/' + id + '/repair',{action:actionName}); const applied=updated?.repair_controls?.blocker_action; setMessage(actionName==='USE_REAL_FOOTAGE'?'Listo. Usaremos solo tu material real y prepararemos una nueva versión.':actionName==='REMOVE_MASCOT'?'Listo. Quitaremos la mascota y prepararemos una nueva versión.':actionName==='FIT_SOURCE_DURATION'?'Listo. Ajustaremos la duración al material disponible.':actionName==='APPLY_SUPPORTED_CHANGE'&&applied==='ADD_FIRMES_MASCOT'?'Listo: agregaremos el Caballito FIRMES autorizado y te mostraremos la nueva versión aquí mismo.':actionName==='APPLY_SUPPORTED_CHANGE'&&applied==='REMOVE_MASCOT'?'Listo. Quitaremos la mascota y te mostraremos la nueva versión aquí mismo.':'Listo. Continuaremos sin ese cambio.'); job.reload(); } catch (err) { setError(err as ApiError); } finally { setBusy(false); } }
 const blocker = j.blockers?.length>0 ? <section className="repair-card" aria-label="Acción necesaria">
   <p className="eyebrow">ACCIÓN NECESARIA</p>
   <h2>{sourceResolutionHref?'Falta el video para continuar':compatibleBlockedMascotChange?'¿Aplicamos este cambio?':durationBlocker?'El video es más corto de lo esperado':decisionBlocker?'Elige cómo continuar':manualBlocker?'Este cambio necesita edición':humanBlocker?'Necesitamos tu aprobación':'Necesitamos un paso más'}</h2>
   <p>{sourceResolutionHref?'Sube el archivo y retomaremos esta misma producción automáticamente.':compatibleBlockedMascotChange?'Sí podemos hacerlo aquí. Aplicaremos el cambio sobre esta misma producción y te mostraremos una nueva versión para revisar.':durationBlocker?'Puedes ajustar la entrega a la duración disponible o reemplazar el archivo.':decisionBlocker?'No vamos a cambiar tu idea por nuestra cuenta. Elige una opción y continuaremos con esta misma producción.':manualBlocker?'Ese cambio todavía no puede hacerse automáticamente. Puedes editar la historia o continuar sin ese cambio.':humanBlocker?'Revisa la versión y decide cómo continuar.':'La producción podrá continuar en cuanto resolvamos este punto.'}</p>
   {j.repair_instructions&&<div className="requested-change"><span>Cambio pedido</span><strong>{j.repair_instructions}</strong></div>}
   <div className="actions">
    {sourceResolutionHref&&<a className={'button primary '+(isFirmesTenant(jobTenant.data)?'gooey-cta':'')} href={sourceResolutionHref} aria-label="Subir el video faltante">Subir video <Icon name="arrow"/></a>}
    {compatibleBlockedMascotChange&&<button className="primary" disabled={busy} onClick={()=>repair('APPLY_SUPPORTED_CHANGE')}>{/(quitar|eliminar|retirar|remove|without)/i.test(j.repair_instructions||'')?'Quitar mascota':'Agregar Caballito'}</button>}
    {durationBlocker&&fitDuration!==null&&fitDuration>=1&&<button className="primary" disabled={busy} onClick={()=>repair('FIT_SOURCE_DURATION')}>Usar {fitDuration.toFixed(1)} s</button>}
    {durationBlocker&&shortResolutionHref&&<Link className="button secondary" href={shortResolutionHref}>Cambiar video</Link>}
    {decisionBlocker&&<button className="primary" disabled={busy} onClick={()=>repair('USE_REAL_FOOTAGE')}>Usar mi material</button>}
    {decisionBlocker&&blockerCodes.has('MASCOT_RENDER_UNAVAILABLE')&&<button className="secondary" disabled={busy} onClick={()=>repair('REMOVE_MASCOT')}>Continuar sin mascota</button>}
    {humanBlocker&&<Link className="button primary" href="/review">Revisar ahora</Link>}
    {!compatibleBlockedMascotChange&&manualBlocker&&editHref&&<Link className="button primary" href={editHref}>Editar historia</Link>}
    {compatibleBlockedMascotChange&&editHref&&<Link className="button secondary" href={editHref}>Editar historia</Link>}
    {decisionBlocker&&manageIntegrations&&<Link className="button secondary" href={integrationHref}>Conectar herramienta</Link>}
   </div>
   {(manualBlocker||decisionBlocker)&&<details className="repair-more"><summary>Otras opciones</summary><div className="actions">{manualBlocker&&<button className="text-button" disabled={busy} onClick={()=>repair('WITHDRAW_MANUAL_CHANGE')}>Continuar sin este cambio</button>}{decisionBlocker&&!manageIntegrations&&<Link className="text-button" href="/review">Pedir ayuda para revisar</Link>}</div></details>}
  </section> : null;
 return <FirmesFrame tenant={jobTenant.data} banner={false}><>
  <Link className="back-link" href="/review">← Mis producciones</Link>
  {isFirmesTenant(jobTenant.data)&&<div className="minimal-brand-mark" aria-label="FIRMES"><FirmesCaballito compact/><span><strong>FIRMES</strong><small>Studio</small></span></div>}
  <Header eyebrow="TU VIDEO" title={j.title || 'Producción'} description={j.objective || 'Revisa tu contenido y decide qué sigue.'} action={<Status value={j.status} />} />
  {j.test && <div className="notice warning">Prueba de integración. Este artefacto verifica el flujo y no es contenido de producción.</div>}
  <ol className="simple-progress" aria-label="Avance de la producción">{simpleJourney.map((group,index)=><li key={group.label} className={index===simpleStep?'current':index<simpleStep?'complete':''}><span>{index<simpleStep?'✓':index+1}</span><strong>{group.label}</strong></li>)}</ol>
  {j.status==='WAITING_EXTERNAL_GENERATION'&&<ExternalGenerationPanel job={j} onChanged={job.reload}/>}
  {blocker}
  {message && <div className="notice success" role="status">{message}</div>}
  <div className="simple-status" role="status"><div><span className={'tiny-dot '+(live?'':'inactive')} /><strong>{statusTitle}</strong></div><p>{statusCopy}</p></div>
  <div className="job-detail-grid minimal-job-grid">
   <section className="panel preview-panel">{artifacts.length ? artifacts.map((a, i) => <div className="artifact" key={a.id || i}>{a.download_url && /video/.test(a.mime_type || '') ? <video controls preload="metadata" src={a.download_url} aria-label={a.name || 'Vista previa de la producción'} /> : a.download_url && /image/.test(a.mime_type || '') ? <img src={a.download_url} alt={a.name || 'Artefacto de producción'} /> : <div className="artifact-placeholder"><Icon name="review" /><h3>{a.name || a.kind || 'Artefacto de producción'}</h3><p>La vista previa aparecerá aquí.</p></div>}{a.download_url && <a className="button secondary" href={a.download_url} target="_blank" rel="noopener noreferrer">Abrir en grande ↗</a>}</div>) : j.review_candidate ? <div className="candidate"><p className="eyebrow">ANTES DE PRODUCIR</p><h2>Así se plantea esta versión.</h2><Candidate value={j.review_candidate} /></div> : <Empty icon="play" title="Tu video aparecerá aquí.">Estamos preparando el contenido de esta producción.</Empty>}</section>
   <aside className="panel job-context simple-context"><p className="eyebrow">IDEA</p><h3>{j.title}</h3><p>{j.objective || 'Tu objetivo de contenido aparecerá aquí.'}</p>{j.production_note&&<p className="production-note">{j.production_note}</p>}{j.tenant_id&&<Link href={'/workspace/'+j.tenant_id+'/weekly'}>Volver al plan →</Link>}<details><summary>Detalles de producción</summary><dl><dt>Estrategia</dt><dd>{strategies.find(s => s.value === j.strategy)?.title || 'Automática'}</dd>{j.production_provider&&<><dt>Herramienta usada</dt><dd>{j.production_provider}</dd></>}<dt>Etapa interna</dt><dd>{stageNames[j.stage] || j.stage}</dd><dt>Creación</dt><dd><DateLabel value={j.created_at} /></dd></dl></details></aside>
  </div>
  {reviewable && <section className="panel approval-panel simple-approval"><div><p className="eyebrow">REVISIÓN HUMANA / {stageNames[j.stage] || j.stage}</p><h2>{isRelease ? '¿La entregamos?' : '¿Te gusta esta versión?'}</h2><p>{isRelease ? 'Si la apruebas, quedará lista para descargar. No se publicará automáticamente.' : 'Aprueba esta versión o dinos qué quieres cambiar. Prepararemos la siguiente versión sobre este mismo trabajo.'}</p>{j.stage==='CRITIC'&&j.critic_rubric&&<details className="review-guidance"><summary>Ver guía de revisión</summary><CriticRubricPanel rubric={j.critic_rubric} onFinding={setReason}/></details>}<Field label="¿Qué cambiarías?"><textarea aria-label="Comentarios para la revisión" value={reason} onChange={e => setReason(e.target.value)} rows={3} maxLength={2000} placeholder="Ejemplo: agrega al Caballito, cambia el inicio o usa otro video…" /></Field><div className="actions"><button className="primary" onClick={() => action('approve')} disabled={busy || !j.candidate_sha}>{isRelease ? 'Aprobar entrega' : 'Aprobar esta versión'}</button><button className="secondary" onClick={() => action('request-changes')} disabled={busy || !reason.trim()}>Solicitar cambios</button></div><details className="review-more"><summary>Más opciones</summary><button className="text-button" onClick={() => action('reject')} disabled={busy || !reason.trim()}>Rechazar esta versión</button></details></div></section>}
  {released && <><div className="notice success">Entrega lista. La publicación en redes sociales se realiza por separado.</div>{release.loading ? <Loading text="Consultando la entrega…" /> : release.error ? <Problem error={release.error} retry={release.reload} /> : release.data && <section className="panel release-snapshot"><h2>Tu entrega</h2><ReleaseDetails release={release.data} /></section>}</>}
  <Problem error={error} />
  <details className="panel technical-panel"><summary>Detalles técnicos</summary><div className="technical-summary"><span>{live?'Actualización automática activa':'Actualización periódica'}</span><button className="text-button" onClick={job.reload}>Actualizar ahora</button></div><dl><dt>Identificador</dt><dd className="hash">{j.id}</dd><dt>Avance interno</dt><dd>{completedStages} de {totalStages} etapas verificadas</dd><dt>Versión revisada</dt><dd className="hash">{j.candidate_sha || 'Aún no disponible'}</dd><dt>Huella del archivo</dt><dd className="hash">{j.artifact_sha256 || 'Aún no disponible'}</dd>{j.provider_execution&&<><dt>Procedencia</dt><dd><Provenance execution={j.provider_execution} /></dd></>}{j.source_assets?.length>0&&<><dt>Material de origen</dt><dd><SourceAssets assets={j.source_assets} /></dd></>}{j.approvals?.length>0&&<><dt>Revisiones</dt><dd><Reviews reviews={j.approvals} /></dd></>}</dl>{j.evidence?.length>0&&<details><summary>Actividad y evidencia ({j.evidence.length})</summary><div className="evidence-list">{j.evidence.map((e:Item,i:number)=><div key={e.id||i}><span className="tiny-dot"/><div><strong>{stageNames[e.kind]||e.kind||'Registro'}</strong><p>{e.summary||e.result||'Evidencia persistida'}</p><small><DateLabel value={e.created_at}/></small></div></div>)}</div></details>}{j.graph?.nodes?.length>0&&<details><summary>Etapas verificables</summary><div className="graph-nodes">{j.graph.nodes.map((n:Item)=><div key={n.id}><span>{stageNames[n.id]||n.title||n.id}</span><Status value={String(n.status||'').toUpperCase()}/></div>)}</div></details>}</details>
 </></FirmesFrame>;
}

const labels: Record<string,string> = {creative_context:'Personajes y lugar de esta versión',character:'Personaje principal',place:'Lugar',name:'Nombre',facts:'Datos y notas aportadas',reference_url:'Referencia',information_status:'Estado de la información',principal:'Protagonista',rights_confirmed:'Autorización declarada',content_sha:'Huella de la ficha',title:'Título',objective:'Intención',strategy:'Estrategia',story_devices:'Recursos narrativos',source_ids:'Material autorizado',creative_hook:'Inicio creativo',narrative:'Narrativa',beats:'Momentos',production_notes:'Notas de producción',visual_direction:'Dirección visual',audio_direction:'Dirección sonora',treatment:'Tratamiento',concept:'Concepto',description:'Descripción',duration_seconds:'Duración en segundos',aspect_ratio:'Formato',rationale:'Intención',shots:'Planos',scene:'Escena',text:'Texto',target:'Formato de entrega'};
function Candidate({value,depth=0}:{value:any;depth?:number}) { if(depth>5||value==null)return null; if(typeof value!=='object')return <span>{typeof value==='boolean'?(value?'Sí':'No'):String(value)}</span>; if(Array.isArray(value))return <ul>{value.slice(0,30).map((v,i)=><li key={i}><Candidate value={v} depth={depth+1}/></li>)}</ul>;return <dl className="candidate-fields">{Object.entries(value).filter(([k])=>!/(sha|hash|schema_version|tenant_id|job_id|path|artifact|snapshot|revision|approved|candidate_sha)/.test(k)).slice(0,30).map(([k,v])=><div key={k}><dt>{labels[k]||k.replaceAll('_',' ')}</dt><dd><Candidate value={v} depth={depth+1}/></dd></div>)}</dl>; }

function SourceAssets({ assets }: { assets: Item[] }) { return <ul className="source-assets">{assets.map(a => <li key={a.source_id}><strong>{a.source_id}</strong><span className="hash">{a.sha256}</span>{a.width && a.height && <small>{a.width} × {a.height}{a.duration_seconds ? ' · ' + Number(a.duration_seconds).toFixed(1) + ' s' : ''}</small>}</li>)}</ul>; }
function Provenance({ execution }: { execution: Item | null }) { if (!execution) return <p className="muted">La procedencia de esta versión no está disponible.</p>; const p = execution.provenance || {}; return <div className="media-provenance"><p><strong>{execution.provider}</strong> · {execution.test ? 'Artefacto sintético de prueba' : p.synthetic === true ? 'Incluye material generado' : p.synthetic === false ? 'Edición de material real' : 'Origen sin clasificar'}</p>{execution.estimate?.credits !== null && execution.estimate?.credits !== undefined && <p>Estimación registrada: {execution.estimate.credits} créditos{execution.estimate.cost === null ? ' · importe monetario no informado' : ''}.</p>}{p.used_sources?.length ? <SourceAssets assets={p.used_sources} /> : <p className="muted">{execution.test ? 'Esta prueba no utilizó material de producción.' : 'No hay fuentes consumidas registradas.'}</p>}{p.brand_assets?.length>0&&<div className="brand-provenance"><strong>Activos de marca autorizados</strong><ul className="source-assets">{p.brand_assets.map((a:Item)=><li key={a.asset_id}><strong>{a.asset_id}</strong><span className="hash">{a.sha256}</span><small>{a.synthetic===false?'Referencia autorizada · no sintética':'Procedencia no clasificada'}</small></li>)}</ul></div>}</div>; }
function Reviews({ reviews }: { reviews: Item[] }) { return <ul className="review-history">{reviews.map((review, i) => <li key={i}><strong>{stageNames[review.scope] || review.scope || 'Revisión'}</strong> · {review.actor_id}<small><DateLabel value={review.created_at} /></small><span className="hash">{review.candidate_sha}</span></li>)}</ul>; }
function ReleaseDetails({ release }: { release: Item }) { return <div className="release-details"><div className="chips"><Tag>{release.aspect_ratio || 'Formato no registrado'}</Tag><Tag>{release.publication_state === 'READY_FOR_MANUAL_PUBLISH' ? 'Lista para publicar manualmente' : release.publication_state === 'NOT_PUBLISHED' ? 'Sin publicar' : release.publication_state}</Tag></div><details><summary>Archivo, aprobación y procedencia</summary><dl><dt>Huella del archivo maestro</dt><dd className="hash">{release.artifact_sha256 || 'No registrada'}</dd><dt>Candidato aprobado</dt><dd className="hash">{release.candidate_sha || 'No registrado'}</dd><dt>Aprobación final</dt><dd>{release.approval?.actor_id || 'No registrada'} · <DateLabel value={release.created_at} /></dd><dt>Procedencia de esta entrega</dt><dd><Provenance execution={release.provider_execution} /></dd>{release.reviews?.length > 0 && <><dt>Historial de revisión</dt><dd><Reviews reviews={release.reviews} /></dd></>}</dl></details><div className="actions">{release.artifacts?.map((artifact: Item) => artifact.download_url && <a key={artifact.id} className="button secondary" href={artifact.download_url} download>{release.test ? 'Descargar artefacto de prueba' : 'Descargar entrega'}</a>)}</div></div>; }
