'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState, useEffect, useRef, type FormEvent } from 'react';
import { api, useLoad, items, Header, Icon, Tag, Empty, Loading, Problem, Field, DateLabel, Status, strategies, deviceLabels, type Item, type Resource, type ApiError } from './ui';
import {creationUpdated} from './CreationGuide';
function weekStart() { const d = new Date(); d.setUTCDate(d.getUTCDate() - ((d.getUTCDay() + 6) % 7)); return d.toISOString().slice(0, 10); }
function blankStory(): Item { return { id: 'story-' + crypto.randomUUID(), title: '', objective: '', source_ids: [], story_devices: [], strategy: 'AUTO', preferred_provider: 'AUTO', mascot: false }; }
export function Planner({ tenant, free }: { tenant: Item; free: boolean }) {
 const base = '/tenants/' + tenant.tenant_id, dna = useLoad(base + '/content-dna'), plans = useLoad(base + '/weekly-plans'), providers = useLoad('/providers'), profiles = useLoad(base+'/creative-profiles'), brandProfile=useLoad(base+'/brand-profile'), brandCharacters=useLoad(base+'/brand-characters'), jobList=useLoad('/jobs?tenant_id='+encodeURIComponent(tenant.tenant_id));
 const [step, setStep] = useState(0), [week, setWeek] = useState(weekStart), [text, setText] = useState(''), [stories, setStories] = useState<Item[]>([]), [selectedSources, setSelectedSources] = useState<string[]>(() => free ? (tenant.sources || []).filter((s: Item) => s.purpose === 'source').map((s: Item) => s.id) : []), [clarifications, setClarifications] = useState<string[]>([]), [busy, setBusy] = useState(false), [error, setError] = useState<ApiError | null>(null), [saved, setSaved] = useState<Item | null>(null), [message, setMessage] = useState(''), [globalStrategy, setGlobalStrategy] = useState('AUTO');
 const anchor=useRef<HTMLElement>(null), seeded=useRef(false), touched=useRef(false), recovered=useRef(false);
 useEffect(()=>{if(touched.current||seeded.current||profiles.loading||!profiles.data)return;const query=new URLSearchParams(window.location.search),character=items(profiles.data).find(p=>p.id===query.get('character')&&p.kind==='character'),place=items(profiles.data).find(p=>p.id===query.get('place')&&p.kind==='place');if(character||place){seeded.current=true;const subject=character||place;setStories([{...blankStory(),title:'Una historia con '+subject!.name,objective:subject!.description.slice(0,500),character_id:character?.id||null,place_id:place?.id||null,mascot:!!character}]);setMessage('La ficha seleccionada ya está en tu historia. Elige su material para continuar.');}},[profiles.data,profiles.loading]);
 useEffect(()=>{const refresh=()=>{if(!document.hidden)jobList.reload()};const timer=setInterval(refresh,10000);return()=>clearInterval(timer)},[jobList.reload]);
 function openPlan(p:Item){touched.current=true;setStories((p.stories||[]).map((s:Item)=>({...s,character_id:s.character_id===undefined?s.creative_context?.character?.id||null:s.character_id,place_id:s.place_id===undefined?s.creative_context?.place?.id||null:s.place_id})));  setSaved(p); setSelectedSources([...new Set<string>((p.stories||[]).flatMap((s:Item)=>s.source_ids||[]))]); setWeek(p.week_of); setStep(6); setClarifications([]); setMessage('Plan guardado recuperado.'); window.scrollTo({ top: 0, behavior: 'smooth' });}
 useEffect(()=>{if(recovered.current||touched.current||plans.loading||!plans.data)return;const id=new URLSearchParams(window.location.search).get('plan'),p=items(plans.data).find(p=>p.id===id);if(p){recovered.current=true;openPlan(p)}},[plans.data,plans.loading]);
 function go(next:number){setStep(next);requestAnimationFrame(()=>anchor.current?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'}))}
 const router = useRouter(), sourceList = (tenant.sources || []).filter((s: Item) => s.purpose === 'source'), dnaData = dna.data?.dna || dna.data;
 function updateStories(next: Item[]) { touched.current=true; setStories(next); setSaved(null); setMessage(''); }
 async function advanceStep() {
  if(step===0&&(!/^\d{4}-\d{2}-\d{2}$/.test(week)||new Date(week+'T00:00:00Z').getUTCDay()!==1)){setError({code:'INVALID_WEEK',message:'Elige el lunes de la semana que quieres planificar.'});return;}
  if(step===6&&saved?.status!=='APPROVED'&&saved?.status!=='LAUNCHED'){setError({code:'APPROVAL_REQUIRED',message:'Aprueba los conceptos antes de pasar a producción.'});return;}
  if(step===1&&!selectedSources.length){setError({code:'SOURCE_REQUIRED',message:'Selecciona un video autorizado para continuar.'});return;}
  if(step===4&&stories.some(s=>!s.title.trim()||!s.objective?.trim()||!s.source_ids?.length||!s.story_devices?.length)){setError({code:'INVALID_PLAN',message:'Completa título, intención, material y un recurso narrativo en cada historia antes de continuar.'});return;}
  if(step===0&&!stories.length) updateStories([{...blankStory(),story_devices:dnaData?.story_devices||[]}]);
  if(step===2){
   if(!dnaData?.story_devices?.length){setError({code:'DNA_REQUIRED',message:'Primero define el estilo creativo con una referencia.'});return;}
   updateStories(stories.map(story=>({...story,story_devices:story.story_devices?.length?story.story_devices:[...dnaData.story_devices]})));
  }
  if(step===4&&!saved){
   const plan=await saveDraft({automatic:true});
   if(!plan)return;
   setError(null);go(5);return;
  }
  setError(null);go(step+1);
 }
 async function interpret(e: FormEvent<HTMLFormElement>) { e.preventDefault(); touched.current=true; setBusy(true); setError(null); setSaved(null); try { const draft = await api(base + '/free-draft', { text, week_of: week, source_ids: selectedSources }); setStories(draft.stories || []); setClarifications((draft.clarifications || []).map((c: any) => typeof c === 'string' ? c : c.message || c.question || 'Aclara un detalle de tu solicitud.')); setMessage(draft.stories?.length ? 'Tu idea ya tiene forma. Revisa y ajusta cada historia antes de guardar.' : 'Necesitamos un poco más de detalle para dar forma al borrador.'); } catch (err) { setError(err as ApiError); } finally { setBusy(false); } }
 async function saveDraft({automatic=false}:{automatic?:boolean}={}) { setBusy(true); setError(null); try { const plan = await api(base + '/weekly-plans', { week_of: week, stories: stories.map(({approved,creative_context,...story})=>({...story,character_id:story.character_id??null,place_id:story.place_id??null})), mode: free ? 'free' : 'guided' }); setSaved(plan); setMessage(automatic?'Guardamos tu borrador automáticamente. Revisa y aprueba cuando estés listo.':'Borrador guardado. Todavía no has aprobado conceptos ni iniciado producción.'); plans.reload();creationUpdated(); return plan; } catch (err) { setError(err as ApiError); return null; } finally { setBusy(false); } }
 async function save() { await saveDraft(); }
 async function approve() { if (!saved) return; setBusy(true); setError(null); try { const plan = await api(base + '/weekly-plans/' + saved.id + '/approve', { story_ids: stories.map(s => s.id) }); setSaved(plan); setMessage('Conceptos aprobados. Ya puedes solicitar producción.'); plans.reload();creationUpdated(); } catch (err) { setError(err as ApiError); } finally { setBusy(false); } }
 async function launch() { if (!saved) return; setBusy(true); setError(null); try { const result = await api(base + '/weekly-plans/' + saved.id + '/launch', {});setSaved({...saved,status:'LAUNCHED'});jobList.reload(); setMessage('Solicitud registrada. Consulta el estado real de cada producción.'); plans.reload();creationUpdated(); const jobs = items(result); if (jobs[0]?.id) router.push('/jobs/' + jobs[0].id); else setSaved({ ...saved, status: 'LAUNCHED' }); } catch (err) { setError(err as ApiError); } finally { setBusy(false); } }
 const sourcePicker = <div>{sourceList.length ? <div className="selection-grid">{sourceList.map((s: Item) => <label className={'selection-card ' + (selectedSources.includes(s.id) ? 'selected' : '')} key={s.id}><input type="checkbox" checked={selectedSources.includes(s.id)} onChange={e => { const next = e.target.checked ? [...selectedSources, s.id] : selectedSources.filter(v => v !== s.id); setSelectedSources(next); updateStories(stories.map(story => ({ ...story, source_ids: next }))); }} /><Icon name="sources" /><strong>{s.id}</strong><small>Material autorizado</small></label>)}</div> : <div className="notice"><p>No hay material de producción autorizado en este espacio.</p><Link href={'/workspace/' + tenant.tenant_id + '/sources'}>Agregar material →</Link></div>}<p className="muted small-text">Las referencias creativas no aparecen como material de producción.</p></div>;
 const strategyPicker = <div className="strategy-grid">{strategies.map(s => <button type="button" className={'strategy-card ' + (globalStrategy === s.value ? 'selected' : '')} key={s.value} onClick={() => { setGlobalStrategy(s.value); updateStories(stories.map(story => ({ ...story, strategy: s.value }))); }}><span className="radio-indicator" /><strong>{s.title}</strong><small>{s.text}</small></button>)}</div>;
 const editor = <StoryEditor tenantId={tenant.tenant_id} stories={stories} update={updateStories} sources={sourceList} devices={dnaData?.story_devices || []} providers={providers} profiles={profiles} brandProfile={brandProfile} brandCharacters={brandCharacters} add={() => updateStories([...stories, { ...blankStory(), strategy: globalStrategy, source_ids: selectedSources, story_devices: dnaData?.story_devices || [] }])} />;
 const needsMaterial=stories.some(s=>!s.source_ids?.length),needsDNA=stories.some(s=>!s.story_devices?.length);
 const planJobs=items(jobList.data).filter(j=>j.plan_id===saved?.id);
 const finalActions = <><div className="plan-action-status" role="status"><strong>{saved?.status==='LAUNCHED'?'Producción solicitada':saved?.status==='APPROVED'?'Listo para solicitar producción':saved?'Borrador guardado · todavía no se produce':'Borrador sin guardar · todavía no se produce'}</strong>{!saved&&needsMaterial&&<p>Falta seleccionar material en una o más historias. <button className="text-button" onClick={()=>go(free?step:1)}>Elegir material →</button></p>}{!saved&&needsDNA&&<p>Falta definir el estilo de una o más historias. <Link href={'/workspace/'+tenant.tenant_id+'/content-dna'}>Definir estilo →</Link></p>}{planJobs.map(j=><Link className="plan-job-link" href={'/jobs/'+j.id} key={j.id}>{j.title} · <Status value={j.status}/> Ver avance →</Link>)}</div><section className="panel approval-panel"><div><p className="eyebrow">TÚ TIENES LA ÚLTIMA PALABRA</p><h2>{saved?.status === 'APPROVED' ? 'Los conceptos están aprobados.' : 'Primero el concepto. Después, la producción.'}</h2><p>Guarda tus ideas, apruébalas y empieza a crear. Si falta algo, te lo pediremos en el momento adecuado.</p></div><div className="actions">{!saved && stories.some(s => !s.story_devices?.length) && <p className="small-text muted">Selecciona al menos un recurso de estilo en cada historia.</p>}{free && !saved && <button className="primary" disabled={busy || !stories.length || stories.some(s => !s.title.trim() || !s.objective?.trim() || !s.story_devices?.length || !s.source_ids?.length) || clarifications.length > 0} onClick={save}>{busy ? 'Guardando…' : 'Guardar borrador'}</button>}{saved?.status === 'DRAFT' && <button className="primary" disabled={busy} onClick={approve}>Aprobar estos {stories.length} conceptos</button>}{saved?.status === 'APPROVED' && <button className="primary" disabled={busy} onClick={launch}><Icon name="play" />Solicitar producción</button>}{saved?.status === 'LAUNCHED' && <Tag>Producción solicitada</Tag>}</div></section></>;
 const steps = ['Contexto', 'Material', 'Identidad', 'Cómo crear', 'Historias', 'Tu plan', 'Aprobación', 'Producción'];
 const phases=['Idea','Material y estilo','Historias','Aprobar y crear'];
 const phaseIndex=step===0?0:step<=3?1:step<=5?2:3;
 return <fieldset disabled={busy} className="planner-fields"><section ref={anchor} className="planner-anchor" tabIndex={-1}/><Header eyebrow={tenant.organization + ' / CREAR'} title={free ? 'Dinos qué imaginas.' : 'Tu próxima semana, en historias.'} description={free ? 'Escribe con tus palabras. Convertimos tu intención en un borrador que tú decides.' : 'Te acompañamos desde la idea hasta una versión lista para crear.'} action={<Link className="button secondary" href={'/workspace/' + tenant.tenant_id + (free ? '/weekly' : '/free')}><Icon name={free ? 'calendar' : 'spark'} />{free ? 'Plan paso a paso' : 'Crear con mis palabras'}</Link>} /><div className="creation-shortcuts"><Link href={'/workspace/'+tenant.tenant_id+'/creative-profiles'}>Crear con un personaje o contar un lugar →</Link></div>{free ? <><section className="panel prompt-panel"><form onSubmit={interpret}><Field label="¿Qué quieres crear?"><textarea className="intent-input" value={text} onChange={e => setText(e.target.value)} required minLength={8} maxLength={4000} rows={5} placeholder="Hazme cuatro videos para esta semana. Dos con nuestro material real, uno más creativo usando IA y otro con el caballito." /></Field><div className="prompt-footer"><Field label="Semana del"><input type="date" value={week} onChange={e => { touched.current=true; setWeek(e.target.value); setSaved(null); }} required /></Field><button className="primary" disabled={busy}>{busy ? 'Dando forma a tu idea…' : 'Crear borrador'}<Icon name="spark" /></button></div><details><summary>Elegir material disponible</summary>{sourcePicker}</details></form></section>{clarifications.length > 0 && <div className="notice warning"><strong>Un detalle antes de continuar</strong><ul>{clarifications.map((c, i) => <li key={i}>{c}</li>)}</ul><p>Ajusta tu solicitud y vuelve a crear el borrador.</p></div>}{stories.length > 0 && <><div className="section-title"><h2>{stories.length} historias para tu semana</h2><Tag>Borrador editable</Tag></div>{editor}{finalActions}</>}</> : <><ol className="stepper simple-plan-phases" aria-label="Progreso del plan">{phases.map((label,i)=><li className={i===phaseIndex?'current':i<phaseIndex?'complete':''} key={label}><div aria-current={i===phaseIndex?'step':undefined}><span>{i<phaseIndex?'✓':i+1}</span>{label}</div></li>)}</ol><section className="guided-body">
 {step === 0 && <div className="panel form-panel"><p className="eyebrow">PASO 01 / CONTEXTO</p><h2>Una buena semana empieza con intención.</h2><p className="muted">Elige la fecha y el número de historias. Podrás ajustar cada idea en el camino.</p><div className="form-grid"><Field label="Semana del"><input type="date" value={week} onChange={e => { touched.current=true; setWeek(e.target.value); setSaved(null); }} required /></Field><Field label="Historias a planificar"><select value={stories.length || 0} onChange={e => { const count = Number(e.target.value); updateStories(Array.from({ length: count }, (_, i) => stories[i] || { ...blankStory(), source_ids: selectedSources, story_devices: dnaData?.story_devices || [], strategy: globalStrategy })); }}><option value="0">Seleccionar</option>{[1, 2, 3, 4, 5, 6, 7].map(n => <option key={n} value={n}>{n} {n === 1 ? 'historia' : 'historias'}</option>)}</select></Field></div><div className="context-note"><span className="workspace-monogram">{tenant.organization.slice(0, 1)}</span><div><strong>{tenant.organization}</strong><p>{tenant.brand?.visual_language || 'La identidad de tu marca acompaña cada historia.'}</p></div></div></div>}
 {step === 1 && <div className="panel"><p className="eyebrow">PASO 02 / MATERIAL</p><h2>Empieza con lo que es tuyo.</h2><p className="muted">Selecciona el material que quieres tener disponible para estas historias.</p>{sourcePicker}</div>}
 {step === 2 && <div className="panel"><p className="eyebrow">PASO 03 / IDENTIDAD</p><h2>El hilo que conecta tus historias.</h2>{dna.loading ? <Loading /> : dna.error ? <Problem error={dna.error} retry={dna.reload} /> : dnaData ? <><p className="muted">Estos recursos acompañarán tus historias. Podrás ajustar la selección en cada concepto.</p><div className="chips">{(dnaData.story_devices || []).map((s: string) => <Tag key={s}>{deviceLabels[s] || s}</Tag>)}</div></> : <div className="notice"><p>Aún no has definido tu estilo creativo. Usa una referencia para elegir el ritmo y los recursos que quieres repetir.</p><Link href={'/workspace/' + tenant.tenant_id + '/content-dna'}>Definir estilo →</Link></div>}</div>}
 {step === 3 && <div className="panel"><p className="eyebrow">PASO 04 / CÓMO CREAR</p><h2>¿Cómo quieres darles vida?</h2><p className="muted">Elige la forma general de crear. Podrás ajustar cada historia después.</p>{strategyPicker}<details className="production-options"><summary>Opciones avanzadas</summary><ProviderNote resource={providers} /></details></div>}
 {step === 4 && <><div className="section-title"><h2>Dale una intención a cada historia.</h2><Tag>Editable</Tag></div>{editor}</>}
 {step >= 5 && <><div className="section-title"><h2>{step === 5 ? 'Así se ve tu semana.' : step === 6 ? 'Revisa y aprueba tus conceptos.' : 'Deja que tus historias tomen forma.'}</h2>{step===5&&<p className="autosave-note"><span aria-hidden="true">✓</span> Se guardará automáticamente cuando continúes.</p>}<span className="muted">Semana del <DateLabel value={week} /></span></div>{stories.length ? <div className="plan-summary">{stories.map((s, i) => <div className="panel" key={s.id}><span className="eyebrow">HISTORIA {i + 1}</span><h3>{s.title || 'Título pendiente'}</h3><p>{s.objective || 'Intención por definir'}</p><div className="chips"><Tag>{strategies.find(v => v.value === s.strategy)?.title}</Tag>{s.mascot && <Tag>Con personaje</Tag>}<Tag>{s.source_ids?.length || 0} fuentes</Tag></div></div>)}</div> : <Empty title="Aún no has agregado historias.">Vuelve al primer paso para definir tu semana.</Empty>}{step===5&&saved&&<div className="autosave-confirmation" role="status"><span className="autosave-check" aria-hidden="true">✓</span><div><strong>Tu semana ya está guardada.</strong><p>La guardamos automáticamente. Nada se produce hasta que tú apruebes los conceptos.</p></div></div>}{step>=6&&finalActions}{step === 7 && <details className="production-options"><summary>Opciones avanzadas</summary><ProviderNote resource={providers} /></details>}</>}
 </section><div className="wizard-actions guided-sticky"><span className="guided-hint">{['Define tu semana →','Selecciona tu material →','Revisa tu identidad →','Elige cómo producir →','Completa cada historia →','Ya guardamos tu semana →','Aprueba los conceptos →','Solicita la producción →'][step]}</span><button className="secondary" disabled={step === 0} onClick={() => go(step-1)}>← Anterior</button><span>Etapa {phaseIndex + 1} de 4</span>{step < 7 ? <button className="primary" onClick={advanceStep} disabled={(step===2&&dna.loading)||(step===1&&!selectedSources.length)}>Continuar<Icon name="arrow" /></button> : <Link className="button secondary" href="/review">Ver producciones<Icon name="arrow" /></Link>}</div></>}
 {message && <div className="notice success" role="status">{message}</div>}<Problem error={error} />{free && <details className="production-options"><summary>Opciones avanzadas</summary><ProviderNote resource={providers} /></details>}<div className="section-title"><h2>Planes guardados</h2><button className="text-button" onClick={plans.reload}>Actualizar</button></div>{plans.loading ? <Loading /> : plans.error ? <Problem error={plans.error} retry={plans.reload} /> : items(plans.data).length ? <div className="list-panel">{items(plans.data).map(p => <div className="list-row" key={p.id}><div><h3>Semana del <DateLabel value={p.week_of} /></h3><p>{p.stories?.length || 0} historias · {p.mode === 'free' ? 'Creado con mis palabras' : 'Plan paso a paso'}</p></div><Status value={p.status} /><button className="secondary" onClick={() => { openPlan(p); }}>Abrir plan</button></div>)}</div> : <Empty icon="calendar" title="Tu primera semana empieza aquí.">Los borradores que guardes aparecerán en este espacio.</Empty>}</fieldset>;
}
function StoryEditor({ tenantId, stories, update, sources, devices, providers, profiles, brandProfile, brandCharacters, add }: { tenantId:string; stories: Item[]; update: (v: Item[]) => void; sources: Item[]; devices: string[]; providers: Resource; profiles: Resource; brandProfile:Resource; brandCharacters:Resource; add: () => void }) {
 function patch(id: string, value: Item) { update(stories.map(s => s.id === id ? { ...s, ...value } : s)); }
 const characterProfiles=items(profiles.data).filter(p=>p.kind==='character'),principal=characterProfiles.find(p=>p.principal&&p.rights_confirmed)!;
 const brandCharacterList=items(brandCharacters.data),defaultBrandCharacter=brandCharacterList.find(c=>c.character_id===brandProfile.data?.default_mascot_character_id)||brandCharacterList.find(c=>c.default_enabled);
 const defaultMascotAssetId=brandProfile.data?.default_mascot_asset_id||defaultBrandCharacter?.reference_asset_id||null;
 const defaultMascotName=defaultBrandCharacter?.name||principal?.name||'Mascota de la marca';
 const additionalProfiles=characterProfiles.filter(p=>p.id!==principal?.id);
 const mascotImage=defaultMascotAssetId?'/api/v1/tenants/'+encodeURIComponent(tenantId)+'/brand-assets/'+encodeURIComponent(defaultMascotAssetId):null;
 return <div className="story-editor">{stories.map((s, i) => {
  const defaultSelected=!!s.mascot&&(!s.character_id||s.character_id===principal?.id),otherSelected=!!s.character_id&&s.character_id!==principal?.id;
  return <article className="panel story-card" key={s.id}>
   <div className="story-number"><span>HISTORIA {String(i + 1).padStart(2, '0')}</span><button className="text-button" aria-label={'Quitar historia ' + (i + 1)} onClick={() => update(stories.filter(v => v.id !== s.id))}>Quitar</button></div>
   <Field label="Título"><input aria-label={'Título de historia ' + (i + 1)} value={s.title} onChange={e => patch(s.id, { title: e.target.value })} maxLength={200} placeholder="¿Qué historia quieres contar?" required /></Field>
   <Field label="Intención"><textarea value={s.objective || ''} onChange={e => patch(s.id, { objective: e.target.value })} maxLength={500} rows={2} placeholder="¿Qué quieres que las personas sientan o descubran?" /></Field>
   <div className="story-character-place">
    <div className="character-choice-block">
     <span className="field-label">Personaje de la historia</span>
     <div className="character-choice-grid" role="radiogroup" aria-label={'Personaje de historia '+(i+1)}>
      <button type="button" role="radio" aria-checked={!s.mascot&&!s.character_id} className={'character-choice '+(!s.mascot&&!s.character_id?'selected':'')} onClick={()=>patch(s.id,{mascot:false,character_id:null})}>
       <span className="character-choice-visual empty-character"><Icon name="spark"/></span><span><strong>Sin personaje</strong><small>La historia funciona solo con el material.</small></span>
      </button>
      {(defaultMascotAssetId||principal)&&<button type="button" role="radio" aria-checked={defaultSelected} className={'character-choice mascot-choice '+(defaultSelected?'selected':'')} aria-label={'Usar '+defaultMascotName+' en historia '+(i+1)} onClick={()=>patch(s.id,{mascot:true,character_id:principal?.id||null})}>
       <span className="character-choice-visual">{mascotImage?<img src={mascotImage} alt={'Avatar autorizado de '+defaultMascotName}/>:<Icon name="spark"/>}</span><span><strong>{defaultMascotName}</strong><small>Mascota autorizada de la marca</small><em>Autorizado</em></span>
      </button>}
     </div>
     {additionalProfiles.length>0&&<Field label="Otro personaje"><select value={otherSelected?s.character_id:''} onChange={e=>patch(s.id,{character_id:e.target.value||null,mascot:!!e.target.value})}><option value="">Elegir otro personaje</option>{additionalProfiles.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field>}
    </div>
    <Field label="Lugar de la historia"><select value={s.place_id||''} onChange={e=>patch(s.id,{place_id:e.target.value||null})}><option value="">Sin ficha de lugar</option>{items(profiles.data).filter(p=>p.kind==='place').map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field>
   </div>
   <details className="production-options"><summary>Opciones avanzadas</summary><div className="form-grid"><Field label="Cómo crear"><select value={s.strategy} onChange={e => patch(s.id, { strategy: e.target.value })}>{strategies.map(st => <option key={st.value} value={st.value}>{st.title}</option>)}</select></Field><Field label="Herramienta"><select value={s.preferred_provider || 'AUTO'} onChange={e => patch(s.id, { preferred_provider: e.target.value })}><option value="AUTO">Auto</option>{items(providers.data).map(p => <option key={p.id} value={p.id} disabled={!providerAvailable(p) || !providerCompatible(p,s.strategy)}>{p.name || p.display_name || p.id}{!providerAvailable(p) ? ' · No disponible' : !providerCompatible(p,s.strategy) ? ' · No compatible' : ''}</option>)}</select></Field></div></details>
   <details open={!s.source_ids?.length}><summary>Material y estilo · {s.source_ids?.length||0} seleccionados</summary>{!s.source_ids?.length&&<p className="field-guidance">↓ Marca el video que esta historia puede utilizar. Es necesario antes de guardar.</p>}<div className="check-grid">{sources.map(source => <label className="check-line" key={source.id}><input type="checkbox" checked={(s.source_ids || []).includes(source.id)} onChange={e => patch(s.id, { source_ids: e.target.checked ? [...(s.source_ids || []), source.id] : (s.source_ids || []).filter((v: string) => v !== source.id) })} />{source.id}</label>)}</div>{devices.map(device => <label className="check-line" key={device}><input type="checkbox" checked={(s.story_devices || []).includes(device)} onChange={e => patch(s.id, { story_devices: e.target.checked ? [...(s.story_devices || []), device] : (s.story_devices || []).filter((v: string) => v !== device) })} />{deviceLabels[device] || device}</label>)}</details>
  </article>
 })}<button className="add-story" disabled={stories.length >= 12} onClick={add}>+ Agregar historia</button></div>;
}
function providerAvailable(p: Item) { return p.available === true || p.executable === true; }
export function ProviderNote({ resource }: { resource: Resource }) { if (resource.loading) return <Loading text="Preparando opciones…" />; if (resource.error) return <Problem error={resource.error} retry={resource.reload} />; return <div className="provider-note"><div><Icon name="spark" /><strong>Herramientas de creación</strong></div><p>En automático elegimos una opción disponible. También puedes escoger una herramienta concreta.</p><div className="chips">{items(resource.data).map(p => <Tag key={p.id} tone={providerAvailable(p) ? 'success' : ''}>{p.name || p.display_name || p.id} · {providerAvailable(p) ? 'Disponible: ' + (p.strategies || []).filter((value: string) => value !== 'AUTO').map((value: string) => strategies.find(strategy => strategy.value === value)?.title || value).join(', ') : 'No disponible'}</Tag>)}</div></div>; }

function providerCompatible(provider: Item, strategy: string) { return strategy === 'AUTO' || (provider.strategies || []).includes(strategy); }
