'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState, type FormEvent } from 'react';
import { api, useLoad, items, Header, Icon, Tag, Empty, Loading, Problem, Field, DateLabel, Status, strategies, deviceLabels, type Item, type Resource, type ApiError } from './ui';
function weekStart() { const d = new Date(); d.setUTCDate(d.getUTCDate() - ((d.getUTCDay() + 6) % 7)); return d.toISOString().slice(0, 10); }
function blankStory(): Item { return { id: 'story-' + crypto.randomUUID(), title: '', objective: '', source_ids: [], story_devices: [], strategy: 'AUTO', preferred_provider: 'AUTO', mascot: false }; }
export function Planner({ tenant, free }: { tenant: Item; free: boolean }) {
 const base = '/tenants/' + tenant.tenant_id, dna = useLoad(base + '/content-dna'), plans = useLoad(base + '/weekly-plans'), providers = useLoad('/providers');
 const [step, setStep] = useState(0), [week, setWeek] = useState(weekStart), [text, setText] = useState(''), [stories, setStories] = useState<Item[]>([]), [selectedSources, setSelectedSources] = useState<string[]>(() => free ? (tenant.sources || []).filter((s: Item) => s.purpose === 'source').map((s: Item) => s.id) : []), [clarifications, setClarifications] = useState<string[]>([]), [busy, setBusy] = useState(false), [error, setError] = useState<ApiError | null>(null), [saved, setSaved] = useState<Item | null>(null), [message, setMessage] = useState(''), [globalStrategy, setGlobalStrategy] = useState('AUTO');
 const router = useRouter(), sourceList = (tenant.sources || []).filter((s: Item) => s.purpose === 'source'), dnaData = dna.data?.dna || dna.data;
 function updateStories(next: Item[]) { setStories(next); setSaved(null); setMessage(''); }
 function advanceStep() { if (step === 0 && !stories.length) updateStories([{ ...blankStory(), story_devices: dnaData?.story_devices || [] }]); if (step === 2) { if (!dnaData?.story_devices?.length) { setError({ code: 'DNA_REQUIRED', message: 'Construye Content DNA a partir de una referencia antes de continuar.' }); return; } updateStories(stories.map(story => ({ ...story, story_devices: story.story_devices?.length ? story.story_devices : [...dnaData.story_devices] }))); } setError(null); setStep(v => v + 1); }
 async function interpret(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); setError(null); setSaved(null); try { const draft = await api(base + '/free-draft', { text, week_of: week, source_ids: selectedSources }); setStories(draft.stories || []); setClarifications((draft.clarifications || []).map((c: any) => typeof c === 'string' ? c : c.message || c.question || 'Aclara un detalle de tu solicitud.')); setMessage(draft.stories?.length ? 'Tu idea ya tiene forma. Revisa y ajusta cada historia antes de guardar.' : 'Necesitamos un poco más de detalle para dar forma al borrador.'); } catch (err) { setError(err as ApiError); } finally { setBusy(false); } }
 async function save() { setBusy(true); setError(null); try { const plan = await api(base + '/weekly-plans', { week_of: week, stories: stories.map(({approved, ...story}) => story), mode: free ? 'free' : 'guided' }); setSaved(plan); setMessage('Borrador guardado. Todavía no has aprobado conceptos ni iniciado producción.'); plans.reload(); } catch (err) { setError(err as ApiError); } finally { setBusy(false); } }
 async function approve() { if (!saved) return; setBusy(true); setError(null); try { const plan = await api(base + '/weekly-plans/' + saved.id + '/approve', { story_ids: stories.map(s => s.id) }); setSaved(plan); setMessage('Conceptos aprobados. Ya puedes solicitar producción.'); plans.reload(); } catch (err) { setError(err as ApiError); } finally { setBusy(false); } }
 async function launch() { if (!saved) return; setBusy(true); setError(null); try { const result = await api(base + '/weekly-plans/' + saved.id + '/launch', {}); setMessage('Solicitud registrada. Consulta el estado real de cada producción.'); plans.reload(); const jobs = items(result); if (jobs[0]?.id) router.push('/jobs/' + jobs[0].id); else setSaved({ ...saved, status: 'LAUNCHED' }); } catch (err) { setError(err as ApiError); } finally { setBusy(false); } }
 const sourcePicker = <div>{sourceList.length ? <div className="selection-grid">{sourceList.map((s: Item) => <label className={'selection-card ' + (selectedSources.includes(s.id) ? 'selected' : '')} key={s.id}><input type="checkbox" checked={selectedSources.includes(s.id)} onChange={e => { const next = e.target.checked ? [...selectedSources, s.id] : selectedSources.filter(v => v !== s.id); setSelectedSources(next); updateStories(stories.map(story => ({ ...story, source_ids: next }))); }} /><Icon name="sources" /><strong>{s.id}</strong><small>Material autorizado</small></label>)}</div> : <div className="notice"><p>No hay material de producción autorizado en este espacio.</p><Link href={'/workspace/' + tenant.tenant_id + '/sources'}>Agregar material →</Link></div>}<p className="muted small-text">Las referencias creativas no aparecen como material de producción.</p></div>;
 const strategyPicker = <div className="strategy-grid">{strategies.map(s => <button type="button" className={'strategy-card ' + (globalStrategy === s.value ? 'selected' : '')} key={s.value} onClick={() => { setGlobalStrategy(s.value); updateStories(stories.map(story => ({ ...story, strategy: s.value }))); }}><span className="radio-indicator" /><strong>{s.title}</strong><small>{s.text}</small></button>)}</div>;
 const editor = <StoryEditor stories={stories} update={updateStories} sources={sourceList} devices={dnaData?.story_devices || []} providers={providers} add={() => updateStories([...stories, { ...blankStory(), strategy: globalStrategy, source_ids: selectedSources, story_devices: dnaData?.story_devices || [] }])} />;
 const finalActions = <section className="panel approval-panel"><div><p className="eyebrow">TÚ TIENES LA ÚLTIMA PALABRA</p><h2>{saved?.status === 'APPROVED' ? 'Los conceptos están aprobados.' : 'Primero el concepto. Después, la producción.'}</h2><p>Guardar conserva el plan. Aprobar confirma estos conceptos. Producir crea trabajos y comprueba fuentes e integraciones disponibles.</p></div><div className="actions">{!saved && stories.some(s => !s.story_devices?.length) && <p className="small-text muted">Selecciona recursos narrativos de Content DNA en cada historia.</p>}{!saved && <button className="primary" disabled={busy || !stories.length || stories.some(s => !s.title.trim() || !s.objective?.trim() || !s.story_devices?.length) || clarifications.length > 0} onClick={save}>{busy ? 'Guardando…' : 'Guardar borrador'}</button>}{saved?.status === 'DRAFT' && <button className="primary" disabled={busy} onClick={approve}>Aprobar estos {stories.length} conceptos</button>}{saved?.status === 'APPROVED' && <button className="primary" disabled={busy} onClick={launch}><Icon name="play" />Solicitar producción</button>}{saved?.status === 'LAUNCHED' && <Tag>Producción solicitada</Tag>}</div></section>;
 const steps = ['Contexto', 'Material', 'Identidad', 'Estrategia', 'Historias', 'Tu plan', 'Aprobación', 'Producción'];
 return <><Header eyebrow={tenant.organization + ' / CREAR'} title={free ? 'Dinos qué imaginas.' : 'Tu próxima semana, en historias.'} description={free ? 'Escribe con tus palabras. Convertimos tu intención en un borrador que tú decides.' : 'Ocho pasos para crear con intención, desde tus fuentes hasta tu aprobación.'} action={<Link className="button secondary" href={'/workspace/' + tenant.tenant_id + (free ? '/weekly' : '/free')}><Icon name={free ? 'calendar' : 'spark'} />{free ? 'Modo guiado' : 'Modo libre'}</Link>} />{free ? <><section className="panel prompt-panel"><form onSubmit={interpret}><Field label="¿Qué quieres crear?"><textarea className="intent-input" value={text} onChange={e => setText(e.target.value)} required minLength={8} maxLength={4000} rows={5} placeholder="Hazme cuatro videos para esta semana. Dos con nuestro material real, uno más creativo usando IA y otro con el caballito." /></Field><div className="prompt-footer"><Field label="Semana del"><input type="date" value={week} onChange={e => { setWeek(e.target.value); setSaved(null); }} required /></Field><button className="primary" disabled={busy}>{busy ? 'Dando forma a tu idea…' : 'Crear borrador'}<Icon name="spark" /></button></div><details><summary>Elegir material disponible</summary>{sourcePicker}</details></form></section>{clarifications.length > 0 && <div className="notice warning"><strong>Un detalle antes de continuar</strong><ul>{clarifications.map((c, i) => <li key={i}>{c}</li>)}</ul><p>Ajusta tu solicitud y vuelve a crear el borrador.</p></div>}{stories.length > 0 && <><div className="section-title"><h2>{stories.length} historias para tu semana</h2><Tag>Borrador editable</Tag></div>{editor}{finalActions}</>}</> : <><ol className="stepper" aria-label="Progreso del plan">{steps.map((label, i) => <li className={i === step ? 'current' : i < step ? 'complete' : ''} key={label}><button onClick={() => setStep(i)} aria-current={step === i ? 'step' : undefined}><span>{i < step ? '✓' : i + 1}</span>{label}</button></li>)}</ol><section className="guided-body">
 {step === 0 && <div className="panel form-panel"><p className="eyebrow">PASO 01 / CONTEXTO</p><h2>Una buena semana empieza con intención.</h2><p className="muted">Elige la fecha y el número de historias. Podrás ajustar cada idea en el camino.</p><div className="form-grid"><Field label="Semana del"><input type="date" value={week} onChange={e => { setWeek(e.target.value); setSaved(null); }} required /></Field><Field label="Historias a planificar"><select value={stories.length || 0} onChange={e => { const count = Number(e.target.value); updateStories(Array.from({ length: count }, (_, i) => stories[i] || { ...blankStory(), source_ids: selectedSources, story_devices: dnaData?.story_devices || [], strategy: globalStrategy })); }}><option value="0">Seleccionar</option>{[1, 2, 3, 4, 5, 6, 7].map(n => <option key={n} value={n}>{n} {n === 1 ? 'historia' : 'historias'}</option>)}</select></Field></div><div className="context-note"><span className="workspace-monogram">{tenant.organization.slice(0, 1)}</span><div><strong>{tenant.organization}</strong><p>{tenant.brand?.visual_language || 'La identidad de tu marca acompaña cada historia.'}</p></div></div></div>}
 {step === 1 && <div className="panel"><p className="eyebrow">PASO 02 / MATERIAL</p><h2>Empieza con lo que es tuyo.</h2><p className="muted">Selecciona el material que quieres tener disponible para estas historias.</p>{sourcePicker}</div>}
 {step === 2 && <div className="panel"><p className="eyebrow">PASO 03 / IDENTIDAD</p><h2>El hilo que conecta tus historias.</h2>{dna.loading ? <Loading /> : dna.error ? <Problem error={dna.error} retry={dna.reload} /> : dnaData ? <><p className="muted">Estos recursos acompañarán tus historias. Podrás ajustar la selección en cada concepto.</p><div className="chips">{(dnaData.story_devices || []).map((s: string) => <Tag key={s}>{deviceLabels[s] || s}</Tag>)}</div></> : <div className="notice"><p>Aún no has definido tu Content DNA. Analiza una referencia para construir una identidad reutilizable antes de producir.</p><Link href={'/workspace/' + tenant.tenant_id + '/content-dna'}>Crear Content DNA →</Link></div>}</div>}
 {step === 3 && <div className="panel"><p className="eyebrow">PASO 04 / ESTRATEGIA</p><h2>¿Cómo quieres darles vida?</h2><p className="muted">Elige una base para el plan. Cada historia puede tener una estrategia diferente.</p>{strategyPicker}<ProviderNote resource={providers} /></div>}
 {step === 4 && <><div className="section-title"><h2>Dale una intención a cada historia.</h2><Tag>Editable</Tag></div>{editor}</>}
 {step >= 5 && <><div className="section-title"><h2>{step === 5 ? 'Así se ve tu semana.' : step === 6 ? 'Revisa y aprueba tus conceptos.' : 'Deja que tus historias tomen forma.'}</h2><span className="muted">Semana del <DateLabel value={week} /></span></div>{stories.length ? <div className="plan-summary">{stories.map((s, i) => <div className="panel" key={s.id}><span className="eyebrow">HISTORIA {i + 1}</span><h3>{s.title || 'Título pendiente'}</h3><p>{s.objective || 'Intención por definir'}</p><div className="chips"><Tag>{strategies.find(v => v.value === s.strategy)?.title}</Tag>{s.mascot && <Tag>Con personaje</Tag>}<Tag>{s.source_ids?.length || 0} fuentes</Tag></div></div>)}</div> : <Empty title="Aún no has agregado historias.">Vuelve al primer paso para definir tu semana.</Empty>}{finalActions}{step === 7 && <ProviderNote resource={providers} />}</>}
 </section><div className="wizard-actions"><button className="secondary" disabled={step === 0} onClick={() => setStep(v => v - 1)}>← Anterior</button><span>Paso {step + 1} de 8</span>{step < 7 ? <button className="primary" onClick={advanceStep} disabled={step === 2 && dna.loading}>Continuar<Icon name="arrow" /></button> : <Link className="button secondary" href="/review">Ver producciones<Icon name="arrow" /></Link>}</div></>}
 {message && <div className="notice success" role="status">{message}</div>}<Problem error={error} />{free && <ProviderNote resource={providers} />}<div className="section-title"><h2>Planes guardados</h2><button className="text-button" onClick={plans.reload}>Actualizar</button></div>{plans.loading ? <Loading /> : plans.error ? <Problem error={plans.error} retry={plans.reload} /> : items(plans.data).length ? <div className="list-panel">{items(plans.data).map(p => <div className="list-row" key={p.id}><div><h3>Semana del <DateLabel value={p.week_of} /></h3><p>{p.stories?.length || 0} historias · {p.mode === 'free' ? 'Modo libre' : 'Modo guiado'}</p></div><Status value={p.status} /><button className="secondary" onClick={() => { setStories(p.stories || []); setSaved(p); setWeek(p.week_of); setStep(6); setClarifications([]); setMessage('Plan guardado recuperado.'); window.scrollTo({ top: 0, behavior: 'smooth' }); }}>Abrir plan</button></div>)}</div> : <Empty icon="calendar" title="Tu primera semana empieza aquí.">Los borradores que guardes aparecerán en este espacio.</Empty>}</>;
}
function StoryEditor({ stories, update, sources, devices, providers, add }: { stories: Item[]; update: (v: Item[]) => void; sources: Item[]; devices: string[]; providers: Resource; add: () => void }) {
 function patch(id: string, value: Item) { update(stories.map(s => s.id === id ? { ...s, ...value } : s)); }
 return <div className="story-editor">{stories.map((s, i) => <article className="panel story-card" key={s.id}><div className="story-number"><span>HISTORIA {String(i + 1).padStart(2, '0')}</span><button className="text-button" aria-label={'Quitar historia ' + (i + 1)} onClick={() => update(stories.filter(v => v.id !== s.id))}>Quitar</button></div><Field label="Título"><input aria-label={'Título de historia ' + (i + 1)} value={s.title} onChange={e => patch(s.id, { title: e.target.value })} maxLength={200} placeholder="¿Qué historia quieres contar?" required /></Field><Field label="Intención"><textarea value={s.objective || ''} onChange={e => patch(s.id, { objective: e.target.value })} maxLength={500} rows={2} placeholder="¿Qué quieres que las personas sientan o descubran?" /></Field><div className="form-grid"><Field label="Estrategia de producción"><select value={s.strategy} onChange={e => patch(s.id, { strategy: e.target.value })}>{strategies.map(st => <option key={st.value} value={st.value}>{st.title}</option>)}</select></Field><Field label="Proveedor preferido"><select value={s.preferred_provider || 'AUTO'} onChange={e => patch(s.id, { preferred_provider: e.target.value })}><option value="AUTO">Auto</option>{items(providers.data).map(p => <option key={p.id} value={p.id} disabled={!providerAvailable(p) || !providerCompatible(p,s.strategy)}>{p.name || p.display_name || p.id}{!providerAvailable(p) ? ' · Integración pendiente' : !providerCompatible(p,s.strategy) ? ' · Estrategia no compatible' : ''}</option>)}</select></Field></div><label className="check-line"><input type="checkbox" checked={!!s.mascot} onChange={e => patch(s.id, { mascot: e.target.checked })} />Incluir el personaje o mascota de la marca</label><details><summary>Material y recursos narrativos</summary><div className="check-grid">{sources.map(source => <label className="check-line" key={source.id}><input type="checkbox" checked={(s.source_ids || []).includes(source.id)} onChange={e => patch(s.id, { source_ids: e.target.checked ? [...(s.source_ids || []), source.id] : (s.source_ids || []).filter((v: string) => v !== source.id) })} />{source.id}</label>)}</div>{devices.map(device => <label className="check-line" key={device}><input type="checkbox" checked={(s.story_devices || []).includes(device)} onChange={e => patch(s.id, { story_devices: e.target.checked ? [...(s.story_devices || []), device] : (s.story_devices || []).filter((v: string) => v !== device) })} />{deviceLabels[device] || device}</label>)}</details></article>)}<button className="add-story" disabled={stories.length >= 12} onClick={add}>+ Agregar historia</button></div>;
}
function providerAvailable(p: Item) { return p.available === true || p.executable === true; }
export function ProviderNote({ resource }: { resource: Resource }) { if (resource.loading) return <Loading text="Consultando integraciones…" />; if (resource.error) return <Problem error={resource.error} retry={resource.reload} />; return <div className="provider-note"><div><Icon name="spark" /><strong>Producción según disponibilidad</strong></div><p>Auto elige una opción compatible. Una integración pendiente puede guardar conceptos, pero no generar videos.</p><div className="chips">{items(resource.data).map(p => <Tag key={p.id} tone={providerAvailable(p) ? 'success' : ''}>{p.name || p.display_name || p.id} · {providerAvailable(p) ? 'Disponible: ' + (p.strategies || []).filter((value: string) => value !== 'AUTO').map((value: string) => strategies.find(strategy => strategy.value === value)?.title || value).join(', ') : 'Integración pendiente'}</Tag>)}</div></div>; }

function providerCompatible(provider: Item, strategy: string) { return strategy === 'AUTO' || (provider.strategies || []).includes(strategy); }
