'use client';
import {useEffect,useMemo,useState,type ChangeEvent} from 'react';
import {useRouter} from 'next/navigation';
import {api,useLoad,items,Header,Field,Problem,Loading,Tag,Icon,type Item,type ApiError} from './ui';
import styles from './SceneBuilder.module.css';

type SceneState={
 subject:{mode:string;character_id?:string|null;wardrobe?:{top?:string;bottom?:string;shoes?:string;forbidden?:string[]}};
 avatar?:{identity_pack_id?:string;outfit_id?:string;accessory_ids:string[];motion_preset_id?:string;scene_pack_id?:string|null;brand_marker_policy?:'ALWAYS_VISIBLE'};
 environment:{reference_asset_id?:string|null;location_name?:string;required_elements:string[];forbidden_elements:string[];civilian_only:boolean};
 action:{verb:string;prop?:string;framing?:string};
 visual_style:{realism:string;look:string[];lighting:string[]};
 hard_constraints:{kind:'must_include'|'must_exclude';value:string}[];
 output:{medium:'image'|'video';aspect_ratio:'9:16'|'1:1'|'16:9';duration_seconds?:number;motion_intent?:string;camera_intent?:string};
 generation_mode:string;preset_id?:string|null;operator_override?:string;
};
const split=(value:string)=>value.split(/\n|,/).map(v=>v.trim()).filter(Boolean);
const defaultScene:SceneState={subject:{mode:'default_brand_character'},environment:{location_name:'Calle del Arco, Antigua Guatemala, Guatemala',required_elements:['Santa Catalina Arch','colonial buildings','cobblestone street','civilian pedestrians and tourists'],forbidden_elements:['industrial environment','port','shipping containers','warehouses','construction site','cranes','forklifts','hard hats','helmets','safety vests','reflective clothing'],civilian_only:true},action:{verb:'walking casually while taking a selfie',prop:'smartphone',framing:'vertical social portrait with landmark visible'},visual_style:{realism:'photorealistic',look:['premium campaign photography','authentic Antigua Guatemala atmosphere'],lighting:['natural sunlight','realistic shadows']},hard_constraints:[],output:{medium:'image',aspect_ratio:'9:16'},generation_mode:'manual_external'};

export function SceneBuilder({tenant}:{tenant:Item}){
 const router=useRouter(),base='/tenants/'+tenant.tenant_id;
 const brand=useLoad(base+'/brand-profile'),characters=useLoad(base+'/brand-characters'),avatarCatalog=useLoad(base+'/avatar-catalog'),presets=useLoad(base+'/scene-presets'),providers=useLoad('/providers');
 const [scene,setScene]=useState<SceneState>(defaultScene),[preview,setPreview]=useState<Item|null>(null),[error,setError]=useState<ApiError|null>(null),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{if(!brand.data)return;setScene(current=>!brand.data.default_mascot_character_id&&current.subject.mode==='default_brand_character'?{...current,subject:{mode:'none'},avatar:undefined}:current)},[brand.data]);
 const character=useMemo(()=>{if(scene.subject.mode==='none')return null;const id=scene.subject.mode==='default_brand_character'?brand.data?.default_mascot_character_id:scene.subject.character_id;return items(characters.data).find(c=>c.character_id===id)||null},[scene.subject,brand.data,characters.data]);
 function patch<K extends keyof SceneState>(key:K,value:SceneState[K]){setScene(s=>({...s,[key]:value}));setPreview(null);setMessage('')}
 function patchAvatar(value:SceneState['avatar']){patch('avatar',value)}
 function toggleAccessory(id:string){const current=scene.avatar?.accessory_ids||[];patchAvatar({...scene.avatar,accessory_ids:current.includes(id)?current.filter(v=>v!==id):[...current,id],brand_marker_policy:'ALWAYS_VISIBLE'})}
 function applyAvatarScenePack(pack:Item){const motion=items(avatarCatalog.data?.motion_profile?.presets).find(m=>m.motion_preset_id===pack.suggested_motion_preset_id);setScene(current=>({...current,avatar:{identity_pack_id:avatarCatalog.data.default_identity_pack_id,outfit_id:pack.suggested_outfit_id,accessory_ids:pack.suggested_accessory_ids||[],motion_preset_id:pack.suggested_motion_preset_id,scene_pack_id:pack.scene_pack_id,brand_marker_policy:'ALWAYS_VISIBLE'},environment:{...pack.environment},action:{...current.action,verb:motion?.verb||current.action.verb},output:{...current.output,...(current.output.medium==='video'&&motion?{motion_intent:motion.verb}:{})}}));setPreview(null);setMessage(pack.name+' aplicado. El Caballito conserva su identidad y distintivo FIRMES.')}
 function setMedium(medium:'image'|'video'){const motion=items(avatarCatalog.data?.motion_profile?.presets).find(m=>m.motion_preset_id===(scene.avatar?.motion_preset_id||'avatar_motion_idle_v1'));patch('output',{...scene.output,medium,...(medium==='video'?{duration_seconds:Math.min(6,motion?.duration_range_seconds?.[1]||6),motion_intent:motion?.verb||'subtle natural movement',camera_intent:'stable realistic vertical camera'}:{duration_seconds:undefined,motion_intent:undefined,camera_intent:undefined})})}
 function applyPreset(p:Item){const next={...p.scene,generation_mode:scene.generation_mode,preset_id:p.id} as SceneState;patch('subject',next.subject);setScene({...next});setPreview(null);setMessage('Plantilla aplicada. Puedes ajustar cualquier detalle antes de continuar.');}
 async function uploadEnvironment(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setUploading(true);setError(null);try{const response=await fetch('/api/v1'+base+'/scene-references/ENVIRONMENT_ONLY',{method:'POST',credentials:'same-origin',headers:{'Content-Type':file.type},body:file});const payload=await response.json();if(!response.ok)throw payload.error||{code:String(response.status),message:'No pudimos cargar la referencia.'};patch('environment',{...scene.environment,reference_asset_id:payload.data.asset_id});setMessage('Referencia del lugar cargada. Solo se usará para el entorno.');}catch(e){setError(e as ApiError)}finally{setUploading(false);e.target.value=''}}
 async function compile(){setBusy(true);setError(null);try{const result=await api(base+'/scenes/preview',scene);setPreview(result);setMessage('La instrucción de creación está lista.');}catch(e){setError(e as ApiError)}finally{setBusy(false)}}
 async function create(){setBusy(true);setError(null);try{const result=await api(base+'/scenes',scene);router.push('/jobs/'+result.id)}catch(e){setError(e as ApiError)}finally{setBusy(false)}}
 if(brand.loading||characters.loading||avatarCatalog.loading||presets.loading)return <Loading text="Preparando tu espacio creativo…"/>;
 if(brand.error)return <Problem error={brand.error} retry={brand.reload}/>;
 const mascotAsset=brand.data?.default_mascot_asset_id;
 const availableProviders=items(providers.data);
 return <>
  <Header eyebrow={tenant.organization+' / CREAR UNA ESCENA'} title="Imagina la escena" description="Elige personaje, lugar y acción. Nosotros preparamos lo demás."/>
  <div className={styles.presets}><span>Ideas para empezar:</span>{items(presets.data).map(p=><button key={p.id} type="button" className="secondary" onClick={()=>applyPreset(p)}>{p.name}</button>)}</div>
  <section className={'panel '+styles.section}><div className={styles.sectionHead}><span className={styles.number}>01</span><div><p className="eyebrow">PERSONAJE</p><h2>Personaje principal</h2></div></div>
   <div className={styles.characterGrid}><div className={styles.characterCard}>{mascotAsset&&<img src={'/api/v1'+base+'/brand-assets/'+encodeURIComponent(mascotAsset)} alt="Referencia autorizada del Caballito FIRMES"/>}<div><strong>{character?.name||'Sin personaje'}</strong>{scene.subject.mode==='default_brand_character'&&<Tag tone="success">Predeterminado del espacio</Tag>}<small>{character?'Este personaje está listo para usar en tu escena.':'La escena se creará sin personaje de marca.'}</small></div></div>
    <div className={styles.controls}><label className="check-line"><input type="radio" name="character-mode" checked={scene.subject.mode==='default_brand_character'} onChange={()=>{setScene(current=>({...current,subject:{mode:'default_brand_character'},avatar:undefined}));setPreview(null)}}/>Usar personaje predeterminado</label><label className="check-line"><input type="radio" name="character-mode" checked={scene.subject.mode==='none'} onChange={()=>{setScene(current=>({...current,subject:{mode:'none'},avatar:undefined}));setPreview(null)}}/>Sin personaje</label>{items(characters.data).length>1&&<Field label="Cambiar personaje"><select value={scene.subject.mode==='explicit_character'?scene.subject.character_id||'':''} onChange={e=>{setScene(current=>({...current,subject:e.target.value?{mode:'explicit_character',character_id:e.target.value}:{mode:'default_brand_character'},avatar:undefined}));setPreview(null)}}><option value="">Predeterminado</option>{items(characters.data).map(c=><option key={c.character_id} value={c.character_id}>{c.name}</option>)}</select></Field>}</div></div>
   {character&&<details><summary>Ver detalles del personaje</summary><div className={styles.ruleColumns}><div><strong>Preservar</strong><ul>{(character.identity_constraints?.preserve||[]).map((v:string)=><li key={v}>{v}</li>)}</ul></div><div><strong>No copiar de la referencia</strong><ul>{(character.identity_constraints?.exclude_from_source||[]).map((v:string)=><li key={v}>{v}</li>)}</ul></div></div></details>}
  </section>
  {character&&avatarCatalog.data?.enabled&&<section className={'panel '+styles.section+' '+styles.avatarSection}>
   <div className={styles.sectionHead}><span className={styles.number}>02</span><div><p className="eyebrow">AVATAR REUTILIZABLE</p><h2>Look y movimiento</h2><p className={styles.sectionHint}>Cambia ropa, accesorios y movimiento sin cambiar quién es el Caballito.</p></div></div>
   <div className={styles.avatarIdentity}>
    <div><strong>Identidad bloqueada</strong><small>{avatarCatalog.data.identity_packs?.[0]?.completeness?.status==='PARTIAL'?'Referencia principal aprobada · turnaround completo pendiente':'Identity Pack completo'}</small></div>
    <Tag tone="success">FIRMES siempre visible</Tag>
   </div>
   <div className={styles.avatarGrid}>
    <Field label="Look"><select aria-label="Look del avatar" value={scene.avatar?.outfit_id||avatarCatalog.data.default_outfit_id||''} onChange={e=>patchAvatar({...scene.avatar,outfit_id:e.target.value,accessory_ids:[],brand_marker_policy:'ALWAYS_VISIBLE'})}>{items(avatarCatalog.data.outfits).map(o=><option key={o.outfit_id} value={o.outfit_id}>{o.name}</option>)}</select></Field>
    <Field label="Movimiento"><select aria-label="Movimiento del avatar" value={scene.avatar?.motion_preset_id||'avatar_motion_idle_v1'} onChange={e=>{const motion=items(avatarCatalog.data.motion_profile?.presets).find(m=>m.motion_preset_id===e.target.value);patchAvatar({...scene.avatar,motion_preset_id:e.target.value,accessory_ids:scene.avatar?.accessory_ids||[],brand_marker_policy:'ALWAYS_VISIBLE'});if(scene.output.medium==='video'&&motion)patch('output',{...scene.output,motion_intent:motion.verb})}}>{items(avatarCatalog.data.motion_profile?.presets).map(m=><option key={m.motion_preset_id} value={m.motion_preset_id}>{m.name}</option>)}</select></Field>
   </div>
   <div className={styles.avatarSubsection}><span>Accesorios</span><div className={styles.avatarChips}>{items(avatarCatalog.data.accessories).map(a=>{const selected=(scene.avatar?.accessory_ids||[]).includes(a.accessory_id),outfit=scene.avatar?.outfit_id||avatarCatalog.data.default_outfit_id,compatible=!a.compatible_outfit_ids||a.compatible_outfit_ids.includes(outfit);return <button type="button" key={a.accessory_id} disabled={!compatible} className={selected?styles.avatarChipSelected:styles.avatarChip} onClick={()=>toggleAccessory(a.accessory_id)}>{a.name}{!compatible&&<small>No compatible</small>}</button>})}</div></div>
   <div className={styles.avatarSubsection}><span>Escenas rápidas</span><div className={styles.avatarChips}>{items(avatarCatalog.data.scene_packs).map(pack=><button type="button" className={scene.avatar?.scene_pack_id===pack.scene_pack_id?styles.avatarChipSelected:styles.avatarChip} key={pack.scene_pack_id} onClick={()=>applyAvatarScenePack(pack)}>{pack.name}</button>)}</div></div>
   <details><summary>Qué no cambia</summary><div className={styles.ruleColumns}><div><strong>Identidad</strong><ul>{(avatarCatalog.data.identity_packs?.[0]?.invariants||[]).map((v:string)=><li key={v}>{v}</li>)}</ul></div><div><strong>Drift prohibido</strong><ul>{(avatarCatalog.data.identity_packs?.[0]?.forbidden_drift||[]).map((v:string)=><li key={v}>{v}</li>)}</ul></div></div></details>
  </section>}
  <section className={'panel '+styles.section}><div className={styles.sectionHead}><span className={styles.number}>03</span><div><p className="eyebrow">ENTORNO</p><h2>¿Dónde sucede?</h2></div></div><div className="form-grid"><Field label="Lugar"><input value={scene.environment.location_name||''} onChange={e=>patch('environment',{...scene.environment,location_name:e.target.value})} maxLength={300}/></Field><Field label="Referencia del entorno (opcional)" help={scene.environment.reference_asset_id?'Referencia cargada. Se usará solo para el lugar.':'Opcional. La imagen se usará solo para orientar el entorno.'}><input type="file" accept="image/png,image/jpeg" onChange={uploadEnvironment} disabled={uploading}/></Field></div><div className="form-grid"><Field label="Debe aparecer" help="Un elemento por línea o separado por comas."><textarea rows={5} value={scene.environment.required_elements.join('\n')} onChange={e=>patch('environment',{...scene.environment,required_elements:split(e.target.value)})}/></Field><Field label="No debe aparecer"><textarea rows={5} value={scene.environment.forbidden_elements.join('\n')} onChange={e=>patch('environment',{...scene.environment,forbidden_elements:split(e.target.value)})}/></Field></div><label className="check-line"><input type="checkbox" checked={scene.environment.civilian_only} onChange={e=>patch('environment',{...scene.environment,civilian_only:e.target.checked})}/>Mantener un entorno civil, salvo que la escena pida algo diferente.</label></section>
  <section className={'panel '+styles.section}><div className={styles.sectionHead}><span className={styles.number}>04</span><div><p className="eyebrow">ACCIÓN</p><h2>¿Qué está haciendo?</h2></div></div><div className="form-grid"><Field label="Acción"><input value={scene.action.verb} onChange={e=>patch('action',{...scene.action,verb:e.target.value})}/></Field><Field label="Objeto o utilería"><input value={scene.action.prop||''} onChange={e=>patch('action',{...scene.action,prop:e.target.value})} placeholder="smartphone"/></Field></div><Field label="Encuadre"><input value={scene.action.framing||''} onChange={e=>patch('action',{...scene.action,framing:e.target.value})}/></Field></section>
  <section className={'panel '+styles.section}><div className={styles.sectionHead}><span className={styles.number}>05</span><div><p className="eyebrow">ESTILO</p><h2>Cómo debe sentirse</h2></div></div><div className={styles.presetRow}>{['Photorealistic','Premium campaign photography','Documentary','Tourism','Community','Cinematic social'].map(v=><button key={v} type="button" className={scene.visual_style.look.map(x=>x.toLowerCase()).includes(v.toLowerCase())?'primary':'secondary'} onClick={()=>patch('visual_style',{...scene.visual_style,look:[v.toLowerCase()]})}>{v}</button>)}</div><div className="form-grid"><Field label="Realismo"><input value={scene.visual_style.realism} onChange={e=>patch('visual_style',{...scene.visual_style,realism:e.target.value})}/></Field><Field label="Iluminación"><input value={scene.visual_style.lighting.join(', ')} onChange={e=>patch('visual_style',{...scene.visual_style,lighting:split(e.target.value)})}/></Field></div></section>
  <section className={'panel '+styles.section}><div className={styles.sectionHead}><span className={styles.number}>06</span><div><p className="eyebrow">FORMATO</p><h2>¿Qué quieres obtener?</h2></div></div><div className="form-grid"><Field label="Tipo de contenido"><select value={scene.output.medium} onChange={e=>setMedium(e.target.value as 'image'|'video')}><option value="image">Imagen</option><option value="video">Video</option></select></Field><Field label="Formato"><select value={scene.output.aspect_ratio} onChange={e=>patch('output',{...scene.output,aspect_ratio:e.target.value as '9:16'|'1:1'|'16:9'})}><option>9:16</option><option>1:1</option><option>16:9</option></select></Field>{scene.output.medium==='video'&&<Field label="Duración"><input type="number" min={1} max={30} step={1} value={scene.output.duration_seconds||6} onChange={e=>patch('output',{...scene.output,duration_seconds:Number(e.target.value)})}/></Field>}</div>{scene.output.medium==='video'&&<div className="form-grid"><Field label="Movimiento"><input value={scene.output.motion_intent||''} onChange={e=>patch('output',{...scene.output,motion_intent:e.target.value})}/></Field><Field label="Cámara"><input value={scene.output.camera_intent||''} onChange={e=>patch('output',{...scene.output,camera_intent:e.target.value})}/></Field></div>}
   <details className="production-options"><summary>Herramienta de creación · opcional</summary><div className={styles.providerGrid}>{availableProviders.filter(p=>['manual-external','seedance','higgsfield','capcut','gemini'].includes(p.id)).map(p=><button type="button" key={p.id} disabled={p.id!=='manual-external'&&!p.available} className={(scene.generation_mode===(p.id==='manual-external'?'manual_external':'provider:'+p.id)?styles.providerSelected:'')+' '+styles.providerCard} onClick={()=>patch('generation_mode',p.id==='manual-external'?'manual_external':'provider:'+p.id)}><strong>{p.name}</strong><small>{p.id==='manual-external'?'Disponible · CapCut / Seedance / H3 u otra herramienta aprobada':p.available?'Disponible':'Integración no configurada'}</small></button>)}</div></details>
  </section>
  <section className={'panel '+styles.compile}><div><p className="eyebrow">LISTO PARA CONTINUAR</p><h2>Revisa tu idea</h2><p>Cuando estés listo, prepararemos la producción con el personaje, el lugar y el formato que elegiste.</p></div><div className="actions"><button className="secondary" onClick={compile} disabled={busy}>{busy?'Preparando…':'Ver instrucción'}</button><button className="primary" onClick={create} disabled={busy||!scene.action.verb.trim()}><Icon name="spark"/>Crear producción</button></div></section>
  {preview&&<details className={'panel '+styles.preview}><summary>Detalles de la instrucción preparada</summary><div className="section-title"><h2>Instrucción de creación</h2><Tag>Lista</Tag></div><pre>{preview.final_prompt}</pre><details><summary>Detalles técnicos</summary><div className={styles.hashes}><span>Request SHA <code>{preview.structured_request_sha256}</code></span><span>Prompt SHA <code>{preview.final_prompt_sha256}</code></span>{preview.avatar_contract_sha256&&<span>Avatar SHA <code>{preview.avatar_contract_sha256}</code></span>}</div><div className={styles.roles}>{(preview.reference_roles||[]).map((r:Item)=><Tag key={r.asset_id}>{String(r.reference_id).replaceAll('_',' ')} · {String(r.role).replaceAll('_',' ')}</Tag>)}</div></details></details>}
  {message&&<div className="notice success" role="status">{message}</div>}<Problem error={error}/>
 </>;
}
