'use client';
import {useEffect,useMemo,useState,type ChangeEvent} from 'react';
import {useRouter} from 'next/navigation';
import {api,useLoad,items,Header,Field,Problem,Loading,Tag,Icon,type Item,type ApiError} from './ui';
import styles from './SceneBuilder.module.css';

type SceneState={
 subject:{mode:string;character_id?:string|null;wardrobe?:{top?:string;bottom?:string;shoes?:string;forbidden?:string[]}};
 environment:{reference_asset_id?:string|null;location_name?:string;required_elements:string[];forbidden_elements:string[];civilian_only:boolean};
 action:{verb:string;prop?:string;framing?:string};
 visual_style:{realism:string;look:string[];lighting:string[]};
 hard_constraints:{kind:'must_include'|'must_exclude';value:string}[];
 output:{medium:'image'|'video';aspect_ratio:'9:16'|'1:1'|'16:9';duration_seconds?:number;motion_intent?:string;camera_intent?:string};
 generation_mode:string;preset_id?:string|null;operator_override?:string;
};
const split=(value:string)=>value.split(/\n|,/).map(v=>v.trim()).filter(Boolean);
const defaultScene:SceneState={subject:{mode:'default_brand_character'},environment:{location_name:'Calle del Arco, Antigua Guatemala, Guatemala',required_elements:['Santa Catalina Arch','colonial buildings','cobblestone street','civilian pedestrians and tourists'],forbidden_elements:['industrial environment','port','shipping containers','warehouses','construction site','cranes','forklifts','hard hats','helmets','safety vests','reflective clothing'],civilian_only:true},action:{verb:'walking casually while taking a selfie',prop:'smartphone',framing:'vertical social portrait with landmark visible'},visual_style:{realism:'photorealistic',look:['premium campaign photography','authentic Antigua Guatemala atmosphere'],lighting:['natural sunlight','realistic shadows']},hard_constraints:[],output:{medium:'image',aspect_ratio:'9:16'},generation_mode:'manual_external'};

export function SceneBuilder({tenant}:{tenant:Item}){
 const router=useRouter(),base='/tenants/'+tenant.tenant_id;
 const brand=useLoad(base+'/brand-profile'),characters=useLoad(base+'/brand-characters'),presets=useLoad(base+'/scene-presets'),providers=useLoad('/providers');
 const [scene,setScene]=useState<SceneState>(defaultScene),[preview,setPreview]=useState<Item|null>(null),[error,setError]=useState<ApiError|null>(null),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{if(!brand.data)return;setScene(current=>!brand.data.default_mascot_character_id&&current.subject.mode==='default_brand_character'?{...current,subject:{mode:'none'}}:current)},[brand.data]);
 const character=useMemo(()=>{if(scene.subject.mode==='none')return null;const id=scene.subject.mode==='default_brand_character'?brand.data?.default_mascot_character_id:scene.subject.character_id;return items(characters.data).find(c=>c.character_id===id)||null},[scene.subject,brand.data,characters.data]);
 function patch<K extends keyof SceneState>(key:K,value:SceneState[K]){setScene(s=>({...s,[key]:value}));setPreview(null);setMessage('')}
 function applyPreset(p:Item){const next={...p.scene,generation_mode:scene.generation_mode,preset_id:p.id} as SceneState;patch('subject',next.subject);setScene({...next});setPreview(null);setMessage('Preset aplicado. Puedes ajustar cualquier detalle antes de compilar.');}
 async function uploadEnvironment(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setUploading(true);setError(null);try{const response=await fetch('/api/v1'+base+'/scene-references/ENVIRONMENT_ONLY',{method:'POST',credentials:'same-origin',headers:{'Content-Type':file.type},body:file});const payload=await response.json();if(!response.ok)throw payload.error||{code:String(response.status),message:'No pudimos cargar la referencia.'};patch('environment',{...scene.environment,reference_asset_id:payload.data.asset_id});setMessage('Referencia de entorno cargada y marcada como ENVIRONMENT ONLY.');}catch(e){setError(e as ApiError)}finally{setUploading(false);e.target.value=''}}
 async function compile(){setBusy(true);setError(null);try{const result=await api(base+'/scenes/preview',scene);setPreview(result);setMessage('Prompt compilado desde el contrato estructurado.');}catch(e){setError(e as ApiError)}finally{setBusy(false)}}
 async function create(){setBusy(true);setError(null);try{const result=await api(base+'/scenes',scene);router.push('/jobs/'+result.id)}catch(e){setError(e as ApiError)}finally{setBusy(false)}}
 if(brand.loading||characters.loading||presets.loading)return <Loading text="Preparando personajes y presets…"/>;
 if(brand.error)return <Problem error={brand.error} retry={brand.reload}/>;
 const mascotAsset=brand.data?.default_mascot_asset_id;
 const availableProviders=items(providers.data);
 return <>
  <Header eyebrow={tenant.organization+' / ESCENA GUIADA'} title="Crea la escena. El estudio arma la producción." description="Describe el lugar y la acción. Media Factory conserva la identidad, separa las referencias por función y prepara un paquete verificable para generar."/>
  <div className={styles.presets}><span>Empezar con:</span>{items(presets.data).map(p=><button key={p.id} type="button" className="secondary" onClick={()=>applyPreset(p)}>{p.name}</button>)}</div>
  <section className={'panel '+styles.section}><div className={styles.sectionHead}><span className={styles.number}>01</span><div><p className="eyebrow">PERSONAJE</p><h2>Personaje principal</h2></div></div>
   <div className={styles.characterGrid}><div className={styles.characterCard}>{mascotAsset&&<img src={'/api/v1'+base+'/brand-assets/'+encodeURIComponent(mascotAsset)} alt="Referencia autorizada del Caballito FIRMES"/>}<div><strong>{character?.name||'Sin personaje'}</strong>{scene.subject.mode==='default_brand_character'&&<Tag tone="success">Predeterminado del espacio</Tag>}<small>{character?'Referencia de identidad autorizada y hash-bound.':'La escena se genera sin personaje de marca.'}</small></div></div>
    <div className={styles.controls}><label className="check-line"><input type="radio" name="character-mode" checked={scene.subject.mode==='default_brand_character'} onChange={()=>patch('subject',{mode:'default_brand_character'})}/>Usar personaje predeterminado</label><label className="check-line"><input type="radio" name="character-mode" checked={scene.subject.mode==='none'} onChange={()=>patch('subject',{mode:'none'})}/>Sin personaje</label>{items(characters.data).length>1&&<Field label="Cambiar personaje"><select value={scene.subject.mode==='explicit_character'?scene.subject.character_id||'':''} onChange={e=>patch('subject',e.target.value?{mode:'explicit_character',character_id:e.target.value}:{mode:'default_brand_character'})}><option value="">Predeterminado</option>{items(characters.data).map(c=><option key={c.character_id} value={c.character_id}>{c.name}</option>)}</select></Field>}</div></div>
   {character&&<details><summary>Ver reglas de identidad</summary><div className={styles.ruleColumns}><div><strong>Preservar</strong><ul>{(character.identity_constraints?.preserve||[]).map((v:string)=><li key={v}>{v}</li>)}</ul></div><div><strong>No copiar de la referencia</strong><ul>{(character.identity_constraints?.exclude_from_source||[]).map((v:string)=><li key={v}>{v}</li>)}</ul></div></div></details>}
  </section>
  <section className={'panel '+styles.section}><div className={styles.sectionHead}><span className={styles.number}>02</span><div><p className="eyebrow">ENTORNO</p><h2>¿Dónde sucede?</h2></div></div><div className="form-grid"><Field label="Lugar"><input value={scene.environment.location_name||''} onChange={e=>patch('environment',{...scene.environment,location_name:e.target.value})} maxLength={300}/></Field><Field label="Referencia del entorno (opcional)" help={scene.environment.reference_asset_id?'Cargada como ENVIRONMENT ONLY. No puede cambiar la identidad del personaje.':'Solo se usa para el lugar, nunca para la identidad.'}><input type="file" accept="image/png,image/jpeg" onChange={uploadEnvironment} disabled={uploading}/></Field></div><div className="form-grid"><Field label="Debe aparecer" help="Un elemento por línea o separado por comas."><textarea rows={5} value={scene.environment.required_elements.join('\n')} onChange={e=>patch('environment',{...scene.environment,required_elements:split(e.target.value)})}/></Field><Field label="No debe aparecer"><textarea rows={5} value={scene.environment.forbidden_elements.join('\n')} onChange={e=>patch('environment',{...scene.environment,forbidden_elements:split(e.target.value)})}/></Field></div><label className="check-line"><input type="checkbox" checked={scene.environment.civilian_only} onChange={e=>patch('environment',{...scene.environment,civilian_only:e.target.checked})}/>Entorno civil: sin uniformes ni equipamiento industrial salvo que la escena lo pida explícitamente.</label></section>
  <section className={'panel '+styles.section}><div className={styles.sectionHead}><span className={styles.number}>03</span><div><p className="eyebrow">ACCIÓN</p><h2>¿Qué está haciendo?</h2></div></div><div className="form-grid"><Field label="Acción"><input value={scene.action.verb} onChange={e=>patch('action',{...scene.action,verb:e.target.value})}/></Field><Field label="Objeto o utilería"><input value={scene.action.prop||''} onChange={e=>patch('action',{...scene.action,prop:e.target.value})} placeholder="smartphone"/></Field></div><Field label="Encuadre"><input value={scene.action.framing||''} onChange={e=>patch('action',{...scene.action,framing:e.target.value})}/></Field></section>
  <section className={'panel '+styles.section}><div className={styles.sectionHead}><span className={styles.number}>04</span><div><p className="eyebrow">ESTILO</p><h2>Cómo debe sentirse</h2></div></div><div className={styles.presetRow}>{['Photorealistic','Premium campaign photography','Documentary','Tourism','Community','Cinematic social'].map(v=><button key={v} type="button" className={scene.visual_style.look.map(x=>x.toLowerCase()).includes(v.toLowerCase())?'primary':'secondary'} onClick={()=>patch('visual_style',{...scene.visual_style,look:[v.toLowerCase()]})}>{v}</button>)}</div><div className="form-grid"><Field label="Realismo"><input value={scene.visual_style.realism} onChange={e=>patch('visual_style',{...scene.visual_style,realism:e.target.value})}/></Field><Field label="Iluminación"><input value={scene.visual_style.lighting.join(', ')} onChange={e=>patch('visual_style',{...scene.visual_style,lighting:split(e.target.value)})}/></Field></div></section>
  <section className={'panel '+styles.section}><div className={styles.sectionHead}><span className={styles.number}>05</span><div><p className="eyebrow">SALIDA</p><h2>Formato y ruta de generación</h2></div></div><div className="form-grid"><Field label="Medio"><select value={scene.output.medium} onChange={e=>patch('output',{...scene.output,medium:e.target.value as 'image'|'video',...(e.target.value==='video'?{duration_seconds:6,motion_intent:'subtle walking motion, selfie arm movement and natural background movement',camera_intent:'stable realistic vertical camera'}:{duration_seconds:undefined,motion_intent:undefined,camera_intent:undefined})})}><option value="image">Imagen hero</option><option value="video">Video · imagen primero, animación después</option></select></Field><Field label="Formato"><select value={scene.output.aspect_ratio} onChange={e=>patch('output',{...scene.output,aspect_ratio:e.target.value as '9:16'|'1:1'|'16:9'})}><option>9:16</option><option>1:1</option><option>16:9</option></select></Field>{scene.output.medium==='video'&&<Field label="Duración"><input type="number" min={1} max={30} step={1} value={scene.output.duration_seconds||6} onChange={e=>patch('output',{...scene.output,duration_seconds:Number(e.target.value)})}/></Field>}</div>{scene.output.medium==='video'&&<div className="form-grid"><Field label="Movimiento"><input value={scene.output.motion_intent||''} onChange={e=>patch('output',{...scene.output,motion_intent:e.target.value})}/></Field><Field label="Cámara"><input value={scene.output.camera_intent||''} onChange={e=>patch('output',{...scene.output,camera_intent:e.target.value})}/></Field></div>}
   <div className={styles.providerGrid}>{availableProviders.filter(p=>['manual-external','seedance','higgsfield','capcut','gemini'].includes(p.id)).map(p=><button type="button" key={p.id} disabled={p.id!=='manual-external'&&!p.available} className={(scene.generation_mode===(p.id==='manual-external'?'manual_external':'provider:'+p.id)?styles.providerSelected:'')+' '+styles.providerCard} onClick={()=>patch('generation_mode',p.id==='manual-external'?'manual_external':'provider:'+p.id)}><strong>{p.name}</strong><small>{p.id==='manual-external'?'Disponible · CapCut / Seedance / H3 u otra herramienta aprobada':p.available?'Disponible':'Integración no configurada'}</small></button>)}</div>
  </section>
  <section className={'panel '+styles.compile}><div><p className="eyebrow">CONTRATO CREATIVO</p><h2>Compilar antes de generar</h2><p>El prompt final se deriva de identidad, entorno, acción, exclusiones y formato. Las referencias quedan etiquetadas por rol.</p></div><div className="actions"><button className="secondary" onClick={compile} disabled={busy}>{busy?'Compilando…':'Ver prompt compilado'}</button><button className="primary" onClick={create} disabled={busy||!scene.action.verb.trim()}><Icon name="spark"/>Preparar generación</button></div></section>
  {preview&&<section className={'panel '+styles.preview}><div className="section-title"><h2>Prompt compilado</h2><Tag>{preview.compiler_version}</Tag></div><div className={styles.hashes}><span>Request SHA <code>{preview.structured_request_sha256}</code></span><span>Prompt SHA <code>{preview.final_prompt_sha256}</code></span></div><pre>{preview.final_prompt}</pre><div className={styles.roles}>{(preview.reference_roles||[]).map((r:Item)=><Tag key={r.asset_id}>{String(r.reference_id).replaceAll('_',' ')} · {String(r.role).replaceAll('_',' ')}</Tag>)}</div></section>}
  {message&&<div className="notice success" role="status">{message}</div>}<Problem error={error}/>
 </>;
}
