'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { api, useLoad, items, Mark, Icon, Loading, Problem, Empty, type ApiError } from './ui';
import { Dashboard, Workspaces, TenantSurface } from './workspace';
import { JobDetail, JobLibrary } from './jobs';
export default function Studio({ segments }: { segments: string[] }) {
 const router = useRouter(), login = segments[0] === 'login', me = useLoad(login ? null : '/me'), tenants = useLoad(!login && me.data ? '/tenants' : null);
 const tenantId = segments[0] === 'workspace' ? segments[1] : null, current = segments[2] || '';
 const [mobileOpen, setMobileOpen] = useState(false);
 useEffect(() => { if (me.error && /401|AUTH|SESSION/.test(me.error.code)) router.replace('/login'); }, [me.error, router]);
 useEffect(() => setMobileOpen(false), [segments.join('/')]);
 if (login) return <Login />;
 if (me.loading || !me.data && !me.error) return <main className="standalone"><Mark /><Loading /></main>;
 if (me.error) return <main className="standalone"><Mark /><Problem error={me.error} retry={me.reload} /><Link href="/login">Volver a iniciar sesión</Link></main>;
 const tenant = items(tenants.data).find(t => t.tenant_id === tenantId);
 const nav = [{ href: '/dashboard', label: 'Inicio', icon: 'home', active: !segments.length || segments[0] === 'dashboard' }, { href: '/workspaces', label: 'Espacios de trabajo', icon: 'grid', active: segments[0] === 'workspaces' }];
 const local = tenantId ? [{ key: 'sources', label: 'Fuentes y referencias', icon: 'sources' }, { key: 'content-dna', label: 'Content DNA', icon: 'dna' }, { key: 'weekly', label: 'Producción semanal', icon: 'calendar' }, { key: 'free', label: 'Modo libre', icon: 'spark' }] : [];
 let content: ReactNode;
 if (!segments.length || segments[0] === 'dashboard') content = <Dashboard tenants={tenants} user={me.data} />;
 else if (segments[0] === 'workspaces') content = <Workspaces resource={tenants} />;
 else if (segments[0] === 'workspace' && tenantId) content = <TenantSurface id={tenantId} view={current || 'weekly'} />;
 else if (segments[0] === 'jobs' && segments[1]) content = <JobDetail id={segments[1]} />;
 else if (segments[0] === 'review' || segments[0] === 'releases') content = <JobLibrary tenants={tenants} releases={segments[0] === 'releases'} />;
 else content = <Empty title="Esta página no está en el estudio." action={<Link className="button primary" href="/dashboard">Ir al inicio</Link>}>Elige un espacio para continuar.</Empty>;
 return <div className="studio"><a className="skip" href="#main">Saltar al contenido</a><div className="mobile-bar"><Link className="brand" href="/dashboard"><Mark small />Media Factory</Link><button aria-expanded={mobileOpen} aria-controls="studio-nav" aria-label="Abrir navegación" onClick={() => setMobileOpen(v => !v)}>☰</button></div><aside id="studio-nav" className={'sidebar ' + (mobileOpen ? 'open' : '')}><Link className="brand" href="/dashboard"><Mark small /><span>Media Factory<small>CREATIVE STUDIO</small></span></Link><div className="nav-label">ESTUDIO</div><nav aria-label="Principal">{nav.map(n => <Link className={'nav-item ' + (n.active ? 'active' : '')} href={n.href} key={n.href}><Icon name={n.icon} />{n.label}</Link>)}</nav>{local.length > 0 && <><div className="workspace-label"><span className="tenant-avatar">{(tenant?.organization || tenantId || 'E').slice(0, 1).toUpperCase()}</span><span>{tenant?.organization || tenantId}<small>Espacio actual</small></span></div><nav aria-label="Espacio de trabajo">{local.map(n => <Link className={'nav-item ' + (n.key === current ? 'active' : '')} href={'/workspace/' + tenantId + '/' + n.key} key={n.key}><Icon name={n.icon} />{n.label}</Link>)}</nav></>}<div className="nav-label">ENTREGAS</div><nav aria-label="Entregas"><Link className={'nav-item ' + (segments[0] === 'review' ? 'active' : '')} href="/review"><Icon name="review" />Revisión</Link><Link className={'nav-item ' + (segments[0] === 'releases' ? 'active' : '')} href="/releases"><Icon name="release" />Liberaciones</Link></nav><div className="sidebar-bottom"><div className="quiet-note"><span className="tiny-dot" />Cada historia, con intención.<small>La creatividad empieza contigo.</small></div><div className="account"><span className="avatar">{(me.data.name || me.data.email || 'U').slice(0, 1).toUpperCase()}</span><span>{me.data.name || me.data.email}<small>Tu cuenta</small></span><button className="logout" aria-label="Cerrar sesión" title="Cerrar sesión" onClick={async () => { try { await api('/auth/logout', {}); router.replace('/login'); } catch { me.reload(); } }}>↗</button></div></div></aside><main id="main" className="main"><div className="topline"><span>ESTUDIO DE PRODUCCIÓN</span><span><span className="tiny-dot" />Revisión humana en cada entrega</span></div>{content}<footer className="footer"><span>Media Factory</span><span>Ideas propias. Fuentes claras. Historias que conectan.</span></footer></main></div>;
}
function Login() {
 const router = useRouter(), [busy, setBusy] = useState(false), [error, setError] = useState<ApiError | null>(null);
 async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); setError(null); const f = new FormData(e.currentTarget); try { await api('/auth/login', { email: f.get('email'), password: f.get('password') }); router.replace('/dashboard'); router.refresh(); } catch (err) { setError(err as ApiError); } finally { setBusy(false); } }
 return <main className="login"><section className="login-story"><Link className="brand" href="/login"><Mark small />Media Factory</Link><div className="login-manifesto"><p className="eyebrow">TU PRÓXIMA HISTORIA EMPIEZA AQUÍ</p><h1>Menos herramientas.<br />Más <em>historias.</em></h1><p>Tu material, tu identidad y tus ideas.<br />Un estudio para darles forma.</p><div className="story-composition" aria-hidden="true"><div className="composition-card one"><span>01 / MATERIAL REAL</span><div className="landscape"><i /><b /><em /></div><small>Lo que ya hace único a tu mundo.</small></div><div className="composition-card two"><span>02 / TU IDENTIDAD</span><div className="dna-art"><i /><i /><i /><i /></div><small>Una mirada que se reconoce.</small></div><div className="composition-card three"><span>03 / NUEVAS HISTORIAS</span><Mark /><small>Espacio para lo inesperado.</small></div></div></div><span className="login-foot">DE LA IDEA A LA ENTREGA · CON TU APROBACIÓN</span></section><section className="login-form"><div><p className="eyebrow">BIENVENIDO A TU ESTUDIO</p><h2>Vamos a crear.</h2><p className="muted">Inicia sesión para entrar a tus espacios de trabajo.</p><form onSubmit={submit}><label className="field"><span>Usuario o correo</span><input name="email" type="text" autoComplete="username" placeholder="Tu usuario" required /></label><label className="field"><span>Contraseña</span><input name="password" type="password" autoComplete="current-password" required /></label><Problem error={error} /><button className="primary full" disabled={busy}>{busy ? 'Entrando…' : 'Entrar al estudio'}<Icon name="arrow" /></button></form><p className="login-help">El acceso lo gestiona tu organización. Si aún no tienes una cuenta, contacta a la persona responsable de tu espacio.</p></div><small>Contenido con propósito, de principio a fin.</small></section></main>;
}
