'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useEffect, useRef, useState, type FormEvent } from 'react';
import hero from '../assets/media-factory-hero.webp';
import { api, Mark, Icon, Problem, type ApiError } from './ui';
import styles from './StudioEntry.module.css';

export default function StudioEntry({googleAvailable=false,municipalities=[]}:{googleAvailable?:boolean;municipalities?:any[]}) {
 const router = useRouter(), frame = useRef<HTMLElement>(null);
 const [busy,setBusy]=useState(false),[error,setError]=useState<ApiError|null>(null),[googleError,setGoogleError]=useState(''),[mode,setMode]=useState<'login'|'register'>('login'),[notice,setNotice]=useState('');
 const [paused,setPaused]=useState(false),[reduce,setReduce]=useState(true),[visible,setVisible]=useState(true),[inView,setInView]=useState(true);
 useEffect(()=>{const query=window.matchMedia('(prefers-reduced-motion: reduce)');const preference=()=>setReduce(query.matches);const visibility=()=>setVisible(!document.hidden);preference();visibility();query.addEventListener('change',preference);document.addEventListener('visibilitychange',visibility);const observer=new IntersectionObserver(entries=>setInView(entries[0]?.isIntersecting??false),{threshold:0.05});if(frame.current)observer.observe(frame.current);const code=new URLSearchParams(window.location.search).get('google_error');if(code)setGoogleError(code==='ACCESS_NOT_INVITED'?'Tu cuenta de Google es válida, pero aún no tiene una invitación a una marca.':'No pudimos completar el acceso con Google. Puedes intentar de nuevo o usar usuario y contraseña.');return()=>{query.removeEventListener('change',preference);document.removeEventListener('visibilitychange',visibility);observer.disconnect()};},[]);
 const stopped=paused||reduce||!visible||!inView, municipalityOptions=Array.isArray(municipalities)?municipalities:[];
 async function submitLogin(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError(null);setNotice('');const fields=new FormData(e.currentTarget);const tenantId=String(fields.get('tenant_id')||'');try{const user=await api('/auth/login',{identifier:fields.get('identifier'),password:fields.get('password'),...(tenantId?{tenant_id:tenantId}:{})});const selected=tenantId||String(user.current_tenant_id||'');if(selected){router.replace('/workspace/'+encodeURIComponent(selected)+'/start');router.refresh();return}let firstRun:any=null;try{firstRun=await api('/me/onboarding')}catch{}const needsGuide=firstRun?.status==='NEW'&&(firstRun.tenant_count===0||(Array.isArray(firstRun.tenants)&&firstRun.tenants.every((tenant:any)=>tenant.setup_status==='SOURCE_REQUIRED')));router.replace(needsGuide?'/onboarding':'/dashboard');router.refresh()}catch(err){setError(err as ApiError)}finally{setBusy(false)}}
 async function submitRegistration(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=e.currentTarget,fields=new FormData(form),password=String(fields.get('password')||''),confirm=String(fields.get('confirm_password')||'');setError(null);setNotice('');if(password!==confirm){setError({code:'PASSWORD_MISMATCH',message:'Las contraseñas no coinciden.'});return}setBusy(true);try{await api('/auth/register',{name:String(fields.get('name')||''),email:String(fields.get('email')||''),dpi:String(fields.get('dpi')||''),password,tenant_id:String(fields.get('tenant_id')||'')});setNotice('Solicitud enviada. La cuenta quedará pendiente hasta que el propietario o IT del municipio la apruebe.');form.reset();setMode('login')}catch(err){setError(err as ApiError)}finally{setBusy(false)}}
 function switchMode(next:'login'|'register'){setMode(next);setError(null);setNotice('');setGoogleError('')}
 const municipalitySelect=<label className={styles.field}><span>Municipio</span><select name="tenant_id" required={municipalityOptions.length>0} disabled={municipalityOptions.length===0} defaultValue=""><option value="" disabled>{municipalityOptions.length?'Selecciona tu municipio':'No hay municipios disponibles'}</option>{municipalityOptions.map((m:any)=><option key={m.tenant_id} value={m.tenant_id}>{m.municipality}{m.organization&&m.organization!==m.municipality?' · '+m.organization:''}</option>)}</select></label>;
 return <main className={styles.entry}>
  <a className="skip" href="#studio-access">Ir al acceso del estudio</a>
  <section className={styles.story} aria-labelledby="entry-title">
   <header className={styles.header}><Link className="brand" href="/login"><Mark small/><span>Media Factory<small>ESTUDIO CREATIVO</small></span></Link><a className={styles.jump} href="#studio-access">Entrar <span aria-hidden="true">↘</span></a></header>
   <div className={styles.intro}><p className={styles.eyebrow}>LA MIRADA ES TUYA. LAS POSIBILIDADES, INFINITAS.</p><h1 id="entry-title">Dale forma a<br/><span>lo que imaginas.</span></h1><p className={styles.subtitle}>Material real. Identidad propia.<br/>Un nuevo espacio para tus historias.</p></div>
   <figure ref={frame} className={styles.artwork} data-paused={stopped} aria-label="Arte original de Media Factory">
    <img src={hero.src} width={hero.width} height={hero.height} alt="Escultura de vidrio rojo con luz ámbar que fluye alrededor de una apertura oscura" fetchPriority="high" className={styles.hero}/>
    <div className={styles.lightSweep} aria-hidden="true"/>
    <figcaption className={styles.artCaption}><span>01 / UNA IDEA TOMA FORMA</span><span>ARTE CONCEPTUAL · IA</span></figcaption>
    <button type="button" className={styles.motion} onClick={()=>setPaused(p=>!p)} aria-pressed={paused} disabled={reduce} aria-label={reduce?'Movimiento reducido por tu preferencia del sistema':paused?'Reanudar animación':'Pausar animación'}><span aria-hidden="true">{stopped?'▷':'Ⅱ'}</span><span>{reduce?'Movimiento reducido':paused?'Reanudar':'Pausar'}</span></button>
   </figure>
   <footer className={styles.storyFooter}><p>Creatividad con dirección.<br/><strong>Cada entrega, con tu aprobación.</strong></p><span aria-hidden="true" className={styles.signature}>M<span>F</span>—</span></footer>
  </section>
  <section id="studio-access" className={styles.access} aria-labelledby="access-title">
   <div className={styles.accessBody}><div className={styles.number} aria-hidden="true">02 / ACCESO DEPARTAMENTAL</div><p className={styles.eyebrow}>{mode==='login'?'ENTRA A TU MUNICIPIO':'SOLICITA TU ACCESO'}</p><h2 id="access-title">{mode==='login'?'Vamos a crear.':'Crea tu cuenta.'}</h2><p className={styles.accessDescription}>{mode==='login'?'Selecciona el municipio y entra con correo o DPI.':'Tu solicitud no da acceso automáticamente. Propietario o IT deben aprobarla y asignarte un rol.'}</p>
    <div className={styles.modeSwitch} role="tablist" aria-label="Modo de acceso"><button type="button" className={mode==='login'?styles.modeActive:''} onClick={()=>switchMode('login')} aria-selected={mode==='login'}>Entrar</button><button type="button" className={mode==='register'?styles.modeActive:''} onClick={()=>switchMode('register')} aria-selected={mode==='register'}>Crear cuenta</button></div>
    {notice&&<div className={styles.success} role="status">{notice}</div>}
    {mode==='login'?<>{googleAvailable&&<><a className={styles.google} href="/api/v1/auth/google/start"><span className={styles.googleMark} aria-hidden="true">G</span><span>Continuar con Google</span><Icon name="arrow"/></a><p className={styles.googleHint}>Usa el correo al que te invitaron. Google confirma tu identidad; Media Factory decide a qué municipio puedes entrar.</p><div className={styles.divider}><span>o usuario y contraseña</span></div></>}{googleError&&<div className={styles.googleError} role="alert">{googleError}</div>}<form onSubmit={submitLogin} aria-busy={busy}>{municipalitySelect}<label className={styles.field}><span>Correo o DPI</span><input name="identifier" type="text" autoComplete="username" placeholder="correo@ejemplo.com o 13 dígitos" required/></label><label className={styles.field}><span>Contraseña</span><input name="password" type="password" autoComplete="current-password" required/></label><Problem error={error}/><button className={styles.enter} disabled={busy}>{busy?'Entrando…':'Entrar al municipio'}<Icon name="arrow"/></button></form><p className={styles.help}>Elegir un municipio no concede acceso. La cuenta debe tener una membresía aprobada para ese municipio. El acceso administrativo protegido permanece disponible como contingencia.</p></>:<form onSubmit={submitRegistration} aria-busy={busy}><label className={styles.field}><span>Nombre completo</span><input name="name" type="text" autoComplete="name" maxLength={160} required placeholder="Nombre y apellido"/></label>{municipalitySelect}<label className={styles.field}><span>Correo</span><input name="email" type="email" autoComplete="email" maxLength={254} required placeholder="correo@ejemplo.com"/></label><label className={styles.field}><span>DPI guatemalteco</span><input name="dpi" type="text" inputMode="numeric" autoComplete="off" maxLength={17} required placeholder="13 dígitos"/></label><p className={styles.privacyNote}>El DPI se normaliza para validar su formato de 13 dígitos y se guarda únicamente como identificador protegido; Media Factory no consulta RENAP ni verifica identidad gubernamental.</p><label className={styles.field}><span>Contraseña</span><input name="password" type="password" autoComplete="new-password" minLength={12} maxLength={256} required/></label><label className={styles.field}><span>Confirmar contraseña</span><input name="confirm_password" type="password" autoComplete="new-password" minLength={12} maxLength={256} required/></label><Problem error={error}/><button className={styles.enter} disabled={busy||municipalityOptions.length===0}>{busy?'Enviando…':'Solicitar acceso'}<Icon name="arrow"/></button><p className={styles.help}>La solicitud queda pendiente. El administrador del municipio debe aprobarla y elegir tu responsabilidad antes de que puedas entrar.</p></form>}
   </div>
   <footer className={styles.accessFooter}><span>IDEAR. PRODUCIR. REVISAR.</span><p>Las herramientas cambian.<br/>Tu mirada permanece.</p></footer>
  </section>
 </main>
}
