'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useEffect, useState, type ReactNode } from 'react';
import { api, useLoad, items, Mark, Icon, Loading, Problem, Empty, type ApiError } from './ui';
import { Dashboard, Workspaces, TenantSurface } from './workspace';
import { JobDetail, JobLibrary } from './jobs';
import StudioEntry from './StudioEntry';
import {Integrations} from './Integrations';
import { QuickCreate } from './QuickCreate';
import {FirmesLockup,isFirmesTenant} from './FirmesBrand';
export default function Studio({ segments }: { segments: string[] }) {
 const router = useRouter(), login = segments[0] === 'login', me = useLoad(login ? null : '/me'), tenants = useLoad(!login && me.data ? '/tenants' : null);
 const tenantId = segments[0] === 'workspace' ? segments[1] : null, current = segments[2] || '';
 const routeJob = useLoad(!login && me.data && segments[0] === 'jobs' && segments[1] ? '/jobs/' + encodeURIComponent(segments[1]) : null);
 const [mobileOpen, setMobileOpen] = useState(false);
 useEffect(() => { if (me.error && /401|AUTH|SESSION/.test(me.error.code)) router.replace('/login'); }, [me.error, router]);
 useEffect(() => setMobileOpen(false), [segments.join('/')]);
 if (login) return <StudioEntry />;
 if (me.loading || !me.data && !me.error) return <main className="standalone"><Mark /><Loading /></main>;
 if (me.error) return <main className="standalone"><Mark /><Problem error={me.error} retry={me.reload} /><Link href="/login">Volver a iniciar sesión</Link></main>;
 const tenantList=items(tenants.data), shellTenantId = tenantId || routeJob.data?.tenant_id || (tenantList.length===1?tenantList[0].tenant_id:null);
 const tenant = tenantList.find(t => t.tenant_id === shellTenantId), firmesShell=isFirmesTenant(tenant);
 const nav = [{ href: '/dashboard', label: 'Inicio', icon: 'home', active: !segments.length || segments[0] === 'dashboard' }, { href: '/workspaces', label: 'Marcas', icon: 'grid', active: segments[0] === 'workspaces' }];
 const local = tenantId ? [{ key: 'sources', label: 'Material', icon: 'sources' }, { key: 'content-dna', label: 'Estilo', icon: 'dna' }, { key: 'free', label: 'Crear', icon: 'spark' }, {key:'creative-profiles',label:'Personajes y lugares',icon:'dna'}] : [];
 let content: ReactNode;
 if (!segments.length || segments[0] === 'dashboard') content = <Dashboard tenants={tenants} user={me.data} tenant={tenant} />;
 else if (segments[0] === 'workspaces') content = <Workspaces resource={tenants} />;
 else if (segments[0] === 'workspace' && tenantId) content = <TenantSurface id={tenantId} view={current || 'weekly'} />;
 else if (segments[0] === 'admin') content = <Integrations allowed={me.data.manage_integrations===true}/>;
 else if (segments[0] === 'jobs' && segments[1]) content = <JobDetail id={segments[1]} manageIntegrations={me.data.manage_integrations===true} />;
 else if (segments[0] === 'review' || segments[0] === 'releases') content = <JobLibrary tenants={tenants} releases={segments[0] === 'releases'} />;
 else content = <Empty title="Esta página no está en el estudio." action={<Link className="button primary" href="/dashboard">Ir al inicio</Link>}>Elige un espacio para continuar.</Empty>;
 return <div className={'studio '+(firmesShell?'firmes-shell-v2':'')}><a className="skip" href="#main">Saltar al contenido</a><div className="mobile-bar liquid-glass-nav"><Link className="brand" href="/dashboard"><Mark small />Media Factory</Link><div className="mobile-actions"><QuickCreate tenants={items(tenants.data).map(t=>({tenant_id:t.tenant_id,organization:t.organization}))} loading={tenants.loading} brand={firmesShell?'firmes':undefined} /><button aria-expanded={mobileOpen} aria-controls="studio-nav" aria-label="Abrir navegación" onClick={() => setMobileOpen(v => !v)}>☰</button></div></div><aside id="studio-nav" className={'sidebar liquid-glass-nav ' + (mobileOpen ? 'open' : '')}><Link className="brand" href="/dashboard"><Mark small /><span>Media Factory<small>CREATIVE STUDIO</small></span></Link><div className="nav-label">ESTUDIO</div><nav aria-label="Principal">{nav.map(n => <Link className={'nav-item ' + (n.active ? 'active' : '')} href={n.href} aria-current={n.active ? 'page' : undefined} key={n.href}><Icon name={n.icon} />{n.label}</Link>)}</nav>{local.length > 0 && <><div className="workspace-label">{firmesShell?<FirmesLockup compact/>:<span className="tenant-avatar">{(tenant?.organization || tenantId || 'E').slice(0, 1).toUpperCase()}</span>}<span>{tenant?.organization || tenantId}<small>Marca actual</small></span></div><nav aria-label="Marca">{local.map(n => <Link className={'nav-item ' + (n.key === current ? 'active' : '')} href={'/workspace/' + tenantId + '/' + n.key} aria-current={n.key === current ? 'page' : undefined} key={n.key}><Icon name={n.icon} />{n.label}</Link>)}</nav></>}<div className="nav-label">FINALIZAR</div><nav aria-label="Entregas"><Link className={'nav-item ' + (segments[0] === 'review' ? 'active' : '')} href="/review" aria-current={segments[0] === 'review' ? 'page' : undefined}><Icon name="review" />Revisar</Link><Link className={'nav-item ' + (segments[0] === 'releases' ? 'active' : '')} href="/releases" aria-current={segments[0] === 'releases' ? 'page' : undefined}><Icon name="release" />Entregas</Link></nav><>{me.data.manage_integrations===true&&<nav aria-label="Administración"><div className="nav-label">ADMINISTRACIÓN</div><Link className={"nav-item "+(segments[0]==='admin'?'active':'')} href="/admin/integrations"><Icon name="grid"/>APIs e integraciones</Link></nav>}</><div className="sidebar-bottom"><div className="quiet-note"><span className="tiny-dot" />Cada historia, con intención.<small>La creatividad empieza contigo.</small></div><div className="account"><span className="avatar">{(me.data.name || me.data.email || 'U').slice(0, 1).toUpperCase()}</span><span>{me.data.name || me.data.email}<small>Tu cuenta</small></span><button className="logout" aria-label="Cerrar sesión" title="Cerrar sesión" onClick={async () => { try { await api('/auth/logout', {}); router.replace('/login'); } catch { me.reload(); } }}>↗</button></div></div></aside><main id="main" className="main"><div className="topline liquid-glass-topline"><span>TU ESTUDIO</span><div className="topline-actions"><span><span className="tiny-dot" />Tú apruebas cada entrega</span><QuickCreate tenants={items(tenants.data).map(t=>({tenant_id:t.tenant_id,organization:t.organization}))} loading={tenants.loading} brand={firmesShell?'firmes':undefined} /></div></div>{content}<footer className="footer"><span>Media Factory</span><span>Ideas propias. Fuentes claras. Historias que conectan.</span></footer></main></div>;
}
