'use client';
import {useState,type FormEvent} from 'react';
import {api,useLoad,Header,Field,Tag,Loading,Problem,Empty,type ApiError,type Item} from './ui';

const responsibilityForRole=(role:string)=>role==='reviewer'?'municipal_coordinator':role==='admin'?'it':role==='editor'?'editor':role==='viewer'?'viewer':'';
const roleLabel=(role:string)=>role==='owner'?'Propietario':role==='reviewer'?'Coordinador municipal':role==='admin'?'IT / Aprobación técnica':role==='editor'?'Editor':'Consulta';

export function Team({tenant}:{tenant:Item}){
 const resource=useLoad('/tenants/'+encodeURIComponent(tenant.tenant_id)+'/team'),[busy,setBusy]=useState(false),[error,setError]=useState<ApiError|null>(null),[message,setMessage]=useState(''),[invitationUrl,setInvitationUrl]=useState('');
 async function invite(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form);setBusy(true);setError(null);setMessage('');setInvitationUrl('');try{await api('/tenants/'+encodeURIComponent(tenant.tenant_id)+'/team/invitations',{email:String(f.get('email')||''),responsibility:String(f.get('responsibility')||'')});setMessage('Invitación registrada. No se envió un correo. Comparte el enlace con la persona invitada.');setInvitationUrl(window.location.origin+'/login');form.reset();resource.reload()}catch(err){setError(err as ApiError)}finally{setBusy(false)}}
 async function changeRole(userId:string,responsibility:string){setBusy(true);setError(null);try{await api('/tenants/'+encodeURIComponent(tenant.tenant_id)+'/team/'+encodeURIComponent(userId)+'/role',{responsibility});setMessage('Responsabilidad actualizada.');resource.reload()}catch(err){setError(err as ApiError)}finally{setBusy(false)}}
 async function remove(userId:string){setBusy(true);setError(null);try{await api('/tenants/'+encodeURIComponent(tenant.tenant_id)+'/team/'+encodeURIComponent(userId)+'/remove',{});setMessage('Acceso retirado.');resource.reload()}catch(err){setError(err as ApiError)}finally{setBusy(false)}}
 async function revoke(inviteId:string){setBusy(true);setError(null);try{await api('/tenants/'+encodeURIComponent(tenant.tenant_id)+'/team/invitations/'+encodeURIComponent(inviteId),{action:'revoke'});setMessage('Invitación retirada.');resource.reload()}catch(err){setError(err as ApiError)}finally{setBusy(false)}}
 async function approveRegistration(userId:string,responsibility:string){setBusy(true);setError(null);setMessage('');try{await api('/tenants/'+encodeURIComponent(tenant.tenant_id)+'/team/registrations/'+encodeURIComponent(userId),{action:'approve',responsibility});setMessage('Cuenta aprobada. La persona ya puede entrar a este municipio con correo o DPI y contraseña.');resource.reload()}catch(err){setError(err as ApiError)}finally{setBusy(false)}}
 async function rejectRegistration(userId:string){setBusy(true);setError(null);setMessage('');try{await api('/tenants/'+encodeURIComponent(tenant.tenant_id)+'/team/registrations/'+encodeURIComponent(userId),{action:'reject'});setMessage('Solicitud rechazada.');resource.reload()}catch(err){setError(err as ApiError)}finally{setBusy(false)}}
 async function saveGoogle(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form);setBusy(true);setError(null);setMessage('');try{await api('/admin/google-auth',{client_id:String(f.get('client_id')||''),client_secret:String(f.get('client_secret')||'')});setMessage('Acceso con Google configurado. Ya puedes invitar al equipo.');form.reset();resource.reload()}catch(err){setError(err as ApiError)}finally{setBusy(false)}}
 async function removeGoogle(){setBusy(true);setError(null);setMessage('');try{await api('/admin/google-auth',{remove:true});setMessage('Acceso con Google desactivado. El acceso administrativo sigue disponible.');resource.reload()}catch(err){setError(err as ApiError)}finally{setBusy(false)}}
 if(resource.loading)return <Loading/>;if(resource.error)return <Problem error={resource.error} retry={resource.reload}/>;const data=resource.data;if(!data)return null;
 return <><Header eyebrow="PERSONAS Y APROBACIONES" title="Equipo" description="Acceso por marca con responsabilidades claras. Propietario e IT administran el equipo; cada aprobación queda ligada a una persona."/>
  <section className="approval-flow-simple" aria-label="Flujo de aprobaciones">
   <div><span>1</span><div><small>CONTENIDO</small><strong>Coordinador municipal</strong><p>Revisa el enfoque creativo y pide cambios si hace falta.</p></div></div>
   <i aria-hidden="true">→</i>
   <div><span>2</span><div><small>TÉCNICO</small><strong>IT</strong><p>Verifica la versión independiente y el paso técnico.</p></div></div>
   <i aria-hidden="true">→</i>
   <div><span>3</span><div><small>FINAL</small><strong>Propietario / IT</strong><p>Aprueba la entrega exacta antes de liberarla.</p></div></div>
  </section>
  {data.can_configure_google&&<details className="panel google-access-card" open={!data.google_auth?.available}><summary><span><small>ACCESO DEL EQUIPO</small><strong>{data.google_auth?.available?'Google está listo':'Configurar Google'}</strong></span><Tag tone={data.google_auth?.available?'success':'warning'}>{data.google_auth?.available?'ACTIVO':'PENDIENTE'}</Tag></summary><div className="google-access-body"><div><h2>{data.google_auth?.available?'El equipo ya puede entrar con Google.':'Activa el acceso con Google una sola vez.'}</h2><p>En Google Cloud crea un cliente OAuth tipo <strong>Web application</strong> y registra exactamente <code>https://media-factory.textilesdemedellin.com/api/v1/auth/google/callback</code>. Media Factory guarda el secret cifrado y nunca lo vuelve a mostrar.</p>{data.google_auth?.available&&<p className="google-client-status"><span>Configuración</span><code>{data.google_auth.client_id||'Configurado de forma segura en el servidor'}</code></p>}</div><form onSubmit={saveGoogle}><Field label="Google Client ID"><input name="client_id" required maxLength={240} autoComplete="off" placeholder="…apps.googleusercontent.com"/></Field><Field label="Google Client Secret"><input name="client_secret" type="password" required maxLength={4096} autoComplete="new-password" placeholder="Se guarda cifrado"/></Field><div className="actions"><button className="primary" disabled={busy}>{busy?'Guardando…':data.google_auth?.available?'Reemplazar configuración':'Activar Google'}</button>{data.google_auth?.configured&&<button type="button" className="text-button" onClick={removeGoogle} disabled={busy}>Desactivar Google</button>}</div></form></div></details>}
  {data.can_manage&&<section className="panel team-invite-card"><div><p className="eyebrow">AGREGAR AL EQUIPO</p><h2>Invita por correo</h2><p>La persona entra con Google usando ese mismo correo. No tienes que crearle una contraseña.</p></div><form onSubmit={invite}><Field label="Correo"><input name="email" type="email" required maxLength={254} placeholder="persona@gmail.com" autoComplete="off"/></Field><Field label="Responsabilidad"><select name="responsibility" defaultValue="municipal_coordinator"><option value="municipal_coordinator">Coordinador municipal</option><option value="it">IT / Aprobación técnica</option><option value="editor">Editor</option><option value="viewer">Consulta</option></select></Field><button className="primary" disabled={busy}>{busy?'Guardando…':'Invitar persona'}</button></form></section>}
  {message&&<div className="notice success" role="status">{message}</div>}{invitationUrl&&<div className="panel"><Field label="Enlace para compartir"><input readOnly value={invitationUrl} onFocus={e=>e.target.select()}/></Field><button className="text-button" type="button" onClick={async()=>{try{await navigator.clipboard.writeText(invitationUrl);setMessage('Enlace copiado. Compártelo con la persona invitada.')}catch{setMessage('Selecciona y copia el enlace para compartirlo.')}}}>Copiar enlace</button></div>}<Problem error={error}/>
  {data.can_manage&&Array.isArray(data.registrations)&&data.registrations.length>0&&<><div className="section-title"><div><p className="eyebrow">APROBACIÓN DE CUENTAS</p><h2>Solicitudes pendientes</h2></div><span className="muted">{data.registrations.length} por revisar</span></div><div className="team-list pending">{data.registrations.map((r:Item)=><RegistrationRequest key={r.user_id} request={r} busy={busy} approve={approveRegistration} reject={rejectRegistration}/>)}</div></>}
  <div className="section-title"><h2>Personas con acceso</h2><span className="muted">{data.members.length} activas</span></div>
  {data.members.length?<div className="team-list">{data.members.map((m:Item)=><article className="team-row" key={m.user_id}><span className="avatar">{String(m.name||m.email||'?').slice(0,1).toUpperCase()}</span><div className="team-person"><strong>{m.name||m.email}</strong><small>{m.email} · {m.auth_provider==='google'?'Google':m.account_type==='self_service'?'Correo/DPI + contraseña':'Acceso administrativo'}</small></div><Tag tone={m.role==='owner'?'success':''}>{roleLabel(m.role)}</Tag>{data.can_manage&&m.role!=='owner'&&!m.configured_membership&&<div className="team-actions"><select aria-label={'Responsabilidad de '+(m.name||m.email)} value={responsibilityForRole(m.role)} onChange={e=>changeRole(m.user_id,e.target.value)} disabled={busy}>{!responsibilityForRole(m.role)&&<option value="" disabled>{roleLabel(m.role)}</option>}<option value="municipal_coordinator">Coordinador municipal</option><option value="it">IT</option><option value="editor">Editor</option><option value="viewer">Consulta</option></select><button className="text-button" onClick={()=>remove(m.user_id)} disabled={busy}>Quitar</button></div>}</article>)}</div>:<Empty title="Todavía estás tú solo.">Invita a coordinación municipal, IT, edición o consulta según el trabajo de cada persona.</Empty>}
  {data.invitations.length>0&&<><div className="section-title"><h2>Invitaciones pendientes</h2></div><div className="team-list pending">{data.invitations.map((i:Item)=><article className="team-row" key={i.id}><span className="avatar pending">@</span><div className="team-person"><strong>{i.email}</strong><small>Esperando su primer acceso con Google</small></div><Tag>{roleLabel(i.role)}</Tag>{data.can_manage&&<button className="text-button" onClick={()=>revoke(i.id)} disabled={busy}>Retirar</button>}</article>)}</div></>}
 </>;
}


function RegistrationRequest({request,busy,approve,reject}:{request:Item;busy:boolean;approve:(userId:string,responsibility:string)=>void;reject:(userId:string)=>void}){
 const [responsibility,setResponsibility]=useState('viewer');
 return <article className="team-row registration-row"><span className="avatar pending">+</span><div className="team-person"><strong>{request.name}</strong><small>{request.email} · DPI termina en {request.dpi_last4} · esperando aprobación</small></div><div className="team-actions"><select aria-label={'Responsabilidad para '+request.name} value={responsibility} onChange={e=>setResponsibility(e.target.value)} disabled={busy}><option value="municipal_coordinator">Coordinador municipal</option><option value="it">IT</option><option value="editor">Editor</option><option value="viewer">Consulta</option></select><button className="primary" type="button" onClick={()=>approve(request.user_id,responsibility)} disabled={busy}>Aprobar</button><button className="text-button" type="button" onClick={()=>reject(request.user_id)} disabled={busy}>Rechazar</button></div></article>
}
