'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState, useEffect, type FormEvent } from 'react';
import { api, useLoad, items, Header, Icon, Tag, Empty, Loading, Problem, Field, Status, DateLabel, type Item, type Resource, type ApiError } from './ui';
import { Sources, DNA } from './library';
import { Planner } from './planner';
import {CreationGuide} from './CreationGuide';
import {CreativeProfiles} from './CreativeProfiles';
export function Dashboard({ tenants, user }: { tenants: Resource; user: Item }) {
 const list = items(tenants.data);
 return <><Header eyebrow="TU ESTUDIO, EN ORDEN" title={'Hola, ' + (user.name?.split(' ')[0] || 'creador') + '.'} description="Dale forma a lo que viene. Cada historia empieza con una buena idea." action={<Link className="button primary" href="/workspaces"><Icon name="spark" />Crear contenido</Link>} /><section className="hero-panel"><div><Tag tone="warm">DE LA IDEA A LA ENTREGA</Tag><h2>Una semana de historias.<br /><em>Una sola visión.</em></h2><p>Combina material real, ideas nuevas y tu identidad en un plan que puedas revisar antes de producir.</p><Link className="button light" href={list.length === 1 ? '/workspace/' + list[0].tenant_id + '/weekly' : '/workspaces'}>Planear mi semana<Icon name="arrow" /></Link></div><div className="hero-art" aria-hidden="true"><div className="film-frame"><span>YOUR NEXT STORY</span><div className="abstract-orbit"><i /><b /><em /></div><small>PLAY. EXPLORE. CREATE.</small></div><div className="floating-label">Tu material + tu imaginación</div><div className="film-count">01—04</div></div></section><DashboardActivity tenants={list} /><div className="section-title"><h2>Tus espacios de trabajo</h2><Link href="/workspaces">Ver todos ↗</Link></div>{tenants.loading ? <Loading /> : tenants.error ? <Problem error={tenants.error} retry={tenants.reload} /> : list.length ? <div className="workspace-grid">{list.map(t => <WorkspaceCard key={t.tenant_id} tenant={t} />)}</div> : <Empty icon="grid" title="Dale un espacio a tu primera marca." action={<Link className="button secondary" href="/workspaces">Crear espacio de trabajo</Link>}>Organiza sus fuentes, su identidad y sus producciones en un mismo lugar.</Empty>}<div className="process-strip">{[['01', 'Trae tu mundo', 'Fuentes y referencias autorizadas'], ['02', 'Encuentra tu voz', 'Una identidad creativa compartida'], ['03', 'Dale forma', 'Planifica, produce y revisa']].map(([n, title, text]) => <div key={n}><span>{n}</span><div><h3>{title}</h3><p>{text}</p></div></div>)}</div></>;
}
function WorkspaceCard({ tenant }: { tenant: Item }) { return <Link className="workspace-card" href={'/workspace/' + tenant.tenant_id + '/weekly'}><div className="workspace-card-top"><span className="workspace-monogram">{tenant.organization.slice(0, 1).toUpperCase()}</span><span aria-hidden="true">↗</span></div><h3>{tenant.organization}</h3><p>{tenant.territory || 'Tu espacio creativo'}</p><div className="card-foot"><span>{tenant.sources?.length || 0} fuentes y referencias</span><Tag>{tenant.role || 'Espacio'}</Tag></div></Link>; }
export function Workspaces({ resource }: { resource: Resource }) {
 const [open, setOpen] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState<ApiError | null>(null), router = useRouter();
 async function create(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); setBusy(true); setError(null); try { const t = await api('/tenants', Object.fromEntries(f)); resource.reload(); router.push('/workspace/' + t.tenant_id + '/sources'); } catch (err) { setError(err as ApiError); } finally { setBusy(false); } }
 return <><Header eyebrow="UN ESPACIO PARA CADA IDENTIDAD" title="Espacios de trabajo" description="Cada marca tiene sus propias fuentes, su voz y sus historias." action={<button className="primary" onClick={() => setOpen(v => !v)}>+ Nuevo espacio</button>} />{open && <section className="panel form-panel"><div className="section-title"><h2>Crea tu espacio</h2><button className="text-button" onClick={() => setOpen(false)}>Cerrar</button></div><form onSubmit={create}><div className="form-grid"><Field label="Nombre de la organización"><input name="organization" required maxLength={160} placeholder="Nombre de tu marca" /></Field><Field label="Identificador" help="Letras minúsculas, números y guiones. Entre 2 y 64 caracteres."><input name="tenant_id" required pattern="[a-z0-9][a-z0-9-]{1,63}" placeholder="mi-marca" /></Field><Field label="Territorio"><input name="territory" maxLength={160} placeholder="Ciudad o región" /></Field><Field label="Contexto"><select name="content_context"><option value="commercial">Comercial</option><option value="community">Comunidad</option><option value="nonprofit">Sin fines de lucro</option><option value="media">Medios</option><option value="public-affairs">Asuntos públicos</option></select></Field></div><Field label="¿Cómo se siente tu marca?"><textarea name="visual_language" rows={3} maxLength={500} placeholder="Cálida, cercana, documental… Describe tu lenguaje visual." /></Field><Problem error={error} /><button className="primary" disabled={busy}>{busy ? 'Creando…' : 'Crear espacio'}<Icon name="arrow" /></button></form></section>}{resource.loading ? <Loading /> : resource.error ? <Problem error={resource.error} retry={resource.reload} /> : items(resource.data).length ? <div className="workspace-grid">{items(resource.data).map(t => <WorkspaceCard key={t.tenant_id} tenant={t} />)}</div> : <Empty icon="grid" title="Tu estudio está listo para empezar.">Crea un espacio para reunir la identidad y el contenido de tu organización.</Empty>}</>;
}
export function TenantSurface({ id, view }: { id: string; view: string }) {
 const tenant = useLoad('/tenants/' + encodeURIComponent(id));
 if (tenant.loading) return <Loading />;
 if (tenant.error) return <Problem error={tenant.error} retry={tenant.reload} />;
 if (!tenant.data) return <Empty title="No encontramos este espacio.">Vuelve a tus espacios de trabajo para continuar.</Empty>;
 if (view === 'sources') return <><CreationGuide id={id}/><Sources tenant={tenant.data} refresh={tenant.reload} /></>;
 if (view === 'content-dna') return <><CreationGuide id={id}/><DNA tenant={tenant.data} /></>;
 if (view === 'weekly' || view === 'free') return <><CreationGuide id={id}/><Planner tenant={tenant.data} free={view === 'free'} key={id + view} /></>;
 if(view==='creative-profiles')return <CreativeProfiles tenant={tenant.data}/>;
 return <Empty title="Esta sección no existe.">Elige una sección del menú de tu espacio.</Empty>;
}
function DashboardActivity({tenants}:{tenants:Item[]}) {
 const [selected,setSelected]=useState('');useEffect(()=>{if(!selected&&tenants.length)setSelected(tenants[0].tenant_id)},[selected,tenants]);
 const resource=useLoad(selected?'/tenants/'+selected+'/dashboard':null);if(!tenants.length)return null;const d=resource.data,current=d?.plans?.slice().sort((a:Item,b:Item)=>String(b.created_at).localeCompare(a.created_at))[0];
 const eventNames:Record<string,string>={WORKSPACE_CREATED:'Espacio creado',SOURCE_AUTHORIZED:'Fuente autorizada',CONTENT_DNA_UPDATED:'Content DNA actualizado',PLAN_DRAFT_CREATED:'Borrador guardado',PLAN_APPROVED:'Conceptos aprobados',JOB_QUEUED:'Producción solicitada',MASCOT_SOURCE_SELECTED:'Personaje de marca seleccionado'};
 return <section className="dashboard-activity"><div className="section-title"><h2>Lo que sucede en tu estudio</h2><label className="compact-select"><span className="sr-only">Espacio del resumen</span><select value={selected} onChange={e=>setSelected(e.target.value)}>{tenants.map(t=><option key={t.tenant_id} value={t.tenant_id}>{t.organization}</option>)}</select></label></div>{resource.loading?<Loading/>:resource.error?<Problem error={resource.error} retry={resource.reload}/>:d&&<><div className="metric-grid">{[['planned','Por producir'],['producing','En producción'],['awaiting_review','Para revisar'],['released','Liberaciones']].map(([key,label])=><div className="panel metric" key={key}><span>{label}</span><strong>{d[key]??0}</strong></div>)}</div>{d.blockers?.length>0&&<div className="notice warning"><strong>{d.blockers.length} {d.blockers.length===1?'asunto necesita':'asuntos necesitan'} atención</strong><ul>{d.blockers.map((b:Item,i:number)=><li key={i}><Link href={'/jobs/'+b.job_id}>{b.message||b.code} →</Link></li>)}</ul></div>}<div className="dashboard-grid"><section className="panel"><p className="eyebrow">LO MÁS RECIENTE</p>{current?<><h3>Semana del <DateLabel value={current.week_of}/></h3><p className="muted small-text">{current.stories.length} historias en el plan</p><Status value={current.status}/><div className="actions"><Link className="button secondary" href={'/workspace/'+selected+'/weekly'}>Ver el plan →</Link></div></>:<><h3>Tu semana todavía está por escribir.</h3><p className="muted small-text">Crea un primer plan para ver su progreso aquí.</p></>}{d.jobs?.length>0&&<div className="dashboard-jobs">{d.jobs.slice(-4).reverse().map((j:Item)=><Link key={j.id} href={'/jobs/'+j.id}><span>{j.title}</span><Status value={j.status}/></Link>)}</div>}</section><section className="panel"><p className="eyebrow">ACTIVIDAD RECIENTE</p>{d.activity?.length?<div className="activity-list">{d.activity.slice(0,5).map((e:Item,i:number)=><div key={e.id||i}><span className="tiny-dot"/><div><strong>{e.message||eventNames[e.type]||eventNames[e.event]||String(e.type || 'Actividad').replaceAll('_',' ').toLowerCase()}</strong><small><DateLabel value={e.created_at||e.timestamp}/></small></div></div>)}</div>:<p className="muted small-text">Aquí aparecerán las acciones reales de tu espacio.</p>}</section></div></>}</section>;
}
