'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState, useEffect, type FormEvent } from 'react';
import { api, useLoad, items, Header, Icon, Tag, Empty, Loading, Problem, Field, Status, DateLabel, type Item, type Resource, type ApiError } from './ui';
import { Sources, DNA } from './library';
import { Planner } from './planner';
import {CreationGuide} from './CreationGuide';
import {CreativeProfiles} from './CreativeProfiles';
import {SceneBuilder} from './SceneBuilder';
import {FirmesCaballito,FirmesFrame,isFirmesTenant} from './FirmesBrand';
import {BrandStart,NewUserCallout} from './Onboarding';
export function Dashboard({ tenants, user, tenant, onboarding }: { tenants: Resource; user: Item; tenant?:Item|null; onboarding:Resource }) {
 const list = items(tenants.data), firmes=isFirmesTenant(tenant), heroTenant=list.find(t=>isFirmesTenant(t))||list[0];
 const heroFeed=useLoad(heroTenant?'/tenants/'+encodeURIComponent(heroTenant.tenant_id)+'/dashboard':null);
 return <FirmesFrame tenant={tenant}><Header eyebrow="TU ESTUDIO" title={'Hola, ' + (user.name?.split(' ')[0] || 'creador') + '.'} description="Crea, revisa y entrega sin pensar en la parte técnica." action={<Link className="button primary hero-create" href={list.length===1?'/workspace/'+list[0].tenant_id+'/free':'/workspaces'}><Icon name="spark" />Crear contenido</Link>} /><NewUserCallout state={onboarding}/><section className="hero-panel creative-hero"><div className="creative-hero-copy"><span className="hero-kicker">CREATIVE STUDIO</span><h2>Tu contenido,<br/><em>en movimiento.</em></h2><p>Tu material ocupa el centro. Las piezas recientes, las versiones para revisar y las entregas viven en un mismo estudio visual.</p><div className="hero-actions"><Link className="button light" href={list.length === 1 ? '/workspace/' + list[0].tenant_id + '/free' : '/workspaces'}>Crear ahora<Icon name="arrow" /></Link><Link className="hero-link" href="/review">Abrir revisión ↗</Link></div></div><CreativeDeck firmes={firmes} jobs={heroFeed.data?.jobs||[]}/></section><DashboardActivity tenants={list} /><div className="section-title"><h2>Tus marcas</h2><Link href="/workspaces">Ver todas ↗</Link></div>{tenants.loading ? <Loading /> : tenants.error ? <Problem error={tenants.error} retry={tenants.reload} /> : list.length ? <div className="workspace-grid">{list.map(t => <WorkspaceCard key={t.tenant_id} tenant={t} />)}</div> : user.can_create_tenants ? <Empty icon="grid" title="Dale un espacio a tu primera marca." action={<Link className="button secondary" href="/workspaces">Crear primera marca</Link>}>Reúne su material, su estilo y sus historias en un mismo lugar.</Empty> : <Empty icon="grid" title="Aún no tienes una marca asignada." action={<Link className="button secondary" href="/workspaces">Ver acceso</Link>}>Tu organización gestiona las marcas a las que puedes entrar.</Empty>}<div className="process-strip minimal-process">{[['01', 'Material', 'Tus videos y fotos'], ['02', 'Estilo', 'Cómo quieres que se sienta'], ['03', 'Crear', 'Idea → versión → entrega']].map(([n, title, text]) => <div key={n}><span>{n}</span><div><h3>{title}</h3><p>{text}</p></div></div>)}</div></FirmesFrame>;
}

function deckArtifact(job?:Item){return (job?.artifacts||[]).find((a:Item)=>a.download_url&&/^(video|image)\//.test(a.mime_type||''))}

function DeckMedia({job,slot,firmes}:{job?:Item;slot:'left'|'center'|'right';firmes:boolean}){
 const artifact=deckArtifact(job), cls='deck-card deck-card-'+slot+(artifact?' deck-card-real':'');
 const body=<>{artifact&&/video/.test(artifact.mime_type||'')?<video autoPlay muted loop playsInline preload="metadata" src={artifact.download_url}/>:artifact&&/image/.test(artifact.mime_type||'')?<img src={artifact.download_url} alt=""/>:slot==='center'&&firmes?<FirmesCaballito/>:slot==='left'?<div className="deck-orb"/>:slot==='right'?<div className="deck-wave"><i/><i/><i/></div>:<div className="deck-monogram">MF</div>}<div className="deck-caption"><span>{artifact?/video/.test(artifact.mime_type||'')?'VIDEO':'POST':slot==='right'?'STORY':'CONCEPTO'}</span><strong>{job?.title|| (slot==='center'&&firmes?'Caballito FIRMES':slot==='left'?'Una idea clara':slot==='right'?'Una misma identidad':'Historia principal')}</strong><small>{job?.status?<Status value={job.status}/>:slot==='center'?'9:16 · tu estudio':'material + dirección'}</small></div></>;
 return job?<Link className={cls} href={'/jobs/'+(job.job_id||job.id)} aria-label={'Abrir '+(job.title||'pieza reciente')}>{body}</Link>:<article className={cls} aria-hidden="true">{body}</article>;
}

function CreativeDeck({firmes,jobs}:{firmes:boolean;jobs:Item[]}) {
 const recent=[...jobs].reverse().slice(0,3), center=recent[0], left=recent[1], right=recent[2];
 return <div className="creative-deck"><div className="deck-glow"/><DeckMedia slot="left" job={left} firmes={firmes}/><DeckMedia slot="center" job={center} firmes={firmes}/><DeckMedia slot="right" job={right} firmes={firmes}/></div>;
}

function WorkspaceCard({ tenant }: { tenant: Item }) { const roles:Record<string,string>={owner:'Propietario',admin:'Administrador',editor:'Editor',reviewer:'Revisor',viewer:'Consulta'}; return <Link className="workspace-card" href={'/workspace/' + tenant.tenant_id + '/start'}><div className="workspace-card-top"><span className="workspace-monogram">{tenant.organization.slice(0, 1).toUpperCase()}</span><span aria-hidden="true">↗</span></div><h3>{tenant.organization}</h3><p>{tenant.territory || 'Tu espacio creativo'}</p><div className="card-foot"><span>{tenant.sources?.length || 0} elementos de material</span><Tag>{roles[tenant.role] || 'Miembro'}</Tag></div></Link>; }
export function Workspaces({ resource, user }: { resource: Resource; user:Item }) {
 const canCreate=user.can_create_tenants===true;
 const [open, setOpen] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState<ApiError | null>(null), router = useRouter();
 async function create(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget), payload=Object.fromEntries(f) as Record<string,FormDataEntryValue>; const organization=String(payload.organization||'').trim(); if(!String(payload.tenant_id||'').trim()) payload.tenant_id=organization.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,64)||'mi-marca'; setBusy(true); setError(null); try { const t = await api('/tenants', payload); resource.reload(); router.push('/workspace/' + t.tenant_id + '/start'); } catch (err) { setError(err as ApiError); } finally { setBusy(false); } }
 return <><Header eyebrow="UNA MARCA, UN LUGAR PARA CREAR" title="Tus marcas" description="Cada marca mantiene separado su material, su estilo, sus personajes y sus producciones." action={canCreate?<button className="primary" onClick={() => setOpen(v => !v)}>+ Nueva marca</button>:undefined} />{!canCreate&&<div className="notice tenant-access-note"><strong>Tu organización administra las marcas.</strong><p>Puedes entrar a las marcas que te hayan asignado. Crear nuevos espacios requiere autorización de administrador.</p></div>}{open && canCreate && <section className="panel form-panel tenant-create-v8"><div className="section-title"><div><p className="eyebrow">NUEVO ESPACIO DE MARCA</p><h2>Agregar una marca</h2></div><button className="text-button" onClick={() => setOpen(false)}>Cerrar</button></div><p className="tenant-create-intro">Crearemos un espacio aislado para esta marca. Su material, estilo y producciones no se mezclarán con otros espacios.</p><form onSubmit={create}><div className="form-grid"><Field label="Nombre de la marca"><input name="organization" required maxLength={160} placeholder="Nombre de tu marca" /></Field><Field label="Ciudad o región"><input name="territory" maxLength={160} placeholder="Antigua Guatemala" /></Field></div><Field label="¿Cómo se siente tu marca?"><textarea name="visual_language" rows={3} maxLength={500} placeholder="Cálida, cercana, documental…" /></Field><details className="production-options"><summary>Opciones avanzadas</summary><Field label="Identificador interno (opcional)" help="Si lo dejas vacío, lo creamos automáticamente a partir del nombre."><input name="tenant_id" pattern="[a-z0-9][a-z0-9-]{1,63}" placeholder="mi-marca" /></Field><Field label="Tipo de contenido"><select name="content_context" defaultValue="community"><option value="commercial">Comercial</option><option value="community">Comunidad</option><option value="nonprofit">Sin fines de lucro</option><option value="media">Medios</option><option value="public-affairs">Asuntos públicos</option></select></Field></details><Problem error={error} /><button className="primary" disabled={busy}>{busy ? 'Agregando…' : 'Agregar marca'}<Icon name="arrow" /></button></form></section>}{resource.loading ? <Loading /> : resource.error ? <Problem error={resource.error} retry={resource.reload} /> : items(resource.data).length ? <div className="workspace-grid">{items(resource.data).map(t => <WorkspaceCard key={t.tenant_id} tenant={t} />)}</div> : canCreate ? <Empty icon="grid" title="Tu estudio está listo para empezar." action={<button className="primary" onClick={()=>setOpen(true)}>Crear mi primera marca</button>}>Crea un espacio aislado para reunir material, estilo y producciones.</Empty> : <Empty icon="grid" title="Aún no tienes una marca asignada.">Tu cuenta está activa. Pide a la persona responsable de tu organización que te agregue a un espacio de marca.</Empty>}</>;
}
export function TenantSurface({ id, view }: { id: string; view: string }) {
 const tenant = useLoad('/tenants/' + encodeURIComponent(id));
 if (tenant.loading) return <Loading />;
 if (tenant.error) return <Problem error={tenant.error} retry={tenant.reload} />;
 if (!tenant.data) return <Empty title="No encontramos este espacio.">Vuelve a tus espacios de trabajo para continuar.</Empty>;
 let content;
 if (view === 'start') content=<BrandStart tenant={tenant.data}/>;
 else if (view === 'sources') content=<><CreationGuide id={id}/><Sources tenant={tenant.data} refresh={tenant.reload} /></>;
 else if (view === 'content-dna') content=<><CreationGuide id={id}/><DNA tenant={tenant.data} /></>;
 else if (view === 'scene') content=<SceneBuilder tenant={tenant.data}/>;
 else if (view === 'weekly' || view === 'free') content=<><CreationGuide id={id}/><Planner tenant={tenant.data} free={view === 'free'} key={id + view} /></>;
 else if(view==='creative-profiles')content=<CreativeProfiles tenant={tenant.data}/>;
 else content=<Empty title="Esta sección no existe.">Elige una sección del menú de tu espacio.</Empty>;
 return <FirmesFrame tenant={tenant.data}>{content}</FirmesFrame>;
}

function DashboardPiece({job}:{job:Item}){
 const artifacts=Array.isArray(job.artifacts)?job.artifacts:[],artifact=artifacts.find((a:Item)=>a.download_url&&/^(video|image)\//.test(a.mime_type||''));
 return <Link className="dashboard-piece media-card-3d" href={'/jobs/'+job.id}><div className={'dashboard-piece-media '+(!artifact?'media-gradient-art':'')}>{artifact&&/video/.test(artifact.mime_type||'')?<video muted playsInline preload="metadata" src={artifact.download_url}/>:artifact&&/image/.test(artifact.mime_type||'')?<img src={artifact.download_url} alt=""/>:<><i/><b/><em/><span>HISTORIA</span></>}</div><div className="dashboard-piece-copy"><strong>{job.title||'Nueva historia'}</strong><Status value={job.status}/></div></Link>
}

function DashboardActivity({tenants}:{tenants:Item[]}) {
 const [selected,setSelected]=useState('');useEffect(()=>{if(!selected&&tenants.length)setSelected(tenants[0].tenant_id)},[selected,tenants]);
 const resource=useLoad(selected?'/tenants/'+selected+'/dashboard':null);if(!tenants.length)return null;const d=resource.data,current=d?.plans?.slice().sort((a:Item,b:Item)=>String(b.created_at).localeCompare(a.created_at))[0];
 const eventNames:Record<string,string>={WORKSPACE_CREATED:'Espacio creado',SOURCE_AUTHORIZED:'Fuente autorizada',CONTENT_DNA_UPDATED:'Estilo actualizado',PLAN_DRAFT_CREATED:'Borrador guardado',PLAN_APPROVED:'Conceptos aprobados',JOB_QUEUED:'Producción solicitada',MASCOT_SOURCE_SELECTED:'Personaje de marca seleccionado'};
 return <section className="dashboard-activity"><div className="section-title"><h2>Lo que sucede en tu estudio</h2><label className="compact-select"><span className="sr-only">Espacio del resumen</span><select value={selected} onChange={e=>setSelected(e.target.value)}>{tenants.map(t=><option key={t.tenant_id} value={t.tenant_id}>{t.organization}</option>)}</select></label></div>{resource.loading?<Loading/>:resource.error?<Problem error={resource.error} retry={resource.reload}/>:d&&<><div className="studio-pulse">{[['planned','Por producir'],['producing','En producción'],['awaiting_review','Para revisar'],['released','Entregas']].map(([key,label])=><div key={key}><strong>{d[key]??0}</strong><span>{label}</span></div>)}</div>{d.jobs?.length>0&&<div className="dashboard-media-shelf">{d.jobs.slice(-4).reverse().map((j:Item)=><DashboardPiece job={j} key={j.id}/>)}</div>}{d.blockers?.length>0&&<div className="notice warning"><strong>{d.blockers.length} {d.blockers.length===1?'asunto necesita':'asuntos necesitan'} atención</strong><ul>{d.blockers.map((b:Item,i:number)=><li key={i}><Link href={'/jobs/'+b.job_id}>{b.message||b.code} →</Link></li>)}</ul></div>}<div className="dashboard-grid"><section className="panel"><p className="eyebrow">LO MÁS RECIENTE</p>{current?<><h3>Semana del <DateLabel value={current.week_of}/></h3><p className="muted small-text">{current.stories.length} historias en el plan</p><Status value={current.status}/><div className="actions"><Link className="button secondary" href={'/workspace/'+selected+'/weekly'}>Ver el plan →</Link></div></>:<><h3>Tu semana todavía está por escribir.</h3><p className="muted small-text">Crea un primer plan para ver su progreso aquí.</p></>}</section><section className="panel"><p className="eyebrow">ACTIVIDAD RECIENTE</p>{d.activity?.length?<div className="activity-list">{d.activity.slice(0,5).map((e:Item,i:number)=><div key={e.id||i}><span className="tiny-dot"/><div><strong>{e.message||eventNames[e.type]||eventNames[e.event]||String(e.type || 'Actividad').replaceAll('_',' ').toLowerCase()}</strong><small><DateLabel value={e.created_at||e.timestamp}/></small></div></div>)}</div>:<p className="muted small-text">Aquí aparecerán las acciones reales de tu espacio.</p>}</section></div></>}</section>;
}
