import {readFile,open,lstat} from 'node:fs/promises'
import {join} from 'node:path'
import {createHash,createHmac,randomBytes,randomUUID,scrypt as scryptCallback,timingSafeEqual} from 'node:crypto'
import {promisify} from 'node:util'
import {invariant,boundedText,ProductError} from './errors.mjs'
import {GoogleIdentityVerifier,readGoogleJson} from './google-identity.mjs'
import {sacatepequezMunicipalities,ensureSacatepequezTenant} from './sacatepequez-municipalities.mjs'
const scrypt=promisify(scryptCallback)
const tokenHash=token=>createHash('sha256').update(token).digest('hex')
const sessionMs=12*60*60_000
const emailKey=value=>String(value||'').trim().toLowerCase()
const normalizeDpi=value=>String(value||'').replace(/[\s-]/g,'')
const selfServicePublic=(user,state,selectedTenantId)=>({id:user.id,name:user.name,email:user.email,auth_provider:'local',account_type:'self_service',account_status:user.status,can_create_tenants:false,manage_integrations:false,current_tenant_id:selectedTenantId||null,memberships:mergeMemberships([],state.memberships[user.id]||[])})

function mergeMemberships(configured,created){const merged=new Map();for(const item of [...created,...configured])if(item&&typeof item.tenant_id==='string'&&['owner','admin','editor','reviewer','viewer'].includes(item.role))merged.set(item.tenant_id,{tenant_id:item.tenant_id,role:item.role});return [...merged.values()]}
function localPublic(user,state){return{id:user.id,name:user.name||user.email||user.username,email:user.email||user.username,auth_provider:'local',can_create_tenants:user.can_create_tenants===true,manage_integrations:user.system_admin===true,memberships:mergeMemberships(user.memberships||[],state.memberships[user.id]||[])}}
function externalPublic(user,state){return{id:user.id,name:user.name||user.email,email:user.email,auth_provider:user.provider,can_create_tenants:false,manage_integrations:false,memberships:mergeMemberships([],state.memberships[user.id]||[])}}

export class AuthService {
 constructor({repository,identityFile,operatorUsername,operatorPasswordVerifier,googleClientId,googleClientSecret,googleConfigProvider,publicOrigin,googleVerifier,googleFetch=globalThis.fetch,clock=()=>Date.now()}){this.repository=repository;this.identityFile=identityFile;this.operatorUsername=operatorUsername;this.operatorPasswordVerifier=operatorPasswordVerifier;this.clock=clock;this.attempts=new Map();this.globalAttempts={count:0,until:0};this.registrationWindow={count:0,until:0};this.activeLogins=0;this.googleClientId=googleClientId;this.googleClientSecret=googleClientSecret;this.googleConfigProvider=googleConfigProvider;this.publicOrigin=publicOrigin;this.googleFetch=googleFetch;this.googleVerifier=googleVerifier;this.dpiPepperFile=join(repository.root,'.local-account-pepper')}
 async identities(){
  if(this.identityFile){let value;try{value=JSON.parse(await readFile(this.identityFile,'utf8'))}catch{throw new ProductError('AUTH_UNAVAILABLE','Authentication configuration is unavailable',503)};invariant(Array.isArray(value.users),'AUTH_UNAVAILABLE','Authentication configuration is unavailable',503);return value.users}
  if(this.operatorUsername&&this.operatorPasswordVerifier&&/^[a-f0-9]{32}:[a-f0-9]{64}$/.test(this.operatorPasswordVerifier)){const[salt,hash]=this.operatorPasswordVerifier.split(':');return[{id:'host-operator',email:this.operatorUsername,name:'Operator',password:{salt,hash},can_create_tenants:true,system_admin:true,memberships:[]}]}
  throw new ProductError('AUTH_UNAVAILABLE','An operator must configure authentication before sign-in',503)
 }
 async dpiPepper(){
  await this.repository.init();const stat=await lstat(this.dpiPepperFile).catch(e=>e.code==='ENOENT'?null:Promise.reject(e));invariant(!stat?.isSymbolicLink(),'AUTH_UNAVAILABLE','Authentication configuration is unavailable',503)
  if(!stat){try{const fd=await open(this.dpiPepperFile,'wx',0o600);try{await fd.writeFile(randomBytes(32));await fd.sync()}finally{await fd.close()}}catch(e){if(e.code!=='EEXIST')throw e}}
  const secret=await readFile(this.dpiPepperFile);invariant(secret.length===32,'AUTH_UNAVAILABLE','Authentication configuration is unavailable',503);return secret
 }
 async dpiLookup(value){const dpi=normalizeDpi(value);invariant(/^\d{13}$/.test(dpi),'INVALID_DPI','El DPI debe contener 13 dígitos.');return createHmac('sha256',await this.dpiPepper()).update(dpi).digest('hex')}
 async hashPassword(password){invariant(typeof password==='string'&&password.length>=12&&password.length<=256,'WEAK_PASSWORD','Usa una contraseña de al menos 12 caracteres.');const salt=randomBytes(24).toString('hex'),hash=Buffer.from(await scrypt(password,Buffer.from(salt,'hex'),64,{N:16384,r:8,p:1})).toString('hex');return{salt,hash}}
 async verifyPassword(password,record){const valid=record&&/^[a-f0-9]{32,128}$/.test(record.salt)&&/^(?:[a-f0-9]{64}|[a-f0-9]{128})$/.test(record.hash),expected=valid?Buffer.from(record.hash,'hex'):Buffer.alloc(64),actual=await scrypt(typeof password==='string'?password:'',valid?Buffer.from(record.salt,'hex'):Buffer.alloc(24),expected.length,{N:16384,r:8,p:1});return Boolean(valid&&timingSafeEqual(actual,expected))}
 async municipalities(){const state=await this.repository.read();return sacatepequezMunicipalities(state)}
 async register(input){
  const now=this.clock();if(now>this.registrationWindow.until)this.registrationWindow={count:0,until:now+60*60_000};invariant(this.registrationWindow.count<50,'RATE_LIMITED','Demasiadas solicitudes de registro. Intenta de nuevo más tarde.',429);this.registrationWindow.count++
  const name=boundedText(input.name,'Nombre',160),email=emailKey(boundedText(input.email,'Correo',254)),tenantId=boundedText(input.tenant_id,'Municipio',128);invariant(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email),'INVALID_EMAIL','Escribe un correo válido.');const dpiLookup=await this.dpiLookup(input.dpi),dpi=normalizeDpi(input.dpi),password=await this.hashPassword(input.password),configured=await this.identities()
  return this.repository.transact(state=>{state.local_accounts??={};const municipalityTenant=ensureSacatepequezTenant(state,tenantId,configured);invariant(municipalityTenant,'INVALID_MUNICIPALITY','Elige un municipio disponible.');const existing=Object.values(state.local_accounts).find(u=>emailKey(u.email)===email||u.dpi_lookup===dpiLookup),configuredDuplicate=configured.some(u=>emailKey(u.email||u.username)===email);if(existing||configuredDuplicate)return{status:'REQUEST_RECEIVED',tenant_id:tenantId};const pending=Object.values(state.local_accounts).filter(u=>u.status==='PENDING_APPROVAL');invariant(pending.length<500&&pending.filter(u=>u.requested_tenant_id===tenantId).length<100,'REGISTRATION_QUEUE_FULL','Hay demasiadas solicitudes pendientes. Contacta al administrador del municipio.',429);const id='local_'+randomUUID().replaceAll('-',''),createdAt=new Date(now).toISOString(),account={id,name,email,dpi_lookup:dpiLookup,dpi_last4:dpi.slice(-4),password,status:'PENDING_APPROVAL',requested_tenant_id:tenantId,requested_at:createdAt,created_at:createdAt};state.local_accounts[id]=account;state.memberships[id]??=[];state.events.push({id:randomUUID(),tenant_id:tenantId,type:'LOCAL_ACCESS_REQUESTED',created_at:createdAt,actor_id:id,user_id:id});if(state.events.length>10000)state.events.splice(0,state.events.length-10000);return{status:'REQUEST_RECEIVED',tenant_id:tenantId}}
  )
 }
 async pendingLocalRegistrations(state,tenantId){return Object.values(state.local_accounts||{}).filter(u=>u.status==='PENDING_APPROVAL'&&u.requested_tenant_id===tenantId).map(u=>({user_id:u.id,name:u.name,email:u.email,dpi_last4:u.dpi_last4,status:u.status,requested_at:u.requested_at}))}
 async runtimeGoogleConfig(){let stored=null;if(this.googleConfigProvider)stored=await this.googleConfigProvider();const clientId=stored?.client_id||this.googleClientId,clientSecret=stored?.client_secret||this.googleClientSecret;let origin;try{origin=new URL(this.publicOrigin)}catch{}const verifier=this.googleVerifier||new GoogleIdentityVerifier({clientId,fetchImpl:this.googleFetch,clock:this.clock}),available=verifier.configured()&&typeof clientSecret==='string'&&clientSecret.length>=8&&origin?.protocol==='https:'&&!origin.username&&!origin.password&&origin.pathname==='/';return{available,clientId,clientSecret,verifier}}
 async googleConfig(){const config=await this.runtimeGoogleConfig();return{available:config.available}}
 googleRedirectUri(config){invariant(config?.available,'GOOGLE_AUTH_NOT_CONFIGURED','Google sign-in is not configured.',503);return this.publicOrigin.replace(/\/$/,'')+'/api/v1/auth/google/callback'}
 async googleStart(next='/dashboard'){invariant(['/dashboard','/onboarding','/workspaces'].includes(next),'INVALID_INPUT','Unsupported sign-in destination.');const config=await this.runtimeGoogleConfig(),redirect=this.googleRedirectUri(config),state=randomBytes(32).toString('base64url'),nonce=randomBytes(32).toString('base64url'),verifier=randomBytes(48).toString('base64url'),flowToken=randomBytes(32).toString('base64url'),challenge=createHash('sha256').update(verifier).digest('base64url'),now=this.clock(),configHash=tokenHash(config.clientId+':'+config.clientSecret);await this.repository.transact(s=>{s.oauth_states??={};for(const[key,value]of Object.entries(s.oauth_states))if(value.expires_at<=now)delete s.oauth_states[key];const active=Object.entries(s.oauth_states).sort((a,b)=>(a[1].created_at||0)-(b[1].created_at||0));while(active.length>=500){const [key]=active.shift();delete s.oauth_states[key]}s.oauth_states[tokenHash(state)]={nonce,code_verifier:verifier,flow_hash:tokenHash(flowToken),config_hash:configHash,next,created_at:now,expires_at:now+10*60_000};return null});const url=new URL('https://accounts.google.com/o/oauth2/v2/auth');for(const[k,v]of Object.entries({client_id:config.clientId,redirect_uri:redirect,response_type:'code',scope:'openid email profile',state,nonce,code_challenge:challenge,code_challenge_method:'S256',access_type:'online',prompt:'select_account'}))url.searchParams.set(k,v);return{url:url.toString(),flow_token:flowToken}}
 async createSession(state,{user_id,credential_hash,auth_provider,selected_tenant_id=null}){const now=this.clock(),token=randomBytes(32).toString('hex');for(const[id,session]of Object.entries(state.sessions))if(session.expires_at<=now)delete state.sessions[id];state.sessions[tokenHash(token)]={user_id,credential_hash,auth_provider,selected_tenant_id,expires_at:now+sessionMs};return token}
 async login(input,attemptKey='global'){
  const identifier=boundedText(input.identifier??input.email??input.username??input.dpi,'Usuario',254),identifierEmail=emailKey(identifier),password=input.password,tenantId=input.tenant_id===undefined?null:boundedText(input.tenant_id,'Municipio',128);invariant(typeof password==='string'&&password.length>0&&password.length<=1024,'INVALID_INPUT','Password is required')
  const now=this.clock();if(now>this.globalAttempts.until)this.globalAttempts={count:0,until:now+60_000};invariant(this.globalAttempts.count<100&&this.activeLogins<4,'RATE_LIMITED','Too many sign-in attempts; try again later',429);this.globalAttempts.count++;const key=String(attemptKey).slice(0,100)+':'+identifierEmail,prior=this.attempts.get(key)||{count:0,until:now+15*60_000};if(now>prior.until){prior.count=0;prior.until=now+15*60_000};invariant(prior.count<10,'RATE_LIMITED','Too many sign-in attempts; try again later',429);prior.count++;this.attempts.set(key,prior);if(this.attempts.size>1000)this.attempts.delete(this.attempts.keys().next().value)
  this.activeLogins++;try{
   const users=await this.identities(),configured=users.find(u=>emailKey(u.email??u.username)===identifierEmail&&u.disabled!==true),state=await this.repository.read();let self=null
   if(!configured){let dpiLookup=null;if(/^\d{13}$/.test(normalizeDpi(identifier)))dpiLookup=await this.dpiLookup(identifier);self=Object.values(state.local_accounts||{}).find(u=>u.disabled!==true&&(emailKey(u.email)===identifierEmail||(dpiLookup&&u.dpi_lookup===dpiLookup)))||null}
   const record=configured?.password||self?.password,valid=await this.verifyPassword(password,record);invariant(valid,'INVALID_CREDENTIALS','Invalid username or password',401);this.attempts.delete(key)
   if(self){invariant(self.status!=='PENDING_APPROVAL','ACCOUNT_PENDING_APPROVAL','Tu cuenta está pendiente de aprobación por el administrador del municipio.',403);invariant(self.status==='ACTIVE','ACCESS_NOT_APPROVED','Tu cuenta no tiene acceso activo. Contacta al administrador.',403);invariant(tenantId,'MUNICIPALITY_REQUIRED','Elige el municipio al que quieres entrar.');const membership=(state.memberships[self.id]||[]).find(m=>m.tenant_id===tenantId);invariant(membership&&(state.tenants[tenantId]||state.onboarding[tenantId]),'ACCESS_NOT_APPROVED','Tu cuenta no está autorizada para ese municipio.',403);let token,publicUser;await this.repository.transact(async latest=>{const current=latest.local_accounts?.[self.id],member=(latest.memberships[self.id]||[]).find(m=>m.tenant_id===tenantId);invariant(current?.status==='ACTIVE'&&member&&(latest.tenants[tenantId]||latest.onboarding[tenantId]),'ACCESS_NOT_APPROVED','Tu acceso cambió. Vuelve a intentarlo.',403);token=await this.createSession(latest,{user_id:self.id,credential_hash:tokenHash(record.salt+':'+record.hash),auth_provider:'local_self_service',selected_tenant_id:tenantId});publicUser=selfServicePublic(current,latest,tenantId);return null});return{token,user:publicUser}
   }
   invariant(configured,'INVALID_CREDENTIALS','Invalid username or password',401);const publicConfigured=localPublic(configured,state);if(tenantId&&!configured.system_admin)invariant(publicConfigured.memberships.some(m=>m.tenant_id===tenantId),'ACCESS_NOT_APPROVED','Tu cuenta no está autorizada para ese municipio.',403);let token,publicUser;await this.repository.transact(async latest=>{token=await this.createSession(latest,{user_id:configured.id,credential_hash:tokenHash(record.salt+':'+record.hash),auth_provider:'local',selected_tenant_id:tenantId});publicUser={...localPublic(configured,latest),current_tenant_id:tenantId};return null});return{token,user:publicUser}
  }finally{this.activeLogins--}
 }
 async completeGoogleIdentity(claims){
  const now=this.clock();let token,publicUser,firstAdmission=false
  await this.repository.transact(async state=>{
   state.external_users??={};state.invitations??={};state.oauth_states??={}
   for(const invite of Object.values(state.invitations))if(invite.status==='PENDING'&&invite.expires_at<=now)invite.status='EXPIRED'
   let user=Object.values(state.external_users).find(u=>u.provider==='google'&&u.provider_subject===claims.subject)
   const pending=Object.values(state.invitations).filter(i=>i.status==='PENDING'&&i.expires_at>now&&emailKey(i.email)===claims.email&&['admin','reviewer','editor','viewer'].includes(i.role)&&(state.tenants[i.tenant_id]||state.onboarding[i.tenant_id]))
   invariant(user||pending.length>0,'ACCESS_NOT_INVITED','Tu cuenta de Google es válida, pero todavía no tiene una invitación a Media Factory.',403)
   if(!user){firstAdmission=true;const id='google_'+tokenHash(claims.subject).slice(0,24);user={id,provider:'google',provider_subject:claims.subject,email:claims.email,name:claims.name,hosted_domain:claims.hosted_domain,created_at:new Date(now).toISOString(),last_login_at:new Date(now).toISOString()};state.external_users[id]=user}else{user.email=claims.email;user.name=claims.name;user.hosted_domain=claims.hosted_domain;user.last_login_at=new Date(now).toISOString()}
   state.memberships[user.id]??=[]
   for(const invite of pending){const existing=state.memberships[user.id].find(m=>m.tenant_id===invite.tenant_id);if(!existing)state.memberships[user.id].push({tenant_id:invite.tenant_id,role:invite.role});invite.status='ACCEPTED';invite.accepted_by=user.id;invite.accepted_at=new Date(now).toISOString();state.events.push({id:randomUUID(),tenant_id:invite.tenant_id,type:'TEAM_INVITATION_ACCEPTED',created_at:new Date(now).toISOString(),actor_id:user.id,invitation_id:invite.id,role:existing?.role||invite.role,membership_created:!existing});if(state.events.length>10000)state.events.splice(0,state.events.length-10000)}
   invariant(state.memberships[user.id].some(m=>['owner','admin','reviewer','editor','viewer'].includes(m.role)&&(state.tenants[m.tenant_id]||state.onboarding[m.tenant_id])),'ACCESS_NOT_INVITED','Tu cuenta todavía no tiene acceso a una marca.',403)
   token=await this.createSession(state,{user_id:user.id,credential_hash:tokenHash('google:'+user.provider_subject),auth_provider:'google'});publicUser=externalPublic(user,state);return null
  })
  return{token,user:publicUser,first_admission:firstAdmission}
 }
 async googleCallback({state,code,error,flow_token}){
  invariant(!error,'GOOGLE_AUTH_DENIED','Google sign-in was cancelled or denied.',401);state=boundedText(state,'OAuth state',512);code=boundedText(code,'Authorization code',4096);flow_token=boundedText(flow_token,'OAuth flow',512);const key=tokenHash(state),now=this.clock(),oauth=await this.repository.transact(s=>{s.oauth_states??={};const value=s.oauth_states[key];invariant(value&&value.expires_at>now&&typeof value.flow_hash==='string'&&/^[a-f0-9]{64}$/.test(value.flow_hash)&&timingSafeEqual(Buffer.from(value.flow_hash,'hex'),Buffer.from(tokenHash(flow_token),'hex')),'GOOGLE_AUTH_STATE_INVALID','Google sign-in session expired, was already used, or belongs to another browser.',401);delete s.oauth_states[key];return value}),config=await this.runtimeGoogleConfig();invariant(config.available&&oauth.config_hash===tokenHash(config.clientId+':'+config.clientSecret),'GOOGLE_AUTH_CONFIG_CHANGED','La configuración de Google cambió durante el acceso. Intenta entrar de nuevo.',409);const redirect_uri=this.googleRedirectUri(config),body=new URLSearchParams({client_id:config.clientId,client_secret:config.clientSecret,code,code_verifier:oauth.code_verifier,grant_type:'authorization_code',redirect_uri});let response;try{response=await this.googleFetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','Accept':'application/json'},body:body.toString(),signal:AbortSignal.timeout(10_000),redirect:'error'})}catch{throw new ProductError('GOOGLE_AUTH_UNAVAILABLE','Google sign-in is temporarily unavailable.',503)}invariant(response.ok,'GOOGLE_AUTH_FAILED','Google could not complete sign-in.',401);const tokens=await readGoogleJson(response,128*1024,'GOOGLE_AUTH_FAILED','Google sign-in response is invalid or unexpectedly large.');invariant(tokens&&typeof tokens==='object'&&!Array.isArray(tokens),'GOOGLE_AUTH_FAILED','Google sign-in response is invalid.',401);const claims=await config.verifier.verify(tokens.id_token,{nonce:oauth.nonce}),result=await this.completeGoogleIdentity(claims);return{...result,next:result.first_admission?'/onboarding':oauth.next}
 }
 async resolve(token,snapshot){
  invariant(typeof token==='string'&&/^[a-f0-9]{64}$/.test(token),'UNAUTHENTICATED','Sign in to continue',401)
  const state=snapshot||await this.repository.read(),session=state.sessions[tokenHash(token)]
  invariant(session&&session.expires_at>this.clock(),'UNAUTHENTICATED','Session expired; sign in again',401)
  if(session.auth_provider==='google'){const external=state.external_users?.[session.user_id];invariant(external&&external.provider==='google'&&session.credential_hash===tokenHash('google:'+external.provider_subject),'UNAUTHENTICATED','Session expired; sign in again',401);return externalPublic(external,state)}
  if(session.auth_provider==='local_self_service'){const local=state.local_accounts?.[session.user_id];invariant(local&&local.status==='ACTIVE'&&local.disabled!==true&&session.credential_hash===tokenHash(local.password.salt+':'+local.password.hash),'UNAUTHENTICATED','Session expired; sign in again',401);if(session.selected_tenant_id)invariant((state.memberships[local.id]||[]).some(m=>m.tenant_id===session.selected_tenant_id),'UNAUTHENTICATED','Session expired; sign in again',401);return selfServicePublic(local,state,session.selected_tenant_id)}
  const users=await this.identities(),local=users.find(u=>u.id===session.user_id&&u.disabled!==true)
  invariant(local?.password&&session.credential_hash===tokenHash(local.password.salt+':'+local.password.hash),'UNAUTHENTICATED','Session expired; sign in again',401)
  return localPublic(local,state)
 }
 async logout(token){if(typeof token==='string')await this.repository.transact(s=>{delete s.sessions[tokenHash(token)];return null})}
}
