import {readFile} from 'node:fs/promises'
import {createHash,randomBytes,randomUUID,scrypt as scryptCallback,timingSafeEqual} from 'node:crypto'
import {promisify} from 'node:util'
import {invariant,boundedText,ProductError} from './errors.mjs'
import {GoogleIdentityVerifier} from './google-identity.mjs'
const scrypt=promisify(scryptCallback)
const tokenHash=token=>createHash('sha256').update(token).digest('hex')
const sessionMs=12*60*60_000
const emailKey=value=>String(value||'').trim().toLowerCase()

function mergeMemberships(configured,created){const merged=new Map();for(const item of [...created,...configured])if(item&&typeof item.tenant_id==='string'&&['owner','admin','editor','reviewer','viewer'].includes(item.role))merged.set(item.tenant_id,{tenant_id:item.tenant_id,role:item.role});return [...merged.values()]}
function localPublic(user,state){return{id:user.id,name:user.name||user.email||user.username,email:user.email||user.username,auth_provider:'local',can_create_tenants:user.can_create_tenants===true,manage_integrations:user.system_admin===true,memberships:mergeMemberships(user.memberships||[],state.memberships[user.id]||[])}}
function externalPublic(user,state){return{id:user.id,name:user.name||user.email,email:user.email,auth_provider:user.provider,can_create_tenants:false,manage_integrations:false,memberships:mergeMemberships([],state.memberships[user.id]||[])}}

export class AuthService {
 constructor({repository,identityFile,operatorUsername,operatorPasswordVerifier,googleClientId,googleClientSecret,googleConfigProvider,publicOrigin,googleVerifier,googleFetch=globalThis.fetch,clock=()=>Date.now()}){this.repository=repository;this.identityFile=identityFile;this.operatorUsername=operatorUsername;this.operatorPasswordVerifier=operatorPasswordVerifier;this.clock=clock;this.attempts=new Map();this.globalAttempts={count:0,until:0};this.activeLogins=0;this.googleClientId=googleClientId;this.googleClientSecret=googleClientSecret;this.googleConfigProvider=googleConfigProvider;this.publicOrigin=publicOrigin;this.googleFetch=googleFetch;this.googleVerifier=googleVerifier}
 async identities(){
  if(this.identityFile){let value;try{value=JSON.parse(await readFile(this.identityFile,'utf8'))}catch{throw new ProductError('AUTH_UNAVAILABLE','Authentication configuration is unavailable',503)};invariant(Array.isArray(value.users),'AUTH_UNAVAILABLE','Authentication configuration is unavailable',503);return value.users}
  if(this.operatorUsername&&this.operatorPasswordVerifier&&/^[a-f0-9]{32}:[a-f0-9]{64}$/.test(this.operatorPasswordVerifier)){const[salt,hash]=this.operatorPasswordVerifier.split(':');return[{id:'host-operator',email:this.operatorUsername,name:'Operator',password:{salt,hash},can_create_tenants:true,system_admin:true,memberships:[]}]}
  throw new ProductError('AUTH_UNAVAILABLE','An operator must configure authentication before sign-in',503)
 }
 async runtimeGoogleConfig(){let stored=null;if(this.googleConfigProvider)stored=await this.googleConfigProvider();const clientId=stored?.client_id||this.googleClientId,clientSecret=stored?.client_secret||this.googleClientSecret;let origin;try{origin=new URL(this.publicOrigin)}catch{}const verifier=this.googleVerifier||new GoogleIdentityVerifier({clientId,fetchImpl:this.googleFetch,clock:this.clock}),available=verifier.configured()&&typeof clientSecret==='string'&&clientSecret.length>=8&&origin?.protocol==='https:'&&!origin.username&&!origin.password&&origin.pathname==='/';return{available,clientId,clientSecret,verifier}}
 async googleConfig(){const config=await this.runtimeGoogleConfig();return{available:config.available}}
 googleRedirectUri(config){invariant(config?.available,'GOOGLE_AUTH_NOT_CONFIGURED','Google sign-in is not configured.',503);return this.publicOrigin.replace(/\/$/,'')+'/api/v1/auth/google/callback'}
 async googleStart(next='/dashboard'){invariant(['/dashboard','/onboarding','/workspaces'].includes(next),'INVALID_INPUT','Unsupported sign-in destination.');const config=await this.runtimeGoogleConfig(),redirect=this.googleRedirectUri(config),state=randomBytes(32).toString('base64url'),nonce=randomBytes(32).toString('base64url'),verifier=randomBytes(48).toString('base64url'),flowToken=randomBytes(32).toString('base64url'),challenge=createHash('sha256').update(verifier).digest('base64url'),now=this.clock(),configHash=tokenHash(config.clientId+':'+config.clientSecret);await this.repository.transact(s=>{s.oauth_states??={};for(const[key,value]of Object.entries(s.oauth_states))if(value.expires_at<=now)delete s.oauth_states[key];const active=Object.entries(s.oauth_states).sort((a,b)=>(a[1].created_at||0)-(b[1].created_at||0));while(active.length>=500){const [key]=active.shift();delete s.oauth_states[key]}s.oauth_states[tokenHash(state)]={nonce,code_verifier:verifier,flow_hash:tokenHash(flowToken),config_hash:configHash,next,created_at:now,expires_at:now+10*60_000};return null});const url=new URL('https://accounts.google.com/o/oauth2/v2/auth');for(const[k,v]of Object.entries({client_id:config.clientId,redirect_uri:redirect,response_type:'code',scope:'openid email profile',state,nonce,code_challenge:challenge,code_challenge_method:'S256',access_type:'online',prompt:'select_account'}))url.searchParams.set(k,v);return{url:url.toString(),flow_token:flowToken}}
 async createSession(state,{user_id,credential_hash,auth_provider}){const now=this.clock(),token=randomBytes(32).toString('hex');for(const[id,session]of Object.entries(state.sessions))if(session.expires_at<=now)delete state.sessions[id];state.sessions[tokenHash(token)]={user_id,credential_hash,auth_provider,expires_at:now+sessionMs};return token}
 async login(input,attemptKey='global'){
  const identifier=boundedText(input.email??input.username,'Username',254).toLowerCase(),password=input.password;invariant(typeof password==='string'&&password.length>0&&password.length<=1024,'INVALID_INPUT','Password is required')
  const now=this.clock();if(now>this.globalAttempts.until)this.globalAttempts={count:0,until:now+60_000};invariant(this.globalAttempts.count<100&&this.activeLogins<4,'RATE_LIMITED','Too many sign-in attempts; try again later',429);this.globalAttempts.count++;const key=String(attemptKey).slice(0,100)+':'+identifier,prior=this.attempts.get(key)||{count:0,until:now+15*60_000};if(now>prior.until){prior.count=0;prior.until=now+15*60_000};invariant(prior.count<10,'RATE_LIMITED','Too many sign-in attempts; try again later',429);prior.count++;this.attempts.set(key,prior);if(this.attempts.size>1000)this.attempts.delete(this.attempts.keys().next().value)
  this.activeLogins++;try{
   const users=await this.identities(),user=users.find(u=>String(u.email??u.username).toLowerCase()===identifier&&u.disabled!==true),record=user?.password,validRecord=record&&/^[a-f0-9]{32,128}$/.test(record.salt)&&/^(?:[a-f0-9]{64}|[a-f0-9]{128})$/.test(record.hash),expected=validRecord?Buffer.from(record.hash,'hex'):Buffer.alloc(64),actual=await scrypt(password,validRecord?Buffer.from(record.salt,'hex'):Buffer.alloc(24),expected.length,{N:16384,r:8,p:1});invariant(validRecord&&timingSafeEqual(actual,expected),'INVALID_CREDENTIALS','Invalid username or password',401);this.attempts.delete(key)
   let token,publicUser;await this.repository.transact(async state=>{token=await this.createSession(state,{user_id:user.id,credential_hash:tokenHash(record.salt+':'+record.hash),auth_provider:'local'});publicUser=localPublic(user,state);return null});return{token,user:publicUser}
  }finally{this.activeLogins--}
 }
 async completeGoogleIdentity(claims){
  const now=this.clock();let token,publicUser,firstAdmission=false
  await this.repository.transact(async state=>{
   state.external_users??={};state.invitations??={};state.oauth_states??={}
   for(const invite of Object.values(state.invitations))if(invite.status==='PENDING'&&invite.expires_at<=now)invite.status='EXPIRED'
   let user=Object.values(state.external_users).find(u=>u.provider==='google'&&u.provider_subject===claims.subject)
   const pending=Object.values(state.invitations).filter(i=>i.status==='PENDING'&&i.expires_at>now&&emailKey(i.email)===claims.email)
   invariant(user||pending.length>0,'ACCESS_NOT_INVITED','Tu cuenta de Google es válida, pero todavía no tiene una invitación a Media Factory.',403)
   if(!user){firstAdmission=true;const id='google_'+tokenHash(claims.subject).slice(0,24);user={id,provider:'google',provider_subject:claims.subject,email:claims.email,name:claims.name,hosted_domain:claims.hosted_domain,created_at:new Date(now).toISOString(),last_login_at:new Date(now).toISOString()};state.external_users[id]=user}else{user.email=claims.email;user.name=claims.name;user.hosted_domain=claims.hosted_domain;user.last_login_at=new Date(now).toISOString()}
   state.memberships[user.id]??=[]
   for(const invite of pending){const existing=state.memberships[user.id].find(m=>m.tenant_id===invite.tenant_id);if(!existing)state.memberships[user.id].push({tenant_id:invite.tenant_id,role:invite.role});else if(existing.role!=='owner')existing.role=invite.role;invite.status='ACCEPTED';invite.accepted_by=user.id;invite.accepted_at=new Date(now).toISOString();state.events.push({id:randomUUID(),tenant_id:invite.tenant_id,type:'TEAM_INVITATION_ACCEPTED',created_at:new Date(now).toISOString(),actor_id:user.id,invitation_id:invite.id,role:invite.role});if(state.events.length>10000)state.events.splice(0,state.events.length-10000)}
   invariant(state.memberships[user.id].length>0,'ACCESS_NOT_INVITED','Tu cuenta todavía no tiene acceso a una marca.',403)
   token=await this.createSession(state,{user_id:user.id,credential_hash:tokenHash('google:'+user.provider_subject),auth_provider:'google'});publicUser=externalPublic(user,state);return null
  })
  return{token,user:publicUser,first_admission:firstAdmission}
 }
 async googleCallback({state,code,error,flow_token}){
  invariant(!error,'GOOGLE_AUTH_DENIED','Google sign-in was cancelled or denied.',401);state=boundedText(state,'OAuth state',512);code=boundedText(code,'Authorization code',4096);flow_token=boundedText(flow_token,'OAuth flow',512);const key=tokenHash(state),now=this.clock(),oauth=await this.repository.transact(s=>{s.oauth_states??={};const value=s.oauth_states[key];invariant(value&&value.expires_at>now&&typeof value.flow_hash==='string'&&/^[a-f0-9]{64}$/.test(value.flow_hash)&&timingSafeEqual(Buffer.from(value.flow_hash,'hex'),Buffer.from(tokenHash(flow_token),'hex')),'GOOGLE_AUTH_STATE_INVALID','Google sign-in session expired, was already used, or belongs to another browser.',401);delete s.oauth_states[key];return value}),config=await this.runtimeGoogleConfig();invariant(config.available&&oauth.config_hash===tokenHash(config.clientId+':'+config.clientSecret),'GOOGLE_AUTH_CONFIG_CHANGED','La configuración de Google cambió durante el acceso. Intenta entrar de nuevo.',409);const redirect_uri=this.googleRedirectUri(config),body=new URLSearchParams({client_id:config.clientId,client_secret:config.clientSecret,code,code_verifier:oauth.code_verifier,grant_type:'authorization_code',redirect_uri});let response;try{response=await this.googleFetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','Accept':'application/json'},body:body.toString(),signal:AbortSignal.timeout(10_000),redirect:'error'})}catch{throw new ProductError('GOOGLE_AUTH_UNAVAILABLE','Google sign-in is temporarily unavailable.',503)}invariant(response.ok,'GOOGLE_AUTH_FAILED','Google could not complete sign-in.',401);const text=await response.text();invariant(Buffer.byteLength(text)<=128*1024,'GOOGLE_AUTH_FAILED','Google sign-in response is unexpectedly large.',401);let tokens;try{tokens=JSON.parse(text)}catch{throw new ProductError('GOOGLE_AUTH_FAILED','Google sign-in response is invalid.',401)}const claims=await config.verifier.verify(tokens.id_token,{nonce:oauth.nonce}),result=await this.completeGoogleIdentity(claims);return{...result,next:result.first_admission?'/onboarding':oauth.next}
 }
 async resolve(token){
  invariant(typeof token==='string'&&/^[a-f0-9]{64}$/.test(token),'UNAUTHENTICATED','Sign in to continue',401);const state=await this.repository.read(),session=state.sessions[tokenHash(token)];invariant(session&&session.expires_at>this.clock(),'UNAUTHENTICATED','Session expired; sign in again',401)
  const users=await this.identities(),local=users.find(u=>u.id===session.user_id&&u.disabled!==true)
  if(local){invariant(session.credential_hash===tokenHash(local.password.salt+':'+local.password.hash),'UNAUTHENTICATED','Session expired; sign in again',401);return localPublic(local,state)}
  const external=state.external_users?.[session.user_id];invariant(external&&external.provider==='google'&&session.auth_provider==='google'&&session.credential_hash===tokenHash('google:'+external.provider_subject),'UNAUTHENTICATED','Session expired; sign in again',401);return externalPublic(external,state)
 }
 async logout(token){if(typeof token==='string')await this.repository.transact(s=>{delete s.sessions[tokenHash(token)];return null})}
}
