import { readFileSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { isIP } from 'node:net'
import { resolve } from 'node:path'
import Ajv from 'ajv/dist/2020.js'
import addFormats from 'ajv-formats'
import { validateTenantMediaProfile } from '../plugins/media-tenant-profile.mjs'
import { authorizeBrowserSource, resolveBrowserPolicy } from '../plugins/media-browser-policy.mjs'
import { ProductError, invariant, boundedText } from './errors.mjs'
const ajv = new Ajv({ strict: true, allErrors: true }); addFormats(ajv)
const schemas = Object.fromEntries(['tenant-media-profile','content-dna','reference-observation'].map(name => [name, ajv.compile(JSON.parse(readFileSync(resolve(process.cwd(), 'schemas', name + '.schema.json'), 'utf8')))]))
export function validateSchema(name, input) { invariant(schemas[name](input), 'INVALID_CONTRACT', 'The ' + name + ' contract is invalid'); rejectSecretMaterial(input); return input }
export function validateProfile(profile) { validateSchema('tenant-media-profile', profile); for (const source of profile.sources) validatePublicLocator(source.locator); try{return validateTenantMediaProfile(profile)}catch(error){if(error?.name==='TenantMediaProfileError'||error?.name==='MediaBrowserPolicyError')throw new ProductError('INVALID_CONTRACT',error.message);throw error} }
export function validatePublicLocator(value) {
  let url; try { url = new URL(value) } catch { invariant(false, 'INVALID_SOURCE', 'Source must be a public HTTP(S) URL') }
  const host = url.hostname.toLowerCase().replace(/^\[|\]$/g, '').replace(/\.$/,'')
  invariant(['https:','http:'].includes(url.protocol) && !url.username && !url.password && !['9222','9223'].includes(url.port), 'INVALID_SOURCE', 'Source must be a public URL without browser credentials')
  invariant(!/(^|\.)(localhost|local|internal|test|invalid)$/.test(host) && !host.endsWith('.local') && (host.includes('.')||isIP(host)) && !host.includes('devtools') && !url.pathname.includes('/devtools/'), 'INVALID_SOURCE', 'Private and browser debugging locators are unavailable')
  if (isIP(host) === 4) { const [a,b] = host.split('.').map(Number); invariant(!(a === 0 || a === 10 || a === 127 || a >= 224 || (a === 169 && b === 254) || (a === 172 && b >= 16 && b <= 31) || (a === 192 && [0,168].includes(b)) || (a === 100 && b >= 64 && b <= 127) || a === 198), 'INVALID_SOURCE', 'Private and reserved source addresses are unavailable') }
  if (isIP(host) === 6) invariant(!(/^(::|fc|fd|ff|fe[89ab]|2001:db8)/i.test(host) || host.includes('.')), 'INVALID_SOURCE', 'Private and reserved source addresses are unavailable')
  for (const key of url.searchParams.keys()) invariant(!/token|auth|secret|password|cookie|credential|signature|session|api.?key|x-amz|x-goog/i.test(key), 'INVALID_SOURCE', 'Credential-bearing source URLs cannot be saved')
  invariant(value.length <= 2048, 'INVALID_SOURCE', 'Source URL is too long'); return url.href
}
export function rejectSecretMaterial(value) { if (typeof value === 'string') { invariant(!/(?:wss?:\/\/[^\s]+\/devtools|bearer\s+[a-z0-9._-]{12,}|(?:cookie|password|access[_-]?token|authorization|session[_-]?id)\s*[:=]\s*\S+)/i.test(value), 'SECRET_MATERIAL', 'Do not include credentials or browser session material'); return } if (value && typeof value === 'object') for (const [key, child] of Object.entries(value)) { invariant(!/^(password|cookie|cookies|token|accessToken|secret|credentials|storageState|websocketDebuggerUrl)$/i.test(key), 'SECRET_MATERIAL', 'Do not include credentials or browser session material'); rejectSecretMaterial(child) } }
export function validateObservation(observation, tenant) { validateSchema('reference-observation', observation); invariant(observation.tenant_id === tenant.tenant_id, 'TENANT_MISMATCH', 'Observation must belong to the selected workspace'); const source = tenant.sources.find(s => s.id === observation.authorization_id && s.purpose === 'reference'); invariant(source, 'REFERENCE_REQUIRED', 'Observation requires an authorized reference source'); validatePublicLocator(observation.locator); try{authorizeBrowserSource({ locator:observation.locator, authorization:source, operation:'discover-authorized-page' }, resolveBrowserPolicy({failClosed:true,readOnly:true}))}catch(error){if(error?.name==='MediaBrowserPolicyError')throw new ProductError('INVALID_CONTRACT',error.message);throw error}; return observation }
const devices = {'brand-made-by-hand':'participatory-brand-reveal','mascot-character':'recurring-character-bridge','walking-observation':'movement-led-place-context','community-activity':'activity-first-story','place-detail':'place-as-character','human-closeup':'human-scale-intimacy','object-closeup':'detail-led-context','documentary-footage':'documentary-grounding','stylized-animation':'clearly-stylized-augmentation','ambient-sound':'ambient-sound-presence','minimal-on-screen-text':'low-text-visual-storytelling'}
export function deriveDNA(tenant, observations) { invariant(Array.isArray(observations) && observations.length > 0 && observations.length <= 100, 'REFERENCE_REQUIRED', 'Provide one or more evidence-backed reference observations'); observations.forEach(o => validateObservation(o,tenant)); invariant(new Set(observations.map(o => o.id)).size === observations.length, 'INVALID_CONTRACT', 'Observation IDs must be unique'); const dna = {schema_version:'content-dna.v1',tenant_id:tenant.tenant_id,source_observation_ids:observations.map(o=>o.id),story_devices:[...new Set(observations.flatMap(o=>o.observed_elements.map(e=>devices[e])))],pacing_profile:[...new Set(observations.map(o=>o.pacing))],branding_profile:[...new Set(observations.map(o=>o.branding))],audience_mode:'general-audience',copying_policy:{direct_text_reuse:false,shot_for_shot_copying:false,source_audio_reuse:false}}; validateSchema('content-dna',dna); return {...dna,revision:contentHash({dna,observations})} }
export function canonical(value) { if (Array.isArray(value)) return value.map(canonical); if (value && typeof value === 'object') return Object.fromEntries(Object.keys(value).sort().map(k => [k,canonical(value[k])])); return value }
export function contentHash(value) { return createHash('sha256').update(JSON.stringify(canonical(value))).digest('hex') }
export function publicTenant(tenant, role) { const {runtime_namespace,browser_context_ref,...visible} = tenant; return {...visible,role,setup_status:tenant.sources.length ? 'READY' : 'SOURCE_REQUIRED'} }
export function monday(value) { invariant(typeof value === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(value), 'INVALID_WEEK', 'Select a Monday'); const day = new Date(value+'T00:00:00Z'); invariant(!Number.isNaN(day.valueOf()) && day.toISOString().slice(0,10) === value && day.getUTCDay() === 1, 'INVALID_WEEK', 'Production week must begin on a Monday'); return value }
export function assertAudienceSafe(text) { boundedText(text,'Creative request',4000); rejectSecretMaterial(text); invariant(!/(microtarget|micro.segment|voter profil|perfil.*votant|(?:target|segment|persuad|dirig|enfoc|convenc).*(?:voter|votant|elector|relig|catholic|cat[oó]lic|muslim|jud[ií]|etni|ethnic|raza|racial|salud|elderly|ancian|mujer|women|undecided)|(?:voter|votant).*(?:relig|etni|raza|salud))/i.test(text), 'AUDIENCE_POLICY', 'Only general-audience production without voter profiling or sensitive-trait targeting is supported') }
