import {randomUUID} from 'node:crypto'
import {IntegrationVault} from './integration-vault.mjs'
import {fields,invariant,safeId,boundedText} from './errors.mjs'
import {validatePublicLocator,rejectSecretMaterial,assertAudienceSafe,contentHash} from './contracts.mjs'
const editable=['owner','admin','editor'];const active=new Set(['QUEUED','RUNNING','PRODUCING','VALIDATING','REPAIRING'])
export function profileSnapshot(state,tenantId,id,kind){if(!id)return null;safeId(id,'Perfil');const p=state.creative_profiles?.[tenantId]?.[id];invariant(p&&p.kind===kind,'PROFILE_REQUIRED','Selecciona un perfil de este espacio.',409);return structuredClone(p)}
export function creationSupport({repository,providers,auth,context}){
 const vault=new IntegrationVault(repository.root)
 const admin=async token=>{const actor=await auth.resolve(token);invariant(actor.manage_integrations===true,'FORBIDDEN','Solo el administrador del sistema puede gestionar las APIs.',403);return actor}
 return {
  async integrations(token){await admin(token);const stored=await vault.summary();return {providers:providers.list().filter(p=>p.id!=='deterministic-test').map(p=>({id:p.id,name:p.name,strategies:p.strategies,adapter_available:p.available,credential_required:p.id!=='ffmpeg',connection_status:p.id==='ffmpeg'?'LOCAL':'NOT_CHECKED',...(stored.providers[p.id]||{key_configured:false,budget_reference:null})})),audit:stored.audit}},
  async updateIntegration(token,id,input){await admin(token);fields(input,['api_key','remove_key','budget_reference']);invariant(providers.list().some(p=>p.id===id&&p.id!=='deterministic-test'&&p.id!=='ffmpeg'),'INVALID_PROVIDER','Selecciona una integración externa conocida.');invariant(input.remove_key===undefined||typeof input.remove_key==='boolean','INVALID_INPUT','La acción de credencial no es válida.');invariant(!(input.remove_key&&input.api_key),'INVALID_INPUT','Elige guardar o retirar la clave.');if(input.api_key!==undefined)invariant(typeof input.api_key==='string'&&input.api_key.length>=8&&input.api_key.length<=4096&&Buffer.byteLength(input.api_key,'utf8')<=4096&&!/[\r\n\0]/.test(input.api_key),'INVALID_INPUT','Introduce una clave válida de entre 8 y 4096 caracteres.');if(input.budget_reference!==undefined&&input.budget_reference!==null)invariant(typeof input.budget_reference==='number'&&Number.isFinite(input.budget_reference)&&input.budget_reference>=0&&input.budget_reference<=100000,'INVALID_INPUT','Introduce un presupuesto de referencia válido.');await vault.set(id,input,()=>admin(token));return {saved:true,provider:id,message:'Configuración guardada. Esto no activa un adaptador ni autoriza consumo.'}},
  async creativeProfiles(token,id){await context(token,id);return Object.values((await repository.read()).creative_profiles?.[id]||{})},
  async saveCreativeProfile(token,id,input){const {user}=await context(token,id,editable);fields(input,['id','kind','name','description','reference_url','facts','rights_confirmed','source_id','principal']);invariant(['character','place'].includes(input.kind),'INVALID_INPUT','Elige personaje o lugar.');const name=boundedText(input.name,'Nombre',120),description=boundedText(input.description,'Descripción',1800);assertAudienceSafe(name+' '+description);const reference_url=validatePublicLocator(input.reference_url);const facts=input.facts?boundedText(input.facts,'Datos de referencia',2500):'';rejectSecretMaterial(facts);invariant(input.rights_confirmed===true,'AUTHORIZATION_REQUIRED','Confirma que puedes utilizar la referencia con este propósito.');if(input.id)safeId(input.id);if(input.source_id)safeId(input.source_id);invariant(input.principal===undefined||typeof input.principal==='boolean','INVALID_INPUT','Selección de personaje principal no válida.');return repository.transact(state=>{const tenant=state.tenants[id]||state.onboarding[id];invariant(tenant,'NOT_FOUND','No se encontró el espacio.',404);state.creative_profiles??={};state.creative_profiles[id]??={};const prior=input.id?state.creative_profiles[id][input.id]:null;if(input.id)invariant(prior&&prior.kind===input.kind,'NOT_FOUND','No se encontró el perfil.',404);if(input.source_id)invariant(tenant.sources.some(s=>s.id===input.source_id&&s.purpose==='source'),'SOURCE_REQUIRED','Elige material de producción autorizado de este espacio.');const value={id:input.id||'profile_'+randomUUID(),kind:input.kind,name,description,reference_url,facts,rights_confirmed:true,source_id:input.source_id||null,principal:input.kind==='character'&&input.principal===true,revision:(prior?.revision||0)+1,created_by:prior?.created_by||user.id,updated_by:user.id,updated_at:new Date().toISOString(),information_status:input.kind==='place'?'USER_SOURCED_NOT_INDEPENDENTLY_VERIFIED':'AUTHORIZED_FICTIONAL_REFERENCE'};value.content_sha=contentHash(value);if(value.principal)for(const p of Object.values(state.creative_profiles[id]))if(p.kind==='character'&&p.principal){p.principal=false;p.revision++;p.updated_at=value.updated_at;p.updated_by=user.id;delete p.content_sha;p.content_sha=contentHash(p)}state.creative_profiles[id][value.id]=value;state.events.push({id:randomUUID(),tenant_id:id,type:'CREATIVE_PROFILE_SAVED',profile_id:value.id,actor_id:user.id,created_at:value.updated_at});return value})},
  async journey(token,id){await context(token,id);const s=await repository.read();const tenant=s.tenants[id]||s.onboarding[id];invariant(tenant,'NOT_FOUND','No se encontró el espacio.',404);const sources=tenant.sources.filter(x=>x.purpose==='source'),uploaded=sources.filter(x=>s.source_assets?.[id]?.[x.id]);const plans=Object.values(s.plans).filter(p=>p.tenant_id===id),jobs=Object.values(s.jobs).filter(j=>j.tenant_id===id);const latest=plans.slice().sort((a,b)=>b.created_at.localeCompare(a.created_at))[0];const base='/workspace/'+id;let next={label:jobs.length?'Crear otra historia':'Crear mi primera historia',href:base+'/weekly',reason:'Tu material y tu identidad están listos.'};if(!sources.length)next={label:'Agregar material',href:base+'/sources',reason:'Primero registra una fuente que puedas utilizar.'};else if(!uploaded.length)next={label:'Subir mi video',href:base+'/sources',reason:'El enlace está registrado; falta subir el video para producir.'};else if(!s.dna[id])next={label:'Construir mi identidad',href:base+'/content-dna',reason:'Observa una referencia para obtener recursos narrativos.'};else if(latest?.status==='DRAFT')next={label:'Revisar y aprobar mi plan',href:base+'/weekly?plan='+encodeURIComponent(latest.id),reason:'Tienes un borrador guardado. La producción aún no se ha solicitado.'};else if(latest?.status==='APPROVED')next={label:'Solicitar producción',href:base+'/weekly?plan='+encodeURIComponent(latest.id),reason:'Los conceptos están aprobados; falta solicitar los trabajos.'};const attention=jobs.find(j=>j.review_state==='AWAITING_REVIEW')||jobs.find(j=>j.status==='BLOCKED');if(attention)next={label:attention.status==='BLOCKED'?'Resolver bloqueo':'Revisar esta versión',href:'/jobs/'+attention.id,reason:attention.status==='BLOCKED'?'Esta historia necesita un recurso o una integración.':'La producción espera una decisión sobre su versión actual.'};return {sources:sources.length,uploaded:uploaded.length,dna_ready:Boolean(s.dna[id]),drafts:plans.filter(p=>p.status==='DRAFT').length,requested:jobs.length,active:jobs.filter(j=>active.has(j.status)).length,awaiting_review:jobs.filter(j=>j.review_state==='AWAITING_REVIEW').length,blocked:jobs.filter(j=>j.status==='BLOCKED').length,released:jobs.filter(j=>j.status==='RELEASED').length,next,observed_at:new Date().toISOString(),recent_jobs:jobs.slice(-5).reverse().map(j=>({id:j.id,title:j.title,status:j.status,stage:j.stage,updated_at:j.updated_at,completed_stages:(j.graph?.nodes||[]).filter(n=>n.status==='done').length,total_stages:(j.graph?.nodes||[]).length}))}}
 }
}
