import { constants } from 'node:fs'
import { open } from 'node:fs/promises'
import { join } from 'node:path'
import { randomBytes, createCipheriv, createDecipheriv } from 'node:crypto'
import { AtomicRepository } from './repository.mjs'
import { invariant } from './errors.mjs'
// This store is separate from product state, projections, job snapshots and evidence.
export class IntegrationVault {
 constructor(root){this.repository=new AtomicRepository(join(root,'private-integrations'));this.keyPath=join(this.repository.root,'encryption.key')}
 async key(hasCiphertext=false){await this.repository.init();if(!hasCiphertext){try{const fd=await open(this.keyPath,'wx',0o600);try{await fd.writeFile(randomBytes(32));await fd.sync()}finally{await fd.close()}}catch(e){if(e.code!=='EEXIST')throw e}}let fd;try{fd=await open(this.keyPath,constants.O_RDONLY|constants.O_NOFOLLOW);const s=await fd.stat();invariant(s.isFile()&&(s.mode&0o777)===0o600&&s.uid===process.getuid(),'VAULT_UNAVAILABLE','El almacén privado de integraciones no está disponible.',503);const key=await fd.readFile();invariant(key.length===32,'VAULT_UNAVAILABLE','El almacén privado de integraciones no está disponible.',503);return key}catch{invariant(false,'VAULT_UNAVAILABLE','El almacén privado de integraciones no está disponible.',503)}finally{await fd?.close()}}
 async set(id,{api_key,remove_key,budget_reference},authorize){return this.repository.transact(async state=>{for(const provider of Object.keys(state.integrations||{}))await this.credential(provider);const key=await this.key(Object.values(state.integrations||{}).some(v=>v.encrypted));const actor=(await authorize()).id;state.integrations??={};const prior=state.integrations[id]||{};let encrypted=prior.encrypted;if(remove_key)encrypted=undefined;if(api_key){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key,iv);cipher.setAAD(Buffer.from(id));const bytes=Buffer.concat([cipher.update(api_key,'utf8'),cipher.final()]);encrypted={version:1,iv:iv.toString('base64'),tag:cipher.getAuthTag().toString('base64'),value:bytes.toString('base64')}}const entry={...(encrypted?{encrypted}:{}),budget_reference:budget_reference!==undefined?budget_reference:prior.budget_reference??null,updated_at:new Date().toISOString(),updated_by:actor};state.integrations[id]=entry;state.events.push({provider:id,actor_id:actor,type:remove_key?'KEY_REMOVED':api_key?'KEY_UPDATED':'PREFERENCES_UPDATED',created_at:entry.updated_at});state.events=state.events.slice(-100);return {key_configured:Boolean(encrypted),budget_reference:entry.budget_reference,updated_at:entry.updated_at}})}
 async credential(id){const state=await this.repository.read(),entry=state.integrations?.[id]?.encrypted;if(!entry)return null;const key=await this.key(true);try{const decode=(v,max)=>{if(typeof v!=='string'||v.length>max||Buffer.from(v,'base64').toString('base64')!==v)throw Error('Invalid envelope');return Buffer.from(v,'base64')};const iv=decode(entry.iv,16),tag=decode(entry.tag,24),value=decode(entry.value,5500);if(entry.version!==1||iv.length!==12||tag.length!==16||!value.length)throw Error('Invalid envelope');const decipher=createDecipheriv('aes-256-gcm',key,iv,{authTagLength:16});decipher.setAAD(Buffer.from(id));decipher.setAuthTag(tag);return Buffer.concat([decipher.update(value),decipher.final()]).toString('utf8')}catch{invariant(false,'VAULT_UNAVAILABLE','La credencial no se puede descifrar. Restaura el almacén y su clave; no se sobrescribirá.',503)}}
 async summary(){const state=await this.repository.read();return {providers:Object.fromEntries(Object.entries(state.integrations||{}).map(([id,v])=>[id,{key_configured:Boolean(v.encrypted),budget_reference:v.budget_reference,updated_at:v.updated_at}])),audit:state.events.slice(-20).reverse()}}
}
