import { fields, invariant } from './errors.mjs'
export const STRATEGIES = Object.freeze(['AUTO','REAL_FOOTAGE','HYBRID','GENERATIVE'])
const declarations = [
  {id:'manual-external',name:'Generación externa',strategies:['HYBRID','GENERATIVE'],capabilities:{text_to_image:true,image_to_image:true,image_to_video:true,multi_reference:true,character_reference:true,environment_reference:true,negative_constraints:true,execution:'manual'},credit_bearing:false,manual:true},
  {id:'seedance',name:'Seedance',strategies:['HYBRID','GENERATIVE'],capabilities:{text_to_image:false,image_to_image:false,image_to_video:false,multi_reference:false,character_reference:false,environment_reference:false,negative_constraints:false,execution:'integration_required'},credit_bearing:true},
  {id:'higgsfield',name:'Higgsfield · Seedance 2.5',strategies:['GENERATIVE'],capabilities:{text_to_image:false,text_to_video:true,image_to_image:false,image_to_video:false,reference_to_video:false,multi_reference:false,character_reference:false,environment_reference:false,negative_constraints:false,authoritative_numeric_progress:false,execution:'server_adapter'},credit_bearing:true},
  {id:'capcut',name:'CapCut',strategies:['REAL_FOOTAGE','HYBRID'],capabilities:{editing:true,finishing:true,text_to_image:false,image_to_video:false,multi_reference:false,execution:'integration_required'},credit_bearing:false},
  {id:'gemini',name:'Gemini · Veo 3.1 Fast',strategies:['GENERATIVE'],capabilities:{text_to_video:false,image_to_video:true,reference_to_video:true,multi_reference:true,character_reference:true,environment_reference:true,negative_constraints:true,execution:'server_adapter'},credit_bearing:true},
  {id:'ffmpeg',name:'FFmpeg',strategies:['REAL_FOOTAGE'],capabilities:{editing:true,technical_qa:true,text_to_image:false,image_to_video:false,multi_reference:false,execution:'local'},credit_bearing:false},
]
export class ProviderRegistry {
  constructor({ adapters = {}, testMode = false } = {}) { this.adapters = new Map(); for (const [id,adapter] of Object.entries(adapters)) { invariant(declarations.some(d=>d.id===id) || (testMode && id==='deterministic-test'), 'INVALID_PROVIDER', 'Unknown provider adapter'); for (const method of ['capabilities','estimate','prepare','generate','poll','collect','provenance']) invariant(typeof adapter[method]==='function','INVALID_PROVIDER','Provider adapter contract is incomplete'); this.adapters.set(id,adapter) }; this.testMode=testMode }
  list() { const list = declarations.map(d=>({...d,available:d.manual===true||this.adapters.has(d.id),availability:d.manual===true?'AVAILABLE':this.adapters.has(d.id)?'CONFIGURED':'INTEGRATION_REQUIRED',estimate:null})); if(this.testMode && this.adapters.has('deterministic-test')) list.push({id:'deterministic-test',name:'Deterministic test adapter',strategies:STRATEGIES,capabilities:{test_fixture:true,execution:'test'},credit_bearing:false,available:true,availability:'TEST_ONLY',estimate:0}); return list }
  validate(strategy='AUTO', preferred='AUTO') { invariant(STRATEGIES.includes(strategy),'INVALID_STRATEGY','Choose a supported production strategy'); invariant(preferred==='AUTO' || this.list().some(p=>p.id===preferred),'INVALID_PROVIDER','Choose a known provider'); if(preferred!=='AUTO') { const provider=this.list().find(p=>p.id===preferred); invariant(strategy==='AUTO'||provider.strategies.includes(strategy),'PROVIDER_CAPABILITY','Preferred provider does not support this production strategy') }; return {strategy,preferred_provider:preferred} }
  get(id) { invariant(this.adapters.has(id),'PROVIDER_UNAVAILABLE','Provider integration is not configured',503); return this.adapters.get(id) }
}
