import { resolve, join } from 'node:path'
import { mkdir, realpath, writeFile, readFile } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import { randomUUID } from 'node:crypto'
import { AtomicRepository } from './repository.mjs'
import { AuthService } from './auth.mjs'
import {createTeamService} from './team-access.mjs'
import { ProviderRegistry } from './providers.mjs'
import { ProductError, invariant, safeId, fields, boundedText } from './errors.mjs'
import { validateProfile, validatePublicLocator, deriveDNA, publicTenant, contentHash, monday, assertAudienceSafe, rejectSecretMaterial } from './contracts.mjs'
import { buildWeeklyProductionPlan } from '../plugins/media-weekly-factory.mjs'
import { interpretDraft } from './intent.mjs'
import { creationSupport, profileSnapshot } from './creation-support.mjs'
import { publicProviderExecution, publicSourceAssets } from './media-projection.mjs'
import {sceneSupport} from './scene-support.mjs'
import {IntegrationVault} from './integration-vault.mjs'
import {GoogleAuthVault} from './google-auth-vault.mjs'
const EDIT = ['owner','admin','editor']; const REVIEW = ['owner','admin','reviewer']; const ALL = [...EDIT,'reviewer','viewer']
const now = () => new Date().toISOString()
const copy = value => structuredClone(value)
function legacyPlan(input){try{return buildWeeklyProductionPlan(input)}catch(error){if(error?.name==='WeeklyFactoryError'||error?.name==='TenantMediaProfileError')throw new ProductError('INVALID_PLAN',error.message);throw error}}
export function requireMembership(actor, tenantId, roles = ALL) { safeId(tenantId,'Workspace ID'); const member=actor.memberships.find(m=>m.tenant_id===tenantId); invariant(member && roles.includes(member.role),'FORBIDDEN','You do not have access to this workspace or action',403); return member }
function publicGenerationAttempts(values) {
  return (values || []).map(a => ({
    attempt_id:a.attempt_id,
    job_revision:a.job_revision,
    adapter_id:a.adapter_id,
    provider:a.provider ?? null,
    provider_model:a.provider_model ?? null,
    request_sha256:a.request_sha256,
    prompt_sha256:a.prompt_sha256,
    input_assets:(a.input_assets || []).map(v => ({
      ...(v.asset_id ? {asset_id:v.asset_id} : {}),
      ...(v.source_id ? {source_id:v.source_id} : {}),
      ...(v.role ? {role:v.role} : {}),
      sha256:v.sha256,
    })),
    estimate:a.estimate ? structuredClone(a.estimate) : null,
    spend_approval_id:a.spend_approval_id ?? null,
    provider_request_id:a.provider_request_id ?? null,
    status:a.status,
    provider_telemetry:(a.provider_telemetry || []).map(v => ({source:v.source,provider:v.provider,request_id:v.request_id,status:v.status,kind:v.kind,percent:v.percent ?? null,observed_at:v.observed_at})),
    output_asset_id:a.output_asset_id ?? null,
    output_sha256:a.output_sha256 ?? null,
    cost:a.cost ?? null,
    credits:a.credits ?? null,
    error_code:a.error_code ?? null,
    error_detail:a.error_detail ?? null,
    retry_of:a.retry_of ?? null,
    started_at:a.started_at,
    completed_at:a.completed_at ?? null,
  }))
}
export function publicJob(job) {
  const keys=['id','tenant_id','plan_id','story_id','title','objective','source_ids','story_devices','strategy','preferred_provider','target','status','stage','created_at','updated_at','created_by','candidate_sha','release_id','review_status','elapsed_ms','blockers','critic_findings','critic_rubric','fixer_actions','verifier_result','test','review_state','review_candidate','treatment','artifact_sha256','production_provider','production_note','creative_context','repair_requires_manual','repair_instructions','repair_controls','creation_mode','generation_mode','scene_request','prompt_compilation','generation_attempt_count','external_generation_package','generation_phase','hero_image','job_revision','avatar_contract']
  const value=Object.fromEntries(keys.filter(k=>job[k]!==undefined).map(k=>[k,job[k]]))
  value.graph={nodes:(job.graph?.nodes||job.nodes||[]).map(n=>({id:n.id,title:n.title,status:n.status}))}
  value.generation_attempts=publicGenerationAttempts(job.generation_attempts)
  value.provider_telemetry=(job.provider_telemetry||[]).map(v=>({source:v.source,provider:v.provider,request_id:v.request_id,status:v.status,kind:v.kind,percent:v.percent??null,observed_at:v.observed_at}))
  value.provider_spend_request=job.provider_spend_request?{id:job.provider_spend_request.id,scope_sha:job.provider_spend_request.scope_sha,provider:job.provider_spend_request.provider,provider_model:job.provider_spend_request.provider_model,estimate:structuredClone(job.provider_spend_request.estimate),requested_at:job.provider_spend_request.requested_at}:null
  value.provider_spend_approval=job.provider_spend_approval?{id:job.provider_spend_approval.id,scope_sha:job.provider_spend_approval.scope_sha,approved_by:job.provider_spend_approval.approved_by,created_at:job.provider_spend_approval.created_at}:null
  value.provider_execution=publicProviderExecution(job.provider_execution)
  value.source_assets=publicSourceAssets(job.source_asset_snapshot)
  value.artifacts=(job.artifacts||[]).map(a=>({id:a.id,name:a.name||a.filename,mime_type:a.mime_type,sha256:a.sha256,size_bytes:a.size_bytes,width:a.width,height:a.height,duration_seconds:a.duration_seconds,generation_attempt_id:a.generation_attempt_id,provider:a.provider,prompt_sha256:a.prompt_sha256,character_asset_sha256:a.character_asset_sha256,environment_reference_sha256:a.environment_reference_sha256,synthetic:a.synthetic,test:a.test,download_url:'/api/v1/jobs/'+job.id+'/artifacts/'+a.id}))
  value.evidence=(job.evidence||[]).map(e=>({id:e.id,kind:e.kind||e.stage,result:e.result||'PASS',sha256:e.sha256,created_at:e.created_at||e.recorded_at,summary:e.summary,test:e.test}))
  value.approvals=(job.approvals||[]).map(a=>({actor_id:a.actor_id||a.actor,scope:a.scope||a.stage,candidate_sha:a.candidate_sha,created_at:a.created_at}))
  return value
}
export function createService(options = {}) {
  const repository=options.repository || new AtomicRepository(resolve(options.dataRoot || './data'))
  const googleAuthVault=options.googleAuthVault || new GoogleAuthVault(repository.root)
  const auth=new AuthService({repository,identityFile:options.identityFile,operatorUsername:options.operatorUsername,operatorPasswordVerifier:options.operatorPasswordVerifier,googleClientId:options.googleClientId,googleClientSecret:options.googleClientSecret,googleConfigProvider:options.googleConfigProvider||(()=>googleAuthVault.credential()),publicOrigin:options.publicOrigin,googleVerifier:options.googleVerifier,googleFetch:options.googleFetch,clock:options.clock})
  const providers=options.providers || new ProviderRegistry({adapters:options.adapters,testMode:options.testMode === true && options.deploymentClass==='test'})
  const integrationVault=options.integrationVault || new IntegrationVault(repository.root)
  let execution=options.execution
  async function actor(token) {return auth.resolve(token)}
  async function context(token,tenantId,roles=ALL){const user=await actor(token);return {user,membership:requireMembership(user,tenantId,roles)}}
  function tenantIn(state,id){const tenant=state.tenants[id]||state.onboarding[id];invariant(tenant,'NOT_FOUND','Workspace was not found',404);return tenant}
  function activeTenant(state,id){const tenant=state.tenants[id];invariant(tenant,'SOURCE_REQUIRED','Add an authorized source before production',409);return tenant}
  function append(state,tenantId,type,data={}){state.events.push({id:randomUUID(),tenant_id:tenantId,type,created_at:now(),...data});if(state.events.length>10000)state.events.splice(0,state.events.length-10000)}
  function planIn(state,id,tenantId){safeId(id,'Plan ID');const plan=state.plans[id];invariant(plan&&plan.tenant_id===tenantId,'NOT_FOUND','Production plan was not found',404);return plan}
  function normalizedStories(stories,tenant,dna,week,state){invariant(Array.isArray(stories)&&stories.length>0&&stories.length<=12,'INVALID_PLAN','Choose between one and twelve concepts');const normalized=stories.map((story,index)=>{fields(story,['id','title','objective','source_ids','story_devices','strategy','preferred_provider','mascot','character_id','place_id']);const id=story.id||'story-'+String(index+1).padStart(2,'0');const title=boundedText(story.title,'Story title',200);const objective=boundedText(story.objective,'Story objective',500);assertAudienceSafe(title+' '+objective);const strategy=providers.validate(story.strategy,story.preferred_provider);invariant(story.mascot===undefined||typeof story.mascot==='boolean','INVALID_PLAN','Mascot flag must be a boolean');if(story.mascot)invariant(tenant.brand.mascot_asset_key||story.character_id,'MASCOT_REQUIRED','Configure an authorized mascot asset before using the character');return {id,title,objective,source_ids:Array.isArray(story.source_ids)?[...story.source_ids].sort():story.source_ids,story_devices:Array.isArray(story.story_devices)?[...story.story_devices].sort():story.story_devices,...strategy,mascot:story.mascot===true||Boolean(story.character_id),character_id:story.character_id||null,place_id:story.place_id||null,creative_context:{character:profileSnapshot(state,tenant.tenant_id,story.character_id,'character'),place:profileSnapshot(state,tenant.tenant_id,story.place_id,'place')}}});legacyPlan({tenant,contentDna:dna,weekOf:week,stories:normalized.map(({strategy,preferred_provider,mascot,creative_context,character_id,place_id,...s})=>({...s,approved:true}))});return normalized}
  function stateArtifact(r){return r.artifact_sha256?[{id:'artifact_'+r.artifact_sha256,sha256:r.artifact_sha256,mime_type:'video/mp4'}]:[]}
  function stageApprovalRoles(stage){if(stage==='CRITIC')return ['owner','reviewer'];if(stage==='INDEPENDENT_VERIFIER')return ['owner','admin'];if(stage==='RELEASE')return ['owner','admin'];return REVIEW}
  function requireStageApproval(user,job){const member=requireMembership(user,job.tenant_id,REVIEW),allowed=stageApprovalRoles(job.stage);invariant(allowed.includes(member.role),'APPROVAL_ROLE_REQUIRED',job.stage==='CRITIC'?'Esta etapa requiere al coordinador municipal o al propietario.':job.stage==='INDEPENDENT_VERIFIER'?'Esta etapa requiere a IT o al propietario, respetando la revisión independiente.':job.stage==='RELEASE'?'La aprobación final requiere al propietario o a IT.':'No tienes autorización para aprobar esta etapa.',403);return member}
  function snapshot(tenant,stories){const ids=new Set(stories.flatMap(s=>s.source_ids));return tenant.sources.filter(s=>ids.has(s.id)).map(copy).sort((a,b)=>a.id.localeCompare(b.id))}
  function assertFresh(state,plan){const tenant=activeTenant(state,plan.tenant_id);invariant(state.dna[plan.tenant_id]?.revision===plan.content_dna_revision&&contentHash(snapshot(tenant,plan.stories))===contentHash(plan.source_authorization_snapshot),'PLAN_STALE','Sources or Content DNA changed; create and approve an updated plan',409);return tenant}
  const service={repository,auth,providers,options,setExecution(value){execution=value},requireMembership,publicJob,
    async me(token){return actor(token)},
    async googleAuthConfig(){return auth.googleConfig()},
    async updateGoogleAuth(token,input){fields(input,['client_id','client_secret','remove']);const current=await actor(token);invariant(current.manage_integrations===true,'FORBIDDEN','Solo el administrador del sistema puede configurar el acceso con Google.',403);return googleAuthVault.set(input,async()=>{const latest=await actor(token);invariant(latest.manage_integrations===true,'FORBIDDEN','Solo el administrador del sistema puede configurar el acceso con Google.',403);return latest})},
    async googleStart(next){return auth.googleStart(next)},
    async googleCallback(input){return auth.googleCallback(input)},
    async userOnboarding(token){const user=await actor(token);const state=await repository.read();const record=state.user_onboarding?.[user.id]||null,historicalActor=state.events.some(event=>event.actor_id===user.id||event.approved_by===user.id);const tenants=user.memberships.filter(m=>state.tenants[m.tenant_id]||state.onboarding[m.tenant_id]).map(m=>{const tenant=publicTenant(tenantIn(state,m.tenant_id),m.role);return {tenant_id:tenant.tenant_id,organization:tenant.organization,territory:tenant.territory||null,role:m.role,setup_status:tenant.setup_status,material_count:(tenant.sources||[]).filter(source=>source.purpose==='source').length}});return {status:record?.completed_at?'COMPLETED':record?.dismissed_at?'DISMISSED':historicalActor?'RETURNING':'NEW',completed_at:record?.completed_at||null,dismissed_at:record?.dismissed_at||null,can_create_tenants:user.can_create_tenants===true,tenant_count:tenants.length,tenants}},
    async updateUserOnboarding(token,input){const user=await actor(token);fields(input,['action']);invariant(['complete','dismiss'].includes(input.action),'INVALID_INPUT','Choose a supported onboarding action');return repository.transact(state=>{state.user_onboarding??={};const prior=state.user_onboarding[user.id]||{};const timestamp=now();const value={...prior,updated_at:timestamp};if(input.action==='complete')value.completed_at=prior.completed_at||timestamp;else value.dismissed_at=prior.dismissed_at||timestamp;state.user_onboarding[user.id]=value;return {status:value.completed_at?'COMPLETED':'DISMISSED',completed_at:value.completed_at||null,dismissed_at:value.dismissed_at||null}})},
    async listTenants(token){const user=await actor(token);const state=await repository.read();return user.memberships.filter(m=>state.tenants[m.tenant_id]||state.onboarding[m.tenant_id]).map(m=>publicTenant(tenantIn(state,m.tenant_id),m.role))},
    async getTenant(token,id){const {membership}=await context(token,id);return publicTenant(tenantIn(await repository.read(),id),membership.role)},
    ...createTeamService({repository,auth,requireMembership,tenantIn,append,googleAuthVault}),
    async createTenant(token,input){const user=await actor(token);invariant(user.can_create_tenants,'FORBIDDEN','Only configured operators can create workspaces',403);fields(input,['profile','organization','tenant_id','territory','content_context','visual_language','mascot_asset_key']);let profile;
      if(input.profile)profile=copy(validateProfile(input.profile));else{const id=boundedText(input.tenant_id,'Workspace ID',64);invariant(/^[a-z0-9][a-z0-9-]{1,63}$/.test(id),'INVALID_ID','Workspace ID must use lowercase letters, digits and hyphens');const organization=boundedText(input.organization,'Organization',200);const territory=input.territory?boundedText(input.territory,'Territory',200):null;const content=input.content_context||'commercial';invariant(['community','public-affairs','commercial','nonprofit','media'].includes(content),'INVALID_INPUT','Choose a supported organization type');profile={schema_version:'tenant-media-profile.v1',tenant_id:id,organization,territory,runtime_namespace:id,browser_context_ref:id+'-browser',content_context:content,audience_policy:{mode:'general-audience',sensitive_trait_targeting:false,voter_microtargeting:false},brand:{display_name:organization,visual_language:input.visual_language?boundedText(input.visual_language,'Visual language',500):''},sources:[],production_defaults:{aspect_ratio:'9:16',cadence:'weekly',duration_seconds:[8,25]}};if(input.mascot_asset_key)profile.brand.mascot_asset_key=boundedText(input.mascot_asset_key,'Mascot asset key',128);rejectSecretMaterial(profile)}
      return repository.transact(state=>{invariant(!state.tenants[profile.tenant_id]&&!state.onboarding[profile.tenant_id],'ALREADY_EXISTS','Workspace ID already exists',409);const all=[...Object.values(state.tenants),...Object.values(state.onboarding)];invariant(!all.some(t=>t.runtime_namespace===profile.runtime_namespace||t.browser_context_ref===profile.browser_context_ref),'TENANT_COLLISION','Workspace execution context must be isolated',409);if(profile.sources.length)state.tenants[profile.tenant_id]=profile;else state.onboarding[profile.tenant_id]=profile;state.memberships[user.id]=[...(state.memberships[user.id]||[]),{tenant_id:profile.tenant_id,role:'owner'}];append(state,profile.tenant_id,'WORKSPACE_CREATED',{actor_id:user.id});return publicTenant(profile,'owner')})},
    async setMascot(token,id,input){const {user,membership}=await context(token,id,EDIT);fields(input,['source_id']);safeId(input.source_id);return repository.transact(state=>{const tenant=activeTenant(state,id);const source=tenant.sources.find(s=>s.id===input.source_id&&s.purpose==='source');invariant(source,'SOURCE_REQUIRED','Choose an authorized production source containing the character',409);tenant.brand.mascot_asset_key='source:'+source.id;validateProfile(tenant);append(state,id,'MASCOT_SOURCE_SELECTED',{source_id:source.id,actor_id:user.id});return publicTenant(tenant,membership.role)})},
    async sources(token,id){await context(token,id);const state=await repository.read();return tenantIn(state,id).sources.map(s=>({...s,media_asset:state.source_assets?.[id]?.[s.id]||null,inspection_status:state.source_assets?.[id]?.[s.id]?'UPLOADED':'NOT_INSPECTED'}))},
    async addSource(token,id,input){const {user}=await context(token,id,EDIT);fields(input,['source']);const source=copy(input.source);validatePublicLocator(source?.locator);return repository.transact(state=>{const tenant=tenantIn(state,id);invariant(!tenant.sources.some(s=>s.id===source.id),'ALREADY_EXISTS','Source ID already exists',409);const updated=copy(validateProfile({...tenant,sources:[...tenant.sources,source]}));state.tenants[id]=updated;delete state.onboarding[id];append(state,id,'SOURCE_AUTHORIZED',{actor_id:user.id,source_id:source.id});return source})},
    async uploadReferenceEvidence(token,id,sourceId,{bytes,mime_type}){const {user}=await context(token,id,EDIT);safeId(sourceId);invariant(Buffer.isBuffer(bytes)&&bytes.length>0&&bytes.length<=8*1024*1024,'INVALID_EVIDENCE','Reference evidence must be smaller than 8 MB',413);invariant(['image/png','image/jpeg','image/webp','text/plain','application/json','video/mp4'].includes(mime_type),'INVALID_EVIDENCE','Choose an image, short video, or text evidence file',415);if(['text/plain','application/json'].includes(mime_type))rejectSecretMaterial(bytes.toString('utf8'));const state=await repository.read();const source=activeTenant(state,id).sources.find(s=>s.id===sourceId&&s.purpose==='reference');invariant(source,'REFERENCE_REQUIRED','Select an authorized reference source');const sha=createHash('sha256').update(bytes).digest('hex');const directory=join(repository.root,'reference-evidence',id);await mkdir(directory,{recursive:true,mode:0o700});invariant(await realpath(directory)===directory,'UNSAFE_STORAGE','Evidence storage is unavailable',503);await writeFile(join(directory,sha),bytes,{mode:0o600});return repository.transact(s=>{const current=s.tenants[id]?.sources.find(x=>x.id===sourceId);invariant(current&&contentHash(current)===contentHash(source),'SOURCE_CHANGED','Reference authorization changed during upload',409);s.reference_evidence??={};s.reference_evidence[id]??={};const proof={sha256:sha,source_id:sourceId,mime_type,size_bytes:bytes.length,uploaded_by:user.id,created_at:now(),authorization_sha:contentHash(source)};s.reference_evidence[id][sourceId+':'+sha]=proof;return proof})},
    async contentDNA(token,id){await context(token,id);const state=await repository.read();tenantIn(state,id);return state.dna[id]||null},
    async analyzeDNA(token,id,input){const {user}=await context(token,id,EDIT);fields(input,['observations']);return repository.transact(async state=>{const tenant=activeTenant(state,id);const dna=deriveDNA(tenant,input.observations);for(const observation of input.observations){const proof=state.reference_evidence?.[id]?.[observation.authorization_id+':'+observation.evidence_sha256];invariant(proof&&proof.source_id===observation.authorization_id&&proof.authorization_sha===contentHash(tenant.sources.find(s=>s.id===proof.source_id)),'EVIDENCE_REQUIRED','Upload the reference evidence before analyzing Content DNA',409);const path=join(repository.root,'reference-evidence',id,proof.sha256);invariant(await realpath(path)===path&&createHash('sha256').update(await readFile(path)).digest('hex')===proof.sha256,'EVIDENCE_CHANGED','Stored reference evidence changed',409)}state.observations[id]=copy(input.observations);state.dna[id]=dna;append(state,id,'CONTENT_DNA_UPDATED',{actor_id:user.id,revision:dna.revision});return dna})},
    async plans(token,id){await context(token,id);const state=await repository.read();tenantIn(state,id);return Object.values(state.plans).filter(p=>p.tenant_id===id).sort((a,b)=>b.created_at.localeCompare(a.created_at))},
    async createPlan(token,id,input){const {user}=await context(token,id,EDIT);fields(input,['week_of','stories','mode']);monday(input.week_of);invariant(input.mode===undefined||['guided','free'].includes(input.mode),'INVALID_MODE','Choose Guided or Free mode');return repository.transact(state=>{const tenant=activeTenant(state,id);const dna=state.dna[id];invariant(dna,'DNA_REQUIRED','Analyze authorized references before creating a production plan',409);const stories=normalizedStories(input.stories,tenant,dna,input.week_of,state);const sources=snapshot(tenant,stories);const hash=contentHash({tenant_id:id,week_of:input.week_of,stories,source_authorization_snapshot:sources,content_dna_revision:dna.revision});const planId='plan_'+hash.slice(0,32);if(state.plans[planId])return state.plans[planId];const plan={id:planId,tenant_id:id,week_of:input.week_of,mode:input.mode||'guided',status:'DRAFT',stories:stories.map(s=>({...s,approved:false})),content_dna_revision:dna.revision,source_authorization_snapshot:sources,created_at:now(),created_by:user.id,approvals:[],definition_sha:hash};state.plans[planId]=plan;append(state,id,'PLAN_DRAFT_CREATED',{plan_id:planId,actor_id:user.id});return plan})},
    async approvePlan(token,id,planId,input){const {user}=await context(token,id,['owner','reviewer']);fields(input,['story_ids']);invariant(Array.isArray(input.story_ids)&&input.story_ids.length>0&&new Set(input.story_ids).size===input.story_ids.length,'INVALID_APPROVAL','Select concepts to approve');return repository.transact(state=>{const plan=planIn(state,planId,id);invariant(plan.status!=='LAUNCHED','PLAN_LAUNCHED','Launched plans cannot be changed',409);assertFresh(state,plan);invariant(input.story_ids.every(storyId=>plan.stories.some(s=>s.id===storyId)),'INVALID_APPROVAL','Unknown concept selected');for(const story of plan.stories)if(input.story_ids.includes(story.id))story.approved=true;plan.approvals.push({actor_id:user.id,story_ids:[...input.story_ids],scope_sha:plan.definition_sha,created_at:now()});plan.status=plan.stories.every(s=>s.approved)?'APPROVED':'DRAFT';append(state,id,'CONCEPTS_APPROVED',{plan_id:planId,actor_id:user.id});return plan})},
    async launchPlan(token,id,planId){const {user}=await context(token,id,EDIT);const jobs=await repository.transact(state=>{const plan=planIn(state,planId,id);const tenant=assertFresh(state,plan);invariant(plan.status==='APPROVED'||plan.status==='LAUNCHED','APPROVAL_REQUIRED','Approve every selected concept before launch',409);const legacy=legacyPlan({tenant,contentDna:state.dna[id],weekOf:plan.week_of,stories:plan.stories.map(({strategy,preferred_provider,mascot,creative_context,character_id,place_id,...s})=>s)});const jobs=plan.stories.map((story,index)=>{const jobId='mf_'+contentHash({plan:plan.definition_sha,story:story.id}).slice(0,32);if(state.jobs[jobId])return state.jobs[jobId];const job={...legacy.jobs[index],id:jobId,story_id:story.id,tenant_id:id,plan_id:plan.id,week_of:plan.week_of,strategy:story.strategy,preferred_provider:story.preferred_provider,mascot:story.mascot,creative_context:copy(story.creative_context),status:'BRIEF',stage:'BRIEF',graph:{nodes:[]},artifacts:[],evidence:[],approvals:[],blockers:[],source_authorization_snapshot:copy(plan.source_authorization_snapshot.filter(s=>story.source_ids.includes(s.id))),started:true,source_asset_snapshot:story.source_ids.every(sourceId=>state.source_assets?.[id]?.[sourceId])?story.source_ids.map(sourceId=>copy(state.source_assets[id][sourceId])):null,content_dna_revision:plan.content_dna_revision,created_at:now(),created_by:user.id,concept_approvals:copy(plan.approvals)};state.jobs[jobId]=job;append(state,id,'JOB_QUEUED',{job_id:jobId,actor_id:user.id});return job});plan.status='LAUNCHED';return jobs});if(execution?.onJobsQueued)await execution.onJobsQueued(jobs.map(j=>j.id));else if(options.onJobsQueued)await options.onJobsQueued(jobs.map(j=>j.id));return jobs.map(publicJob)},
    async freeDraft(token,id,input){await context(token,id,EDIT);fields(input,['text','week_of','source_ids']);monday(input.week_of);const state=await repository.read();return interpretDraft(input,tenantIn(state,id),state.dna[id],Object.values(state.creative_profiles?.[id]||{}))},
    async jobs(token,tenantId){const user=await actor(token);if(tenantId)requireMembership(user,tenantId);const allowed=new Set(user.memberships.map(m=>m.tenant_id));return Object.values((await repository.read()).jobs).filter(j=>allowed.has(j.tenant_id)&&(!tenantId||j.tenant_id===tenantId)).map(publicJob)},
    async job(token,id){safeId(id,'Job ID');const user=await actor(token);const job=(await repository.read()).jobs[id];invariant(job,'NOT_FOUND','Production job was not found',404);requireMembership(user,job.tenant_id);return publicJob(job)},
    async jobAction(token,id,action,input={}){safeId(id,'Job ID');const user=await actor(token);const job=(await repository.read()).jobs[id];invariant(job,'NOT_FOUND','Production job was not found',404);if(['approve','reject','requestChanges'].includes(action))requireStageApproval(user,job);else requireMembership(user,job.tenant_id,EDIT);fields(input,action==='start'?[]:action==='approve'?['candidate_sha','review_stage']:['candidate_sha','review_stage','reason']);if(action!=='start')safeId(input.review_stage,'Review stage');rejectSecretMaterial(input);if(input.reason)assertAudienceSafe(input.reason);invariant(execution&&typeof execution[action]==='function','EXECUTION_UNAVAILABLE','Production execution is unavailable',503);return publicJob(await execution[action](user,id,input))},
    async approveProviderSpend(token,id,input={}){safeId(id,'Job ID');const user=await actor(token);const job=(await repository.read()).jobs[id];invariant(job,'NOT_FOUND','Production job was not found',404);requireMembership(user,job.tenant_id,['owner','admin']);fields(input,['scope_sha','confirm']);invariant(typeof input.scope_sha==='string'&&/^[a-f0-9]{64}$/.test(input.scope_sha),'INVALID_INPUT','La aprobación de gasto no coincide con esta solicitud.',400);invariant(input.confirm===true,'SPEND_APPROVAL_REQUIRED','Confirma explícitamente el gasto estimado para continuar.',409);invariant(execution&&typeof execution.approveProviderSpend==='function','EXECUTION_UNAVAILABLE','Production execution is unavailable',503);return publicJob(await execution.approveProviderSpend(user,id,input))},
    async repairJob(token,id,input){safeId(id,'Job ID');const user=await actor(token);const job=(await repository.read()).jobs[id];invariant(job,'NOT_FOUND','Production job was not found',404);requireMembership(user,job.tenant_id,EDIT);fields(input,['action']);rejectSecretMaterial(input);invariant(execution&&typeof execution.repairBlocked==='function','EXECUTION_UNAVAILABLE','Production execution is unavailable',503);return publicJob(await execution.repairBlocked(user,id,input))},
    async evidence(token,id){return (await service.job(token,id)).evidence},
    async events(token,id){const job=await service.job(token,id);return (await repository.read()).events.filter(e=>e.tenant_id===job.tenant_id&&e.job_id===id).map(({id,type,event,created_at,stage,status,message})=>({id,type,event,created_at,stage,status,message}))},
    async artifact(token,jobId,artifactId){safeId(jobId);safeId(artifactId);const user=await actor(token);const job=(await repository.read()).jobs[jobId];invariant(job,'NOT_FOUND','Production job was not found',404);requireMembership(user,job.tenant_id);invariant(execution?.artifact,'ARTIFACT_UNAVAILABLE','Artifact is unavailable',503);return execution.artifact(user,jobId,artifactId)},
    async uploadSource(token,tenantId,sourceId,input){const {user}=await context(token,tenantId,EDIT);safeId(sourceId);invariant(execution?.uploadSource,'UPLOAD_UNAVAILABLE','Source upload is unavailable',503);return execution.uploadSource(user,tenantId,sourceId,input)},
    async releases(token,tenantId){const user=await actor(token);if(tenantId)requireMembership(user,tenantId);const allowed=new Set(user.memberships.map(m=>m.tenant_id));return Object.values((await repository.read()).releases).filter(r=>allowed.has(r.tenant_id)&&(!tenantId||r.tenant_id===tenantId)).map(r=>({id:r.id,tenant_id:r.tenant_id,job_id:r.job_id,title:r.title,created_at:r.created_at,version:r.version,aspect_ratio:r.aspect_ratio,candidate_sha:r.candidate_sha||r.artifact_sha256,publication_state:r.publication_state||'NOT_PUBLISHED',provider_execution:publicProviderExecution(r.provider_execution),scene_provenance:r.scene_provenance||null,source_assets:publicSourceAssets(r.source_assets),reviews:(r.reviews||[]).map(a=>({actor_id:a.actor_id||a.actor,scope:a.scope||a.stage,candidate_sha:a.candidate_sha,created_at:a.created_at})),approval:r.approval||{actor_id:r.approved_by},artifact_sha256:r.artifact_sha256,test:r.test,artifact_url:r.artifact_url,artifacts:(r.artifacts||stateArtifact(r)).map(a=>({id:a.id,sha256:a.sha256,mime_type:a.mime_type,size_bytes:a.size_bytes,width:a.width,height:a.height,duration_seconds:a.duration_seconds,generation_attempt_id:a.generation_attempt_id,provider:a.provider,prompt_sha256:a.prompt_sha256,character_asset_sha256:a.character_asset_sha256,environment_reference_sha256:a.environment_reference_sha256,synthetic:a.synthetic,test:a.test,download_url:'/api/v1/jobs/'+r.job_id+'/artifacts/'+a.id}))}))},
    async release(token,id){safeId(id);const release=(await service.releases(token)).find(r=>r.id===id);invariant(release,'NOT_FOUND','Release was not found',404);return release},
    async dashboard(token,id){await context(token,id);const jobs=await service.jobs(token,id);const state=await repository.read();const plans=Object.values(state.plans).filter(p=>p.tenant_id===id);const releases=await service.releases(token,id);return {tenant:await service.getTenant(token,id),planned:plans.filter(p=>p.status!=='LAUNCHED').reduce((n,p)=>n+p.stories.length,0),producing:jobs.filter(j=>!['BRIEF','RELEASED','AWAITING_REVIEW','BLOCKED','FAILED','REJECTED'].includes(j.status)).length,awaiting_review:jobs.filter(j=>['AWAITING_REVIEW','REVIEW_READY'].includes(j.status)).length,released:releases.length,blockers:jobs.flatMap(j=>(j.blockers||[]).map(b=>({job_id:j.id,...(typeof b==='object'?b:{message:b})}))),jobs,plans,activity:state.events.filter(e=>e.tenant_id===id).slice(-30).reverse()}},
    async providerList(token){await actor(token);const stored=await integrationVault.summary();return providers.list().map(p=>{if(!p.credit_bearing||p.manual===true||p.id==='ffmpeg'||p.id==='deterministic-test')return p;const configured=stored.providers[p.id]?.key_configured===true;if(!p.available)return p;return {...p,available:configured,availability:configured?'CONFIGURED':'CREDENTIAL_REQUIRED'}})},
    async health(){let storage=false,authentication=false;try{await repository.read();storage=true}catch{}try{authentication=(await auth.identities()).length>0}catch{}let graph=false;try{graph=execution?.health?Boolean((await execution.health()).graph):false}catch{}return {status:storage&&authentication&&graph?'ready':'degraded',service:'media-factory-web',checks:{storage,authentication,graph},release_sha:options.releaseSha||null}},
  };return Object.assign(service,creationSupport({repository,providers,auth,context}),sceneSupport({repository,providers,auth,context,getExecution:()=>execution,publicJob,append}))
}
